import type { Recipe } from '@/types';

export const recipesMakanMalam2: Recipe[] = [
  {
    id: 'daging-sapi-lada-hitam',
    name: 'Daging Sapi Lada Hitam',
    description: 'Daging sapi yang dimasak dengan saus lada hitam pekat dan gurih. Perpaduan pedas lada hitam dengan manisnya kecap menjadikan hidangan ini favorit di restoran Chinese.',
    image: '🥩',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'Daging sapi has dalam', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Lada hitam butiran', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Maizena', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging sapi tipis melebar melawan serat. Marinasi dengan kecap asin dan 1 sdt lada hitam selama 15 menit.',
      'Tumis bawang putih cincang dan jahe geprek hingga harum.',
      'Masukkan daging sapi, aduk hingga berubah warna. Angkat, sisihkan.',
      'Tumis bawang bombay iris hingga layu dan harum.',
      'Masukkan kembali daging sapi, tambahkan kecap manis, saus tiram, dan lada hitam tumbuk.',
      'Tuang larutan maizena sedikit demi sedikit, aduk hingga saus mengental.',
      'Bumbui garam, aduk rata. Sajikan hangat dengan nasi putih.',
    ],
    tags: ['daging sapi', 'lada hitam', 'Chinese', 'gurih', 'pedas'],
    rating: 4.7,
  },
  {
    id: 'ayam-goreng-lengkuas',
    name: 'Ayam Goreng Lengkuas',
    description: 'Ayam goreng khas Sunda yang dibumbui dengan lengkuas parut yang renyah dan harum. Bumbu meresap hingga ke tulang dengan aroma lengkuas yang khas.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 25,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Lengkuas parut', amount: 200, unit: 'gram', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang putih, bawang merah, kunyit, dan jahe.',
      'Campurkan bumbu halus dengan lengkuas parut, garam, daun salam, dan serai yang dimemarkan.',
      'Bumbui ayam dengan campuran bumbu, aduk rata hingga merata. Diamkan 30 menit agar bumbu meresap.',
      'Ungkep ayam dengan api sedang hingga air menyusut dan bumbu meresap, sekitar 25 menit.',
      'Tiriskan ayam dan saring bumbu lengkuasnya (sangrai kering untuk taburan).',
      'Goreng ayam dalam minyak panas hingga kuning keemasan dan renyah.',
      'Sajikan dengan taburan serundeng lengkuas kering dan lalapan segar.',
    ],
    tags: ['ayam', 'goreng', 'lengkuas', 'Sunda', 'harum'],
    rating: 4.8,
  },
  {
    id: 'bebek-goreng-sambal-ijo',
    name: 'Bebek Goreng Sambal Ijo',
    description: 'Bebek goreng renyah dengan sambal hijau khas Padang yang pedas dan segar. Daging bebek yang empuk berpadu dengan sambal ijo yang menggugah selera.',
    image: '🦆',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 45,
    prepTime: 30,
    servings: 3,
    calories: 520,
    ingredients: [
      { name: 'Bebek potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Cabai hijau besar', amount: 15, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit hijau', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat hijau', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 600, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Rebus bebek dengan air, garam, dan sedikit jahe selama 30 menit hingga empuk. Tiriskan.',
      'Haluskan cabai hijau, cabai rawit hijau, bawang merah, dan bawang putih untuk sambal ijo.',
      'Tumis sambal ijo dengan daun jeruk, serai, dan lengkuas geprek hingga matang dan harum.',
      'Goreng bebek dalam minyak panas hingga renyah dan kuning keemasan.',
      'Siram bebek goreng dengan sambal ijo di atasnya.',
      'Sajikan dengan nasi putih hangat dan lalapan.',
    ],
    tags: ['bebek', 'goreng', 'sambal ijo', 'Padang', 'pedas'],
    rating: 4.6,
  },
  {
    id: 'ikan-asin-goreng',
    name: 'Ikan Asin Goreng Sambal',
    description: 'Ikan asin goreng renyah dengan sambal matah yang segar dan pedas. Lauk sederhana tapi sangat nikmat untuk makan dengan nasi putih hangat.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 280,
    ingredients: [
      { name: 'Ikan asin', amount: 5, unit: 'ekor', category: 'Protein' },
      { name: 'Serai', amount: 3, unit: 'batang', category: 'Bumbu' },
      { name: 'Cabai rawit merah', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Jeruk limau', amount: 1, unit: 'buah', category: 'Pelengkap' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam ikan asin dalam air hangat selama 15 menit untuk mengurangi rasa asin. Tiriskan.',
      'Panaskan minyak, goreng ikan asin hingga kering dan renyah. Angkat, tiriskan.',
      'Iris halus serai, cabai rawit, dan bawang merah untuk sambal matah.',
      'Tumis sebentar bahan sambal matah dengan daun jeruk hingga layu tapi tidak gosong.',
      'Beri perasan jeruk limau dan garam, aduk rata.',
      'Siram sambal matah di atas ikan asin goreng. Sajikan dengan nasi putih.',
    ],
    tags: ['ikan asin', 'goreng', 'sambal matah', 'sederhana', 'renyah'],
    rating: 4.4,
  },
  {
    id: 'tumis-daging-sapi',
    name: 'Tumis Daging Sapi Paprika',
    description: 'Tumis daging sapi dengan paprika berwarna-warni dan saus tiram yang gurih. Hidangan bergizi tinggi dengan tampilan cantik dan rasa lezat.',
    image: '🥘',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'Daging sapi has dalam', amount: 350, unit: 'gram', category: 'Protein' },
      { name: 'Paprika merah', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Paprika hijau', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Maizena', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Potong tipis daging sapi melawan serat. Marinasi dengan saus tiram dan merica selama 15 menit.',
      'Potong paprika dan bawang bombay memanjang. Cincang bawang putih dan jahe.',
      'Panaskan minyak, tumis bawang putih dan jahe hingga harum.',
      'Tumis daging sapi dengan api besar hingga berubah warna, angkat sisihkan.',
      'Tumis bawang bombay dan paprika hingga setengah layu tapi masih renyah.',
      'Masukkan daging sapi, tambahkan kecap manis dan larutan maizena. Aduk rata hingga saus mengental.',
      'Sajikan hangat dengan nasi putih.',
    ],
    tags: ['daging sapi', 'tumis', 'paprika', 'sayuran', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'ayam-goreng-serundeng',
    name: 'Ayam Goreng Serundeng',
    description: 'Ayam goreng dengan taburan serundeng kelapa parut yang gurih dan renyah. Perpaduan ayam berbumbu dengan kelapa sangrai yang lezat.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 25,
    servings: 4,
    calories: 410,
    ingredients: [
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Kelapa parut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang putih, bawang merah, kunyit, dan jahe untuk bumbu ayam.',
      'Bumbui ayam dengan bumbu halus, daun salam, serai, dan garam. Ungkep hingga empuk dan air menyusut.',
      'Tiriskan ayam, goreng dalam minyak panas hingga renyah.',
      'Untuk serundeng: tumis kelapa parut dengan sisa bumbu halus, garam, dan gula merah.',
      'Sangrai kelapa parut di api kecil sambil terus diaduk hingga kering dan berwarna kecoklatan.',
      'Sajikan ayam goreng dengan taburan serundeng kelapa.',
    ],
    tags: ['ayam', 'goreng', 'serundeng', 'kelapa', 'gurih'],
    rating: 4.7,
  },
  {
    id: 'udang-goreng-tepung',
    name: 'Udang Goreng Tepung Crispy',
    description: 'Udang goreng dengan balutan tepung yang crispy dan renyah. Cocok disajikan dengan saus sambal mayo atau saus tartar sebagai camilan atau lauk.',
    image: '🦐',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 3,
    calories: 340,
    ingredients: [
      { name: 'Udang segar', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung maizena', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan udang, buang kepala, kulit, dan ekor. Kerat punggung untuk menghilangkan darah.',
      'Marinasi udang dengan bawang putih halus, garam, dan merica selama 15 menit.',
      'Campurkan tepung terigu dan maizena sebagai adonan kering.',
      'Kocok lepas telur sebagai adonan basah.',
      'Celupkan udang ke telur kocok, lalu gulingkan ke adonan tepung hingga rata.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan dan crispy.',
      'Tiriskan, sajikan dengan saus sambal mayo.',
    ],
    tags: ['udang', 'goreng tepung', 'crispy', 'seafood', 'camilan'],
    rating: 4.6,
  },
  {
    id: 'cumi-goreng-tepung',
    name: 'Cumi Goreng Tepung',
    description: 'Cumi goreng dengan tepung crispy yang renyah di luar dan kenyal di dalam. Camilan seafood favorit yang cocok disajikan dengan saus cabai.',
    image: '🦑',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 25,
    servings: 3,
    calories: 290,
    ingredients: [
      { name: 'Cumi segar', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung maizena', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan cumi, buang tulang dan tinta. Potong membentuk cincin atau sesuai selera.',
      'Marinasi cumi dengan bawang putih halus, garam, dan merica selama 15 menit.',
      'Campurkan tepung terigu dan maizena untuk adonan kering.',
      'Kocok lepas telur sebagai pencelup.',
      'Celupkan cumi ke telur, lalu gulingkan ke tepung hingga terbalut rata.',
      'Goreng dalam minyak panas api sedang hingga kuning keemasan dan crispy.',
      'Tiriskan, sajikan dengan saus sambal atau saus cabai.',
    ],
    tags: ['cumi', 'goreng tepung', 'crispy', 'seafood', 'camilan'],
    rating: 4.5,
  },
  {
    id: 'kepiting-saus-tiram',
    name: 'Kepiting Saus Tiram',
    description: 'Kepiting dimasak dengan saus tiram yang gurih dan manis, disertai telur puyuh dan sayuran. Hidangan seafood mewah dengan rasa yang lezat.',
    image: '🦀',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 25,
    servings: 3,
    calories: 380,
    ingredients: [
      { name: 'Kepiting', amount: 2, unit: 'ekor', category: 'Protein' },
      { name: 'Telur puyuh rebus', amount: 6, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Maizena', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan kepiting, potong-potong menjadi bagian yang mudah dimakan.',
      'Goreng kepiting sebentar hingga berubah warna, angkat dan tiriskan.',
      'Tumis bawang putih cincang dan jahe hingga harum.',
      'Masukkan bawang bombay iris, tumis hingga layu.',
      'Tambahkan saus tiram, kecap manis, dan garam. Masukkan kepiting, aduk rata.',
      'Tuang larutan maizena, masukkan telur puyuh. Masak hingga saus mengental.',
      'Taburi daun bawang iris, sajikan hangat.',
    ],
    tags: ['kepiting', 'saus tiram', 'seafood', 'gurih', 'mewah'],
    rating: 4.7,
  },
  {
    id: 'nila-goreng-crispy',
    name: 'Nila Goreng Crispy',
    description: 'Ikan nila goreng renyah dengan bumbu kuning yang meresap. Disajikan dengan sambal terasi dan lalapan segar sebagai lauk utama yang mengenyangkan.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 320,
    ingredients: [
      { name: 'Ikan nila', amount: 2, unit: 'ekor', category: 'Protein' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 1, unit: 'cm', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Tepung beras', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan nila, kerat-kerat bagian daging. Lumuri dengan jeruk nipis dan garam.',
      'Haluskan bawang putih, kunyit, dan jahe. Oleskan pada ikan secara merata.',
      'Diamkan ikan selama 20 menit agar bumbu meresap.',
      'Campurkan tepung beras dengan sedikit garam untuk balutan.',
      'Gulingkan ikan di tepung beras hingga terbalut rata.',
      'Goreng dalam minyak panas api sedang hingga kuning keemasan dan renyah.',
      'Sajikan dengan sambal terasi, lalapan, dan nasi putih.',
    ],
    tags: ['nila', 'goreng', 'crispy', 'ikan', 'sederhana'],
    rating: 4.5,
  },
  {
    id: 'lele-goreng-crispy',
    name: 'Lele Goreng Crispy',
    description: 'Lele goreng renyah dengan bumbu gurih yang sederhana. Lauk favorit sehari-hari yang nikmat disajikan dengan sambal dan lalapan.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 300,
    ingredients: [
      { name: 'Ikan lele', amount: 5, unit: 'ekor', category: 'Protein' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tepung beras', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan lele, buang insang dan organ dalam. Cuci bersih.',
      'Haluskan bawang putih dan kunyit, campurkan dengan garam.',
      'Lumuri lele dengan bumbu halus, diamkan 15 menit.',
      'Balutkan lele dengan tepung beras secara merata.',
      'Goreng dalam minyak panas api sedang hingga renyah dan kuning keemasan.',
      'Sajikan dengan sambal, lalapan, dan nasi putih hangat.',
    ],
    tags: ['lele', 'goreng', 'crispy', 'ikan', 'sederhana'],
    rating: 4.3,
  },
  {
    id: 'pindang-bandeng',
    name: 'Pindang Bandeng Presto',
    description: 'Pindang bandeng yang dimasak dengan panci presto sehingga durinya lunak dan bisa dimakan. Kuah kuning yang gurih dan pedas dengan aroma rempah.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 20,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Bandeng', amount: 2, unit: 'ekor', category: 'Protein' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Asam jawa', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 500, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Bersihkan bandeng, potong menjadi beberapa bagian.',
      'Haluskan bawang merah, bawang putih, kunyit, jahe, dan cabai merah.',
      'Didihkan air dalam panci presto, masukkan bumbu halus, daun salam, dan serai.',
      'Masukkan bandeng dan asam jawa. Bumbui garam.',
      'Tutup panci presto, masak selama 45-60 menit hingga duri lunak.',
      'Angkat, sajikan bandeng dengan kuahnya.',
    ],
    tags: ['bandeng', 'pindang', 'presto', 'kuah kuning', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'bandeng-presto',
    name: 'Bandeng Presto Duri Lunak',
    description: 'Bandeng presto khas Semarang dengan duri lunak dan bumbu rempah yang meresap. Bisa dimakan langsung atau digoreng renyah.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 20,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'Bandeng', amount: 2, unit: 'ekor', category: 'Protein' },
      { name: 'Daun pisang', amount: 5, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan bandeng, potong-potong sesuai selera.',
      'Haluskan bawang merah, bawang putih, kunyit, dan jahe.',
      'Lumuri bandeng dengan bumbu halus, lengkuas geprek, daun salam, dan garam.',
      'Bungkus bandeng dengan daun pisang, ikat dengan tali.',
      'Masukkan ke panci presto, tambahkan air secukupnya.',
      'Presto selama 60 menit hingga duri benar-benar lunak.',
      'Angkat, bisa disajikan langsung atau digoreng terlebih dahulu.',
    ],
    tags: ['bandeng', 'presto', 'Semarang', 'duri lunak', 'olahan ikan'],
    rating: 4.6,
  },
  {
    id: 'ayam-geprek-sambal',
    name: 'Ayam Geprek Sambal Bawang',
    description: 'Ayam goreng tepung yang digeprek dan disiram sambal bawang pedas. Hidangan viral yang gurih renyah dengan sensasi pedas yang nagih.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 390,
    ingredients: [
      { name: 'Ayam dada fillet', amount: 3, unit: 'potong', category: 'Protein' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung maizena', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Cabai rawit merah', amount: 15, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Bumbui ayam fillet dengan garam dan bawang putih halus. Diamkan 15 menit.',
      'Balut ayam dengan tepung campuran terigu dan maizena, celup telur, balut tepung lagi.',
      'Goreng ayam dalam minyak panas hingga kuning keemasan dan renyah.',
      'Buat sambal: goreng cabai rawit, cabai merah, bawang merah, dan bawang putih hingga layu.',
      'Ulek bahan sambal dengan garam dan gula merah.',
      'Geprek ayam goreng menggunakan cobek, siram dengan sambal bawang.',
      'Sajikan dengan nasi putih dan lalapan.',
    ],
    tags: ['ayam geprek', 'sambal bawang', 'pedas', 'crispy', 'viral'],
    rating: 4.8,
  },
  {
    id: 'ikan-mas-bakar',
    name: 'Ikan Mas Bakar Bumbu Kecap',
    description: 'Ikan mas bakar dengan olesan bumbu kecap manis yang meresap dan harum. Aroma bakaran yang menggoda dengan rasa manis gurih.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 3,
    calories: 310,
    ingredients: [
      { name: 'Ikan mas', amount: 2, unit: 'ekor', category: 'Protein' },
      { name: 'Kecap manis', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan mas, kerat-kerat bagian dagingnya. Lumuri jeruk nipis dan garam.',
      'Haluskan bawang putih, bawang merah, jahe, dan cabai rawit.',
      'Campurkan bumbu halus dengan kecap manis dan gula merah sebagai olesan.',
      'Olesi ikan dengan bumbu secara merata, diamkan 20 menit.',
      'Panggang ikan di atas arang atau grill pan, olesi bumbu secara berkala.',
      'Bakar hingga kedua sisi matang dan bumbu meresap.',
      'Sajikan dengan nasi putih dan sambal.',
    ],
    tags: ['ikan mas', 'bakar', 'kecap', 'panggang', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'udang-goreng-butter',
    name: 'Udang Goreng Butter Sauce',
    description: 'Udang goreng dengan saus butter yang gurih manis dan aroma daun jeruk. Perpaduan tekstur renyah dengan saus creamy yang lezat.',
    image: '🦐',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 360,
    ingredients: [
      { name: 'Udang segar', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Butter', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tepung maizena', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan udang, buang kulit dan kepala. Kerat punggung.',
      'Lumuri udang dengan tepung maizena dan garam.',
      'Goreng udang sebentar hingga berwarna merah muda. Angkat, tiriskan.',
      'Lelehkan butter di wajan, tumis bawang putih cincang hingga harum.',
      'Masukkan cabai rawit iris dan daun jeruk, tumis hingga wangi.',
      'Masukkan saus tiram, kecap manis, dan udang goreng. Aduk rata.',
      'Masak sebentar hingga saus meresap. Sajikan hangat.',
    ],
    tags: ['udang', 'butter sauce', 'seafood', 'gurih', 'creamy'],
    rating: 4.6,
  },
  {
    id: 'tumis-udang-petas',
    name: 'Tumis Udang Petas',
    description: 'Tumis udang dengan petas (pete) dan bumbu kecap yang gurih. Perpaduan aroma petas yang khas dengan udang segar yang lezat.',
    image: '🦐',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 280,
    ingredients: [
      { name: 'Udang segar', amount: 350, unit: 'gram', category: 'Protein' },
      { name: 'Petai', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan udang, buang kepala dan kulit.',
      'Iris tipis bawang merah, cincang bawang putih, potong cabai.',
      'Belah petai menjadi dua bagian.',
      'Panaskan minyak, tumis bawang merah dan bawang putih hingga harum.',
      'Masukkan cabai dan petai, tumis hingga layu.',
      'Masukkan udang, kecap manis, saus tiram, dan garam. Masak hingga udang berwarna merah.',
      'Aduk rata, masak sebentar. Sajikan hangat dengan nasi putih.',
    ],
    tags: ['udang', 'petai', 'tumis', 'kecap', 'gurih'],
    rating: 4.4,
  },
  {
    id: 'ayam-saus-padang',
    name: 'Ayam Saus Padang',
    description: 'Ayam goreng dengan saus Padang yang pedas, manis, dan gurih. Bumbu saus kental berwarna merah dengan cita rasa yang menggugah selera.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 400,
    ingredients: [
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Cabai merah keriting', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat merah', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Saus tomat', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Goreng ayam hingga setengah matang, angkat dan tiriskan.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan tomat.',
      'Tumis bumbu halus hingga matang dan minyak keluar.',
      'Tambahkan saus tomat, kecap manis, saus tiram, dan garam. Aduk rata.',
      'Masukkan ayam goreng, aduk hingga bumbu meresap dan saus mengental.',
      'Masak dengan api kecil selama 5 menit agar bumbu meresap sempurna.',
      'Sajikan dengan nasi putih hangat.',
    ],
    tags: ['ayam', 'saus Padang', 'pedas', 'manis', 'gurih'],
    rating: 4.7,
  },
  {
    id: 'daging-tumis-jamur',
    name: 'Daging Tumis Jamur',
    description: 'Tumis daging sapi dengan jamur kancing dan bumbu kecap yang lezat. Perpaduan daging yang empuk dan jamur yang kenyal dalam saus gurih.',
    image: '🥩',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 15,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'Daging sapi has dalam', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Jamur kancing', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Maizena', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging sapi tipis melawan serat. Potong jamur menjadi dua bagian.',
      'Marinasi daging dengan kecap asin dan merica selama 10 menit.',
      'Panaskan minyak, tumis bawang putih dan jahe hingga harum.',
      'Tumis daging hingga berubah warna, angkat sisihkan.',
      'Tumis bawang bombay dan jamur hingga layu.',
      'Masukkan daging, saus tiram, kecap manis, dan larutan maizena.',
      'Aduk rata hingga saus mengental dan meresap. Sajikan dengan nasi.',
    ],
    tags: ['daging sapi', 'tumis', 'jamur', 'kecap', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'telur-balado',
    name: 'Telur Balado Padang',
    description: 'Telur rebus yang dimasak dengan sambal balado khas Padang yang pedas dan gurih. Lauk sederhana tapi penuh rasa yang menggugah selera.',
    image: '🥚',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Telur ayam', amount: 6, unit: 'butir', category: 'Protein' },
      { name: 'Cabai merah keriting', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat merah', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Rebus telur hingga matang, kupas kulitnya. Goreng sebentar hingga kuning kecoklatan.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan tomat.',
      'Panaskan minyak, tumis bumbu halus hingga matang dan harum.',
      'Tambahkan garam dan gula merah, aduk rata.',
      'Masukkan telur goreng, aduk perlahan hingga bumbu meresap.',
      'Masak dengan api kecil selama 5 menit. Sajikan dengan nasi putih.',
    ],
    tags: ['telur', 'balado', 'Padang', 'pedas', 'sederhana'],
    rating: 4.4,
  },
  {
    id: 'perkedel-kentang-padang',
    name: 'Perkedel Kentang Padang',
    description: 'Perkedel kentang khas Padang dengan cincangan daging dan bumbu rempah. Tekstur lembut di dalam dan renyah di luar.',
    image: '🥔',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Kentang', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging sapi giling', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Seledri', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Goreng kentang hingga matang, angkat dan haluskan selagi hangat.',
      'Tumis daging giling hingga matang, sisihkan.',
      'Campurkan kentang halus, daging tumis, bawang merah goreng, daun bawang iris, dan seledri iris.',
      'Tambahkan garam, merica, dan pala. Aduk rata.',
      'Bentuk adonan bulat pipih, celupkan ke telur kocok.',
      'Goreng dalam minyak panas api sedang hingga kuning keemasan.',
      'Tiriskan, sajikan sebagai lauk pendamping nasi.',
    ],
    tags: ['perkedel', 'kentang', 'Padang', 'goreng', 'lauk'],
    rating: 4.4,
  },
  {
    id: 'sayur-gado-gado-padang',
    name: 'Sayur Gado Padang',
    description: 'Sayur gado-gado khas Padang dengan kuah santan kuning dan bumbu rempah. Campuran sayuran segar yang dimasak dengan santan gurih.',
    image: '🥬',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Nangka muda', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Labu siam', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 2, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Potong nangka muda dan labu siam bentuk dadu. Potong kacang panjang sepanjang 4 cm.',
      'Haluskan bawang merah, bawang putih, kunyit, dan cabai merah.',
      'Didihkan santan, masukkan bumbu halus dan daun kunyit.',
      'Masukkan nangka muda dan labu siam, masak hingga setengah empuk.',
      'Tambahkan kacang panjang, masak hingga sayuran matang.',
      'Terakhir masukkan tauge, masak sebentar saja. Bumbui garam.',
      'Sajikan hangat sebagai lauk pendamping nasi Padang.',
    ],
    tags: ['sayur gado', 'Padang', 'santan', 'sayuran', 'gurih'],
    rating: 4.3,
  },
  {
    id: 'gulai-otak',
    name: 'Gulai Otak Sapi',
    description: 'Gulai otak sapi dengan kuah santan kental berwarna kuning dan bumbu rempah yang kaya. Tekstur lembut otak berpadu dengan kuah gulai yang gurih.',
    image: '🍲',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 45,
    prepTime: 20,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Otak sapi', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan otak sapi, rendam air garam selama 15 menit. Kukus sebentar, potong-potong.',
      'Haluskan bawang merah, bawang putih, cabai merah, kunyit, dan jahe.',
      'Didihkan santan, masukkan bumbu halus, lengkuas, serai, daun jeruk, dan daun kunyit.',
      'Masak kuah dengan api kecil sambil diaduk agar santan tidak pecah.',
      'Masukkan potongan otak sapi ke dalam kuah.',
      'Masak dengan api kecil selama 30 menit hingga otak matang dan bumbu meresap.',
      'Bumbui garam, sajikan hangat dengan nasi putih.',
    ],
    tags: ['gulai', 'otak sapi', 'santan', 'Padang', 'rempah'],
    rating: 4.3,
  },
  {
    id: 'ikan-kakap-bakar',
    name: 'Ikan Kakap Bakar Kecap',
    description: 'Ikan kakap bakar dengan bumbu kecap yang manis gurih dan aroma arang. Daging ikan yang tebal dan lembut berpadu dengan bumbu yang meresap.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 3,
    calories: 300,
    ingredients: [
      { name: 'Ikan kakap', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Kecap manis', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan kakap, kerat-kerat dagingnya. Lumuri jeruk nipis dan garam.',
      'Haluskan bawang putih, bawang merah, jahe, dan cabai rawit.',
      'Campurkan bumbu halus dengan kecap manis sebagai olesan.',
      'Olesi ikan dengan bumbu kecap secara merata, diamkan 20 menit.',
      'Bakar ikan di atas arang atau grill pan, olesi bumbu berkala.',
      'Bakar kedua sisi hingga matang dan bumbu meresap.',
      'Sajikan dengan nasi putih dan sambal.',
    ],
    tags: ['kakap', 'bakar', 'kecap', 'ikan', 'panggang'],
    rating: 4.6,
  },
  {
    id: 'ayam-panggang-bumbu',
    name: 'Ayam Panggang Bumbu Rujak',
    description: 'Ayam panggang dengan bumbu rujak yang pedas manis khas Jawa. Bumbu meresap sempurna dengan aroma rempah yang menggugah selera.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 25,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Cabai merah', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, kunyit, dan jahe.',
      'Tumis bumbu halus hingga matang dan harum.',
      'Tambahkan kecap manis, gula merah, dan garam. Masak hingga kental.',
      'Olesi ayam dengan bumbu rujak secara merata, diamkan 30 menit.',
      'Panggang ayam di oven 180°C atau di atas grill pan.',
      'Panggang selama 30-35 menit, olesi bumbu secara berkala.',
      'Sajikan dengan nasi putih dan lalapan segar.',
    ],
    tags: ['ayam', 'panggang', 'bumbu rujak', 'pedas manis', 'Jawa'],
    rating: 4.7,
  },
  {
    id: 'tahu-goreng-kuah',
    name: 'Tahu Goreng Kuah Santan',
    description: 'Tahu goreng disajikan dengan kuah santan kuning yang gurih dan hangat. Perpaduan tahu renyah dengan kuah santan yang nikmat.',
    image: '🧈',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'Tahu putih', amount: 6, unit: 'buah', category: 'Protein' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 200, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Potong tahu bentuk dadu, goreng hingga kuning kecoklatan dan renyah.',
      'Haluskan bawang merah, bawang putih, kunyit, dan cabai merah.',
      'Didihkan santan, masukkan bumbu halus dan daun salam.',
      'Masak kuah dengan api kecil sambil diaduk hingga mendidih.',
      'Bumbui garam, koreksi rasa.',
      'Tata tahu goreng di mangkuk, siram dengan kuah santan panas.',
      'Sajikan hangat dengan nasi putih dan sambal.',
    ],
    tags: ['tahu', 'goreng', 'kuah santan', 'gurih', 'sederhana'],
    rating: 4.3,
  },
  {
    id: 'kue-tarts-nanas',
    name: 'Kue Tarts Nanas',
    description: 'Kue tart kecil dengan isian selai nanas homemade yang manis asam segar. Kulit tart yang renyah berpadu dengan selai nanas yang lezat.',
    image: '🥧',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 45,
    servings: 20,
    calories: 120,
    ingredients: [
      { name: 'Tepung terigu', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 130, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Nanas matang', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Gula pasir (selai)', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Parut nanas, masak dengan gula pasir di api kecil hingga kering dan bisa digelindingkan.',
      'Kocok mentega dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Masukkan tepung terigu sedikit demi sedikit, aduk dengan spatula hingga adonan bisa dibentuk.',
      'Cetak adonan di cetakan tart kecil, tekan tipis rata.',
      'Isi tengah cetakan dengan selai nanas yang sudah dingin.',
      'Panggang oven 160°C selama 20-25 menit hingga matang keemasan.',
      'Dinginkan, sajikan sebagai camilan atau hidangan penutup.',
    ],
    tags: ['tart', 'nanas', 'kue', 'manis asam', 'camilan'],
    rating: 4.5,
  },
  {
    id: 'nasi-goreng-kambing-madura',
    name: 'Nasi Goreng Kambing Madura',
    description: 'Nasi goreng khas Madura dengan potongan daging kambing yang empuk dan bumbu rempah yang kuat. Aroma khas yang menggugah selera saat malam hari.',
    image: '🍛',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 3,
    calories: 480,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging kambing', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging kambing kecil-kecil, tumis hingga empuk. Sisihkan.',
      'Haluskan bawang merah, bawang putih, dan cabai merah.',
      'Panaskan minyak, tumis bumbu halus hingga harum.',
      'Masukkan daging kambing tumis, aduk rata.',
      'Tambahkan nasi dingin, aduk dengan api besar hingga nasi terpisah.',
      'Tuang kecap manis, saus tiram, dan garam. Aduk rata.',
      'Masukkan irisan daun bawang, aduk sebentar. Sajikan dengan acar dan kerupuk.',
    ],
    tags: ['nasi goreng', 'kambing', 'Madura', 'rempah', 'malam'],
    rating: 4.6,
  },
  {
    id: 'nasi-liwet-pandan',
    name: 'Nasi Liwet Pandan',
    description: 'Nasi liwet yang dimasak dengan santan dan daun pandan sehingga harum dan gurih. Lauk lengkap dengan ayam suwir, teri, dan tempe orek.',
    image: '🍚',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'Beras', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Ayam suwir', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Teri medan', amount: 50, unit: 'gram', category: 'Protein' },
      { name: 'Tempe orek', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Telur dadar iris', amount: 2, unit: 'butir', category: 'Protein' },
    ],
    steps: [
      'Cuci beras hingga bersih, tiriskan.',
      'Campurkan santan dengan air (total 600ml), masukkan daun pandan, daun salam, serai, dan garam.',
      'Masukkan beras ke rice cooker, tuang campuran santan. Masak hingga matang.',
      'Siapkan lauk: ayam suwir, orek tempe, dan teri medan goreng.',
      'Buat telur dadar tipis, iris menjadi pita-pita.',
      'Sajikan nasi liwet di piring daun pisang.',
      'Tata ayam suwir, teri, orek tempe, dan telur dadar di sekeliling nasi.',
    ],
    tags: ['nasi liwet', 'pandan', 'santan', 'Sunda', 'lauk lengkap'],
    rating: 4.6,
  },
  {
    id: 'ayam-bakar-kecap',
    name: 'Ayam Bakar Kecap Manis',
    description: 'Ayam bakar dengan olesan kecap manis yang meresap dan menghasilkan warna kecoklatan menggoda. Rasa manis gurih dengan aroma arang yang khas.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Kecap manis', amount: 5, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, jahe, dan cabai rawit.',
      'Ungkep ayam dengan bumbu halus, garam, merica, dan sedikit air.',
      'Masak hingga air menyusut dan bumbu meresap ke dalam ayam.',
      'Campurkan sisa bumbu ungkepan dengan kecap manis sebagai olesan.',
      'Bakar ayam di atas arang atau grill pan, olesi bumbu kecap secara berkala.',
      'Bakar hingga kedua sisi matang dan berwarna kecoklatan.',
      'Sajikan dengan nasi putih, lalapan, dan sambal.',
    ],
    tags: ['ayam', 'bakar', 'kecap', 'manis gurih', 'panggang'],
    rating: 4.8,
  },
  {
    id: 'ikan-tongkol-bumbu',
    name: 'Ikan Tongkol Bumbu Kuning',
    description: 'Ikan tongkol dimasak dengan bumbu kuning santan yang gurih dan harum. Kuah kental berwarna kuning dengan potongan tongkol yang empuk.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Ikan tongkol', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong ikan tongkol sesuai selera, cuci bersih.',
      'Haluskan bawang merah, bawang putih, kunyit, jahe, dan cabai merah.',
      'Didihkan santan, masukkan bumbu halus, daun salam, dan serai.',
      'Masak kuah dengan api kecil sambil diaduk hingga mendidih.',
      'Masukkan potongan tongkol, masak dengan api kecil.',
      'Bumbui garam, masak hingga kuah sedikit menyusut dan bumbu meresap.',
      'Sajikan hangat dengan nasi putih.',
    ],
    tags: ['tongkol', 'bumbu kuning', 'santan', 'ikan', 'gurih'],
    rating: 4.4,
  },
  {
    id: 'sate-lilit-ayam',
    name: 'Sate Lilit Ayam Bali',
    description: 'Sate lilit ayam khas Bali yang dibalut di sekeliling tusuk bambu atau serai. Perpaduan daging ayam cincang dengan kelapa parut dan bumbu genep.',
    image: '🍢',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 30,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Daging ayam cincang', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Kelapa parut', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kemiri', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Daun jeruk iris', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, cabai, kunyit, jahe, dan kemiri (bumbu genep).',
      'Campurkan daging ayam cincang dengan bumbu genep, kelapa parut, daun jeruk iris, garam, dan gula merah.',
      'Uleni adonan hingga kalis dan bisa dibentuk.',
      'Ambil adonan, lilitkan memanjang di sekeliling batang serai atau tusuk bambu yang sudah dialasi daun pisang.',
      'Bakar sate lilit di atas arang atau grill pan dengan api sedang.',
      'Bolak-balik hingga matang dan berwarna kecoklatan.',
      'Sajikan dengan sambal matah dan nasi putih.',
    ],
    tags: ['sate lilit', 'ayam', 'Bali', 'bumbu genep', 'panggang'],
    rating: 4.7,
  },
  {
    id: 'kambing-guling',
    name: 'Kambing Guling',
    description: 'Kambing guling khas Bali dengan bumbu bawang, cabai, dan rempah yang meresap sempurna. Daging yang empuk dan juicy dengan kulit yang renyah.',
    image: '🐐',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 180,
    prepTime: 60,
    servings: 8,
    calories: 520,
    ingredients: [
      { name: 'Kambing (kaki dan paha)', amount: 2, unit: 'kg', category: 'Protein' },
      { name: 'Bawang merah', amount: 10, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Kemiri', amount: 5, unit: 'butir', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 6, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 4, unit: 'batang', category: 'Bumbu' },
      { name: 'Garam', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan kambing, kerat-kerat daging agar bumbu meresap.',
      'Haluskan bawang merah, bawang putih, cabai, kunyit, jahe, lengkuas, dan kemiri.',
      'Tumis bumbu halus dengan daun jeruk dan serai hingga matang.',
      'Bumbui kambing dengan bumbu tumis, garam, dan gula merah secara merata.',
      'Diamkan minimal 2 jam di kulkas agar bumbu meresap sempurna.',
      'Panggang kambing di atas arang dengan cara diputar perlahan.',
      'Panggang selama 2-3 jam sambil sesekali diolesi bumbu hingga matang dan kulit renyah.',
    ],
    tags: ['kambing', 'guling', 'Bali', 'panggang', 'rempah'],
    rating: 4.8,
  },
  {
    id: 'ayam-rica-rica',
    name: 'Ayam Rica-Rica Manado',
    description: 'Ayam rica-rica khas Manado dengan bumbu cabai, jahe, dan daun kemangi yang pedas segar. Kuahnya yang merah dengan aroma harum kemangi.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 35,
    prepTime: 20,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Cabai merah', amount: 12, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun kemangi', amount: 2, unit: 'ikat', category: 'Sayuran' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, jahe, dan kunyit.',
      'Panaskan minyak, tumis bumbu halus bersama daun jeruk hingga matang dan harum.',
      'Masukkan ayam potong, aduk hingga berubah warna.',
      'Tambahkan air secukupnya, masak dengan api kecil hingga ayam empuk.',
      'Bumbui garam dan gula merah, masak hingga kuah mengental.',
      'Masukkan daun kemangi, aduk sebentar hingga layu.',
      'Sajikan hangat dengan nasi putih.',
    ],
    tags: ['ayam', 'rica-rica', 'Manado', 'pedas', 'kemangi'],
    rating: 4.7,
  },
  {
    id: 'ikan-mujair-bakar',
    name: 'Ikan Mujair Bakar',
    description: 'Ikan mujair bakar dengan bumbu kecap dan rempah yang meresap. Lauk ikan air tawar yang sederhana tapi lezat untuk makan malam.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 20,
    servings: 3,
    calories: 290,
    ingredients: [
      { name: 'Ikan mujair', amount: 2, unit: 'ekor', category: 'Protein' },
      { name: 'Kecap manis', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan mujair, kerat-kerat daging. Lumuri jeruk nipis dan garam.',
      'Haluskan bawang putih, bawang merah, cabai rawit, dan jahe.',
      'Campurkan bumbu halus dengan kecap manis sebagai olesan.',
      'Olesi ikan dengan bumbu, diamkan 20 menit.',
      'Bakar ikan di atas arang atau grill pan, olesi bumbu berkala.',
      'Bakar kedua sisi hingga matang.',
      'Sajikan dengan nasi putih dan sambal.',
    ],
    tags: ['mujair', 'bakar', 'kecap', 'ikan air tawar', 'sederhana'],
    rating: 4.4,
  },
  {
    id: 'sop-ikan',
    name: 'Sop Ikan Bumbu Kuning',
    description: 'Sop ikan dengan kuah kuning santan yang gurih dan hangat. Potongan ikan segar dengan sayuran dalam kuah rempah yang menyegarkan.',
    image: '🍲',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Ikan kakap atau kerapu', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Tomat', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Potong ikan menjadi bagian-bagian, cuci bersih.',
      'Haluskan bawang merah, bawang putih, kunyit, dan jahe.',
      'Didihkan santan, masukkan bumbu halus dan daun salam.',
      'Masukkan potongan tomat, masak hingga kuah mendidih.',
      'Masukkan potongan ikan, masak dengan api kecil hingga ikan matang.',
      'Bumbui garam, tambahkan irisan daun bawang.',
      'Sajikan hangat dengan perasan jeruk nipis dan nasi.',
    ],
    tags: ['sop ikan', 'kuah kuning', 'santan', 'hangat', 'segar'],
    rating: 4.4,
  },
  {
    id: 'tahu-gejrot-kuah',
    name: 'Tahu Gejrot Kuah Pedas',
    description: 'Tahu pong goreng disiram kuah gejrot pedas manis khas Cirebon. Perpaduan tahu renyah dengan kuah pedas yang segar dan menggugah selera.',
    image: '🧈',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 3,
    calories: 200,
    ingredients: [
      { name: 'Tahu pong', amount: 8, unit: 'buah', category: 'Protein' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air asam', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Petis', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air panas', amount: 150, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Goreng tahu pong hingga renyah di luar tapi tetap lembut di dalam.',
      'Haluskan cabai rawit, cabai merah, dan bawang merah.',
      'Campurkan bumbu halus dengan kecap manis, gula merah, garam, air asam, petis, dan air panas.',
      'Aduk rata kuah gejrot hingga semua bumbu larut.',
      'Potong-potong tahu pong goreng, tata di mangkuk.',
      'Siram kuah gejrot di atas tahu goreng.',
      'Sajikan selagi hangat sebagai camilan atau lauk.',
    ],
    tags: ['tahu gejrot', 'Cirebon', 'pedas manis', 'kuah', 'camilan'],
    rating: 4.5,
  },
  {
    id: 'sayur-krecek-padang',
    name: 'Sayur Krecek Padang',
    description: 'Sayur krecek khas Padang dari kulit sapi yang dimasak dengan santan dan bumbu rempah. Tekstur kenyal dengan kuah santan kuning yang gurih.',
    image: '🍲',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Krecek kulit sapi', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam krecek kulit sapi dalam air hangat selama 15 menit. Tiriskan.',
      'Haluskan bawang merah, bawang putih, cabai merah, cabai rawit, dan kunyit.',
      'Didihkan santan, masukkan bumbu halus, daun kunyit, daun salam, dan serai.',
      'Masak kuah dengan api kecil sambil diaduk hingga mendidih.',
      'Masukkan krecek, masak hingga mengembang dan empuk.',
      'Bumbui garam, masak hingga kuah mengental dan bumbu meresap.',
      'Sajikan hangat dengan nasi putih dan lauk Padang lainnya.',
    ],
    tags: ['krecek', 'Padang', 'kulit sapi', 'santan', 'gurih'],
    rating: 4.3,
  },
  {
    id: 'tumis-kulit-sapi',
    name: 'Tumis Kulit Sapi',
    description: 'Tumis kulit sapi dengan bumbu kecap dan cabai yang gurih pedas. Tekstur kenyal kulit sapi berpadu dengan bumbu yang meresap.',
    image: '🥘',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 15,
    servings: 3,
    calories: 260,
    ingredients: [
      { name: 'Kulit sapi', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Rebus kulit sapi hingga empuk, potong-potong sesuai selera.',
      'Iris tipis bawang merah, cincang bawang putih, potong cabai.',
      'Panaskan minyak, tumis bawang merah dan bawang putih hingga harum.',
      'Masukkan cabai dan daun salam, tumis hingga layu.',
      'Masukkan kulit sapi, kecap manis, dan saus tiram.',
      'Masak dengan api sedang sambil diaduk hingga bumbu meresap.',
      'Bumbui garam, sajikan hangat dengan nasi putih.',
    ],
    tags: ['kulit sapi', 'tumis', 'kecap', 'kenyal', 'gurih'],
    rating: 4.3,
  },
  {
    id: 'bakso-goreng',
    name: 'Bakso Goreng Crispy',
    description: 'Bakso goreng renyah dengan tekstur garing di luar dan kenyal di dalam. Bisa dimakan langsung atau ditambahkan ke dalam mie goreng.',
    image: '🥘',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 25,
    servings: 4,
    calories: 270,
    ingredients: [
      { name: 'Daging sapi giling', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Tepung tapioka', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih goreng', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang putih goreng. Campurkan dengan daging giling, garam, dan merica.',
      'Uleni adonan bakso, masukkan es batu sedikit demi sedikit agar kenyal.',
      'Tambahkan tepung tapioka, tepung terigu, telur, dan daun bawang. Uleni rata.',
      'Bulatkan adonan bakso sesuai ukuran yang diinginkan.',
      'Panaskan minyak, goreng bakso dengan api sedang hingga kuning keemasan.',
      'Tiriskan, sajikan dengan saus sambal atau sebagai campuran mie.',
    ],
    tags: ['bakso', 'goreng', 'crispy', 'sapi', 'camilan'],
    rating: 4.4,
  },
];
