import type { Recipe } from '@/types';
import { westernRecipes } from './recipes/western';

export const recipes: Recipe[] = [
  {
    id: 'nasi-goreng',
    name: 'Nasi Goreng',
    description:
      'Nasi goreng khas Indonesia dengan bumbu kecap manis, cabai, dan sayuran segar. Lauk pelengkap telur dadar, kerupuk, dan acar.',
    image: '🍛',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 2,
    calories: 450,
    ingredients: [
      { name: 'Nasi putih (dingin)', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk udang', amount: 5, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Acar timun & wortel', amount: 50, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang halus bawang merah, bawang putih, dan cabai merah keriting.',
      'Panaskan minyak goreng di wajan dengan api besar. Tumis bumbu halus hingga harum, sekitar 1-2 menit.',
      'Masukkan telur, orak-arik hingga setengah matang.',
      'Tambahkan nasi dingin, aduk rata dengan api besar selama 3-4 menit hingga nasi terpisah dan sedikit kering.',
      'Tuangkan kecap manis dan saus tiram. Aduk rata hingga semua butiran nasi berwarna merata.',
      'Masukkan irisan daun bawang, aduk sebentar.',
      'Sajikan dengan kerupuk udang, acar, dan telur dadar di atasnya.',
    ],
    tags: ['nasi', 'goreng', 'kecap', 'cepat saji', 'populer'],
    rating: 4.9,
    youtubeUrl: 'https://www.youtube.com/watch?v=RLzC7W0zc8Q',
  },
  {
    id: 'mie-goreng',
    name: 'Mie Goreng',
    description:
      'Mie goreng spesial dengan bumbu kecap, sayuran segar, dan telur. Cocok untuk makan siang yang mengenyangkan.',
    image: '🍜',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 8,
    prepTime: 10,
    servings: 2,
    calories: 520,
    ingredients: [
      { name: 'Mie kuning basah', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Sawi hijau', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol (kubis)', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kerupuk', amount: 5, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Didihkan air, rebus mie kuning selama 2 menit. Tiriskan dan siram air dingin agar tidak lengket.',
      'Cincang halus bawang merah, bawang putih, dan cabai rawit. Iris sawi dan kol.',
      'Panaskan minyak di wajan. Tumis bumbu halus hingga harum.',
      'Masukkan telur, orak-arik hingga setengah matang.',
      'Tambahkan sawi dan kol, tumis sebentar hingga layu.',
      'Masukkan mie, kecap manis, dan saus tiram. Aduk rata dengan api besar selama 3 menit.',
      'Sajikan dengan kerupuk dan acar.',
    ],
    tags: ['mie', 'goreng', 'kecap', 'cepat saji', 'populer'],
    rating: 4.7,
    youtubeUrl: 'https://www.youtube.com/watch?v=pWBrMKm6XtE',
  },
  {
    id: 'ayam-goreng',
    name: 'Ayam Goreng Kremes',
    description:
      'Ayam goreng renyah dengan bumbu kuning yang meresap hingga ke tulang. Disajikan dengan sambal dan lalapan.',
    image: '🍗',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 30,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Ayam potong (4 bagian)', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tepung beras', amount: 100, unit: 'gram', category: 'Bahan Sambal' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang putih, bawang merah, kunyit, jahe, dan lengkuas menggunakan blender atau cobek.',
      'Bumbui ayam dengan bumbu halus, serai yang dimemarkan, daun salam, dan garam. Aduk rata dan diamkan minimal 30 menit (lebih baik semalam di kulkas).',
      'Masukkan ayam ke dalam panci, tambahkan air hingga ayam setengah terendam. Ungkep dengan api kecil selama 25 menit hingga bumbu meresap dan air menyusut.',
      'Angkat ayam, tiriskan hingga kering sempurna.',
      'Campurkan tepung beras dengan sedikit air bumbu ungkepan untuk adonan kremesan.',
      'Panaskan minyak goreng dengan api sedang. Goreng ayam hingga kuning keemasan dan renyah, sekitar 8-10 menit.',
      'Siramkan adonan kremesan ke minyak goreng untuk membuat kerak renyah.',
      'Sajikan dengan lalapan (timun, kemangi, kol) dan sambal.',
    ],
    tags: ['ayam', 'goreng', 'kremes', 'kuning', 'populer'],
    rating: 4.8,
    youtubeUrl: 'https://www.youtube.com/watch?v=RQx0VNq5LBw',
  },
  {
    id: 'soto-ayam',
    name: 'Soto Ayam',
    description:
      'Soto ayam bening khas Jawa dengan kuah kuning gurih, suwiran ayam, telur rebus, tauge, dan kerupuk emping.',
    image: '🍲',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Ayam potong', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Air', amount: 1500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Mie kuning', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur rebus', amount: 4, unit: 'butir', category: 'Protein' },
      { name: 'Bawang goreng', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Kerupuk emping', amount: 10, unit: 'butir', category: 'Pelengkap' },
      { name: 'Jeruk nipis', amount: 2, unit: 'buah', category: 'Pelengkap' },
      { name: 'Garam dan merica', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang putih, bawang merah, kunyit, dan jahe.',
      'Didihkan air dalam panci besar. Masukkan ayam, bumbu halus, lengkuas yang digeprek, serai yang dimemarkan, daun salam, dan daun jeruk.',
      'Masak dengan api kecil selama 35 menit hingga ayam empuk dan kuah beraroma harum. Beri garam dan merica.',
      'Angkat ayam, suwir-suwir dagingnya. Kembalikan tulang ke kuah untuk menambah rasa.',
      'Seduh tauge dengan air panas, tiriskan. Rebus mie kuning sebentar, tiriskan.',
      'Tata di mangkuk: mie kuning, suwiran ayam, tauge, dan telur rebus yang dibelah dua.',
      'Siram dengan kuah soto panas.',
      'Taburi bawang goreng dan kerupuk emping. Sajikan dengan perasan jeruk nipis dan sambal.',
    ],
    tags: ['soto', 'ayam', 'kuah', 'kuning', 'hangat'],
    rating: 4.8,
    youtubeUrl: 'https://www.youtube.com/watch?v=WswQ9RV3jL4',
  },
  {
    id: 'rendang',
    name: 'Rendang Daging',
    description:
      'Rendang daging sapi khas Minangkabau dengan bumbu rempah yang kaya dan dimasak hingga kering. Lauk wajib saat Lebaran.',
    image: '🥩',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 180,
    prepTime: 45,
    servings: 6,
    calories: 550,
    ingredients: [
      { name: 'Daging sapi (has dalam)', amount: 750, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kelapa parut sangrai (serundeng)', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Cabai merah besar', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 4, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 2, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 1, unit: 'potong', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging sapi berukuran 5x5 cm. Cuci bersih dan tiriskan.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, jahe, dan kunyit menggunakan blender.',
      'Panaskan sedikit minyak, tumis bumbu halus bersama lengkuas yang digeprek, serai yang dimemarkan, daun jeruk, dan daun kunyit hingga harum.',
      'Masukkan daging sapi, aduk hingga berubah warna.',
      'Tuangkan santan kental sedikit demi sedikit sambil terus diaduk agar santan tidak pecah.',
      'Masak dengan api kecil selama 2-3 jam. Aduk sesekali. Tambahkan garam dan gula merah di tengah proses.',
      'Saat kuah mulai menyusut dan minyak keluar, masukkan serundeng kelapa. Aduk rata.',
      'Terus masak hingga kuah benar-benar kering dan daging berwarna coklat gelap. Matikan api.',
      'Sajikan dengan nasi putih hangat. Rendang makin enak saat disimpan dan dipanaskan kembali.',
    ],
    tags: ['rendang', 'daging sapi', 'Padang', 'rempah', 'Lebaran'],
    rating: 5.0,
    youtubeUrl: 'https://www.youtube.com/watch?v=jn6JY5FxSbE',
  },
  {
    id: 'gado-gado',
    name: 'Gado-Gado',
    description:
      'Salad Indonesia dengan sayuran rebus, tahu, tempe, telur, dan bumbu kacang yang gurih. Makanan sehat dan bergizi.',
    image: '🥗',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 3,
    calories: 400,
    ingredients: [
      { name: 'Kacang tanah sangrai', amount: 200, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Tahu goreng', amount: 3, unit: 'buah', category: 'Protein' },
      { name: 'Tempe goreng', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Kangkung', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol (kubis)', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kentang rebus', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Telur rebus', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Kerupuk', amount: 10, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus kangkung, kol, dan tauge sebentar (masing-masing 1 menit). Tiriskan dan atur di piring saji.',
      'Haluskan kacang tanah sangrai, cabai merah, cabai rawit, dan bawang putih menggunakan cobek atau blender.',
      'Tambahkan kecap manis dan gula merah ke bumbu kacang. Aduk rata. Tambahkan sedikit air panas jika terlalu kental.',
      'Potong-potong tahu goreng, tempe goreng, kentang rebus, dan telur rebus.',
      'Tata sayuran rebus, tahu, tempe, kentang, dan telur di piring saji.',
      'Siram dengan saus kacang secara merata.',
      'Taburi kerupuk di atasnya. Sajikan dengan lontong atau nasi.',
    ],
    tags: ['gado-gado', 'kacang', 'sayuran', 'sehat', 'vegetarian-option'],
    rating: 4.6,
    youtubeUrl: 'https://www.youtube.com/watch?v=kXWsrV3LjMU',
  },
  {
    id: 'nasi-padang',
    name: 'Nasi Padang Komplit',
    description:
      'Nasi putih hangat disajikan dengan berbagai lauk Padang: rendang, ayam pop, sayur nangka, dan sambal hijau.',
    image: '🍚',
    category: 'Makan Siang',
    difficulty: 'Susah',
    cookTime: 90,
    prepTime: 30,
    servings: 4,
    calories: 680,
    ingredients: [
      { name: 'Nasi putih', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging sapi (untuk rendang mini)', amount: 250, unit: 'gram', category: 'Protein' },
      { name: 'Ayam (untuk ayam pop)', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Nangka muda', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Santan', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cabai hijau', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Serai', amount: 3, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Masak nasi putih menggunakan rice cooker.',
      'Bumbui ayam dengan bawang putih halus dan garam. Kukus ayam selama 30 menit hingga matang.',
      'Goreng ayam kukus sebentar (ayam pop) hanya hingga kulit sedikit renyah. Angkat, pukul-pukul agar daging lepas dari tulang.',
      'Untuk sayur nangka: rebus nangka muda hingga setengah empuk. Tumis bumbu halus, masukkan nangka dan santan. Masak hingga matang.',
      'Untuk sambal hijau: goreng cabai hijau dan tomat hijau sebentar. Ulek kasar bersama bawang merah goreng dan garam.',
      'Untuk rendang mini: masak daging dengan bumbu halus dan santan selama 1.5 jam dengan api kecil hingga kering.',
      'Tata nasi putih di piring. Susun ayam pop, sayur nangka, rendang mini, dan sambal hijau di sekelilingnya.',
      'Sajikan dengan kerupuk merah dan daun singkong.',
    ],
    tags: ['Padang', 'nasi', 'komplit', 'rendang', 'ayam pop'],
    rating: 4.9,
    youtubeUrl: 'https://www.youtube.com/watch?v=R8E4GCi5wDU',
  },
  {
    id: 'bakso',
    name: 'Bakso Sapi',
    description:
      'Bakso sapi homemade dengan kuah gurih yang hangat, disajikan dengan mie kuning, bihun, tahu, dan sambal.',
    image: '🥣',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 35,
    prepTime: 45,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Daging sapi giling', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Tepung tapioka', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih goreng', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu', amount: 5, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Air kaldu tulang sapi', amount: 1500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah goreng', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Mie kuning', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bihun', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tahu putih', amount: 4, unit: 'buah', category: 'Protein' },
      { name: 'Seledri', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang goreng', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Sambal', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Haluskan bawang putih goreng. Campurkan dengan daging giling, garam, dan merica. Uleni hingga adonan kalis.',
      'Masukkan es batu dan tepung tapioka sedikit demi sedikit. Uleni kembali hingga adonan elastis dan kenyal.',
      'Rebus air dalam panci besar. Bulatkan adonan bakso dengan sendok dan masukkan ke air rebusan. Masak hingga bakso mengambang (±8 menit). Angkat dan tiriskan.',
      'Untuk kuah: tumis bawang putih cincang hingga harum, masukkan ke air kaldu. Bumbui garam dan merica.',
      'Rebus mie kuning dan bihun sebentar, tiriskan.',
      'Goreng tahu putih sebentar hingga kuning kecoklatan.',
      'Tata di mangkuk: mie, bihun, bakso, tahu goreng. Siram kuah panas.',
      'Taburi seledri iris dan bawang goreng. Sajikan dengan sambal dan kecap manis.',
    ],
    tags: ['bakso', 'sapi', 'kuah', 'hangat', 'populer'],
    rating: 4.7,
    youtubeUrl: 'https://www.youtube.com/watch?v=KpMxlb0ED3o',
  },
  {
    id: 'sate-ayam',
    name: 'Sate Ayam Madura',
    description:
      'Sate ayam dengan bumbu kacang khas Madura yang manis gurih. Dibakar di atas arang dengan aroma smoky yang menggoda.',
    image: '🍢',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 40,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'Daging ayam fillet', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Kacang tanah sangrai', amount: 200, unit: 'gram', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Lontong', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Bawang merah goreng', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Potong daging ayam fillet berukuran 2x2 cm.',
      'Marinasi ayam dengan campuran kecap asin, bawang putih halus, dan garam selama minimal 30 menit.',
      'Tusukkan potongan ayam ke tusuk sate bambu (5-6 potong per tusuk). Ratakan.',
      'Haluskan kacang tanah sangrai. Tumis bawang merah dan cabai merah hingga layu. Masukkan ke dalam kacang halus.',
      'Tambahkan kecap manis, gula merah, dan sedikit air ke campuran kacang. Aduk rata hingga menjadi saus kacang yang kental.',
      'Bakar sate di atas arang atau pemanggang, bolak-balik dan olesi saus kacang sesekali selama 10-12 menit hingga matang.',
      'Sajikan sate dengan saus kacang yang tersisa, lontong, dan taburan bawang merah goreng.',
    ],
    tags: ['sate', 'ayam', 'Madura', 'kacang', 'panggang'],
    rating: 4.9,
    youtubeUrl: 'https://www.youtube.com/watch?v=easIgRCQ7I0',
  },
  {
    id: 'nasi-uduk',
    name: 'Nasi Uduk',
    description:
      'Nasi yang dimasak dengan santan, daun salam, dan serai sehingga beraroma harum gurih. Disajikan dengan lauk-pelengkap.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Beras', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Ayam goreng suwir', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Orek tempe', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Telur dadar iris', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang goreng', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Sambal', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci beras hingga bersih, tiriskan.',
      'Campurkan santan dengan air (total ±600ml). Masukkan daun salam, serai yang dimemarkan, daun jeruk, dan garam. Aduk rata.',
      'Masukkan beras ke dalam rice cooker. Tuang campuran santan. Masak seperti biasa.',
      'Setelah matang, aduk rata nasi uduk. Biarkan 5 menit sebelum dibuka.',
      'Siapkan lauk: ayam goreng suwir, orek tempe, dan telur dadar yang diiris tipis.',
      'Penyajian: cetak nasi uduk di mangkuk, balikkan ke piring. Tata lauk di sekelilingnya.',
      'Taburi bawang goreng. Sajikan dengan sambal dan kerupuk.',
    ],
    tags: ['nasi', 'uduk', 'santan', 'sarapan', 'Betawi'],
    rating: 4.6,
  },
  {
    id: 'bubur-ayam',
    name: 'Bubur Ayam',
    description:
      'Bubur ayam hangat dengan kuah kuning gurih, suwiran ayam, telur, kerupuk, dan cakwe. Sarapan favorit orang Indonesia.',
    image: '🥣',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 15,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air kaldu ayam', amount: 1000, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Dada ayam', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak wijen', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Telur rebus', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Kerupuk bawang', amount: 10, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Cakwe', amount: 4, unit: 'batang', category: 'Pelengkap' },
      { name: 'Bawang goreng', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Seledri iris', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci beras, rendam 30 menit. Masak bubur dengan air kaldu di api kecil selama 30-40 menit hingga mengental, aduk sesekali.',
      'Rebus dada ayam dengan serai, daun salam, dan garam hingga matang. Suwir-suwir dagingnya.',
      'Haluskan bawang putih, bawang merah, kunyit, dan jahe. Tumis bumbu halus hingga harum.',
      'Masukkan suwiran ayam ke tumisan bumbu, tambahkan kecap asin dan minyak wijen. Aduk rata. Angkat.',
      'Untuk kuah: rebus air kaldu sisa, bumbui garam dan merica secukupnya.',
      'Penyajian: taruh bubur di mangkuk, tambahkan suwiran ayam berbumbu.',
      'Siram kuah panas di atasnya.',
      'Taburi bawang goreng, seledri iris, kerupuk, irisan cakwe, dan telur rebus. Sajikan selagi hangat.',
    ],
    tags: ['bubur', 'ayam', 'sarapan', 'hangat', 'kuah'],
    rating: 4.7,
    youtubeUrl: 'https://www.youtube.com/watch?v=fNH7giPUGKc',
  },
  {
    id: 'perkedel',
    name: 'Perkedel Kentang',
    description:
      'Perkedel kentang goreng yang renyah di luar dan lembut di dalam. Lengkap dengan daun bawang dan seledri.',
    image: '🥔',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Kentang', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Seledri iris', amount: 2, unit: 'sendok makan', category: 'Sayuran' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Kupas kentang, potong-potong. Goreng dalam minyak banyak hingga matang dan empuk. Angkat, tiriskan.',
      'Haluskan kentang goreng selagi hangat menggunakan garpu atau potato masher. Jangan terlalu halus, biarkan sedikit bertekstur.',
      'Campurkan kentang halus dengan bawang merah goreng, daun bawang, seledri, garam, merica, dan pala. Aduk rata.',
      'Ambil 1 sendok makan adonan, bulatkan lalu pipihkan sedikit. Lakukan hingga adonan habis.',
      'Kocok lepas telur. Celupkan perkedel ke telur kocok.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan, sekitar 3-4 menit per sisi.',
      'Angkat, tiriskan di tisu dapur. Sajikan sebagai lauk atau camilan.',
    ],
    tags: ['perkedel', 'kentang', 'goreng', 'lauk', 'camilan'],
    rating: 4.5,
  },
  {
    id: 'tempe-orek',
    name: 'Tempe Orek',
    description:
      'Tempe orek kering dengan bumbu kecap manis yang gurih. Lauk sehari-hari yang tahan lama dan cocok untuk bekal.',
    image: '🫘',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 3,
    calories: 220,
    ingredients: [
      { name: 'Tempe', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Potong tempe berukuran 1x3 cm, agak tipis. Goreng sebentar hingga setengah kering. Angkat, tiriskan.',
      'Iris tipis bawang merah, cincang bawang putih, potong-potong cabai.',
      'Panaskan 3 sdm minyak goreng. Tumis bawang merah dan bawang putih hingga harum.',
      'Masukkan cabai rawit, cabai merah, dan daun salam. Tumis sebentar.',
      'Masukkan tempe goreng, aduk rata.',
      'Tambahkan kecap manis, garam, dan gula merah. Masak dengan api kecil sambil diaduk hingga bumbu meresap dan tempe kering.',
      'Angkat dan sajikan. Bisa disimpan di kulkas hingga 3 hari.',
    ],
    tags: ['tempe', 'orek', 'kecap', 'kering', 'lauk'],
    rating: 4.4,
  },
  {
    id: 'sayur-asem',
    name: 'Sayur Asem',
    description:
      'Sayur asem segar khas Sunda dengan kuah asam segar, labu siam, kacang panjang, jagung, dan melinjo.',
    image: '🥬',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 150,
    ingredients: [
      { name: 'Labu siam', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Jagung manis', amount: 2, unit: 'bonggol', category: 'Sayuran' },
      { name: 'Melinjo', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kangkung', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kecipir', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Asem jawa', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 1000, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ikan asin (opsional)', amount: 2, unit: 'ekor', category: 'Protein' },
    ],
    steps: [
      'Larutkan asem jawa dengan 3 sdm air panas, saring ambil airnya.',
      'Iris tipis bawang merah, cincang bawang putih. Potong labu siam, kacang panjang, dan jagung manis sesuai selera.',
      'Didihkan air dalam panci. Masukkan jagung manis dan melinjo terlebih dahulu (butuh waktu lebih lama).',
      'Setelah 5 menit, masukkan labu siam dan kacang panjang.',
      'Setelah sayuran setengah matang, masukkan bumbu iris: bawang merah, bawang putih, dan cabai rawit.',
      'Tuangkan air asem jawa. Bumbui garam dan gula merah. Masak hingga sayuran matang.',
      'Terakhir masukkan kangkung dan kecipir, masak sebentar saja agar tidak layu terlalu.',
      'Angkat, sajikan dengan ikan asin goreng dan sambal terasi.',
    ],
    tags: ['sayur asem', 'Sunda', 'asam', 'segar', 'sayuran'],
    rating: 4.5,
  },
  {
    id: 'plecing-kangkung',
    name: 'Plecing Kangkung',
    description:
      'Plecing kangkung khas Bali dan Lombok dengan sambal tomat pedas, kacang tanah, dan kelapa parut goreng.',
    image: '🌶️',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 2,
    calories: 160,
    ingredients: [
      { name: 'Kangkung', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Tomat merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Terasi', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kacang tanah goreng', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Kelapa parut goreng', amount: 30, unit: 'gram', category: 'Pelengkap' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 10, unit: 'gram', category: 'Bumbu' },
      { name: 'Jeruk limau', amount: 1, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Petik daun kangkung, cuci bersih. Rebus air, blansir kangkung sebentar (30 detik) hingga layu tapi masih renyah. Segera tiriskan dan siram air dingin.',
      'Tata kangkung di piring saji.',
      'Goreng sebentar tomat, cabai merah, cabai rawit, dan bawang merah hingga layu (jangan gosong).',
      'Ulek bahan goreng bersama terasi, garam, dan gula merah hingga kasar (sambal plecing).',
      'Tata sambal plecing di atas kangkung.',
      'Taburi kacang tanah goreng dan kelapa parut goreng.',
      'Berikan perasan jeruk limau di atasnya sebelum disajikan.',
    ],
    tags: ['plecing', 'kangkung', 'Bali', 'Lombok', 'sambal'],
    rating: 4.6,
  },
  {
    id: 'es-teh-manis',
    name: 'Es Teh Manis',
    description:
      'Minuman segar khas Indonesia yang menyegarkan. Teh manis dingin dengan es batu, minuman sehari-hari yang sederhana tapi nikmat.',
    image: '🧊',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 5,
    servings: 2,
    calories: 90,
    ingredients: [
      { name: 'Teh celup (atau teh tubruk)', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Air panas', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Jeruk nipis (opsional)', amount: 1, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Seduh teh celup dengan 400ml air panas selama 3-5 menit. Angkat teh celup.',
      'Masukkan gula pasir ke dalam teh panas, aduk hingga larut. Biarkan dingin.',
      'Setelah dingin, tuang ke dalam gelas.',
      'Tambahkan es batu secukupnya.',
      'Beri irisan jeruk nipis di pinggir gelas jika suka. Sajikan segera.',
    ],
    tags: ['es teh', 'minuman', 'dingin', 'segar', 'sederhana'],
    rating: 4.3,
  },
  {
    id: 'es-campur',
    name: 'Es Campur',
    description:
      'Es campur segar dengan aneka buah, cincau, biji selasih, kelapa muda, dan sirup manis. Dessert favorit di cuaca panas.',
    image: '🍧',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 2,
    calories: 250,
    ingredients: [
      { name: 'Kelapa muda', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Cincau hitam', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Biji selasih', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Nangka potong', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kolang-kaling', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Sirup cocopandan / gula merah cair', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Susu kental manis', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Kerok kelapa muda, ambil dagingnya. Potong cincau hitam berbentuk kubus kecil.',
      'Rendam biji selasih dalam air hangat selama 10 menit hingga mengembang.',
      'Siapkan gelas saji. Tata nangka, kolang-kaling, dan cincau hitam di dasar gelas.',
      'Masukkan daging kelapa muda dan biji selasih.',
      'Tambahkan es batu serut hingga gelas penuh.',
      'Tuangkan sirup cocopandan dan susu kental manis di atasnya.',
      'Aduk sebelum diminum. Sajikan segera.',
    ],
    tags: ['es campur', 'dessert', 'segar', 'buah', 'dingin'],
    rating: 4.7,
  },
  {
    id: 'klepon',
    name: 'Klepon',
    description:
      'Kue klepon tradisional dari tepung ketan berisi gula merah cair, dibalut kelapa parut. Jajan pasar favorit sepanjang masa.',
    image: '🟢',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Tepung ketan', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah (sisir halus)', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut (sangrai sebentar)', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air hangat', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Pewarna hijau (pandan atau daun suji)', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung ketan dengan air hangat sedikit demi sedikit, uleni hingga adonan kalis dan bisa dibentuk.',
      'Tambahkan pewarna hijau dari air daun suji/pandan, aduk rata hingga adonan berwarna hijau merata.',
      'Ambil sedikit adonan (±15 gram), pipihkan. Isi dengan 1 sendok teh gula merah sisir. Bulatkan kembali dan pastikan tidak bocor.',
      'Rebus air dalam panci. Masukkan klepon ke air rebusan. Masak hingga klepon mengambang (±5 menit), tanda sudah matang.',
      'Angkat klepon, langsung gulingkan di kelapa parut sangrai yang sudah ditaburi sedikit garam.',
      'Lakukan hingga adonan habis. Sajikan dalam piring atau cup.',
    ],
    tags: ['klepon', 'ketan', 'gula merah', 'jajan pasar', 'tradisional'],
    rating: 4.8,
    youtubeUrl: 'https://www.youtube.com/watch?v=e7dLpCKLz7E',
  },
  {
    id: 'pisang-goreng',
    name: 'Pisang Goreng Crispy',
    description:
      'Pisang goreng renyah berbalut adonan tepung crispy. Camilan gorengan favorit yang sempurna dinikmati saat hujan.',
    image: '🍌',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Pisang raja / kepok (matang)', amount: 6, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Air es', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Kupas pisang, potong-potong sesuai selera (bulat miring atau memanjang).',
      'Campurkan tepung terigu, tepung beras, gula pasir, garam, dan soda kue dalam mangkuk.',
      'Tambahkan air es sedikit demi sedikit sambil diaduk. Jangan terlalu encer, adonan harus cukup kental untuk melapisi pisang.',
      'Celupkan potongan pisang ke adonan tepung, pastikan terlapisi rata.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan dan renyah (±5 menit). Bolak-balik agar matang merata.',
      'Angkat, tiriskan di tisu dapur. Sajikan selagi hangat.',
    ],
    tags: ['pisang', 'goreng', 'crispy', 'camilan', 'gorengan'],
    rating: 4.5,
  },
  {
    id: 'martabak-manis',
    name: 'Martabak Manis',
    description:
      'Martabak manis tebal dengan isian coklat, keju, kacang, dan meses. Jajanan malam legendaris yang menggugah selera.',
    image: '🥞',
    category: 'Snack',
    difficulty: 'Susah',
    cookTime: 30,
    prepTime: 30,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'Tepung terigu protein sedang', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Air', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat chip / meises', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Keju parut', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Kacang tanah sangrai cincang', amount: 30, unit: 'gram', category: 'Isian' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Isian' },
      { name: 'Gula pasir (untuk taburan)', amount: 2, unit: 'sendok makan', category: 'Isian' },
    ],
    steps: [
      'Campurkan tepung terigu, gula pasir, ragi instan, dan soda kue. Buat lubang di tengah.',
      'Masukkan telur, susu cair, dan air. Aduk rata hingga adonan licin dan tidak bergerindil. Diamkan 1 jam hingga mengembang.',
      'Panaskan wajan anti lengket dengan api kecil (gunakan api terkecil). Olesi sedikit margarine.',
      'Tuangkan setengah adonan, ratakan hingga menipis dan membentuk lingkaran besar.',
      'Taburi sedikit gula pasir di permukaan. Tutup wajan dan biarkan hingga permukaan kering dan berlubang-lubang (±5 menit).',
      'Olesi permukaan martabak dengan margarine. Taburi coklat chip, keju parut, kacang cincang, dan susu kental manis.',
      'Lipat martabak menjadi setengah lingkaran. Olesi permukaan luar dengan margarine.',
      'Potong-potong dan sajikan selagi hangat.',
    ],
    tags: ['martabak', 'manis', 'coklat', 'keju', 'malam'],
    rating: 4.9,
    youtubeUrl: 'https://www.youtube.com/watch?v=TKQiMY3XrGk',
  },
  {
    id: 'pempek',
    name: 'Pempek Palembang',
    description:
      'Pempek kapal selam khas Palembang dengan kuah cuko pedas asam manis yang menggugah selera.',
    image: '🐟',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 30,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Ikan tenggiri (fillet)', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Tepung sagu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air es', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Telur rebus (untuk isi)', amount: 4, unit: 'butir', category: 'Protein' },
      { name: 'Cuka masak', amount: 200, unit: 'ml', category: 'Bumbu' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Ebi (udang kering)', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan ikan tenggiri dengan food processor. Tambahkan garam dan gula, proses kembali hingga halus dan kalis.',
      'Masukkan air es sedikit demi sedikit sambil proses. Lalu tambahkan tepung sagu sedikit demi sedikit. Uleni hingga adonan kenyal.',
      'Ambil adonan, pipihkan di tangan. Letakkan telur rebus di tengah, bungkus rapat membentuk seperti kapal selam.',
      'Untuk pempek lenjer: ambil adonan, bentuk memanjang seperti silinder.',
      'Rebus pempek dalam air mendidih hingga mengambang (±10 menit). Angkat dan tiriskan.',
      'Goreng pempek yang sudah direbus dalam minyak panas hingga kuning kecoklatan.',
      'Untuk kuah cuko: rebus gula merah, cuka, cabai rawit halus, bawang putih halus, dan ebi. Masak hingga gula larut dan kuah mengental. Saring.',
      'Sajikan pempek dengan kuah cuko dan mie kuning.',
    ],
    tags: ['pempek', 'Palembang', 'ikan', 'cuko', 'kapal selam'],
    rating: 4.7,
  },
  {
    id: 'rawon',
    name: 'Rawon Surabaya',
    description:
      'Rawon daging sapi khas Surabaya dengan kuah hitam pekat dari kluwek. Rasanya gurih dan kaya rempah.',
    image: '🥘',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 120,
    prepTime: 20,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'Daging sapi (has dalam atau sandung lamur)', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Kluwek (kepayang)', amount: 6, unit: 'butir', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kemiri', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Tauge pendek', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Telur asin', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Sambal terasi', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Kerupuk udang', amount: 5, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 1200, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Pecahkan kluwek, ambil isinya. Rendam dalam air hangat selama 5 menit. Buang biji bagian tengah yang pahit.',
      'Haluskan bumbu: bawang merah, bawang putih, cabai merah, kemiri, kunyit, jahe, dan isian kluwek.',
      'Potong daging sapi berukuran 3x3 cm.',
      'Tumis bumbu halus bersama lengkuas geprek, serai memarkan, dan daun salam hingga harum dan matang.',
      'Masukkan potongan daging, aduk hingga berubah warna.',
      'Tuangkan air, masak dengan api kecil selama 1.5-2 jam hingga daging empuk dan kuah berwarna hitam pekat.',
      'Bumbui garam secukupnya. Masak terakhir hingga kuah mengental.',
      'Sajikan dengan nasi putih, tauge pendek rebus, telur asin, sambal terasi, dan kerupuk udang.',
    ],
    tags: ['rawon', 'Surabaya', 'kluwek', 'kuah hitam', 'daging sapi'],
    rating: 4.8,
  },
  {
    id: 'tahu-gejrot',
    name: 'Tahu Gejrot',
    description:
      'Tahu pong khas Cirebon disiram kuah gejrot pedas manis asam yang segar. Camilan khas yang menggugah selera.',
    image: '🧈',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 150,
    ingredients: [
      { name: 'Tahu pong (tahu bandung)', amount: 8, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air asam (dari asam jawa)', amount: 100, unit: 'ml', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Petis udang', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kerupuk mie', amount: 5, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Potong tahu pong menjadi 4 bagian. Goreng sebentar dalam minyak banyak hingga setengah kering. Angkat, tiriskan.',
      'Serut gula merah, larutkan dengan 150ml air hangat. Saring jika perlu.',
      'Haluskan cabai rawit dan bawang merah (ulek kasar, jangan terlalu halus).',
      'Campurkan air gula merah, ulekan cabai dan bawang, kecap manis, air asam, garam, dan petis udang. Aduk rata dan koreksi rasa (harusnya pedas, manis, asam).',
      'Tata tahu pong di piring saji.',
      'Siram dengan kuah gejrot secukupnya.',
      'Tambahkan kerupuk mie di atasnya. Sajikan segera.',
    ],
    tags: ['tahu', 'gejrot', 'Cirebon', 'pedas', 'manis'],
    rating: 4.5,
  },
  {
    id: 'kolak',
    name: 'Kolak Pisang Ubi',
    description:
      'Kolak tradisional dengan pisang, ubi jalar, dan kelapa muda dalam kuah santan manis yang hangat. Menu wajib saat bulan puasa.',
    image: '🫕',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Pisang raja (matang)', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Ubi jalar kuning', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah (sisir)', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kelapa muda (opsional)', amount: 0.5, unit: 'butir', category: 'Bahan Utama' },
    ],
    steps: [
      'Kupas pisang, potong-potong. Kupas ubi jalar, potong dadu.',
      'Ikat simpul daun pandan.',
      'Rebus santan bersama daun pandan dengan api kecil. Aduk sesekali agar santan tidak pecah.',
      'Setelah santan mendidih, masukkan gula merah dan gula pasir. Aduk hingga gula larut.',
      'Masukkan ubi jalar, masak hingga setengah empuk (±8 menit).',
      'Masukkan pisang, masak hingga empuk (±5 menit). Tambahkan garam.',
      'Angkat dari api. Sajikan hangat atau dingin. Jika dingin, bisa ditambahkan es batu.',
    ],
    tags: ['kolak', 'pisang', 'ubi', 'santan', 'puasa'],
    rating: 4.6,
  },
  {
    id: 'martabak-telur',
    name: 'Martabak Telur',
    description:
      'Martabak telur asin gurih dengan isian daging, telur, dan daun bawang. Kulitnya tipis dan renyah, disajikan dengan acar dan kuah cuka.',
    image: '🥙',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 20,
    prepTime: 25,
    servings: 4,
    calories: 440,
    ingredients: [
      { name: 'Tepung terigu protein tinggi', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 4, unit: 'butir', category: 'Protein' },
      { name: 'Daging sapi giling', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Daun bawang iris', amount: 5, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang putih goreng', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam (untuk adonan kulit)', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Acar timun & cabai', amount: 100, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Buat adonan kulit: campurkan tepung terigu, garam, dan air. Uleni hingga elastis (minimal 15 menit). Bagi menjadi 4 bola, diamkan 30 menit.',
      'Tumis daging giling dengan bawang putih goreng, garam, dan merica hingga matang. Angkat, dinginkan.',
      'Campurkan daging tumis dengan telur, daun bawang iris, dan sedikit garam. Aduk rata.',
      'Tipiskan adonan kulit sangat tipis (sebesar piring) menggunakan rolling pin atau teknik tangan.',
      'Ambil 1 lembar kulit tipis, letakkan di teflon datar. Tuang 1/4 isian telur di atasnya.',
      'Lipat kulit membentuk kotak. Tekan-tekan pinggiran agar menutup rapat.',
      'Goreng dengan api sedang sambil sesekali ditekan dan dibalik hingga kedua sisi kuning kecoklatan dan renyah.',
      'Potong-potong dan sajikan dengan acar timun cabai serta kuah cuka pedas.',
    ],
    tags: ['martabak', 'telur', 'daging', 'goreng', 'malam'],
    rating: 4.7,
  },
  {
    id: 'opor-ayam',
    name: 'Opor Ayam',
    description:
      'Opor ayam berkuah santan kuning yang gurih dan lembut. Menu wajib Lebaran bersama ketupat dan sambal ati.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 20,
    servings: 5,
    calories: 400,
    ingredients: [
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Santan kental', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Kemiri', amount: 4, unit: 'butir', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Telur rebus (opsional)', amount: 4, unit: 'butir', category: 'Protein' },
    ],
    steps: [
      'Haluskan bawang putih, bawang merah, kemiri, kunyit, dan jahe.',
      'Tumis bumbu halus bersama lengkuas geprek, serai memarkan, dan daun salam hingga harum.',
      'Masukkan potongan ayam, aduk hingga berubah warna.',
      'Tuangkan santan sedikit demi sedikit sambil terus diaduk agar tidak pecah.',
      'Masak dengan api kecil selama 45-60 menit hingga ayam empuk dan kuah mengental.',
      'Tambahkan garam dan gula merah. Masukkan telur rebus jika menggunakan.',
      'Masak 10 menit lagi hingga bumbu meresap sempurna.',
      'Sajikan dengan ketupat, lontong, atau nasi putih hangat. Lengkapi dengan sambal goreng ati.',
    ],
    tags: ['opor', 'ayam', 'santan', 'Lebaran', 'kuning'],
    rating: 4.8,
    youtubeUrl: 'https://www.youtube.com/watch?v=zIBGPkL_8VM',
  },
  ...westernRecipes,
];

/**
 * Get all unique categories from the recipe database
 */
export function getCategories(): string[] {
  const categories = new Set(recipes.map((r) => r.category));
  return Array.from(categories);
}

/**
 * Get recipes by category
 */
export function getRecipesByCategory(category: string): Recipe[] {
  return recipes.filter((r) => r.category === category);
}

/**
 * Get a single recipe by ID
 */
export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}

/**
 * Search recipes by name, description, tags, or ingredients
 */
export function searchRecipes(query: string): Recipe[] {
  const q = query.toLowerCase().trim();
  return recipes.filter(
    (r) =>
      r.name.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.tags.some((t) => t.toLowerCase().includes(q)) ||
      r.ingredients.some((i) => i.name.toLowerCase().includes(q))
  );
}

/**
 * Get recipes filtered by difficulty
 */
export function getRecipesByDifficulty(difficulty: 'Mudah' | 'Sedang' | 'Susah'): Recipe[] {
  return recipes.filter((r) => r.difficulty === difficulty);
}

/**
 * Get recipes that can be made within a given total time (prep + cook in minutes)
 */
export function getRecipesByMaxTime(maxMinutes: number): Recipe[] {
  return recipes.filter((r) => r.prepTime + r.cookTime <= maxMinutes);
}

/**
 * Get recipes sorted by rating (highest first)
 */
export function getTopRatedRecipes(limit = 10): Recipe[] {
  return [...recipes].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

/**
 * Get a random recipe
 */
export function getRandomRecipe(): Recipe {
  return recipes[Math.floor(Math.random() * recipes.length)];
}
