import type { Recipe } from '@/types';
export const recipesSarapanExtra: Recipe[] = [
  {
    id: 'bubur-ayam-kuning',
    name: 'Bubur Ayam Kuning',
    description:
      'Bubur ayam berwarna kuning cerah dari kunyit dengan suwiran ayam, telur rebus, dan kacang tanah. Sarapan hangat khas nusantara yang mengenyangkan.',
    image: '🥣',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam kampung', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Kunyit parut', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Kacang tanah goreng', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Kerupuk', amount: 4, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus beras dengan air hingga menjadi bubur, tambahkan kunyit parut. Aduk rata.',
      'Rebus ayam kampung hingga empuk, suwir-suwir dagingnya.',
      'Haluskan bawang putih dan bawang merah, tumis hingga harum.',
      'Masukkan tumisan bumbu ke dalam bubur, tambahkan daun salam dan serai.',
      'Masak bubur dengan api kecil hingga mengental dan matang.',
      'Sajikan bubur di mangkuk, tambahkan suwiran ayam.',
      'Taburi kacang tanah goreng, bawang goreng, dan kerupuk.',
    ],
    tags: ['bubur', 'ayam', 'kunyit', 'hangat', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'bubur-kacang-merah',
    name: 'Bubur Kacang Merah',
    description:
      'Bubur kacang merah yang manis gurih dengan santan dan gula aren. Sarapan tradisional khas Sumatera yang kaya protein nabati.',
    image: '🫘',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 60,
    prepTime: 10,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'Kacang merah', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula aren', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 600, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Rendam kacang merah semalam hingga mengembang. Tiriskan.',
      'Rebus kacang merah dengan air hingga empuk dan pecah-pecah.',
      'Masukkan santan, daun pandan, dan garam. Masak hingga mendidih.',
      'Tambahkan gula aren, aduk rata hingga gula larut.',
      'Masak dengan api kecil hingga bubur mengental.',
      'Sajikan hangat sebagai sarapan pagi.',
    ],
    tags: ['bubur', 'kacang merah', 'santan', 'gula aren', 'Sumatera'],
    rating: 4.5,
  },
  {
    id: 'bubur-sumsum-pandan',
    name: 'Bubur Sumsum Pandan',
    description:
      'Bubur sumsum dengan aroma harum pandan dan kuah gula merah kinca. Sarapan manis tradisional yang lembut dan nikmat.',
    image: '🍵',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    calories: 270,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 200, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Blender daun pandan dengan 50ml air, saring ambil air hijaunya.',
      'Campurkan tepung beras dengan 200ml santan dan air pandan, aduk rata.',
      'Panaskan sisa santan dengan garam hingga mendidih.',
      'Tuang adonan tepung ke santan mendidih, aduk terus hingga mengental.',
      'Angkat, tuang ke cetakan atau mangkuk kecil.',
      'Rebus gula merah dengan 200ml air hingga kental, saring.',
      'Sajikan bubur sumsum dengan siraman kuah kinca pandan.',
    ],
    tags: ['bubur', 'sumsum', 'pandan', 'gula merah', 'manis'],
    rating: 4.7,
  },
  {
    id: 'bubur-durian',
    name: 'Bubur Durian',
    description:
      'Bubur pulen dari tepung beras yang dimasak dengan daging durian dan santan. Sarapan istimewa penggemar durian yang creamy dan harum.',
    image: '🤤',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'Tepung beras', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging durian', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung beras dengan 200ml santan, aduk rata hingga tidak bergerindil.',
      'Panaskan sisa santan dengan daun pandan dan garam hingga mendidih.',
      'Tuang adonan tepung ke santan mendidih, aduk hingga mengental.',
      'Masukkan daging durian dan gula pasir, aduk rata.',
      'Masak sebentar hingga durian menyatu dengan bubur.',
      'Angkat, sajikan hangat dalam mangkuk.',
    ],
    tags: ['bubur', 'durian', 'santan', 'khas Medan', 'creamy'],
    rating: 4.4,
  },
  {
    id: 'nasi-goreng-kampung',
    name: 'Nasi Goreng Kampung',
    description:
      'Nasi goreng khas kampung dengan bumbu sederhana, kangkung, dan ikan teri. Sarapan rakyat yang gurih dan penuh kenangan.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 3,
    calories: 380,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Teri medan', amount: 50, unit: 'gram', category: 'Protein' },
      { name: 'Kangkung iris', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kerupuk', amount: 6, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang halus bawang merah dan bawang putih.',
      'Panaskan minyak, tumis bumbu halus dan cabai rawit hingga harum.',
      'Goreng teri medan hingga renyah, sisihkan sebagian.',
      'Masukkan nasi dingin, aduk dengan api besar.',
      'Tambahkan kecap manis, garam, dan merica. Aduk rata.',
      'Masukkan kangkung, aduk sebentar hingga layu.',
      'Sajikan dengan taburan teri goreng dan kerupuk.',
    ],
    tags: ['nasi goreng', 'kampung', 'teri', 'kangkung', 'tradisional'],
    rating: 4.7,
  },
  {
    id: 'nasi-goreng-kambing',
    name: 'Nasi Goreng Kambing',
    description:
      'Nasi goreng dengan potongan daging kambing empuk dan bumbu rempah yang khas. Sarapan spesial khas Kebon Sirih Jakarta.',
    image: '🥘',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging kambing potong', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Ketumbar bubuk', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Acar', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, kunyit, dan jahe.',
      'Tumis bumbu halus hingga harum dan matang.',
      'Masukkan daging kambing, masak hingga berubah warna dan empuk.',
      'Tambahkan ketumbar bubuk, garam, dan merica.',
      'Masukkan nasi dingin, aduk rata dengan api besar.',
      'Tambahkan kecap manis, aduk hingga terbalut rata.',
      'Sajikan dengan acar timun dan kerupuk.',
    ],
    tags: ['nasi goreng', 'kambing', 'rempah', 'Jakarta', 'spesial'],
    rating: 4.6,
  },
  {
    id: 'nasi-kucing',
    name: 'Nasi Kucing',
    description:
      'Porsi kecil nasi dengan lauk sambal teri, orek tempe, dan ayam suwir. Sarapan khas Yogyakarta yang murah dan lezat.',
    image: '🍚',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 6,
    calories: 150,
    ingredients: [
      { name: 'Nasi putih', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Teri nasi', amount: 50, unit: 'gram', category: 'Protein' },
      { name: 'Tempe potong kecil', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Ayam suwir', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun pisang', amount: 6, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Tumis bawang merah dan cabai rawit hingga harum.',
      'Masukkan teri, tumis hingga kering. Tambahkan kecap manis.',
      'Goreng tempe potong kecil hingga renyah.',
      'Buat ayam suwir bumbu sederhana dengan garam dan penyedap.',
      'Ambil sejumput nasi, tata di atas daun pisang.',
      'Tambahkan sambal teri, tempe goreng, dan ayam suwir.',
      'Bungkus daun pisang, semat dengan lidi. Sajikan.',
    ],
    tags: ['nasi kucing', 'Yogyakarta', 'jajanan', 'porsi kecil', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'nasi-lengko',
    name: 'Nasi Lengko',
    description:
      'Nasi putih dengan tahu goreng, tempe, tauge, dan kuah santan kacang khas Cirebon. Sarapan sederhana yang gurih dan segar.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 3,
    calories: 350,
    ingredients: [
      { name: 'Nasi putih', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tahu putih', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Tempe', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang tanah goreng', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kerupuk', amount: 6, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Daun kucai', amount: 2, unit: 'batang', category: 'Sayuran' },
    ],
    steps: [
      'Goreng tahu putih dan tempe hingga kecoklatan. Potong-potong.',
      'Rebus tauge sebentar, tiriskan.',
      'Haluskan kacang tanah goreng bersama cabai rawit.',
      'Tambahkan air panas sedikit demi sedikit untuk mengencerkan bumbu.',
      'Bumbui garam dan gula merah, aduk rata.',
      'Tata nasi di piring, susun tauge, tahu, tempe, dan daun kucai.',
      'Siram bumbu kacang, taburi kerupuk dan bawang goreng.',
    ],
    tags: ['nasi lengko', 'Cirebon', 'tahu', 'tempe', 'kacang'],
    rating: 4.5,
  },
  {
    id: 'nasi-liwet-sunda',
    name: 'Nasi Liwet Sunda',
    description:
      'Nasi gurih dimasak dengan santan, daun salam, dan ikan asin. Sarapan khas Sunda yang dimakan dengan lalapan dan sambal.',
    image: '🍚',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    calories: 390,
    ingredients: [
      { name: 'Beras', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 350, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ikan asin', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Tahu goreng', amount: 2, unit: 'buah', category: 'Protein' },
      { name: 'Terong goreng', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Sambal terasi', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci beras, tiriskan.',
      'Panaskan santan dengan daun salam dan serai yang dimemarkan.',
      'Masukkan beras ke dalam santan, masak di rice cooker seperti biasa.',
      'Goreng ikan asin hingga garing.',
      'Goreng tahu dan terong hingga matang.',
      'Siapkan lalapan: kemangi, mentimun, dan cabai rawit.',
      'Sajikan nasi liwet dengan ikan asin, tahu, terong, lalapan, dan sambal terasi.',
    ],
    tags: ['nasi liwet', 'Sunda', 'santan', 'ikan asin', 'lalapan'],
    rating: 4.7,
  },
  {
    id: 'nasi-tim-ikan',
    name: 'Nasi Tim Ikan',
    description:
      'Nasi tim lembut dengan suwiran ikan kakap dan bumbu jahe. Sarapan bergizi tinggi untuk anak-anak dan keluarga.',
    image: '🥘',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 20,
    servings: 2,
    calories: 280,
    ingredients: [
      { name: 'Beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ikan kakap fillet', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Jahe parut', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak wijen', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 1, unit: 'batang', category: 'Sayuran' },
      { name: 'Kaldu ayam', amount: 200, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Cuci beras, tiriskan. Rendam selama 15 menit.',
      'Marinasi ikan kakap dengan jahe parut, kecap asin, dan minyak wijen.',
      'Kukus ikan selama 10 menit hingga matang, suwir-suwir.',
      'Campurkan beras dengan kaldu ayam dan bawang putih cincang.',
      'Kukus nasi setengah matang, masukkan suwiran ikan dan daun bawang.',
      'Lanjutkan mengukus hingga nasi matang sempurna.',
      'Sajikan hangat dengan taburan bawang goreng.',
    ],
    tags: ['nasi tim', 'ikan', 'kukus', 'bergizi', 'anak'],
    rating: 4.4,
  },
  {
    id: 'nasi-uduk-komplit',
    name: 'Nasi Uduk Betawi Komplit',
    description:
      'Nasi uduk gurih santan disajikan dengan orek tempe, bihun goreng, semur daging, dan sambal kacang. Sarapan komplit khas Betawi.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 20,
    servings: 4,
    calories: 450,
    ingredients: [
      { name: 'Beras', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Tempe', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Bihun', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging sapi potong', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Kacang tanah goreng', amount: 80, unit: 'gram', category: 'Pelengkap' },
      { name: 'Telur rebus', amount: 4, unit: 'butir', category: 'Protein' },
    ],
    steps: [
      'Cuci beras, masukkan ke rice cooker. Tuang santan, daun salam, serai, dan garam. Masak.',
      'Buat orek tempe: potong tempe, tumis dengan bumbu kecap manis.',
      'Goreng bihun dengan bawang putih dan sayuran secukupnya.',
      'Buat semur daging: rebus daging dengan kecap manis, pala, dan cengkeh.',
      'Rebus telur, belah dua. Goreng sebentar.',
      'Buat sambal kacang dari kacang goreng yang diulek dengan cabai.',
      'Tata nasi uduk dengan lauk-pauk komplit. Sajikan.',
    ],
    tags: ['nasi uduk', 'Betawi', 'komplit', 'santan', 'lauk'],
    rating: 4.8,
  },
  {
    id: 'lontong-balap',
    name: 'Lontong Balap',
    description:
      'Lontong, tahu, tauge, lentho, dan kuah kecap manis khas Surabaya. Sarapan tradisional Jawa Timur yang gurih dan mengenyangkan.',
    image: '🥘',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 4,
    calories: 370,
    ingredients: [
      { name: 'Lontong', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Tahu putih goreng', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Tauge', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kacang tanah goreng', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lentho (kacang tholo)', amount: 8, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus tauge sebentar, tiriskan.',
      'Goreng tahu hingga kecoklatan, potong-potong.',
      'Haluskan kacang tanah goreng dengan cabai rawit dan kunyit.',
      'Encerkan bumbu kacang dengan air panas, tambahkan kecap manis.',
      'Potong lontong, tata di piring saji.',
      'Tata tauge, tahu goreng, dan lentho di atas lontong.',
      'Siram kuah kecap kacang, taburi bawang goreng.',
    ],
    tags: ['lontong balap', 'Surabaya', 'tahu', 'kecap', 'Jawa Timur'],
    rating: 4.6,
  },
  {
    id: 'lontong-cap-go-meh',
    name: 'Lontong Cap Go Meh',
    description:
      'Lontong dengan sayur lodeh, opor ayam, dan sambal goreng khas peranakan. Sarapan perayaan Cap Go Meh yang spesial.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Susah',
    cookTime: 90,
    prepTime: 30,
    servings: 6,
    calories: 460,
    ingredients: [
      { name: 'Beras (untuk lontong)', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam potong', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Santan', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Labu siam', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Tahu kuning', amount: 3, unit: 'buah', category: 'Protein' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
    ],
    steps: [
      'Buat lontong: masak beras dalam daun pisang, kukus 2 jam hingga padat.',
      'Buat opor ayam: haluskan bumbu, tumis, masukkan ayam dan santan. Masak hingga matang.',
      'Buat sayur lodeh: rebus santan dengan bumbu, masukkan labu siam dan kacang panjang.',
      'Buat sambal goreng ati ampela atau kentang sesuai selera.',
      'Goreng tahu kuning hingga kecoklatan.',
      'Potong-potong lontong, tata di piring.',
      'Siram sayur lodeh, tata opor ayam dan lauk lainnya.',
    ],
    tags: ['lontong', 'cap go meh', 'opor', 'peranakan', 'spesial'],
    rating: 4.8,
  },
  {
    id: 'opor-telur',
    name: 'Opor Telur',
    description:
      'Telur rebus dimasak dalam kuah santan kuning yang gurih dan harum. Sarapan sederhana khas Jawa yang nikmat.',
    image: '🥚',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'Telur ayam', amount: 6, unit: 'butir', category: 'Protein' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 1, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
    ],
    steps: [
      'Rebus telur hingga matang, kupas kulitnya.',
      'Haluskan bawang merah, bawang putih, kunyit, dan jahe.',
      'Tumis bumbu halus bersama daun salam dan serai hingga harum.',
      'Tuang santan, masak dengan api kecil hingga mendidih.',
      'Masukkan telur rebus, bumbui garam dan gula.',
      'Masak dengan api kecil selama 15 menit hingga kuah mengental dan bumbu meresap.',
      'Sajikan opor telur dengan nasi putih hangat dan sambal.',
    ],
    tags: ['opor', 'telur', 'santan', 'Jawa', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'telur-ceplok-bumbu-iris',
    name: 'Telur Ceplok Bumbu Iris',
    description:
      'Telur ceplok dimasak dengan bumbu iris kecap manis yang gurih manis. Sarapan sederhana khas rumahan yang favorit keluarga.',
    image: '🍳',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 3,
    calories: 300,
    ingredients: [
      { name: 'Telur ayam', amount: 4, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah iris', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih iris', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Tomat iris', amount: 1, unit: 'buah', category: 'Sayuran' },
    ],
    steps: [
      'Goreng telur ceplok (mata sapi) satu per satu, sisihkan.',
      'Panaskan sedikit minyak, tumis bawang merah dan bawang putih iris.',
      'Masukkan cabai merah dan cabai rawit, tumis hingga layu.',
      'Tambahkan kecap manis, aduk rata.',
      'Masukkan tomat iris, masak sebentar.',
      'Masukkan telur ceplok, aduk perlahan hingga bumbu terbalut.',
      'Sajikan dengan nasi putih hangat.',
    ],
    tags: ['telur', 'ceplok', 'bumbu iris', 'kecap', 'rumahan'],
    rating: 4.6,
  },
  {
    id: 'telur-dadar-padang',
    name: 'Telur Dadar Padang',
    description:
      'Telur dadar tebal berisi daun bawang dan cabai, renyah di tepi dan lembut di dalam. Sarapan khas Padang yang gurih.',
    image: '🍳',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 280,
    ingredients: [
      { name: 'Telur ayam', amount: 4, unit: 'butir', category: 'Protein' },
      { name: 'Daun bawang iris', amount: 3, unit: 'batang', category: 'Sayuran' },
      { name: 'Cabai merah iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kelapa parut', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur bersama garam.',
      'Masukkan daun bawang iris, cabai merah, dan cabai rawit.',
      'Tambahkan kelapa parut dan tepung beras, aduk rata.',
      'Panaskan minyak di wajan dengan api sedang.',
      'Tuang adonan telur sedikit demi sedikit sambil ditepuk-tepuk pinggirannya.',
      'Goreng hingga kedua sisi kecoklatan dan tepi renyah.',
      'Angkat, potong-potong. Sajikan dengan nasi Padang.',
    ],
    tags: ['telur dadar', 'Padang', 'kelapa', 'cabai', 'gurih'],
    rating: 4.7,
  },
  {
    id: 'dadar-telur-sayur',
    name: 'Dadar Telur Sayur',
    description:
      'Dadar telur tipis berisi wortel, kol, dan daun bawang. Sarapan sederhana yang praktis dan bergizi untuk keluarga.',
    image: '🥚',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 230,
    ingredients: [
      { name: 'Telur ayam', amount: 4, unit: 'butir', category: 'Protein' },
      { name: 'Wortel parut', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol iris halus', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang putih cincang', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur bersama garam dan merica bubuk.',
      'Masukkan wortel parut, kol iris, dan daun bawang. Aduk rata.',
      'Panaskan wajan anti lengket dengan sedikit minyak.',
      'Tuang satu sendok sayur adonan, ratakan tipis.',
      'Masak hingga permukaan setengah matang, lipat menjadi setengah lingkaran.',
      'Balik dan masak sebentar lagi hingga matang.',
      'Sajikan dengan nasi putih dan sambal.',
    ],
    tags: ['dadar', 'telur', 'sayur', 'praktis', 'sehat'],
    rating: 4.3,
  },
  {
    id: 'roti-jala',
    name: 'Roti Jala',
    description:
      'Roti jaring tipis berwarna kuning dari kunyit, disajikan dengan kari ayam. Sarapan khas Melayu Riau yang cantik dan lezat.',
    image: '🥞',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 4,
    calories: 330,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Susu cair', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kunyit parut', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kari ayam (kuah)', amount: 400, unit: 'ml', category: 'Pelengkap' },
    ],
    steps: [
      'Parut kunyit, peras ambil airnya.',
      'Campurkan tepung terigu, telur, susu, air kunyit, dan garam. Aduk rata dan saring.',
      'Panaskan wajan anti lengket, olesi sedikit minyak.',
      'Tuang adonan ke dalam botol dengan lubang atau cetakan roti jala.',
      'Semprotkan adonan ke wajan membentuk jaring-jaring tipis.',
      'Masak hingga matang, angkat. Lipat menjadi segitiga.',
      'Sajikan roti jala dengan kuah kari ayam.',
    ],
    tags: ['roti jala', 'Melayu', 'Riau', 'kari', 'kunyit'],
    rating: 4.5,
  },
  {
    id: 'roti-maryam',
    name: 'Roti Maryam',
    description:
      'Roti pipih berlapis berbentuk spiral yang renyah dan empuk. Sarapan khas Timur Tengah yang populer di Indonesia.',
    image: '🫓',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 45,
    servings: 6,
    calories: 300,
    ingredients: [
      { name: 'Tepung terigu', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung, gula, garam, telur, dan susu. Uleni hingga kalis.',
      'Bagi adonan menjadi 6 bulatan. Olesi permukaan dengan minyak, diamkan 30 menit.',
      'Giling adonan tipis, olesi mentega. Lipat dan gulung membentuk spiral.',
      'Pipihkan spiral adonan menjadi roti pipih.',
      'Panaskan pan, panggang roti dengan api kecil hingga kecoklatan.',
      'Balik, panggang sisi lainnya hingga matang.',
      'Sajikan dengan kari, madu, atau selai sesuai selera.',
    ],
    tags: ['roti maryam', 'berlapis', 'Timur Tengah', 'panggang', ' spiral'],
    rating: 4.6,
  },
  {
    id: 'roti-bakar-coklat-kacang',
    name: 'Roti Bakar Coklat Kacang',
    description:
      'Roti tawar dipanggang dengan isian selai coklat dan taburan kacang. Sarapan manis praktis yang disukai anak-anak.',
    image: '🍞',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 8,
    prepTime: 5,
    servings: 2,
    calories: 340,
    ingredients: [
      { name: 'Roti tawar', amount: 4, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Selai coklat', amount: 4, unit: 'sendok makan', category: 'Isian' },
      { name: 'Kacang tanah sangrai', amount: 30, unit: 'gram', category: 'Pelengkap' },
      { name: 'Mentega', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Keju parut', amount: 20, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Olesi permukaan roti tawar dengan mentega.',
      'Panggang roti di pan anti lengket hingga kecoklatan.',
      'Olesi satu sisi roti dengan selai coklat.',
      'Taburi kacang sangrai cincang dan keju parut.',
      'Tutup dengan roti lainnya, tekan perlahan.',
      'Panggang sebentar lagi, potong diagonal.',
      'Sajikan hangat dengan segelas susu.',
    ],
    tags: ['roti bakar', 'coklat', 'kacang', 'manis', 'anak-anak'],
    rating: 4.3,
  },
  {
    id: 'roti-canai-sardin',
    name: 'Roti Canai Sardin',
    description:
      'Roti canai berisi sarden pedas manis yang gurih. Sarapan Melayu yang mengenyangkan dengan cita rasa kuat.',
    image: '🫓',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Tepung terigu', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Sarden kaleng', amount: 1, unit: 'kaleng', category: 'Protein' },
      { name: 'Bawang merah iris', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Mentega', amount: 40, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 80, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung, garam, susu, dan air. Uleni hingga elastis. Diamkan 1 jam.',
      'Tumis bawang merah dan cabai hingga layu.',
      'Masukkan sarden, aduk rata. Tambahkan daun bawang, angkat.',
      'Ambil adonan roti, pipihkan dan olesi mentega. Lipat dan pipihkan kembali.',
      'Berisi tumisan sarden, lipat menjadi segitiga.',
      'Panggang di pan dengan api kecil hingga kecoklatan kedua sisi.',
      'Sajikan hangat dengan saus sambal.',
    ],
    tags: ['roti canai', 'sarden', 'Melayu', 'berisi', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'roti-buaya',
    name: 'Roti Buaya',
    description:
      'Roti manis berbentuk buaya yang biasanya disajikan di acara pernikahan Betawi. Sarapan tradisional yang cantik dan lembut.',
    image: '🐊',
    category: 'Sarapan',
    difficulty: 'Susah',
    cookTime: 25,
    prepTime: 40,
    servings: 8,
    calories: 260,
    ingredients: [
      { name: 'Tepung terigu', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Selai stroberi (isi)', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Coklat leleh (hiasan)', amount: 50, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan ragi, gula, dan susu hangat. Diamkan 10 menit hingga berbusa.',
      'Campurkan tepung, telur, dan adonan ragi. Uleni hingga kalis.',
      'Tambahkan mentega, uleni hingga elastis dan tidak lengket.',
      'Diamkan adonan selama 1 jam hingga mengembang dua kali lipat.',
      'Bentuk adonan menjadi buaya. Gunakan pisau untuk membuat sisik.',
      'Olesi dengan kuning telur, panggang oven 180°C selama 20 menit.',
      'Hias dengan coklat leleh untuk mata dan detail buaya.',
    ],
    tags: ['roti buaya', 'Betawi', 'pernikahan', 'hias', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'martabak-manis-mini',
    name: 'Martabak Manis Mini',
    description:
      'Martabak manis ukuran kecil berbagai topping coklat, kacang, dan keju. Sarapan manis yang praktis dan bisa dibuat sendiri.',
    image: '🥞',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Gula pasir', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Air', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Coklat meises', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Kacang tanah cincang', amount: 30, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung, telur, gula, dan air. Aduk rata hingga halus.',
      'Tambahkan soda kue, aduk perlahan. Diamkan 30 menit.',
      'Panaskan wajan datar dengan api kecil, olesi sedikit minyak.',
      'Tuang adonan tipis, masak hingga permukaan kering dan berpori.',
      'Olesi mentega, taburi gula pasir, coklat meises, dan kacang.',
      'Lipat menjadi setengah lingkaran, olesi permukaan dengan mentega.',
      'Potong-potong, sajikan hangat.',
    ],
    tags: ['martabak', 'manis', 'mini', 'coklat', 'topping'],
    rating: 4.5,
  },
  {
    id: 'serabi-kinca-solo',
    name: 'Serabi Solo Kinca',
    description:
      'Serabi lembut dari tepung beras disajikan dengan kuah kinca gula merah khas Solo. Sarapan manis tradisional yang legit.',
    image: '🥞',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Kelapa parut sangrai', amount: 50, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras, ragi, gula, dan santan. Aduk rata.',
      'Diamkan adonan 30 menit hingga mengembang. Tambahkan soda kue.',
      'Buat kinca: rebus gula merah dengan 100ml air hingga kental, saring.',
      'Panaskan pan cetakan serabi di atas api kecil.',
      'Tuang adonan, tutup pan. Masak hingga pori-pori muncul.',
      'Angkat serabi, sajikan dengan kuah kinca dan kelapa parut.',
    ],
    tags: ['serabi', 'Solo', 'kinca', 'gula merah', 'tradisional'],
    rating: 4.7,
  },
  {
    id: 'kue-apem-gula-merah',
    name: 'Kue Apem',
    description:
      'Kue apem berwarna coklat dari gula merah dengan aroma pandan. Sarapan tradisional yang manis legit dan bertekstur lembut.',
    image: '🟤',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 6,
    calories: 210,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah sisir', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Larutkan gula merah dengan santan, rebus bersama daun pandan. Saring.',
      'Dinginkan larutan santan gula, tambahkan ragi instan.',
      'Masukkan tepung beras sedikit demi sedikit, aduk rata.',
      'Diamkan adonan selama 1 jam hingga mengembang.',
      'Tuang adonan ke cetakan apem yang sudah diolesi minyak.',
      'Kukus selama 20 menit hingga matang.',
      'Angkat, dinginkan. Sajikan sebagai sarapan.',
    ],
    tags: ['apem', 'gula merah', 'pandan', 'kukus', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'kue-mangkok-pandan',
    name: 'Kue Mangkok',
    description:
      'Kue mangkok yang mekar sempurna berwarna hijau pandan dengan rasa manis. Sarapan tradisional yang cantik dan lezat.',
    image: '🟢',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun suji/pandan', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
    ],
    steps: [
      'Blender daun suji/pandan dengan sedikit air, saring ambil air hijaunya.',
      'Campurkan ragi instan, gula pasir, dan santan hangat. Diamkan 10 menit.',
      'Masukkan tepung terigu, tepung beras, dan air pandan. Aduk rata.',
      'Diamkan adonan selama 1 jam hingga mengembang.',
      'Tambahkan soda kue, aduk perlahan.',
      'Tuang adonan ke cetakan kue mangkok hingga 3/4 penuh.',
      'Kukus 15-20 menit hingga mekar sempurna.',
    ],
    tags: ['kue mangkok', 'pandan', 'merekah', 'kukus', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'kue-bika-ambon-mini',
    name: 'Kue Bika Ambon',
    description:
      'Kue bolu berpori khas Medan dengan aroma pandan. Sarapan khas Sumatera yang bertekstur unik dan lembut.',
    image: '🍰',
    category: 'Sarapan',
    difficulty: 'Susah',
    cookTime: 50,
    prepTime: 30,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'Tepung sagu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 5, unit: 'butir', category: 'Protein' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Mentega', amount: 30, unit: 'gram', category: 'Bumbu' },
    ],
    steps: [
      'Blender santan dengan daun pandan, saring.',
      'Kocok telur dan gula hingga kental.',
      'Masukkan tepung sagu sedikit demi sedikit, aduk perlahan.',
      'Tuang santan pandan dan ragi, aduk rata. Diamkan 2 jam hingga berbusa.',
      'Tambahkan mentega leleh, aduk perlahan.',
      'Tuang ke cetakan, oven dengan api bawah 180°C selama 40 menit.',
      'Dinginkan, potong-potong dan sajikan.',
    ],
    tags: ['bika ambon', 'Medan', 'pandan', 'berpori', 'khas'],
    rating: 4.6,
  },
  {
    id: 'kue-serabi-bandung',
    name: 'Kue Serabi Bandung',
    description:
      'Serabi khas Bandung dengan oncom atau kuah gula merah. Sarapan tradisional Sunda yang gurih dan mengenyangkan.',
    image: '🥞',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Ebi sangrai', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras, kelapa parut, dan garam.',
      'Tuang santan sedikit demi sedikit, aduk rata hingga tidak bergerindil.',
      'Diamkan adonan selama 30 menit.',
      'Rebus gula merah dengan daun salam untuk kuah kinca, saring.',
      'Panaskan pan tanah liat, olesi sedikit minyak.',
      'Tuang 1 sendok sayur adonan, tutup pan. Masak hingga pori-pori muncul.',
      'Sajikan serabi dengan kuah gula merah dan taburan ebi.',
    ],
    tags: ['serabi', 'Bandung', 'Sunda', 'oncom', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'onde-onde-kacang-tanah',
    name: 'Onde-Onde Kacang Tanah',
    description:
      'Onde-onde renyah berisi kacang tanah sangrai dan gula merah. Sarapan jajan pasar yang manis dan gurih.',
    image: '🟡',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 30,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'Tepung ketan', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang tanah sangrai', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah sisir', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Wijen putih', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Air hangat', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan kacang tanah sangrai cincang dengan gula merah sisir.',
      'Ambil sedikit campuran, bulatkan menjadi bola kecil sebagai isian.',
      'Campurkan tepung ketan, gula pasir, dan air hangat. Uleni hingga kalis.',
      'Ambil sedikit adonan, pipihkan. Isi bola kacang tanah, bulatkan rapat.',
      'Basahi bola adonan, gulingkan di wijen hingga rata.',
      'Goreng dalam minyak dengan api sedang hingga kuning keemasan.',
      'Tiriskan, sajikan sebagai sarapan.',
    ],
    tags: ['onde-onde', 'kacang tanah', 'wijen', 'goreng', 'manis'],
    rating: 4.4,
  },
  {
    id: 'klepon-ubi-ungu',
    name: 'Klepon Ubi Ungu',
    description:
      'Klepon dari tepung ubi ungu berisi gula merah cair, dibalut kelapa parut. Sarapan unik berwarna cantik dan lezat.',
    image: '🟣',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Ubi ungu kukus', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung ketan', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah sisir', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Kelapa parut sangrai', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air hangat', amount: 50, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Haluskan ubi ungi kukus menggunakan garpu.',
      'Campurkan ubi ungu halus, tepung ketan, dan garam. Uleni hingga kalis.',
      'Ambil sedikit adonan, pipihkan. Isi gula merah sisir, bulatkan rapat.',
      'Didihkan air, rebus klepon hingga mengambang.',
      'Angkat klepon, langsung gulingkan di kelapa parut sangrai.',
      'Sajikan dalam piring atau cup kecil.',
    ],
    tags: ['klepon', 'ubi ungu', 'gula merah', 'ketan', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'lupis-durian-medan',
    name: 'Lupis Durian',
    description:
      'Lupis ketan disajikan dengan daging durian dan gula merah cair. Sarapan istimewa khas Medan untuk penggemar durian.',
    image: '🟢',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 50,
    prepTime: 20,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Beras ketan', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging durian', amount: 200, unit: 'gram', category: 'Isian' },
      { name: 'Kelapa parut', amount: 150, unit: 'gram', category: 'Pelengkap' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Daun pisang', amount: 8, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam beras ketan minimal 3 jam. Tiriskan.',
      'Bungkus ketan dalam daun pisang membentuk segitiga, ikat rapi.',
      'Kukus lupis selama 45 menit hingga matang dan pulen.',
      'Sangrai kelapa parut sebentar, taburi garam.',
      'Rebus gula merah dengan 100ml air hingga kental, saring.',
      'Buka bungkusan lupis, gulingkan di kelapa parut.',
      'Sajikan dengan daging durian dan siraman gula merah cair.',
    ],
    tags: ['lupis', 'durian', 'ketan', 'Medan', 'istimewa'],
    rating: 4.6,
  },
  {
    id: 'puto-maya',
    name: 'Puto Maya',
    description:
      'Kue beras ketan kukus berwarna-warni dari bunga telang. Sarapan khas Manado yang cantik dan manis legit.',
    image: '🟡',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 20,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'Beras ketan', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 150, unit: 'gram', category: 'Pelengkap' },
      { name: 'Bunga telang kering', amount: 10, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam beras ketan semalam. Tiriskan.',
      'Seduh bunga telang dengan air panas, saring ambil air birunya.',
      'Bagi ketan menjadi 3 bagian: satu warna biru, satu hijau pandan, satu putih.',
      'Masukkan masing-masing ketan ke dalam daun pisang, bungkus rapi.',
      'Kukus selama 30 menit hingga matang.',
      'Sangrai kelapa parut dengan garam, sajikan sebagai pelengkap.',
      'Sajikan puto maya dengan kelapa parut dan gula merah cair.',
    ],
    tags: ['puto maya', 'Manado', 'bunga telang', 'ketan', 'warna-warni'],
    rating: 4.5,
  },
  {
    id: 'bubur-ayam-mangga',
    name: 'Bubur Ayam Mangga',
    description:
      'Bubur ayam dengan topping potongan mangga segar dan kuah santan. Sarapan fusion Nusantara yang segar dan unik.',
    image: '🥭',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'Beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam dada', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Mangga harum manis', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Santan', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Jahe', amount: 1, unit: 'cm', category: 'Bumbu' },
      { name: 'Kacang tanah goreng', amount: 40, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus beras dengan air hingga menjadi bubur.',
      'Rebus ayam dada hingga matang, suwir-suwir dagingnya.',
      'Tumis bawang putih, daun salam, dan jahe hingga harum.',
      'Masukkan tumisan ke bubur, tambahkan santan. Masak hingga mengental.',
      'Potong mangga menjadi dadu kecil.',
      'Sajikan bubur di mangkuk, tambahkan suwiran ayam.',
      'Hias dengan potongan mangga, kacang tanah, dan bawang goreng.',
    ],
    tags: ['bubur', 'ayam', 'mangga', 'fusion', 'segar'],
    rating: 4.3,
  },
  {
    id: 'sate-taichan',
    name: 'Sate Taichan',
    description:
      'Sate ayam tanpa bumbu kacang, disajikan dengan sambal jeruk limau. Sarapan ringan khas Jakarta yang segar dan pedas.',
    image: '🍢',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 250,
    ingredients: [
      { name: 'Dada ayam fillet', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Jeruk limau', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tusuk sate', amount: 15, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Potong dada ayam menjadi dadu kecil, tusuk di tusuk sate.',
      'Bakar sate di atas arang atau pan anti lengket hingga matang kecoklatan.',
      'Haluskan cabai rawit dan bawang merah untuk sambal.',
      'Tambahkan garam dan gula pasir ke sambal, aduk rata.',
      'Peras jeruk limau ke atas sambal.',
      'Sajikan sate dengan sambal jeruk limau di sampingnya.',
    ],
    tags: ['sate', 'taichan', 'ayam', 'pedas', 'Jakarta'],
    rating: 4.5,
  },
  {
    id: 'sate-bandeng',
    name: 'Sate Bandeng',
    description:
      'Sate dari daging bandeng tanpa durian yang dibakar dengan bumbu rempah. Sarapan khas Banten yang gurih dan nikmat.',
    image: '🐠',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Bandeng tanpa duri', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Kelapa parut', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 1, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun pisang', amount: 4, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Haluskan bumbu: bawang merah, bawang putih, kunyit, dan jahe.',
      'Campurkan bumbu halus dengan kelapa parut dan garam.',
      'Tumis kelapa bumbu hingga matang dan kering. Dinginkan.',
      'Gepuk bandeng, lumuri kelapa bumbu secara merata.',
      'Gulung bandeng yang sudah dibumbui, bungkus dengan daun pisang.',
      'Bakar di atas arang hingga matang dan daun layu.',
      'Buka bungkusan, potong-potong. Sajikan dengan nasi hangat.',
    ],
    tags: ['sate bandeng', 'Banten', 'ikan', 'kelapa', 'bakar'],
    rating: 4.6,
  },
  {
    id: 'hakau-udang',
    name: 'Hakau',
    description:
      'Dumpling kukus berisi udang dengan kulit transparan tipis. Sarapan dimsum khas Tiongkok yang populer di Indonesia.',
    image: '🥟',
    category: 'Sarapan',
    difficulty: 'Susah',
    cookTime: 15,
    prepTime: 40,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Udang kupas', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Tepung tapioka', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe parut', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak wijen', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air panas', amount: 80, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Cincang kasar udang kupas, campurkan dengan bawang putih, jahe, minyak wijen, dan kecap asin.',
      'Untuk kulit: campurkan tepung tapioka, tepung beras, dan air panas. Uleni hingga kalis.',
      'Giling tipis adonan kulit, potong bulat kecil.',
      'Ambil selembar kulit, isi 1 sdt udang. Lipat membentuk kantong hakau.',
      'Rekatkan tepi dengan air. Bentuk seperti jaring udang.',
      'Kukus di atas kain yang diolesi minyak selama 10 menit.',
      'Sajikan dengan saus sambal dan kecap asin.',
    ],
    tags: ['hakau', 'dimsum', 'udang', 'kukus', 'Tiongkok'],
    rating: 4.7,
  },
  {
    id: 'gulali-gula-kapas',
    name: 'Gulali',
    description:
      'Permen kapas tradisional yang manis dan lembut. Sarapan jajanan pasar nostalgia masa kecil yang unik.',
    image: '🍬',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 5,
    servings: 4,
    calories: 150,
    ingredients: [
      { name: 'Gula pasir', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cuka putih', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu besar', amount: 2, unit: 'buah', category: 'Pelengkap' },
      { name: 'Pewarna makanan', amount: 2, unit: 'tetes', category: 'Bumbu' },
    ],
    steps: [
      'Masukkan gula pasir, air, dan cuka ke dalam panci.',
      'Masak dengan api sedang hingga gula berwarna coklat keemasan.',
      'Masukkan pewarna makanan sesuai selera.',
      'Celupkan garpu atau sumpit ke gula cair.',
      'Angkat dan gerakkan cepat di atas es batu membentuk benang-benang halus.',
      'Kumpulkan benang gula membentuk bola kapas.',
      'Sajikan segera sebelum meleleh.',
    ],
    tags: ['gulali', 'permen kapas', 'gula', 'jajanan', 'nostalgia'],
    rating: 4.2,
  },
  {
    id: 'cenil-jawa',
    name: 'Cenil',
    description:
      'Jajanan dari tepung kanji berwarna-warni yang kenyal disajikan dengan parutan kelapa. Sarapan tradisional Jawa yang manis gurih.',
    image: '🟠',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Tepung kanji', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut sangrai', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Gula merah sisir', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Pewarna makanan', amount: 3, unit: 'warna', category: 'Bumbu' },
      { name: 'Air panas', amount: 200, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Rebus gula merah dengan 100ml air hingga kental, saring. Dinginkan.',
      'Bagi tepung kanji menjadi 3 bagian, beri pewarna berbeda.',
      'Tuang air panas ke masing-masing bagian, uleni hingga kalis.',
      'Bentuk adonan menjadi bulatan kecil-kecil.',
      'Rebus cenil dalam air mendidih hingga mengambang.',
      'Angkat, tiriskan. Gulingkan di kelapa parut sangrai.',
      'Siram dengan gula merah cair, sajikan.',
    ],
    tags: ['cenil', 'kanji', 'warna-warni', 'Jawa', 'kenyal'],
    rating: 4.3,
  },
  {
    id: 'gethuk-singkong',
    name: 'Gethuk',
    description:
      'Jajahan singkong yang dilumatkan dengan gula kelapa. Sarapan tradisional Jawa yang sederhana dan manis legit.',
    image: '🟤',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Singkong', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pisang', amount: 4, unit: 'lembar', category: 'Bahan Utama' },
    ],
    steps: [
      'Kupas singkong, potong-potong. Rebus hingga empuk.',
      'Tiriskan singkong, haluskan selagi hangat.',
      'Campurkan singkong halus dengan kelapa parut dan garam.',
      'Bagi adonan menjadi dua, satu bagian tambahkan gula merah parut.',
      'Bungkus masing-masing adonan dengan daun pisang.',
      'Kukus selama 20 menit hingga matang.',
      'Angkat, dinginkan, potong-potong dan sajikan.',
    ],
    tags: ['gethuk', 'singkong', 'kelapa', 'gula merah', 'Jawa'],
    rating: 4.4,
  },
  {
    id: 'nasi-pecel-madiun',
    name: 'Nasi Pecel Madiun',
    description:
      'Nasi putih dengan sayuran pecel dan bumbu kacang khas Madiun yang gurih pedas. Sarapan tradisional Jawa Timur yang sehat.',
    image: '🥗',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 340,
    ingredients: [
      { name: 'Nasi putih', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang tanah goreng', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Kangkung', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Tauge', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol iris', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Gula merah', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Rempeyek', amount: 5, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus air hingga mendidih. Blansir kangkung, kacang panjang, tauge, dan kol.',
      'Tiriskan sayuran, tata di piring saji.',
      'Haluskan kacang tanah goreng bersama cabai rawit dan gula merah.',
      'Tambahkan air panas sedikit demi sedikit untuk mengencerkan bumbu kacang.',
      'Bumbui garam secukupnya, aduk rata.',
      'Tata nasi putih di piring, letakkan sayuran rebus di sampingnya.',
      'Siram bumbu kacang Madiun di atas sayuran. Taburi rempeyek.',
    ],
    tags: ['pecel', 'Madiun', 'kacang', 'sayuran', 'sehat'],
    rating: 4.7,
  },
];
