import type { Recipe } from '@/types';

export const recipesMinumanExtra: Recipe[] = [
  {
    id: 'es-pisang-ijo',
    name: 'Es Pisang Ijo',
    description:
      'Minuman khas Makassar berisi pisang yang dibungkus adonan pandan hijau, disajikan dengan sirup gula merah dan santan dingin.',
    image: '🍌',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Pisang raja matang', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air daun suji/pandan', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras, tapioka, dan air daun suji. Masak di api kecil sambil diaduk hingga kental dan mengkilap.',
      'Kupas pisang raja, bungkus dengan adonan pandan hijau membentuk selimut tipis.',
      'Kukus pisang yang sudah dibungkus selama 15 menit hingga matang. Angkat, dinginkan.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring, dinginkan.',
      'Masak santan dengan garam, aduk rata. Dinginkan.',
      'Potong-potong es pisang ijo, tata di mangkuk. Tambahkan es batu serut.',
      'Tuang santan dan sirup gula merah. Sajikan dingin.',
    ],
    tags: ['pisang ijo', 'Makassar', 'pandan', 'santan', 'tradisional'],
    rating: 4.7,
  },
  {
    id: 'es-palu-butung',
    name: 'Es Palu Butung',
    description:
      'Es khas Palu dengan pisang raja, sirup merah, susu kental manis, dan es serut. Sederhana tapi sangat menyegarkan.',
    image: '🍧',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 3,
    calories: 190,
    ingredients: [
      { name: 'Pisang raja matang', amount: 3, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 4, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Sirup merah/rosegren', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang dingin', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Kupas pisang raja, belah jadi dua bagian memanjang.',
      'Siapkan gelas atau mangkuk saji.',
      'Tata potongan pisang raja di dalam gelas.',
      'Tambahkan es batu serut hingga penuh.',
      'Tuangkan susu kental manis dan sirup merah.',
      'Tambahkan sedikit air matang dingin. Sajikan segera.',
    ],
    tags: ['palu butung', 'pisang', 'sirup', 'segar', 'Sulawesi'],
    rating: 4.4,
  },
  {
    id: 'es-kelapa-jelly',
    name: 'Es Kelapa Muda Jelly',
    description:
      'Kombinasi segar kelapa muda dengan jelly kenyal warna-warni. Minuman dingin yang cocok untuk cuaca panas.',
    image: '🧊',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 130,
    ingredients: [
      { name: 'Kelapa muda', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Nutrijell plain', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Sirup cocopandan', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 8, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Masak nutrijell dengan air dan gula sesuai petunjuk kemasan. Tuang ke cetakan, dinginkan hingga set.',
      'Buka kelapa muda, tuang airnya dan kerok dagingnya.',
      'Potong jelly yang sudah dingin berbentuk dadu kecil.',
      'Bagi air kelapa ke empat gelas.',
      'Tambahkan jelly, daging kelapa muda, dan sirup cocopandan.',
      'Masukkan es batu. Sajikan segera.',
    ],
    tags: ['kelapa muda', 'jelly', 'segar', 'dingin', 'simple'],
    rating: 4.5,
  },
  {
    id: 'es-blewah',
    name: 'Es Blewah',
    description:
      'Es buah blewah segar dengan sirup manis dan es serut. Rasa manis segar khas blewah yang menggugah selera.',
    image: '🍈',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 3,
    calories: 90,
    ingredients: [
      { name: 'Blewah matang', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Sirup gula', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang dingin', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu serut', amount: 150, unit: 'gram', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'pinch', category: 'Bumbu' },
    ],
    steps: [
      'Belah blewah, buang bijinya. Kerok daging buah blewah dengan sendok.',
      'Potong daging blewah menjadi bentuk dadu atau serutan sesuai selera.',
      'Siapkan gelas, masukkan potongan blewah.',
      'Tambahkan sirup gula, sedikit garam, dan air matang dingin.',
      'Tambahkan es batu serut.',
      'Aduk rata dan sajikan segera.',
    ],
    tags: ['blewah', 'buah', 'segar', 'dingin', 'sederhana'],
    rating: 4.3,
  },
  {
    id: 'es-timun-suri',
    name: 'Es Timun Suri',
    description:
      'Minuman tradisional Ramadhan dari timun suri dengan sirup gula merah. Manis segar dan menyegarkan untuk berbuka puasa.',
    image: '🥒',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    calories: 100,
    ingredients: [
      { name: 'Timun suri', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Jahe (geprek)', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
      { name: 'Perasan jeruk nipis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Belah timun suri, buang biji. Kerok dagingnya dan potong dadu.',
      'Rebus gula merah dengan air dan jahe hingga gula larut dan mendidih. Saring, dinginkan.',
      'Siapkan gelas, masukkan potongan timun suri.',
      'Tuang sirup gula merah yang sudah dingin.',
      'Tambahkan perasan jeruk nipis.',
      'Tambahkan es batu serut. Sajikan segera.',
    ],
    tags: ['timun suri', 'Ramadhan', 'gula merah', 'segar', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'es-kacang-hijau',
    name: 'Es Kacang Hijau',
    description:
      'Minuman segar dengan kacang hijau rebus empuk, santan, gula merah, dan es batu. Manis gurih dan mengenyangkan.',
    image: '🫘',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Kacang hijau', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam kacang hijau selama minimal 2 jam. Tiriskan.',
      'Rebus kacang hijau dengan daun pandan hingga empuk dan meletus. Angkat.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring, dinginkan.',
      'Panaskan santan dengan garam, aduk rata. Dinginkan.',
      'Siapkan gelas, tata kacang hijau rebus.',
      'Tuang sirup gula merah dan santan.',
      'Tambahkan es batu serut. Sajikan segera.',
    ],
    tags: ['kacang hijau', 'santan', 'gula merah', 'segar', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'es-buah-segar',
    name: 'Es Buah Segar',
    description:
      'Campuran potongan buah-buahan segar dengan sirup, susu, dan es serut. Pilihan menyegarkan untuk cuaca terik.',
    image: '🍹',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 20,
    servings: 4,
    calories: 140,
    ingredients: [
      { name: 'Nanas', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Melon', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Semangka', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Jeruk mandarin', amount: 3, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Nata de coco', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Sirup cocopandan', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 250, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Potong dadu semua buah: nanas, melon, semangka. Kupas jeruk mandarin.',
      'Tiriskan nata de coco.',
      'Campurkan semua potongan buah dan nata de coco dalam mangkuk besar.',
      'Tambahkan sirup cocopandan dan susu kental manis, aduk rata.',
      'Dinginkan di kulkas selama 15 menit.',
      'Sajikan dalam gelas dengan es batu serut.',
    ],
    tags: ['buah segar', 'nata de coco', 'segar', 'sehat', 'dingin'],
    rating: 4.6,
  },
  {
    id: 'es-campur-kacang',
    name: 'Es Campur Kacang',
    description:
      'Es campur khas dengan kacang tanah, kacang hijau, cincau, dan kuah santan gula merah. Manis, gurih, dan legit.',
    image: '🥤',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 20,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'Kacang tanah', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang hijau', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Cincau hitam', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam kacang hijau 2 jam, rebus hingga empuk.',
      'Rebus kacang tanah hingga empuk, kupas kulitnya.',
      'Potong cincau hitam berbentuk dadu kecil.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring, dinginkan.',
      'Masak santan dengan garam, aduk rata. Dinginkan.',
      'Tata kacang hijau, kacang tanah, dan cincau di gelas.',
      'Tambahkan es batu serut, tuang santan dan sirup gula merah. Sajikan.',
    ],
    tags: ['es campur', 'kacang', 'cincau', 'santan', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'es-sari-kedelai',
    name: 'Es Sari Kedelai',
    description:
      'Minuman sehat dari sari kedelai segar dengan gula aren dan es batu. Bergizi tinggi dan cocok untuk diet sehat.',
    image: '🥛',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 15,
    servings: 3,
    calories: 140,
    ingredients: [
      { name: 'Kedelai putih', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula aren', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam kedelai putih selama 6-8 jam atau semalaman. Bilas bersih.',
      'Blender kedelai dengan 600ml air hingga halus. Saring dengan kain bersih, peras ambil sarinya.',
      'Masak sari kedelai dengan daun pandan dan garam di atas api sedang.',
      'Masak sambil terus diaduk hingga mendidih. Angkat, dinginkan.',
      'Tambahkan gula aren cair ke dalam gelas.',
      'Tuang sari kedelai dingin, tambahkan es batu. Sajikan.',
    ],
    tags: ['sari kedelai', 'sehat', 'bergizi', 'trending', 'diet'],
    rating: 4.2,
  },
  {
    id: 'es-gandum',
    name: 'Es Gandum',
    description:
      'Minuman segar dari biji gandum rebus dengan santan, gula merah, dan es serut. Tekstur gandum yang kenyal menjadi daya tarik.',
    image: '🌾',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 15,
    servings: 3,
    calories: 180,
    ingredients: [
      { name: 'Biji gandum', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 150, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam biji gandum selama 3-4 jam. Tiriskan.',
      'Rebus gandum dengan daun pandan hingga empuk dan mengembang (±30 menit). Angkat, tiriskan.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring, dinginkan.',
      'Panaskan santan dengan garam, aduk rata. Dinginkan.',
      'Siapkan gelas, tata biji gandum rebus.',
      'Tuang santan dan sirup gula merah.',
      'Tambahkan es batu serut. Sajikan dingin.',
    ],
    tags: ['gandum', 'santan', 'gula merah', 'kenyal', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'es-lidah-buaya',
    name: 'Es Lidah Buaya',
    description:
      'Minuman sehat dari lidah buaya yang direbus, dipotong, dan dicampur sirup lemon. Menyegarkan dan berkhasiat untuk pencernaan.',
    image: '🪴',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 80,
    ingredients: [
      { name: 'Lidah buaya segar', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Perasan lemon/jeruk nipis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Kupas lidah buaya, ambil dagingnya yang bening. Cuci bersih untuk menghilangkan lendir.',
      'Potong daging lidah buaya berbentuk kubus kecil.',
      'Rebus potongan lidah buaya dengan air dan gula selama 10 menit. Tiriskan.',
      'Dinginkan lidah buaya yang sudah direbus.',
      'Siapkan gelas, masukkan lidah buaya.',
      'Tambahkan perasan lemon, madu, dan es batu. Aduk rata dan sajikan.',
    ],
    tags: ['lidah buaya', 'sehat', 'detoks', 'segar', 'herbal'],
    rating: 4.1,
  },
  {
    id: 'es-wortel',
    name: 'Es Wortel',
    description:
      'Minuman segar dari wortel yang diblender dengan susu dan gula. Kaya vitamin A dan cocok untuk kesehatan mata.',
    image: '🥕',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 120,
    ingredients: [
      { name: 'Wortel', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu', amount: 4, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Kupas wortel, potong-potong kecil.',
      'Masukkan wortel, susu cair, gula, dan air ke dalam blender.',
      'Blender hingga halus dan rata.',
      'Saring jus wortel jika diinginkan.',
      'Tuang ke dalam gelas, tambahkan es batu.',
      'Sajikan segera selagi dingin.',
    ],
    tags: ['wortel', 'susu', 'vitamin A', 'sehat', 'segar'],
    rating: 4.0,
  },
  {
    id: 'es-mangga',
    name: 'Es Mangga',
    description:
      'Segarnya mangga harum manis diblender dengan susu dan es batu. Minuman tropis yang manis segar dan harum.',
    image: '🥭',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 160,
    ingredients: [
      { name: 'Mangga harum manis', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Perasan jeruk nipis', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kupas mangga, potong dagingnya.',
      'Masukkan potongan mangga, susu cair, dan gula ke dalam blender.',
      'Blender hingga halus dan kental.',
      'Tambahkan perasan jeruk nipis, aduk rata.',
      'Tuang ke dalam gelas, tambahkan es batu.',
      'Sajikan segera dengan potongan mangga segar sebagai topping.',
    ],
    tags: ['mangga', 'susu', 'tropis', 'segar', 'manis'],
    rating: 4.6,
  },
  {
    id: 'es-melon',
    name: 'Es Melon',
    description:
      'Daging melon hijau yang diblender halus dengan susu dan gula. Warnanya cantik hijau segar dan rasanya manis menyegarkan.',
    image: '🍈',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 110,
    ingredients: [
      { name: 'Melon hijau', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang dingin', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu', amount: 5, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Kupas melon, potong dagingnya dan buang bijinya.',
      'Masukkan daging melon, susu cair, gula, dan air dingin ke dalam blender.',
      'Blender hingga halus dan rata.',
      'Saring jika diinginkan untuk tekstur yang lebih halus.',
      'Tuang ke dalam gelas, tambahkan es batu.',
      'Sajikan segera. Bisa ditambah potongan melon sebagai hiasan.',
    ],
    tags: ['melon', 'susu', 'hijau', 'segar', 'dingin'],
    rating: 4.4,
  },
  {
    id: 'es-semangka',
    name: 'Es Semangka',
    description:
      'Jus semangka segar yang diblender dengan es batu. Minuman pelepas dahaga yang manis alami dan kaya air.',
    image: '🍉',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 80,
    ingredients: [
      { name: 'Semangka merah', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Perasan jeruk nipis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Pelengkap' },
      { name: 'Daun mint (opsional)', amount: 3, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Potong semangka, buang bijinya. Ambil daging buahnya.',
      'Masukkan daging semangka dan gula ke dalam blender.',
      'Blender hingga halus dan menyatu.',
      'Tambahkan perasan jeruk nipis, aduk rata.',
      'Tuang ke dalam gelas, tambahkan es batu.',
      'Hias dengan daun mint. Sajikan segera.',
    ],
    tags: ['semangka', 'jus', 'segar', 'pelepas dahaga', 'sederhana'],
    rating: 4.5,
  },
  {
    id: 'es-markisa',
    name: 'Es Markisa',
    description:
      'Minuman segar dari daging buah markisa dengan air gula dan es batu. Aroma khas markisa yang harum dan rasa asam manis.',
    image: '🟡',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 95,
    ingredients: [
      { name: 'Buah markisa', amount: 8, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu', amount: 9, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Belah buah markisa, ambil daging dan bijinya menggunakan sendok.',
      'Masukkan daging markisa ke dalam panci, tambahkan air.',
      'Rebus dengan api kecil selama 5 menit. Saring untuk memisahkan biji dan ampas.',
      'Masukkan gula pasir ke dalam air markisa, aduk hingga larut. Dinginkan.',
      'Tuang ke dalam gelas, tambahkan es batu.',
      'Sajikan segera selagi dingin.',
    ],
    tags: ['markisa', 'asam manis', 'harum', 'tropis', 'segar'],
    rating: 4.4,
  },
  {
    id: 'es-duren',
    name: 'Es Duren',
    description:
      'Es daging durian dengan susu kental manis, coklat, dan es serut. Untuk pecinta durian yang ingin sensasi dingin.',
    image: '🤤',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 310,
    ingredients: [
      { name: 'Daging durian matang', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 4, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Coklat meses', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Es batu serut', amount: 150, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Ambil daging durian yang sudah matang, sisihkan sebagian untuk topping.',
      'Blender sebagian durian dengan susu kental manis dan susu cair hingga halus.',
      'Siapkan gelas, tata es batu serut.',
      'Tuang blended durian di atas es.',
      'Tambahkan potongan durian segar sebagai topping.',
      'Taburi coklat meses. Sajikan segera.',
    ],
    tags: ['durian', 'susu', 'premium', 'dingin', 'aroma'],
    rating: 4.6,
  },
  {
    id: 'es-coklat',
    name: 'Es Coklat',
    description:
      'Es coklat creamy dengan susu, coklat bubuk, dan es batu. Minuman coklat dingin yang disukai anak-anak dan dewasa.',
    image: '🍫',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 5,
    servings: 2,
    calories: 220,
    ingredients: [
      { name: 'Susu cair', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 3, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Susu kental manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan susu cair, coklat bubuk, gula pasir, dan susu kental manis di dalam blender.',
      'Blender hingga rata dan mengembang sedikit.',
      'Siapkan gelas, masukkan es batu.',
      'Tuang campuran coklat ke dalam gelas.',
      'Bisa ditambah whipped cream atau coklat parut sebagai topping.',
      'Sajikan segera selagi dingin.',
    ],
    tags: ['coklat', 'susu', 'dingin', 'creamy', 'manis'],
    rating: 4.5,
  },
  {
    id: 'es-susu-pensil',
    name: 'Es Susu Pensil',
    description:
      'Minuman es khas Palembang dengan susu, agar-agar panjang seperti pensil, dan sirup. Unik dalam penyajian dan segar rasanya.',
    image: '🥤',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 130,
    ingredients: [
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Sirup cocopandan', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan agar-agar, susu cair, dan gula. Masak hingga mendidih.',
      'Tuang adonan ke dalam plastik es krim atau cetakan silinder panjang seperti pensil.',
      'Dinginkan hingga agar-agar mengeras. Keluarkan dari cetakan.',
      'Potong-potong agar-agar panjang sekitar 5 cm.',
      'Siapkan gelas, tata potongan agar-agar susu.',
      'Tambahkan es batu serut, tuang susu kental manis dan sirup cocopandan.',
    ],
    tags: ['susu pensil', 'Palembang', 'unik', 'susu', 'segar'],
    rating: 4.3,
  },
  {
    id: 'es-tape-ketan',
    name: 'Es Tape Ketan',
    description:
      'Minuman segar dengan tape ketan hitam, santan, gula merah, dan es serut. Rasa tape yang asam manis menjadi ciri khas.',
    image: '🍶',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 200,
    ingredients: [
      { name: 'Tape ketan hitam', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci tape ketan hitam, tiriskan.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring, dinginkan.',
      'Panaskan santan dengan daun pandan dan garam. Masak hingga mendidih, aduk rata. Dinginkan.',
      'Siapkan gelas saji, tata tape ketan.',
      'Tambahkan es batu serut.',
      'Tuang santan dingin dan sirup gula merah di atasnya. Sajikan segera.',
    ],
    tags: ['tape ketan', 'santan', 'gula merah', 'asam manis', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'es-pleret',
    name: 'Es Pleret',
    description:
      'Es khas Yogyakarta berisi pleret (adonan tepung beras pipih), tape ketan, dan kuah santan gula merah yang manis gurih.',
    image: '🧊',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 30,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Tepung beras', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Tape ketan', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras dengan sedikit air, uleni hingga bisa dibentuk.',
      'Bentuk adonan pipih tipis bulat kecil (seperti koin), rebus dalam air mendidih hingga mengambang. Angkat, tiriskan.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring, dinginkan.',
      'Panaskan santan dengan daun pandan dan garam. Aduk rata, dinginkan.',
      'Siapkan mangkuk, tata pleret dan tape ketan.',
      'Tambahkan es batu serut.',
      'Tuang santan dan sirup gula merah. Sajikan segera.',
    ],
    tags: ['pleret', 'Yogyakarta', 'tape', 'santan', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'es-mochi',
    name: 'Es Mochi',
    description:
      'Minuman segar dengan mochi kenyal, cincau, kelapa muda, dan susu. Perpaduan tekstur dan rasa yang unik.',
    image: '🍡',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 30,
    servings: 3,
    calories: 190,
    ingredients: [
      { name: 'Tepung ketan', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Pewarna makanan', amount: 2, unit: 'tetes', category: 'Bumbu' },
      { name: 'Cincau hitam', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung ketan dengan gula dan pewarna makanan. Tambahkan air sedikit demi sedikit, uleni hingga kalis.',
      'Rebus air, ambil sedikit adonan ketan, bentuk bola-bola kecil. Rebus hingga mengambang.',
      'Angkat mochi, langsung masukkan ke air dingin agar tidak lengket.',
      'Potong cincau hitam berbentuk dadu kecil.',
      'Siapkan gelas, tata mochi dan cincau.',
      'Tambahkan susu cair, susu kental manis, dan es batu.',
    ],
    tags: ['mochi', 'ketan', 'cincau', 'susu', 'kekinian'],
    rating: 4.5,
  },
  {
    id: 'es-jelly',
    name: 'Es Jelly',
    description:
      'Campuran jelly warna-warni dengan sirup manis, susu, dan es serut. Tampilan cantik dan rasa yang menyegarkan.',
    image: '🍧',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 4,
    calories: 120,
    ingredients: [
      { name: 'Nutrijell warna-warni', amount: 3, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 900, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Sirup cocopandan', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Masak masing-masing nutrijell dengan rasa berbeda (300ml air per bungkus) beserta gula. Tuang ke cetakan terpisah.',
      'Dinginkan hingga jelly mengeras.',
      'Potong jelly berbagai warna menjadi dadu kecil.',
      'Siapkan gelas, tata campuran jelly warna-warni.',
      'Tambahkan es batu serut.',
      'Tuangkan susu kental manis dan sirup cocopandan di atasnya. Sajikan.',
    ],
    tags: ['jelly', 'warna-warni', 'susu', 'segar', 'anak-anak'],
    rating: 4.4,
  },
  {
    id: 'es-rumput-laut',
    name: 'Es Rumput Laut',
    description:
      'Minuman sehat dari rumput laut yang direbus dengan jahe, gula merah, dan perasan jeruk nipis. Berkhasiat untuk kesehatan.',
    image: '🥬',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 85,
    ingredients: [
      { name: 'Rumput laut kering', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Jahe (geprek)', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Perasan jeruk nipis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam rumput laut kering dalam air selama 15 menit hingga mengembang. Cuci bersih.',
      'Didihkan air, masukkan jahe geprek dan gula merah.',
      'Masak hingga gula larut, masukkan rumput laut.',
      'Masak selama 5 menit dengan api kecil. Angkat, dinginkan.',
      'Tambahkan perasan jeruk nipis, aduk rata.',
      'Tuang ke gelas, tambahkan es batu. Sajikan.',
    ],
    tags: ['rumput laut', 'sehat', 'herbal', 'segar', 'alami'],
    rating: 4.0,
  },
  {
    id: 'es-liang-teh',
    name: 'Es Liang Teh',
    description:
      'Minuman teh herbal dingin khas Tiongkok dengan longan, kolang-kaling, dan jelly. Manis menyegarkan dan menenangkan.',
    image: '🍵',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 110,
    ingredients: [
      { name: 'Teh hitam', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Longan kalengan', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kolang-kaling', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 700, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu', amount: 8, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Seduh teh hitam dengan 300ml air panas selama 10 menit. Saring, dinginkan.',
      'Rebus kolang-kaling dengan gula dan 400ml air selama 10 menit. Dinginkan.',
      'Belah longan kalengan jadi dua bagian.',
      'Campurkan teh yang sudah dingin dengan air kolang-kaling gula.',
      'Siapkan gelas, masukkan longan dan kolang-kaling.',
      'Tuang teh manis, tambahkan es batu. Sajikan.',
    ],
    tags: ['liang teh', 'longan', 'herbal', 'Tiongkok', 'segar'],
    rating: 4.3,
  },
  {
    id: 'es-ketimun',
    name: 'Es Ketimun',
    description:
      'Jus ketimun segar dengan madu dan perasan lemon. Minuman detox yang menyegarkan dan membantu melancarkan pencernaan.',
    image: '🥒',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 60,
    ingredients: [
      { name: 'Ketimun', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Perasan lemon', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang dingin', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun mint', amount: 3, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Es batu', amount: 4, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Kupas ketimun, potong-potong kecil. Buang biji jika suka.',
      'Masukkan ketimun dan air dingin ke dalam blender.',
      'Blender hingga halus. Saring jika diinginkan.',
      'Tambahkan madu dan perasan lemon, aduk rata.',
      'Tuang ke dalam gelas, tambahkan es batu.',
      'Hias dengan daun mint. Sajikan segera.',
    ],
    tags: ['ketimun', 'detoks', 'sehat', 'lemon', 'segar'],
    rating: 4.2,
  },
  {
    id: 'es-asem',
    name: 'Es Asem',
    description:
      'Minuman asam segar dari buah asem jawa dengan gula merah dan jahe. Rasa asam manis yang khas dan menyegarkan.',
    image: '🧃',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    calories: 90,
    ingredients: [
      { name: 'Asem jawa', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Jahe (geprek)', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu', amount: 8, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Larutkan asem jawa dengan 200ml air, saring ambil airnya.',
      'Geprek jahe agar aromanya keluar.',
      'Didihkan sisa air, masukkan air asem jawa, jahe, dan gula merah.',
      'Masak dengan api kecil selama 10 menit hingga gula larut.',
      'Beri garam, aduk rata. Saring, dinginkan.',
      'Tuang ke dalam gelas, tambahkan es batu. Sajikan dingin.',
    ],
    tags: ['asem jawa', 'asam manis', 'jahe', 'segar', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'es-nanas',
    name: 'Es Nanas',
    description:
      'Jus nanas segar yang manis asam dengan sedikit gula dan es batu. Kaya vitamin C dan enzim bromelain untuk kesehatan.',
    image: '🍍',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 95,
    ingredients: [
      { name: 'Nanas matang', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang dingin', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Perasan jeruk nipis', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu', amount: 4, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Kupas nanas, potong-potong kecil.',
      'Masukkan potongan nanas, air dingin, dan gula ke dalam blender.',
      'Blender hingga halus.',
      'Saring jus nanas untuk menghilangkan serat kasar.',
      'Tambahkan perasan jeruk nipis, aduk rata.',
      'Tuang ke gelas, tambahkan es batu. Sajikan segera.',
    ],
    tags: ['nanas', 'jus', 'vitamin C', 'segar', 'tropis'],
    rating: 4.4,
  },
  {
    id: 'es-delima',
    name: 'Es Delima',
    description:
      'Minuman segar khas Ramadhan dengan biji delima putih, sirup gula merah, dan santan dingin. Manis dan bertekstur unik.',
    image: '❄️',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 3,
    calories: 140,
    ingredients: [
      { name: 'Biji delima putih', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 150, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci bersih biji delima putih, tiriskan.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring, dinginkan.',
      'Panaskan santan dengan garam, aduk rata. Dinginkan.',
      'Siapkan gelas, masukkan biji delima putih.',
      'Tambahkan es batu serut.',
      'Tuang santan dingin dan sirup gula merah. Sajikan segera.',
    ],
    tags: ['delima', 'Ramadhan', 'santan', 'gula merah', 'segar'],
    rating: 4.4,
  },
  {
    id: 'es-sirsak',
    name: 'Es Sirsak',
    description:
      'Jus sirsak segar yang creamy dengan susu dan gula. Daging buah sirsak yang lembut membuat tekstur minuman istimewa.',
    image: '🥛',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 3,
    calories: 140,
    ingredients: [
      { name: 'Buah sirsak matang', amount: 1, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang dingin', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Belah buah sirsak, ambil dagingnya. Buang biji besar.',
      'Masukkan daging sirsak, susu cair, gula, dan air dingin ke dalam blender.',
      'Blender sebentar saja agar daging buah tidak terlalu halus (tetap ada tekstur).',
      'Tuang ke dalam gelas.',
      'Tambahkan es batu.',
      'Sajikan segera selagi dingin.',
    ],
    tags: ['sirsak', 'susu', 'creamy', 'segar', 'sehat'],
    rating: 4.5,
  },
];
