name = "dapurmindai"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NEXT_PUBLIC_CONVEX_URL = "https://silent-ocelot-29.convex.cloud"
NEXT_PUBLIC_CONVEX_SITE_URL = "https://silent-ocelot-29.convex.site"
