import type { Recipe } from '@/types';

export const westernRecipes4: Recipe[] = [
  // ─── Appetizers / Starters (western-234 to western-253) ───
  {
    "id": "western-234-classic-bruschetta",
    "name": "Classic Bruschetta",
    "category": "Western",
    "description": "Roti baguette panggang dengan topping tomat segar basil dan bawang putih. Appetizer Italia klasik yang menyegarkan.",
    "ingredients": [
      "1 buah baguette iris",
      "4 buah tomat matang cincang",
      "3 siung bawang putih cincang",
      "1/4 cup basil segar cincang",
      "2 sdm minyak zaitun",
      "1 sdm cuka balsamic",
      "garam dan merica",
      "1 sdm minyak zaitun untuk olesan"
    ],
    "steps": [
      "Potong baguette diagonal olesi minyak zaitun panggang hingga kecokelatan",
      "Campurkan tomat bawang putih basil minyak zaitun dan cuka balsamic",
      "Bumbui dengan garam dan merica aduk rata",
      "Olesi sisi panggang roti dengan bawang putih",
      "Sendokkan campuran tomat di atas roti panggang",
      "Sajikan segera selagi hangat"
    ],
    "cookTime": 8,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 180,
    "image": "",
    "tags": ["appetizer", "italia", "roti", "tomat"]
  },
  {
    "id": "western-235-cheesy-garlic-bread",
    "name": "Cheesy Garlic Bread",
    "category": "Western",
    "description": "Roti baguette dengan olesan mentega bawang putih dan keju leleh. Side dish yang selalu jadi favorit.",
    "ingredients": [
      "1 buah baguette",
      "4 sdm mentega lunak",
      "3 siung bawang putih cincang halus",
      "1 cup keju mozzarella parut",
      "1/4 cup keju parmesan parut",
      "1 sdm peterseli cincang",
      "garam",
      "sejumput paprika"
    ],
    "steps": [
      "Panaskan oven 200C",
      "Campurkan mentega bawang putih peterseli dan garam",
      "Belah baguette olesi campuran mentega",
      "Taburi mozzarella dan parmesan secara merata",
      "Panggang 10 menit hingga keju meleleh dan roti renyah",
      "Potong-potong sajikan hangat"
    ],
    "cookTime": 10,
    "prepTime": 10,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 220,
    "image": "",
    "tags": ["appetizer", "amerika", "roti", "keju"]
  },
  {
    "id": "western-236-stuffed-mushrooms",
    "name": "Stuffed Mushrooms",
    "category": "Western",
    "description": "Jamur champignon berisi campuran keju bawang putih dan remah roti. Appetizer elegan dan gurih.",
    "ingredients": [
      "16 buah jamur champignon besar",
      "100g keju krim",
      "1/2 cup keju parmesan parut",
      "3 siung bawang putih cincang",
      "1/4 cup remah roti",
      "2 sdm peterseli cincang",
      "2 sdm minyak zaitun",
      "garam dan merica"
    ],
    "steps": [
      "Bersihkan jamur cabut batangnya cincang halus",
      "Tumis batang jamur dan bawang putih dengan minyak zaitun",
      "Campurkan keju krim parmesan remah roti dan peterseli",
      "Masukkan tumisan jamur ke campuran keju aduk rata",
      "Isi jamur dengan campuran keju",
      "Panggang 180C selama 20 menit hingga kecokelatan",
      "Sajikan hangat"
    ],
    "cookTime": 20,
    "prepTime": 15,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 190,
    "image": "",
    "tags": ["appetizer", "amerika", "jamur", "keju"]
  },
  {
    "id": "western-237-caprese-salad",
    "name": "Caprese Salad",
    "category": "Western",
    "description": "Salad Italia sederhana dengan irisan mozzarella tomat segar dan basil. Disiram minyak zaitun dan balsamic.",
    "ingredients": [
      "250g keju mozzarella segar iris",
      "3 buah tomat besar iris",
      "1 cup basil segar",
      "2 sdm minyak zaitun extra virgin",
      "1 sdm cuka balsamic",
      "garam laut",
      "merica hitam"
    ],
    "steps": [
      "Iris mozzarella dan tomat dengan ketebalan yang sama",
      "Tata bergantian tomat mozzarella dan basil di piring saji",
      "Perciki minyak zaitun secara merata",
      "Teteskan cuka balsamic di atasnya",
      "Taburi garam laut dan merica hitam",
      "Sajikan segar sebagai appetizer"
    ],
    "cookTime": 0,
    "prepTime": 10,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 200,
    "image": "",
    "tags": ["appetizer", "italia", "salad", "keju"]
  },
  {
    "id": "western-238-loaded-nachos",
    "name": "Loaded Nachos",
    "category": "Western",
    "description": "Tortilla chips dengan topping keju jalapeño daging cincang dan sour cream. Camilan pesta yang mengenyangkan.",
    "ingredients": [
      "200g tortilla chips",
      "1.5 cup keju cheddar parut",
      "150g daging sapi cincang",
      "1/2 buah bawang bombay cincang",
      "1 buah paprika merah cincang",
      "4 sdm salsa",
      "3 sdm sour cream",
      "1 buah jalapeño iris",
      "1/4 cup daun bawang iris"
    ],
    "steps": [
      "Tumis bawang bombay masukkan daging cincang bumbui garam dan merica",
      "Masukkan paprika masak hingga layu angkat",
      "Tata tortilla chips di loyang beri topping daging dan keju",
      "Panggang 180C selama 8 menit hingga keju meleleh",
      "Tambahkan salsa sour cream dan jalapeño",
      "Taburi daun bawang sajikan langsung"
    ],
    "cookTime": 15,
    "prepTime": 10,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 350,
    "image": "",
    "tags": ["appetizer", "meksiko", "snack", "keju"]
  },
  {
    "id": "western-239-mozzarella-sticks",
    "name": "Mozzarella Sticks",
    "category": "Western",
    "description": "Tongkat keju mozzarella dibalut tepung roti dan digoreng renyah. Disajikan dengan saus marinara.",
    "ingredients": [
      "250g keju mozzarella potong tongkat",
      "1/2 cup tepung terigu",
      "2 butir telur kocok",
      "1 cup tepung roti",
      "1/2 cup parmesan parut",
      "1 sdt garlic powder",
      "minyak goreng",
      "saus marinara"
    ],
    "steps": [
      "Potong mozzarella menjadi tongkat-tongkat",
      "Balutkan keju ke tepung lalu celup ke telur kocok",
      "Gulingkan ke campuran tepung roti parmesan dan garlic powder",
      "Ulangi proses celup telur dan tepung roti untuk lapisan ganda",
      "Bekukan 30 menit agar tidak meleleh saat digoreng",
      "Goreng dalam minyak panas hingga keemasan",
      "Sajikan dengan saus marinara"
    ],
    "cookTime": 10,
    "prepTime": 25,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 280,
    "image": "",
    "tags": ["appetizer", "italia", "keju", "goreng"]
  },
  {
    "id": "western-240-fried-calamari",
    "name": "Fried Calamari",
    "category": "Western",
    "description": "Cincin cumi dibalut adonan tepung ringan dan digoreng renyah keemasan. Favort seafood appetizer.",
    "ingredients": [
      "400g cumi potong cincin",
      "1 cup tepung terigu",
      "1/2 cup tepung jagung",
      "1 sdt paprika",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "1 butir telur",
      "minyak goreng",
      "saus lemon aioli"
    ],
    "steps": [
      "Bersihkan cumi potong menjadi cincin-cincin",
      "Campurkan tepung terigu tepung jagung paprika garam dan merica",
      "Celupkan cumi ke telur kocok lalu gulingkan ke tepung",
      "Panaskan minyak goreng hingga 180C",
      "Goreng cumi 2-3 menit hingga keemasan renyah",
      "Tiriskan di tisu kertas",
      "Sajikan dengan saus lemon aioli dan irisan lemon"
    ],
    "cookTime": 10,
    "prepTime": 20,
    "servings": 4,
    "difficulty": "Sedang",
    "calories": 260,
    "image": "",
    "tags": ["appetizer", "mediterania", "seafood", "goreng"]
  },
  {
    "id": "western-241-deviled-eggs",
    "name": "Deviled Eggs",
    "category": "Western",
    "description": "Telur rebus setengah diisi campuran kuning telur mayones dan mustard. Appetizer klasik pesta.",
    "ingredients": [
      "6 butir telur rebus",
      "3 sdm mayones",
      "1 sdt mustard dijon",
      "1 sdm cuka putih",
      "1/4 sdt garam",
      "sejumput paprika",
      "sejumput merica",
      "daun peterseli untuk hiasan"
    ],
    "steps": [
      "Rebus telur 12 menit masukkan air dingin kupas",
      "Belah telur menjadi dua bagian ambil kuning telurnya",
      "Haluskan kuning telur dengan garpu",
      "Campurkan mayones mustard cuka garam dan merica",
      "Isi kembali putih telur dengan campuran kuning",
      "Taburi paprika dan hias dengan peterseli",
      "Dinginkan 30 menit sebelum disajikan"
    ],
    "cookTime": 15,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 150,
    "image": "",
    "tags": ["appetizer", "amerika", "telur", "pasta"]
  },
  {
    "id": "western-242-spinach-artichoke-dip",
    "name": "Spinach Artichoke Dip",
    "category": "Western",
    "description": "Dip krim bayam dan artichoke dengan keju meleleh. Camilan favorit di restoran Amerika.",
    "ingredients": [
      "300g bayam segar",
      "1 kaleng artichoke hearts cincang",
      "200g keju krim",
      "1/2 cup keju parmesan parut",
      "1/2 cup keju mozzarella parut",
      "3 siung bawang putih cincang",
      "1/4 cup susu",
      "garam dan merica",
      "tortilla chips"
    ],
    "steps": [
      "Tumis bawang putih dengan sedikit minyak hingga harum",
      "Masukkan bayam masak hingga layu",
      "Campurkan bayam artichoke keju krim parmesan dan susu",
      "Bumbui garam dan merica aduk rata",
      "Tuang ke loyang taburi mozzarella",
      "Panggang 180C selama 25 menit hingga kecokelatan",
      "Sajikan hangat dengan tortilla chips"
    ],
    "cookTime": 30,
    "prepTime": 10,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 220,
    "image": "",
    "tags": ["appetizer", "amerika", "dip", "keju"]
  },
  {
    "id": "western-243-shrimp-cocktail",
    "name": "Shrimp Cocktail",
    "category": "Western",
    "description": "Udang rebus besar disajikan dingin dengan saus cocktail. Appetizer elegan untuk acara formal.",
    "ingredients": [
      "500g udang besar kupas",
      "1 buah lemon",
      "2 sdm old bay seasoning",
      "saus cocktail: 1/2 cup ketchup",
      "2 sdm horseradish",
      "1 sdm cuka lemon",
      "1 sdt worcestershire sauce",
      "sejumput cabai sauce",
      "daun peterseli"
    ],
    "steps": [
      "Didihkan air dengan lemon dan old bay seasoning",
      "Masukkan udang rebus 2-3 menit hingga merah muda",
      "Segera masukkan ke air es untuk menghentikan proses masak",
      "Buat saus cocktail campurkan ketchup horseradish cuka lemon worcestershire dan cabai sauce",
      "Tata udang di mangkuk saji dengan es",
      "Sajikan saus cocktail di mangkuk terpisah",
      "Hias dengan irisan lemon dan peterseli"
    ],
    "cookTime": 5,
    "prepTime": 15,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 170,
    "image": "",
    "tags": ["appetizer", "amerika", "seafood", "udang"]
  },
  {
    "id": "western-244-buffalo-chicken-wings",
    "name": "Buffalo Chicken Wings",
    "category": "Western",
    "description": "Sayap ayam panggang renyah dengan saus buffalo pedas. Camilan pesta yang paling digemari.",
    "ingredients": [
      "1 kg sayap ayam",
      "1 sdt garam",
      "1/2 sdt merica",
      "1 sdt paprika",
      "saus buffalo: 1/2 cup saus cabai",
      "3 sdm mentega",
      "1 sdm cuka putih",
      "1/2 sdt bawang putih bubuk",
      "saus blue cheese untuk celupan",
      "batang seledri iris"
    ],
    "steps": [
      "Bumbui sayap ayam dengan garam merica dan paprika",
      "Panggang sayap 200C selama 40 menit hingga renyah dan kecokelatan",
      "Lelehkan mentega campurkan saus cabai cuka putih dan bawang putih bubuk",
      "Masukkan sayap panggang ke saus buffalo aduk hingga merata",
      "Panggang lagi 5 menit agar saus meresap",
      "Sajikan dengan saus blue cheese dan batang seledri"
    ],
    "cookTime": 45,
    "prepTime": 10,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 380,
    "image": "",
    "tags": ["appetizer", "amerika", "ayam", "pedas"]
  },
  {
    "id": "western-245-antipasto-platter",
    "name": "Antipasto Platter",
    "category": "Western",
    "description": "Piring berisi aneka daging olahan keju zaitun dan sayuran asinan. Pembuka makan Italia yang meriah.",
    "ingredients": [
      "100g prosciutto",
      "100g salami",
      "100g keju provolone iris",
      "100g mozzarella bola kecil",
      "1/2 cup zaitun hitam",
      "1/2 cup zaitun hijau",
      "100g jamur acar",
      "100g paprika acar",
      "4 sdm artichoke hearts",
      "kerupuk dan roti panggang"
    ],
    "steps": [
      "Siapkan piring saji besar",
      "Tata irisan prosciutto dan salami di satu sisi piring",
      "Susun keju provolone dan mozzarella di bagian lain",
      "Atur zaitun jamur acar dan paprika acar di tengah",
      "Tambahkan artichoke hearts",
      "Isi celah dengan kerupuk dan roti panggang",
      "Sajikan sebagai pembuka makan"
    ],
    "cookTime": 0,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 280,
    "image": "",
    "tags": ["appetizer", "italia", "daging", "keju"]
  },
  {
    "id": "western-246-potato-skins",
    "name": "Potato Skins",
    "category": "Western",
    "description": "Kulit kentang panggang renyah diisi keju bacon dan daun bawang. Camilan barat yang gurih.",
    "ingredients": [
      "4 buah kentang besar",
      "150g bacon iris",
      "1 cup keju cheddar parut",
      "1/4 cup daun bawang iris",
      "1/4 cup sour cream",
      "garam dan merica",
      "1 sdm minyak zaitun"
    ],
    "steps": [
      "Panggang kentang utuh 200C selama 45 menit hingga empuk",
      "Belah kentang ambil isinya sisihkan kulit",
      "Olesi kulit kentang dengan minyak zaitun",
      "Goreng bacon hingga renyah cincang",
      "Isi kulit kentang dengan keju dan bacon",
      "Panggang 180C selama 10 menit hingga keju meleleh",
      "Sajikan dengan sour cream dan taburan daun bawang"
    ],
    "cookTime": 55,
    "prepTime": 15,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 310,
    "image": "",
    "tags": ["appetizer", "amerika", "kentang", "keju"]
  },
  {
    "id": "western-247-jalapeno-poppers",
    "name": "Jalapeno Poppers",
    "category": "Western",
    "description": "Cabai jalapeno berisi keju krim dan dibalut tepung roti goreng renyah. Camilan pedas yang bikin ketergantungan.",
    "ingredients": [
      "12 buah jalapeno besar",
      "150g keju krim",
      "1/2 cup keju cheddar parut",
      "1/2 cup tepung terigu",
      "1 butir telur kocok",
      "1 cup tepung roti",
      "garam",
      "minyak goreng"
    ],
    "steps": [
      "Belah jalapeno memanjang buang bijinya",
      "Campurkan keju krim dan cheddar parut",
      "Isi jalapeno dengan campuran keju",
      "Balutkan ke tepung lalu celup ke telur",
      "Gulingkan ke tepung roti",
      "Goreng dalam minyak panas hingga keemasan",
      "Tiriskan sajikan hangat"
    ],
    "cookTime": 10,
    "prepTime": 20,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 230,
    "image": "",
    "tags": ["appetizer", "meksiko", "pedas", "keju"]
  },
  {
    "id": "western-248-cocktail-meatballs",
    "name": "Cocktail Meatballs",
    "category": "Western",
    "description": "Bola-bola daging kecil dengan saus manis asam. Camilan pesta klasik yang selalu habis duluan.",
    "ingredients": [
      "400g daging sapi cincang",
      "1/2 cup tepung roti",
      "1 butir telur",
      "3 siung bawang putih cincang",
      "1/4 cup peterseli cincang",
      "garam dan merica",
      "saus: 1 cup ketchup",
      "3 sdm gula merah",
      "2 sdm cuka apel",
      "1 sdt mustard"
    ],
    "steps": [
      "Campurkan daging cincang tepung roti telur bawang putih dan peterseli",
      "Bumbui garam dan merica aduk rata",
      "Bentuk bola-bola kecil seukuran meatball cocktail",
      "Panggang 200C selama 15 menit hingga matang",
      "Campurkan ketchup gula merah cuka apel dan mustard panaskan",
      "Masukkan meatball ke saus aduk hingga merata",
      "Sajikan dengan tusuk gigi"
    ],
    "cookTime": 20,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 250,
    "image": "",
    "tags": ["appetizer", "amerika", "daging", "pasta"]
  },
  {
    "id": "western-249-caponata",
    "name": "Caponata",
    "category": "Western",
    "description": "Hidangan sayuran asin manis khas Sisilia dengan terong zaitun dan kaper. Rasa Mediterania yang kaya.",
    "ingredients": [
      "2 buah terong potong dadu",
      "1 buah paprika merah potong dadu",
      "1 buah bawang bombay cincang",
      "2 batang seledri iris",
      "400g tomat kalengan",
      "1/4 cup zaitun hijau iris",
      "2 sdm kaper",
      "2 sdm cuka anggur merah",
      "3 sdm gula",
      "3 sdm minyak zaitun",
      "garam dan merica"
    ],
    "steps": [
      "Goreng terong dalam minyak zaitun hingga kecokelatan angkat",
      "Tumis bawang bombay dan seledri hingga layu",
      "Masukkan paprika masak 5 menit",
      "Tambahkan tomat kalengan zaitun dan kaper",
      "Masukkan cuka dan gula masak api kecil 20 menit",
      "Masukkan terong goreng aduk rata",
      "Dinginkan sajikan suhu ruangan dengan roti panggang"
    ],
    "cookTime": 30,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Sedang",
    "calories": 180,
    "image": "",
    "tags": ["appetizer", "italia", "sayuran", "mediterania"]
  },
  {
    "id": "western-250-cheese-fondue",
    "name": "Cheese Fondue",
    "category": "Western",
    "description": "Keju leleh kental untuk mencelupkan roti dan sayuran. Pengalaman makan interaktif khas Swiss.",
    "ingredients": [
      "200g keju gruyere parut",
      "200g keju emmental parut",
      "1 cup anggur putih",
      "1 sdm tepung jagung",
      "1 siung bawang putih cincang",
      "sejumput pala",
      "garam dan merica",
      "roti sourdough potong kubus",
      "sayuran segar untuk celupan"
    ],
    "steps": [
      "Panaskan panci fondue api sedang",
      "Tumis bawang putih sebentar masukkan anggur putih",
      "Didihkan anggur masukkan keju sedikit demi sedikit aduk terus",
      "Larutkan tepung jagung dengan sedikit anggur tuang ke campuran keju",
      "Tambahkan pala garam dan merica",
      "Aduk hingga keju meleleh dan saus kental halus",
      "Sajikan di fondue pot dengan roti dan sayuran untuk dicelupkan"
    ],
    "cookTime": 15,
    "prepTime": 10,
    "servings": 4,
    "difficulty": "Sedang",
    "calories": 320,
    "image": "",
    "tags": ["appetizer", "swiss", "keju", "pasta"]
  },
  {
    "id": "western-251-hummus-platter",
    "name": "Hummus Platter",
    "category": "Western",
    "description": "Hummus lembut dari kacang koro disajikan dengan minyak zaitun dan pita bread. Appetizer Timur Tengah populer.",
    "ingredients": [
      "2 cup kacang koro kalengan",
      "3 sdm tahini",
      "3 siung bawang putih",
      "3 sdm jus lemon",
      "2 sdm minyak zaitun",
      "1/2 sdt jinten",
      "garam",
      "2 sdm air es",
      "minyak zaitun extra virgin untuk topping",
      "paprika untuk taburan",
      "pita bread"
    ],
    "steps": [
      "Blender kacang koro dengan tahini dan jus lemon",
      "Masukkan bawang putih jinten garam dan air es",
      "Blender hingga sangat halus dan kental",
      "Tuang ke piring saji buat cekungan di tengah",
      "Perciki minyak zaitun di atasnya",
      "Taburi paprika",
      "Sajikan dengan pita bread yang dipanggang"
    ],
    "cookTime": 0,
    "prepTime": 10,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 180,
    "image": "",
    "tags": ["appetizer", "timur tengah", "healthy", "vegan"]
  },
  {
    "id": "western-252-tzatziki-platter",
    "name": "Tzatziki Platter",
    "category": "Western",
    "description": "Saus yogurt Yunani dengan mentimun dan bawang putih. Disajikan dengan sayuran segar dan roti pita.",
    "ingredients": [
      "2 cup yogurt Greek",
      "1 buah mentimun parut peras airnya",
      "3 siung bawang putih cincang halus",
      "2 sdm minyak zaitun",
      "2 sdm jus lemon",
      "1 sdm dill cincang",
      "1/4 sdt garam",
      "sayuran segar potong",
      "roti pita panggang"
    ],
    "steps": [
      "Parut mentimun peras airnya dengan kain bersih",
      "Campurkan yogurt Greek mentimun parut dan bawang putih",
      "Tambahkan minyak zaitun jus lemon dill dan garam",
      "Aduk rata dan dinginkan minimal 30 menit",
      "Potong sayuran segar seperti wortel paprika dan timun",
      "Tuang tzatziki ke mangkuk saji",
      "Sajikan dengan sayuran segar dan roti pita"
    ],
    "cookTime": 0,
    "prepTime": 15,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 160,
    "image": "",
    "tags": ["appetizer", "yunani", "healthy", "yogurt"]
  },
  {
    "id": "western-253-spring-rolls",
    "name": "Fresh Spring Rolls",
    "category": "Western",
    "description": "Roll segar dengan kulit beras transparan berisi udang sayuran dan bihun. Sehat dan menyegarkan.",
    "ingredients": [
      "12 lembar kulit lumpia beras",
      "200g udang rebus belah dua",
      "100g bihun rendam",
      "1 cup selada romaine iris",
      "1 buah wortel iris tipis",
      "1 buah mentimun iris tipis",
      "1/4 cup daun mint",
      "1/4 cup daun peterseli",
      "saus hoisin untuk celupan",
      "kacang tanah cincang"
    ],
    "steps": [
      "Rendam bihun dalam air panas hingga lunak tiriskan",
      "Rendam kulit lumpia beras satu per satu di air hangat selama 10 detik",
      "Letakkan isian di dekat tepi kulit: selada bihun sayuran dan udang",
      "Lipat kedua sisi ke dalam lalu gulung rapat",
      "Ulangi untuk semua bahan",
      "Sajikan dengan saus hoisin dan taburan kacang tanah",
      "Sajikan segar dinginkan di kulkas 1 jam lebih dulu"
    ],
    "cookTime": 5,
    "prepTime": 30,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 170,
    "image": "",
    "tags": ["appetizer", "asia", "healthy", "udang"]
  },

  // ─── Western Drinks / Beverages (western-254 to western-273) ───
  {
    "id": "western-254-hot-chocolate",
    "name": "Hot Chocolate",
    "category": "Western",
    "description": "Cokelat hangat kental dan creamy dengan taburan marshmallow. Minuman penghangat tubuh saat cuaca dingin.",
    "ingredients": [
      "2 cup susu",
      "100g dark chocolate potong",
      "2 sdm gula",
      "1 sdt vanilla",
      "sejumput garam",
      "marshmallow untuk topping",
      "whipped cream",
      "bubuk cocoa untuk taburan"
    ],
    "steps": [
      "Panaskan susu dengan api sedang jangan sampai mendidih",
      "Masukkan potongan dark chocolate aduk hingga meleleh sempurna",
      "Tambahkan gula vanilla dan garam aduk rata",
      "Tuang ke cangkir saji",
      "Tambahkan whipped cream di atasnya",
      "Taburi marshmallow dan bubuk cocoa",
      "Sajikan selagi hangat"
    ],
    "cookTime": 5,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 320,
    "image": "",
    "tags": ["minuman", "amerika", "cokelat", "hangat"]
  },
  {
    "id": "western-255-vanilla-milkshake",
    "name": "Vanilla Milkshake",
    "category": "Western",
    "description": "Milkshake vanilla klasik yang creamy dan manis dengan whipped cream dan cherry di atas.",
    "ingredients": [
      "2 cup es krim vanilla",
      "1 cup susu",
      "1 sdt vanilla extract",
      "1 sdm gula",
      "whipped cream",
      "cherry merah untuk hiasan",
      "sprinkles warna-warni"
    ],
    "steps": [
      "Masukkan es krim vanilla susu vanilla extract dan gula ke blender",
      "Blender hingga halus dan creamy",
      "Tuang ke gelas milkshake",
      "Tambahkan whipped cream di atasnya",
      "Hias dengan cherry merah dan taburan sprinkles",
      "Sajikan segera dengan sedotan"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 380,
    "image": "",
    "tags": ["minuman", "amerika", "es krim", "manis"]
  },
  {
    "id": "western-256-fresh-lemonade",
    "name": "Fresh Lemonade",
    "category": "Western",
    "description": "Lemonade segar dari perasan lemon asli dengan madu dan daun mint. Menyegarkan di hari panas.",
    "ingredients": [
      "6 buah lemon peras airnya",
      "5 cup air dingin",
      "1/2 cup gula atau madu",
      "1 cup air panas",
      "daun mint segar",
      "es batu",
      "irisan lemon untuk hiasan"
    ],
    "steps": [
      "Buat simple syrup campurkan gula dan air panas aduk hingga larut",
      "Dinginkan simple syrup",
      "Peras lemon saring bijinya",
      "Campurkan air lemon simple syrup dan air dingin",
      "Aduk rata koreksi rasa manis asam",
      "Masukkan es batu dan daun mint",
      "Sajikan dengan irisan lemon di gelas"
    ],
    "cookTime": 5,
    "prepTime": 10,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 120,
    "image": "",
    "tags": ["minuman", "amerika", "segar", "lemon"]
  },
  {
    "id": "western-257-virgin-mojito",
    "name": "Virgin Mojito",
    "category": "Western",
    "description": "Mojito tanpa alkohol dengan mint segar lemon dan soda. Minuman tropis yang sangat menyegarkan.",
    "ingredients": [
      "8 buah lemon nipis",
      "10 daun mint segar",
      "2 sdm gula",
      "1 cup soda tawar",
      "es batu",
      "1 sdt air gula",
      "daun mint untuk hiasan"
    ],
    "steps": [
      "Belah lemon nipis menjadi dua bagian",
      "Masukkan lemon daun mint dan gula ke gelas",
      "Muddler atau tumbuk dengan sendok hingga mengeluarkan sari",
      "Tambahkan es batu",
      "Tuang soda tawar dan air gula",
      "Aduk rata",
      "Hias dengan daun mint dan irisan lemon"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 100,
    "image": "",
    "tags": ["minuman", "kuba", "segar", "mint"]
  },
  {
    "id": "western-258-fruit-punch-sangria",
    "name": "Fruit Punch Sangria",
    "category": "Western",
    "description": "Sangria buah tanpa alkohol dengan campuran jus buah segar dan potongan buah. Minuman pesta meriah.",
    "ingredients": [
      "2 cup jus anggur merah",
      "1 cup jus orange",
      "1/2 cup jus cranberry",
      "1 buah apel potong dadu",
      "1 buah jeruk iris",
      "1 buah lemon iris",
      "1/2 cup strawberry",
      "2 sdm gula",
      "1 sdm jus lemon",
      "es batu",
      "daun mint"
    ],
    "steps": [
      "Campurkan jus anggur jus orange dan jus cranberry",
      "Tambahkan gula dan jus lemon aduk hingga gula larut",
      "Masukkan potongan apel jeruk lemon dan strawberry",
      "Dinginkan di kulkas minimal 2 jam agar rasa menyatu",
      "Tuang ke gelas dengan es batu",
      "Hias dengan irisan buah dan daun mint",
      "Sajikan dingin"
    ],
    "cookTime": 0,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 150,
    "image": "",
    "tags": ["minuman", "spanyol", "buah", "pasta"]
  },
  {
    "id": "western-259-berry-smoothie",
    "name": "Berry Smoothie",
    "category": "Western",
    "description": "Smoothie campuran berry segar dengan yogurt dan madu. Minuman sehat kaya antioksidan.",
    "ingredients": [
      "1 cup strawberry",
      "1/2 cup blueberry",
      "1/2 cup raspberry",
      "1 cup yogurt Greek",
      "1/2 cup susu",
      "1 sdm madu",
      "1 sdm chia seeds",
      "es batu"
    ],
    "steps": [
      "Masukkan semua buah berry yogurt dan susu ke blender",
      "Tambahkan madu dan es batu",
      "Blender hingga halus dan creamy",
      "Tuang ke gelas",
      "Taburi chia seeds di atasnya",
      "Sajikan segera"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 200,
    "image": "",
    "tags": ["minuman", "amerika", "healthy", "berry"]
  },
  {
    "id": "western-260-cappuccino",
    "name": "Cappuccino",
    "category": "Western",
    "description": "Kopi espresso dengan steamed milk dan foam lembut. Kopi Italia klasik yang creamy.",
    "ingredients": [
      "2 shot espresso",
      "1/2 cup susu",
      "1 sdm gula",
      "bubuk cocoa untuk taburan"
    ],
    "steps": [
      "Buat 2 shot espresso menggunakan mesin kopi atau moka pot",
      "Panaskan susu jangan sampai mendidih froth hingga berbusa",
      "Tuang espresso ke cangkir tambahkan gula",
      "Tuang susu perlahan dengan sudut menyamping",
      "Sendokkan foam di atasnya",
      "Taburi sedikit bubuk cocoa",
      "Sajikan panas"
    ],
    "cookTime": 5,
    "prepTime": 5,
    "servings": 1,
    "difficulty": "Sedang",
    "calories": 150,
    "image": "",
    "tags": ["minuman", "italia", "kopi", "hangat"]
  },
  {
    "id": "western-261-cafe-latte",
    "name": "Cafe Latte",
    "category": "Western",
    "description": "Espresso dengan susu steamed yang dominan. Kopi yang lembut dan cocok untuk yang tidak suka pahit.",
    "ingredients": [
      "1 shot espresso",
      "1 cup susu",
      "1 sdm gula",
      "1 sdt vanilla extract",
      "bubuk cocoa untuk hiasan"
    ],
    "steps": [
      "Buat 1 shot espresso tuang ke gelas",
      "Panaskan susu dengan vanilla hingga hangat",
      "Froth susu hingga berbusa lembut",
      "Tuang susu ke espresso perlahan",
      "Buat layer foam di atas",
      "Taburi bubuk cocoa di atas foam",
      "Sajikan hangat"
    ],
    "cookTime": 5,
    "prepTime": 5,
    "servings": 1,
    "difficulty": "Sedang",
    "calories": 180,
    "image": "",
    "tags": ["minuman", "italia", "kopi", "hangat"]
  },
  {
    "id": "western-262-iced-matcha-latte",
    "name": "Iced Matcha Latte",
    "category": "Western",
    "description": "Matcha green tea dengan susu dingin dan es batu. Minuman Jepang modern yang populer.",
    "ingredients": [
      "2 sdt matcha powder",
      "2 sdm air panas",
      "1 cup susu dingin",
      "2 sdm gula atau madu",
      "es batu",
      "1 sdm susu kental"
    ],
    "steps": [
      "Ayak matcha powder ke mangkuk kecil",
      "Tambahkan air panas kocok dengan chasen atau sendok hingga halus",
      "Dalam gelas masukkan es batu",
      "Tuang susu dingin dan gula",
      "Tuang matcha perlahan ke atas susu",
      "Buat layer hijau yang cantik",
      "Sajikan dingin aduk sebelum minum"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 1,
    "difficulty": "Mudah",
    "calories": 190,
    "image": "",
    "tags": ["minuman", "jepang", "matcha", "segar"]
  },
  {
    "id": "western-263-mango-lassi",
    "name": "Mango Lassi",
    "category": "Western",
    "description": "Smoothie mangga India dengan yogurt dan cardamom. Manis segar dan menyegarkan.",
    "ingredients": [
      "2 buah mangga matang potong",
      "1 cup yogurt",
      "1/2 cup susu",
      "2 sdm gula",
      "1/4 sdt cardamom",
      "1/2 cup es batu",
      "1 sdm kacang almond iris untuk hiasan"
    ],
    "steps": [
      "Masukkan potongan mangga yogurt susu dan gula ke blender",
      "Tambahkan cardamom dan es batu",
      "Blender hingga halus dan creamy",
      "Tuang ke gelas",
      "Taburi kacang almond iris di atasnya",
      "Sajikan dingin"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 220,
    "image": "",
    "tags": ["minuman", "india", "mango", "yogurt"]
  },
  {
    "id": "western-264-orange-julius",
    "name": "Orange Julius",
    "category": "Western",
    "description": "Smoothie jeruk creamy khas Amerika dengan vanilla dan susu. Rasa seperti milkshake jeruk.",
    "ingredients": [
      "1 cup jus orange segar",
      "1/2 cup susu",
      "1/2 cup es krim vanilla",
      "1/2 cup es batu",
      "1 sdm gula",
      "1 sdt vanilla extract",
      "sejumput garam"
    ],
    "steps": [
      "Masukkan jus orange susu es krim vanilla dan es batu ke blender",
      "Tambahkan gula vanilla extract dan garam",
      "Blender hingga halus dan berbusa",
      "Tuang ke gelas tinggi",
      "Sajikan segera dengan sedotan"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 200,
    "image": "",
    "tags": ["minuman", "amerika", "jeruk", "segar"]
  },
  {
    "id": "western-265-root-beer-float",
    "name": "Root Beer Float",
    "category": "Western",
    "description": "Root beer dengan es krim vanilla yang meleleh. Minuman soda klasik Amerika yang nostalgik.",
    "ingredients": [
      "2 cup root beer dingin",
      "2 scoop es krim vanilla",
      "whipped cream",
      "cherry merah",
      "es batu"
    ],
    "steps": [
      "Siapkan gelas tinggi",
      "Masukkan 1-2 buah es batu",
      "Tuang root beer perlahan",
      "Letakkan 2 scoop es krim vanilla di atasnya",
      "Beri whipped cream",
      "Hias dengan cherry merah",
      "Sajikan segera dengan sendok dan sedotan"
    ],
    "cookTime": 0,
    "prepTime": 3,
    "servings": 1,
    "difficulty": "Mudah",
    "calories": 300,
    "image": "",
    "tags": ["minuman", "amerika", "es krim", "soda"]
  },
  {
    "id": "western-266-chai-tea-latte",
    "name": "Chai Tea Latte",
    "category": "Western",
    "description": "Teh masala India dengan susu steamed dan rempah. Hangat harum dan menghibur.",
    "ingredients": [
      "2 cup susu",
      "1 cup air",
      "2 sdm teh hitam",
      "3 buah kapulaga",
      "2 batang kayu manis",
      "3 cengkeh",
      "1 sdt jahe parut",
      "2 sdm gula"
    ],
    "steps": [
      "Didihkan air dengan kapulaga kayu manis cengkeh dan jahe",
      "Masukkan teh hitam masak 3 menit",
      "Tuang susu masak hingga mendidih",
      "Saring ke cangkir",
      "Tambahkan gula aduk rata",
      "Sajikan panas dengan foam alami dari susu"
    ],
    "cookTime": 10,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 180,
    "image": "",
    "tags": ["minuman", "india", "teh", "hangat"]
  },
  {
    "id": "western-267-strawberry-banana-smoothie",
    "name": "Strawberry Banana Smoothie",
    "category": "Western",
    "description": "Smoothie strawberry dan pisang yang creamy dan manis alami. Minuman sehat untuk sarapan.",
    "ingredients": [
      "1 cup strawberry",
      "1 buah pisang beku",
      "1 cup susu",
      "1/2 cup yogurt",
      "1 sdm madu",
      "1/2 cup es batu"
    ],
    "steps": [
      "Masukkan strawberry pisang beku susu dan yogurt ke blender",
      "Tambahkan madu dan es batu",
      "Blender hingga halus dan creamy",
      "Tuang ke gelas",
      "Sajikan segera",
      "Bisa ditambahkan topping granola di atasnya"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 210,
    "image": "",
    "tags": ["minuman", "amerika", "healthy", "smoothie"]
  },
  {
    "id": "western-268-tropical-pinacolada",
    "name": "Tropical Pina Colada",
    "category": "Western",
    "description": "Smoothie nanas kelapa yang tropis dan menyegarkan. Tanpa alkohol cocok untuk semua usia.",
    "ingredients": [
      "1 cup nanas potong",
      "1/2 cup santan",
      "1/2 cup susu",
      "3 sdm gula",
      "1 cup es batu",
      "1 sdm kelapa parut untuk hiasan",
      "irisan nanas untuk hiasan"
    ],
    "steps": [
      "Masukkan nanas susu santan gula dan es batu ke blender",
      "Blender hingga halus dan creamy",
      "Tuang ke gelas",
      "Taburi kelapa parut di atasnya",
      "Hias dengan irisan nanas",
      "Sajikan dingin"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 230,
    "image": "",
    "tags": ["minuman", "tropis", "nanas", "segar"]
  },
  {
    "id": "western-269-peach-iced-tea",
    "name": "Peach Iced Tea",
    "category": "Western",
    "description": "Teh dingin dengan rasa persik segar dan manis. Minuman musim panas yang menyegarkan.",
    "ingredients": [
      "3 kantong teh hitam",
      "4 cup air panas",
      "2 buah persik matang",
      "3 sdm gula",
      "1 sdm jus lemon",
      "es batu",
      "daun mint untuk hiasan"
    ],
    "steps": [
      "Seduh kantong teh dalam air panas selama 5 menit angkat kantong teh",
      "Haluskan persik dengan blender",
      "Campurkan persik halus gula dan jus lemon ke teh",
      "Aduk rata dinginkan di kulkas",
      "Tuang ke gelas dengan es batu",
      "Hias dengan irisan persik dan daun mint"
    ],
    "cookTime": 5,
    "prepTime": 10,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 130,
    "image": "",
    "tags": ["minuman", "amerika", "teh", "segar"]
  },
  {
    "id": "western-270-caramel-macchiato",
    "name": "Caramel Macchiato",
    "category": "Western",
    "description": "Vanilla latte dengan drizzle karamel. Kopi favorit di kedai kopi ternama.",
    "ingredients": [
      "1 shot espresso",
      "1 cup susu",
      "2 sdm vanilla syrup",
      "2 sdm saus karamel",
      "es batu",
      "whipped cream"
    ],
    "steps": [
      "Olesi saus karamel di dinding gelas",
      "Tambahkan vanilla syrup dan susu ke gelas",
      "Masukkan es batu",
      "Tuang espresso perlahan di atas susu",
      "Buat layer yang cantik",
      "Tambahkan whipped cream di atasnya",
      "Drizzle saus karamel di atas whipped cream"
    ],
    "cookTime": 5,
    "prepTime": 5,
    "servings": 1,
    "difficulty": "Sedang",
    "calories": 250,
    "image": "",
    "tags": ["minuman", "italia", "kopi", "karamel"]
  },
  {
    "id": "western-271-watermelon-agua-fresca",
    "name": "Watermelon Agua Fresca",
    "category": "Western",
    "description": "Minuman semangka segar khas Meksiko. Dingin menyegarkan dan manis alami.",
    "ingredients": [
      "4 cup daging semangka potong",
      "2 cup air dingin",
      "3 sdm gula",
      "2 sdm jus lemon",
      "es batu",
      "daun mint",
      "garam sejumput"
    ],
    "steps": [
      "Blender daging semangka dengan air hingga halus",
      "Saring ampas semangka",
      "Tambahkan gula jus lemon dan garam",
      "Aduk rata koreksi rasa",
      "Dinginkan di kulkas",
      "Tuang ke gelas dengan es batu",
      "Hias dengan daun mint"
    ],
    "cookTime": 0,
    "prepTime": 10,
    "servings": 4,
    "difficulty": "Mudah",
    "calories": 110,
    "image": "",
    "tags": ["minuman", "meksiko", "buah", "segar"]
  },
  {
    "id": "western-272-blueberry-smoothie-bowl",
    "name": "Blueberry Smoothie Bowl",
    "category": "Western",
    "description": "Smoothie blueberry kental yang disajikan dalam mangkuk dengan topping granola dan buah segar.",
    "ingredients": [
      "1 cup blueberry beku",
      "1 buah pisang beku",
      "1/2 cup yogurt",
      "1/4 cup susu almond",
      "1 sdm madu",
      "granola untuk topping",
      "irisan pisang",
      "chia seeds",
      "kacang almond iris"
    ],
    "steps": [
      "Blender blueberry pisang beku yogurt susu almond dan madu",
      "Blender hingga kental seperti soft serve",
      "Tuang ke mangkuk",
      "Atur topping granola irisan pisang chia seeds dan almond",
      "Sajikan segera"
    ],
    "cookTime": 0,
    "prepTime": 10,
    "servings": 1,
    "difficulty": "Mudah",
    "calories": 280,
    "image": "",
    "tags": ["minuman", "amerika", "healthy", "smoothie"]
  },
  {
    "id": "western-273-mint-hot-chocolate",
    "name": "Mint Hot Chocolate",
    "category": "Western",
    "description": "Cokelat hangat dengan aroma mint yang menyegarkan. Kombinasi rasa yang unik dan menenangkan.",
    "ingredients": [
      "2 cup susu",
      "100g dark chocolate potong",
      "1 sdt peppermint extract",
      "2 sdm gula",
      "sejumput garam",
      "whipped cream",
      "crushed candy cane untuk topping",
      "marshmallow"
    ],
    "steps": [
      "Panaskan susu dengan api sedang",
      "Masukkan dark chocolate potong aduk hingga meleleh",
      "Tambahkan peppermint extract gula dan garam",
      "Aduk rata jangan sampai mendidih",
      "Tuang ke cangkir saji",
      "Tambahkan whipped cream marshmallow dan candy cane",
      "Sajikan hangat"
    ],
    "cookTime": 8,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 340,
    "image": "",
    "tags": ["minuman", "amerika", "cokelat", "mint"]
  },

  // ─── Light Meals / Sandwiches (western-274 to western-287) ───
  {
    "id": "western-274-club-sandwich",
    "name": "Club Sandwich",
    "category": "Western",
    "description": "Sandwich triple decker dengan ayam bacon telur dan sayuran. Sandwich klasik Amerika yang mengenyangkan.",
    "ingredients": [
      "6 lembar roti tawar panggang",
      "200g ayam dada panggang iris",
      "6 iris bacon goreng",
      "2 butir telur rebus iris",
      "selada",
      "2 iris tomat",
      "2 iris keju cheddar",
      "mayones",
      "garam dan merica",
      "tusuk gigi untuk menjaga bentuk"
    ],
    "steps": [
      "Panggang roti tawar hingga kecokelatan",
      "Olesi mayones di setiap sisi roti",
      "Tata lapis pertama: roti selada ayam dan tomat",
      "Tata lapis kedua: roti telur rebus dan bacon",
      "Tutup dengan roti ketiga dan keju",
      "Tutup roti terakhir potong diagonal",
      "Tusuk dengan tusuk gigi sajikan dengan keripik kentang"
    ],
    "cookTime": 15,
    "prepTime": 15,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 520,
    "image": "",
    "tags": ["sandwich", "amerika", "ayam", "bacon"]
  },
  {
    "id": "western-275-grilled-cheese-sandwich",
    "name": "Grilled Cheese Sandwich",
    "category": "Western",
    "description": "Sandwich keju yang dipanggang hingga keju meleleh dan roti renyah keemasan. Comfort food sederhana yang sempurna.",
    "ingredients": [
      "4 lembar roti tawar",
      "200g keju cheddar parut",
      "2 sdm mentega",
      "garam",
      "1/4 sdt paprika",
      "sup tomat untuk sajian"
    ],
    "steps": [
      "Olesi mentega di kedua sisi setiap lembar roti",
      "Berisi keju cheddar parut di antara dua lembar roti",
      "Taburi sedikit garam dan paprika di atas keju",
      "Panaskan wajan api sedang",
      "Panggang sandwich 3-4 menit per sisi hingga kecokelatan",
      "Keju harus meleleh sempurna di dalam",
      "Potong diagonal sajikan dengan sup tomat"
    ],
    "cookTime": 10,
    "prepTime": 5,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 380,
    "image": "",
    "tags": ["sandwich", "amerika", "keju", "panggang"]
  },
  {
    "id": "western-276-blt-sandwich",
    "name": "BLT Sandwich",
    "category": "Western",
    "description": "Sandwich klasik dengan bacon lettuce dan tomato. Sederhana tapi selalu memuaskan.",
    "ingredients": [
      "4 lembar roti tawar panggang",
      "8 iris bacon goreng renyah",
      "4 lembar selada",
      "2 buah tomat iris",
      "2 sdm mayones",
      "1/2 sdt lada hitam",
      "garam"
    ],
    "steps": [
      "Goreng bacon hingga renyah tiriskan di tisu kertas",
      "Panggang roti tawar hingga kecokelatan",
      "Olesi mayones di kedua sisi roti",
      "Tata selada iris tomat di atas roti",
      "Letakkan bacon di atasnya",
      "Taburi merica hitam dan garam",
      "Tutup roti potong diagonal sajikan"
    ],
    "cookTime": 10,
    "prepTime": 10,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 420,
    "image": "",
    "tags": ["sandwich", "amerika", "bacon", "klasik"]
  },
  {
    "id": "western-277-italian-panini",
    "name": "Italian Panini",
    "category": "Western",
    "description": "Panini Italia dengan ham mozzarella basil dan pesto dipanggang hingga renyah dan keju meleleh.",
    "ingredients": [
      "2 buah roti ciabatta",
      "150g ham italia iris",
      "100g keju mozzarella iris",
      "2 sdm pesto",
      "selada",
      "2 iris tomat",
      "2 sdm minyak zaitun",
      "garam dan merica"
    ],
    "steps": [
      "Belah roti ciabatta olesi pesto di kedua bagian",
      "Tata ham mozzarella selada dan tomat",
      "Taburi garam dan merica",
      "Tutup roti olesi luar dengan minyak zaitun",
      "Panggang di panini press atau wajan berat selama 5 menit",
      "Roti harus renyah kecokelatan dan keju meleleh",
      "Potong diagonal sajikan panas"
    ],
    "cookTime": 8,
    "prepTime": 10,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 440,
    "image": "",
    "tags": ["sandwich", "italia", "panini", "keju"]
  },
  {
    "id": "western-278-chicken-caesar-wrap",
    "name": "Chicken Caesar Wrap",
    "category": "Western",
    "description": "Tortilla berisi ayam panggang selada romaine dan caesar dressing. Makan siang praktis dan sehat.",
    "ingredients": [
      "2 lembar tortilla besar",
      "200g ayam dada panggang iris",
      "2 cup selada romaine cincang",
      "1/4 cup keju parmesan parut",
      "3 sdm caesar dressing",
      "1/2 cup crouton",
      "2 iris tomat"
    ],
    "steps": [
      "Panggang ayam dada bumbui garam dan merica iris tipis",
      "Campurkan selada dengan caesar dressing",
      "Letakkan tortilla di alas",
      "Tata ayam selada crouton tomat dan parmesan di tengah",
      "Lipat kedua ujung lalu gulung rapat",
      "Potong diagonal",
      "Sajikan dengan sisa caesar dressing"
    ],
    "cookTime": 15,
    "prepTime": 10,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 390,
    "image": "",
    "tags": ["sandwich", "amerika", "ayam", "wrap"]
  },
  {
    "id": "western-279-classic-hamburger",
    "name": "Classic Hamburger",
    "category": "Western",
    "description": "Hamburger daging sapi klasik dengan keju selada tomat dan saus spesial. Ikon makanan Amerika.",
    "ingredients": [
      "400g daging sapi giling",
      "2 buah roti burger panggang",
      "2 iris keju cheddar",
      "selada",
      "2 iris tomat",
      "2 iris bawang bombay",
      "2 iris acar mentimun",
      "saus: 2 sdm mayones",
      "1 sdm mustard",
      "1 sdm ketchup",
      "garam dan merica"
    ],
    "steps": [
      "Campurkan daging giling garam dan merica bentuk patty",
      "Panggang patty di grill pan 4 menit per sisi",
      "Satu menit sebelum matang letakkan keju di atas patty",
      "Campurkan mayones mustard dan ketchup untuk saus",
      "Olesi saus di kedua sisi roti burger",
      "Tata selada tomat bawang acar dan patty",
      "Tutup burger sajikan dengan kentang goreng"
    ],
    "cookTime": 15,
    "prepTime": 15,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 550,
    "image": "",
    "tags": ["sandwich", "amerika", "burger", "daging"]
  },
  {
    "id": "western-280-reuben-sandwich",
    "name": "Reuben Sandwich",
    "category": "Western",
    "description": "Sandwich dengan daging corned beef sauerkraut keju Swiss dan thousand island dressing. Khas New York.",
    "ingredients": [
      "4 lembar roti rye",
      "200g corned beef iris",
      "1 cup sauerkraut",
      "4 iris keju Swiss",
      "3 sdm thousand island dressing",
      "2 sdm mentega"
    ],
    "steps": [
      "Tumis sauerkraut sebentar untuk mengurangi keasaman",
      "Olesi mentega di luar kedua roti",
      "Olesi thousand island dressing di dalam roti",
      "Tata corned beef sauerkraut dan keju Swiss",
      "Tutup roti",
      "Panggang di wajan api sedang 3-4 menit per sisi",
      "Potong diagonal sajikan panas"
    ],
    "cookTime": 10,
    "prepTime": 10,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 480,
    "image": "",
    "tags": ["sandwich", "amerika", "daging", "keju"]
  },
  {
    "id": "western-281-philly-cheesesteak",
    "name": "Philly Cheesesteak",
    "category": "Western",
    "description": "Sandwich daging sapi iris dengan paprika bawang dan keju provolone. Legendaris dari Philadelphia.",
    "ingredients": [
      "300g daging sapi sirloin iris tipis",
      "1 buah paprika hijau iris",
      "1 buah bawang bombay iris",
      "200g keju provolone iris",
      "2 buah roti hoagie",
      "2 sdm minyak zaitun",
      "garam dan merica",
      "mayones"
    ],
    "steps": [
      "Panaskan minyak zaitun di wajan api besar",
      "Tumis bawang bombay dan paprika hingga layu",
      "Masukkan daging sapi iris masak hingga kecokelatan",
      "Bumbui garam dan merica",
      "Letakkan keju provolone di atas daging biarkan meleleh",
      "Buka roti hoagie isi dengan campuran daging",
      "Sajikan panas dengan mayones"
    ],
    "cookTime": 12,
    "prepTime": 10,
    "servings": 2,
    "difficulty": "Sedang",
    "calories": 560,
    "image": "",
    "tags": ["sandwich", "amerika", "daging", "keju"]
  },
  {
    "id": "western-282-tuna-melt",
    "name": "Tuna Melt",
    "category": "Western",
    "description": "Sandwich tuna dengan keju yang dipanggang hingga meleleh. Makan siang sederhana yang memuaskan.",
    "ingredients": [
      "2 kaleng tuna dalam air tiriskan",
      "3 sdm mayones",
      "1 batang seledri cincang",
      "2 sdm bawang merah cincang",
      "1 sdt mustard dijon",
      "garam dan merica",
      "4 lembar roti tawar",
      "4 iris keju cheddar",
      "1 sdm mentega"
    ],
    "steps": [
      "Campurkan tuna mayones seledri bawang merah dan mustard",
      "Bumbui garam dan merica aduk rata",
      "Olesi mentega di luar roti",
      "Berisi campuran tuna di atas roti",
      "Tata irisan keju cheddar di atas tuna",
      "Tutup roti",
      "Panggang di wajan 3 menit per sisi hingga keju meleleh"
    ],
    "cookTime": 10,
    "prepTime": 10,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 420,
    "image": "",
    "tags": ["sandwich", "amerika", "tuna", "keju"]
  },
  {
    "id": "western-283-banh-mi-sandwich",
    "name": "Banh Mi Sandwich",
    "category": "Western",
    "description": "Sandwich Vietnam dengan roti baguette isinya daging babi pate sayuran acar dan saus pedas.",
    "ingredients": [
      "1 buah baguette",
      "200g daging babi panggang iris",
      "2 sdm pate hati",
      "1/4 cup wortel acar",
      "1/4 cup daun bawang acar",
      "irisan mentimun",
      "iris cabai rawit",
      "daun ketumbar segar",
      "2 sdm saus sambal",
      "2 sdm kecap asin",
      "mayones"
    ],
    "steps": [
      "Panggang baguette hingga renyah di luar",
      "Belah baguette olesi mayones dan pate",
      "Tata daging babi panggang di dalam roti",
      "Tambahkan wortel acar daun bawang acar dan mentimun",
      "Siram saus sambal dan kecap asin",
      "Tambahkan cabai rawit dan daun ketumbar",
      "Tutup roti sajikan"
    ],
    "cookTime": 10,
    "prepTime": 15,
    "servings": 2,
    "difficulty": "Sedang",
    "calories": 460,
    "image": "",
    "tags": ["sandwich", "vietnam", "daging", "pedas"]
  },
  {
    "id": "western-284-pulled-pork-sandwich",
    "name": "Pulled Pork Sandwich",
    "category": "Western",
    "description": "Daging babi suwir slow-cooked dengan saus BBQ di atas roti hamburger. Comfort food Amerika Selatan.",
    "ingredients": [
      "500g daging babi shoulder",
      "1 cup saus BBQ",
      "2 sdm cuka apel",
      "1 sdm gula merah",
      "1 sdt paprika asap",
      "1 sdt bawang putih bubuk",
      "1 sdt garam",
      "4 buah roti hamburger",
      "coleslaw untuk lauk"
    ],
    "steps": [
      "Bumbui daging babi dengan paprika asap bawang putih garam",
      "Slow cook daging 150C selama 3 jam hingga empuk",
      "Suwir daging dengan garpu",
      "Campurkan saus BBQ cuka apel dan gula merah",
      "Masukkan daging suwir ke saus BBQ aduk rata",
      "Panaskan sebentar",
      "Sajikan di roti hamburger dengan coleslaw"
    ],
    "cookTime": 180,
    "prepTime": 15,
    "servings": 4,
    "difficulty": "Sedang",
    "calories": 520,
    "image": "",
    "tags": ["sandwich", "amerika", "daging", "bbq"]
  },
  {
    "id": "western-285-lobster-roll",
    "name": "Lobster Roll",
    "category": "Western",
    "description": "Daging lobster segar dengan mayones dan seledri di dalam roti panggang. Sandwich premium New England.",
    "ingredients": [
      "300g daging lobster rebus potong",
      "3 sdm mayones",
      "1 batang seledri cincang halus",
      "1 sdm jus lemon",
      "sejumput paprika",
      "garam dan merica",
      "2 buah roti hot dog bun",
      "mentega untuk olesan",
      "daun peterseli cincang"
    ],
    "steps": [
      "Rebus lobster hingga matang kupas dan potong dagingnya",
      "Campurkan lobster mayones seledri jus lemon dan paprika",
      "Bumbui garam dan merica",
      "Olesi roti bun dengan mentega panggang hingga keemasan",
      "Isi roti dengan campuran lobster",
      "Taburi peterseli cincang",
      "Sajikan segera dengan kerupuk kentang"
    ],
    "cookTime": 15,
    "prepTime": 15,
    "servings": 2,
    "difficulty": "Sedang",
    "calories": 470,
    "image": "",
    "tags": ["sandwich", "amerika", "seafood", "lobster"]
  },
  {
    "id": "western-286-veggie-burger",
    "name": "Veggie Burger",
    "category": "Western",
    "description": "Burger vegetarian dengan patty dari kacang hitam dan sayuran. Sehat dan mengenyangkan.",
    "ingredients": [
      "1 cup kacang hitam kalengan",
      "1/2 cup roti tawar remah",
      "1/4 cup wortel parut",
      "1/4 cup bawang bombay cincang",
      "2 siung bawang putih cincang",
      "1 butir telur",
      "1 sdt jinten",
      "1/2 sdt paprika",
      "garam dan merica",
      "2 buah roti burger",
      "selada tomat bawang",
      "saus burger"
    ],
    "steps": [
      "Haluskan kacang hitam sebagian sisakan tekstur",
      "Campurkan kacang hitam remah roti wortel bawang bombay bawang putih dan telur",
      "Bumbui jinten paprika garam dan merica",
      "Bentuk patty diamkan 15 menit di kulkas",
      "Panggang patty di wajan api sedang 4 menit per sisi",
      "Olesi roti burger saus tata selada tomat bawang dan patty",
      "Tutup roti sajikan"
    ],
    "cookTime": 15,
    "prepTime": 20,
    "servings": 2,
    "difficulty": "Mudah",
    "calories": 380,
    "image": "",
    "tags": ["sandwich", "amerika", "vegetarian", "sehat"]
  },
  {
    "id": "western-287-falafel-wrap",
    "name": "Falafel Wrap",
    "category": "Western",
    "description": "Wrap berisi falafel goreng renyah dengan sayuran segar dan saus tahini. Makanan Timur Tengah yang populer.",
    "ingredients": [
      "400g kacang koro kalengan rendam",
      "1 buah bawang bombay",
      "4 siung bawang putih",
      "1/4 cup peterseli cincang",
      "1 sdt jinten",
      "1 sdt ketumbar",
      "2 sdm tepung",
      "garam",
      "2 lembar tortilla",
      "sayuran: selada tomat timun",
      "saus tahini"
    ],
    "steps": [
      "Haluskan kacang koro bawang bombay bawang putih dan peterseli",
      "Tambahkan jinten ketumbar tepung dan garam aduk rata",
      "Bentuk bola-bola kecil pipihkan sedikit",
      "Goreng dalam minyak panas hingga keemasan renyah",
      "Panaskan tortilla beri sayuran segar",
      "Letakkan 4-5 falafel di atas sayuran",
      "Siram saus tahini gulung rapat sajikan"
    ],
    "cookTime": 15,
    "prepTime": 20,
    "servings": 2,
    "difficulty": "Sedang",
    "calories": 420,
    "image": "",
    "tags": ["sandwich", "timur tengah", "vegetarian", "wrap"]
  },

  // ─── More Desserts / Snacks (western-288 to western-300) ───
  {
    "id": "western-288-chocolate-chip-cookies",
    "name": "Chocolate Chip Cookies",
    "category": "Western",
    "description": "Kue kue cokelat chip klasik yang renyah di luar dan lembut di dalam. Cookie favorit sepanjang masa.",
    "ingredients": [
      "2.5 cup tepung terigu",
      "1/2 cup mentega lunak",
      "1/2 cup gula merah",
      "1/2 cup gula putih",
      "2 butir telur",
      "1 sdt vanilla",
      "1 sdt baking soda",
      "1/2 sdt garam",
      "1.5 cup cokelat chip",
      "1/2 cup walnut cincang"
    ],
    "steps": [
      "Kocok mentega gula merah dan gula putih hingga creamy",
      "Masukkan telur satu per satu dan vanilla",
      "Campurkan tepung baking soda dan garam masukkan ke adonan",
      "Lipatkan cokelat chip dan walnut",
      "Sendokkan adonan ke loyang beri jarak",
      "Panggang 180C selama 12 menit",
      "Dinginkan 5 menit di loyah sebelum dipindahkan"
    ],
    "cookTime": 12,
    "prepTime": 15,
    "servings": 24,
    "difficulty": "Mudah",
    "calories": 180,
    "image": "",
    "tags": ["dessert", "amerika", "cookie", "cokelat"]
  },
  {
    "id": "western-289-vanilla-cupcakes",
    "name": "Vanilla Cupcakes",
    "category": "Western",
    "description": "Cupcake vanilla lembut dengan frosting buttercream yang manis. Camilan pesta yang cantik dan lezat.",
    "ingredients": [
      "1.5 cup tepung terigu",
      "1 cup gula",
      "1.5 sdt baking powder",
      "1/4 sdt garam",
      "1/2 cup mentega lunak",
      "2 butir telur",
      "1/2 cup susu",
      "1 sdt vanilla",
      "frosting: 1 cup mentega",
      "3 cup gula halus",
      "1 sdt vanilla",
      "3 sdm susu",
      "sprinkles warna-warni"
    ],
    "steps": [
      "Kocok mentega dan gula hingga pucat dan creamy",
      "Masukkan telur satu per satu",
      "Campurkan tepung baking powder dan garam masukkan bergantian dengan susu",
      "Tambahkan vanilla aduk rata",
      "Tuang ke cetakan cupcake isi 2/3",
      "Panggang 180C selama 18 menit",
      "Buat frosting kocok mentega gula halus vanilla dan susu",
      "Pipe frosting di atas cupcake taburi sprinkles"
    ],
    "cookTime": 20,
    "prepTime": 20,
    "servings": 12,
    "difficulty": "Sedang",
    "calories": 250,
    "image": "",
    "tags": ["dessert", "amerika", "cupcake", "vanilla"]
  },
  {
    "id": "western-290-snickerdoodle-cookies",
    "name": "Snickerdoodle Cookies",
    "category": "Western",
    "description": "Cookie kayu manis yang lembut dan chewy dengan taburan gula kayu manis. Kue kue klasik Amerika.",
    "ingredients": [
      "2.5 cup tepung terigu",
      "1.5 sdt baking powder",
      "1/4 sdt garam",
      "1/2 cup mentega lunak",
      "1 cup gula",
      "2 butir telur",
      "1 sdt vanilla",
      "taburan: 3 sdm gula",
      "2 sdt kayu manis"
    ],
    "steps": [
      "Campurkan gula dan kayu manis untuk taburan sisihkan",
      "Kocok mentega dan gula hingga creamy",
      "Masukkan telur dan vanilla",
      "Masukkan tepung baking powder dan garam aduk rata",
      "Bentuk bulatan adonan gulingkan ke campuran gula kayu manis",
      "Tata di loyang beri jarak",
      "Panggang 180C selama 10-12 menit hingga pinggir kecokelatan"
    ],
    "cookTime": 12,
    "prepTime": 15,
    "servings": 24,
    "difficulty": "Mudah",
    "calories": 160,
    "image": "",
    "tags": ["dessert", "amerika", "cookie", "kayu manis"]
  },
  {
    "id": "western-291-apple-crumble",
    "name": "Apple Crumble",
    "category": "Western",
    "description": "Irisan apel dengan topping crumble renyah yang manis. Dessert musim gugur yang hangat dan menghibur.",
    "ingredients": [
      "filling: 6 buah apel kupas potong",
      "1/4 cup gula",
      "1 sdt kayu manis",
      "1 sdt jus lemon",
      "crumble: 1 cup tepung",
      "1/2 cup gula merah",
      "1/2 cup mentega dingin",
      "1/2 cup oat",
      "1/2 sdt kayu manis",
      "sejumput garam",
      "es krim vanilla untuk sajian"
    ],
    "steps": [
      "Campurkan apel gula kayu manis dan jus lemon",
      "Masukkan ke loyang yang sudah dioles mentega",
      "Campurkan tepung gula merah oat kayu manis dan garam",
      "Potong mentega dingin ke campuran tepung hingga remah-remah",
      "Taburi crumble topping di atas apel",
      "Panggang 180C selama 40 menit hingga keemasan",
      "Sajikan hangat dengan es krim vanilla"
    ],
    "cookTime": 40,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 320,
    "image": "",
    "tags": ["dessert", "inggris", "apple", "panggang"]
  },
  {
    "id": "western-292-ice-cream-sundae",
    "name": "Ice Cream Sundae",
    "category": "Western",
    "description": "Es krim vanilla dengan saus cokelat whipped cream kacang dan cherry. Dessert klasik yang menyenangkan.",
    "ingredients": [
      "3 scoop es krim vanilla",
      "1/4 cup saus cokelat",
      "whipped cream",
      "2 sdm kacang cincang",
      "cherry merah",
      "2 sdm saus karamel",
      "sprinkles warna-warni",
      "1 buah pisang iris opsional"
    ],
    "steps": [
      "Siapkan mangkuk saji atau gelas tall",
      "Letakkan 3 scoop es krim vanilla",
      "Siram saus cokelat dan saus karamel di atas es krim",
      "Tambahkan whipped cream",
      "Taburi kacang cincang dan sprinkles",
      "Hias dengan cherry merah di puncak",
      "Sajikan segera sebelum es krim meleleh"
    ],
    "cookTime": 0,
    "prepTime": 5,
    "servings": 1,
    "difficulty": "Mudah",
    "calories": 420,
    "image": "",
    "tags": ["dessert", "amerika", "es krim", "cokelat"]
  },
  {
    "id": "western-293-cinnamon-sugar-donuts",
    "name": "Cinnamon Sugar Donuts",
    "category": "Western",
    "description": "Donat goreng lembut digulingkan dalam gula kayu manis. Manis harum dan bikin nagih.",
    "ingredients": [
      "2 cup tepung terigu",
      "1/3 cup gula",
      "2 sdt baking powder",
      "1/2 sdt garam",
      "1/4 cup mentega leleh",
      "1/2 cup susu",
      "1 butir telur",
      "1 sdt vanilla",
      "taburan: 1/2 cup gula",
      "2 sdt kayu manis",
      "minyak goreng"
    ],
    "steps": [
      "Campurkan tepung gula baking powder dan garam",
      "Campurkan mentega leleh susu telur dan vanilla",
      "Tuang bahan cair ke bahan kering aduk rata",
      "Giling adonan setebal 1cm potong dengan cetakan donat",
      "Goreng dalam minyak 180C hingga keemasan kedua sisi",
      "Campurkan gula dan kayu manis untuk taburan",
      "Gulingkan donat hangat ke campuran gula kayu manis"
    ],
    "cookTime": 15,
    "prepTime": 20,
    "servings": 12,
    "difficulty": "Mudah",
    "calories": 220,
    "image": "",
    "tags": ["dessert", "amerika", "donat", "goreng"]
  },
  {
    "id": "western-294-berry-crumble",
    "name": "Mixed Berry Crumble",
    "category": "Western",
    "description": "Campuran buah berry dengan topping crumble renyah. Dessert buah yang segar dan manis.",
    "ingredients": [
      "filling: 2 cup strawberry",
      "1 cup blueberry",
      "1 cup raspberry",
      "3 sdm gula",
      "1 sdm tepung jagung",
      "1 sdt jus lemon",
      "crumble: 1 cup tepung",
      "1/2 cup gula merah",
      "1/2 cup mentega dingin",
      "1/2 cup oat",
      "1/2 sdt kayu manis"
    ],
    "steps": [
      "Campurkan semua buah berry gula tepung jagung dan jus lemon",
      "Masukkan ke loyang",
      "Campurkan tepung gula merah oat dan kayu manis",
      "Potong mentega dingin ke campuran tepung hingga remah-remah",
      "Taburi crumble di atas buah berry",
      "Panggang 180C selama 35 menit hingga keemasan dan buah meletus",
      "Sajikan hangat dengan krim vanilla atau es krim"
    ],
    "cookTime": 35,
    "prepTime": 15,
    "servings": 6,
    "difficulty": "Mudah",
    "calories": 280,
    "image": "",
    "tags": ["dessert", "amerika", "berry", "panggang"]
  },
  {
    "id": "western-295-carrot-cake",
    "name": "Carrot Cake",
    "category": "Western",
    "description": "Kue wortel yang lembap dan lembut dengan frosting cream cheese. Kue yang enak dan berisi sayuran.",
    "ingredients": [
      "2 cup tepung",
      "1 sdt baking soda",
      "1 sdt kayu manis",
      "1/2 sdt garam",
      "1 cup gula",
      "3/4 cup minyak sayur",
      "3 butir telur",
      "2 cup wortel parut",
      "1/2 cup kacang walnut cincang",
      "frosting: 250g cream cheese",
      "100g mentega",
      "2 cup gula halus",
      "1 sdt vanilla"
    ],
    "steps": [
      "Campurkan tepung baking soda kayu manis dan garam",
      "Kocok gula minyak dan telur hingga creamy",
      "Masukkan campuran tepung aduk",
      "Lipatkan wortel parut dan walnut",
      "Tuang ke loyang panggang 180C 35 menit",
      "Buat frosting kocok cream cheese mentega gula halus dan vanilla",
      "Olesi frosting di atas kue yang sudah dingin",
      "Taburi walnut cincang untuk hiasan"
    ],
    "cookTime": 35,
    "prepTime": 20,
    "servings": 12,
    "difficulty": "Sedang",
    "calories": 340,
    "image": "",
    "tags": ["dessert", "amerika", "cake", "wortel"]
  },
  {
    "id": "western-296-sugar-cookies",
    "name": "Sugar Cookies",
    "category": "Western",
    "description": "Cookie gula lembut dan manis yang bisa dihias dengan icing berwarna. Favorit hari raya dan pesta.",
    "ingredients": [
      "2.5 cup tepung terigu",
      "1/2 sdt baking powder",
      "1/4 sdt garam",
      "1 cup mentega lunak",
      "1 cup gula",
      "1 butir telur",
      "1 sdt vanilla",
      "gula halus untuk taburan",
      "icing: 2 cup gula halus",
      "2 sdm susu",
      "food coloring"
    ],
    "steps": [
      "Kocok mentega dan gula hingga pucat dan creamy",
      "Masukkan telur dan vanilla aduk rata",
      "Masukkan tepung baking powder dan garam",
      "Uleni adonan bungkus plastik dinginkan 1 jam",
      "Gilas adonan setebal 5mm potong dengan cookie cutter",
      "Panggang 180C selama 10 menit hingga tepi keemasan",
      "Dinginkan hias dengan icing dan gula hiasan"
    ],
    "cookTime": 12,
    "prepTime": 30,
    "servings": 36,
    "difficulty": "Sedang",
    "calories": 140,
    "image": "",
    "tags": ["dessert", "amerika", "cookie", "manis"]
  },
  {
    "id": "western-297-chocolate-cupcakes",
    "name": "Chocolate Cupcakes",
    "category": "Western",
    "description": "Cupcake cokelat yang lembap dengan frosting cokelat creamy. Penyuka cokelat pasti menyukainya.",
    "ingredients": [
      "1.5 cup tepung terigu",
      "1 cup gula",
      "1/3 cup cocoa",
      "1 sdt baking soda",
      "1/2 sdt garam",
      "1 cup air panas",
      "1/3 cup minyak sayur",
      "1 sdt vanilla",
      "1 sdt cuka putih",
      "frosting: 100g mentega",
      "2 cup gula halus",
      "1/3 cup cocoa",
      "3 sdm susu"
    ],
    "steps": [
      "Campurkan tepung gula cocoa baking soda dan garam",
      "Tambahkan air panas minyak vanila dan cuka aduk rata",
      "Tuang ke cetakan cupcake isi 2/3 penuh",
      "Panggang 180C selama 18 menit",
      "Buat frosting kocok mentega gula halus cocoa dan susu",
      "Dinginkan cupcake pipe frosting di atasnya",
      "Hias dengan cokelat shavings atau sprinkles"
    ],
    "cookTime": 20,
    "prepTime": 20,
    "servings": 12,
    "difficulty": "Mudah",
    "calories": 260,
    "image": "",
    "tags": ["dessert", "amerika", "cupcake", "cokelat"]
  },
  {
    "id": "western-298-caramel-popcorn",
    "name": "Caramel Popcorn",
    "category": "Western",
    "description": "Popcorn dengan saus karamel manis yang renyah. Camilan bioskop yang dibuat sendiri lebih enak.",
    "ingredients": [
      "1/2 cup biji jagung popcorn",
      "2 sdm minyak sayur",
      "1 cup gula",
      "1/4 cup mentega",
      "2 sdm madu",
      "1/2 sdt baking soda",
      "1/2 sdt garam",
      "1 sdt vanilla"
    ],
    "steps": [
      "Pop biji jagung dengan minyak di panci tertutup",
      "Pindahkan popcorn ke mangkuk besar sisihkan",
      "Dalam panci lelehkan gula mentega dan madu api sedang",
      "Masak hingga warna keemasan dan mengental",
      "Angkat dari api tambahkan baking soda garam dan vanilla aduk",
      "Tuang saus karamel ke popcorn aduk cepat",
      "Sebarkan di loyang panggang 120C selama 45 menit agar renyah"
    ],
    "cookTime": 50,
    "prepTime": 5,
    "servings": 8,
    "difficulty": "Mudah",
    "calories": 200,
    "image": "",
    "tags": ["snack", "amerika", "karamel", "popcorn"]
  },
  {
    "id": "western-299-lemon-bars",
    "name": "Lemon Bars",
    "category": "Western",
    "description": "Bar dessert dengan crust renyah dan filling lemon asam manis yang creamy. Segar dan bikin ketagihan.",
    "ingredients": [
      "crust: 1 cup tepung",
      "1/2 cup mentega",
      "1/4 cup gula",
      "sejumput garam",
      "filling: 1 cup gula",
      "3 butir telur",
      "2/3 cup jus lemon",
      "2 sdm tepung terigu",
      "1 sdt kulit lemon parut",
      "gula halus untuk taburan"
    ],
    "steps": [
      "Campurkan tepung mentega gula dan garam untuk crust",
      "Tekan ke dasar loyang panggang 180C selama 15 menit",
      "Kocok telur dan gula masukkan jus lemon tepung dan kulit lemon",
      "Tuang filling ke atas crust",
      "Panggang 180C selama 20 menit hingga set",
      "Dinginkan sepenuhnya",
      "Potong kotak taburi gula halus"
    ],
    "cookTime": 35,
    "prepTime": 15,
    "servings": 16,
    "difficulty": "Mudah",
    "calories": 170,
    "image": "",
    "tags": ["dessert", "amerika", "lemon", "bar"]
  },
  {
    "id": "western-300-peanut-butter-cookies",
    "name": "Peanut Butter Cookies",
    "category": "Western",
    "description": "Kue kacang tanah yang renyah dan kaya rasa kacang. Dengan pola garpu klasik di atasnya.",
    "ingredients": [
      "1 cup kacang tanah creamy",
      "1/2 cup gula merah",
      "1/2 cup gula putih",
      "1/3 cup mentega lunak",
      "1 butir telur",
      "1 sdt vanilla",
      "1 cup tepung terigu",
      "1/2 sdt baking soda",
      "1/4 sdt garam",
      "gula untuk taburan"
    ],
    "steps": [
      "Kocok kacang tanah gula merah gula putih dan mentega hingga creamy",
      "Masukkan telur dan vanilla aduk rata",
      "Masukkan tepung baking soda dan garam aduk hingga rata",
      "Bentuk bola-bola adonan tata di loyang beri jarak",
      "Tekan adonan dengan garpu buat pola silang",
      "Taburi sedikit gula di atasnya",
      "Panggang 180C selama 12 menit hingga pinggir kecokelatan"
    ],
    "cookTime": 12,
    "prepTime": 15,
    "servings": 24,
    "difficulty": "Mudah",
    "calories": 190,
    "image": "",
    "tags": ["dessert", "amerika", "cookie", "kacang"]
  }
];
