import type { Recipe } from '@/types';

export const recipesDessertExtra2: Recipe[] = [
  {
    id: 'kue-lapis-legit-v2',
    name: 'Kue Lapis Legit',
    description: 'Kue lapis legit spesial dengan aroma rempah dan mentega yang kaya. Setiap lapisan dipanggang satu per satu menghasilkan tekstur lembut dan padat.',
    image: '🟤',
    category: 'Dessert',
    difficulty: 'Susah',
    cookTime: 120,
    prepTime: 30,
    servings: 12,
    calories: 320,
    ingredients: [
      { name: 'Kuning telur', amount: 20, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu protein rendah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kayu manis bubuk', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Spekuk', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok mentega, margarine, dan gula halus hingga lembut dan pucat selama 10 menit.',
      'Masukkan kuning telur satu per satu, kocok rata setiap penambahan.',
      'Ayak tepung terigu, campurkan ke adonan secara bertahap sambil diaduk lipat.',
      'Tambahkan susu kental manis, kayu manis, pala, dan spekuk. Aduk rata.',
      'Panaskan oven 170°C. Siapkan loyang lapis legit yang sudah diolesi mentega.',
      'Tuang satu sendok sayur adonan, ratakan. Panggang 5-7 menit hingga matang.',
      'Ulangi proses menuang dan memanggang hingga adonan habis (±20 lapisan).',
      'Panggang lapisan terakhir sedikit lebih lama. Dinginkan sebelum dipotong.',
    ],
    tags: ['lapis legit', 'rempah', 'premium', 'Imlek', 'spesial'],
    rating: 4.9,
  },
  {
    id: 'kue-nastar-keju-v2',
    name: 'Kue Nastar Keju',
    description: 'Variasi nastar premium dengan taburan keju parut di atasnya. Perpaduan selai nanas dan keju yang gurih manis.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 50,
    servings: 20,
    calories: 100,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 280, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 160, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 40, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Nanas matang', amount: 2, unit: 'buah', category: 'Pelengkap' },
      { name: 'Gula pasir (selai)', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Keju cheddar parut', amount: 60, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Parut nanas, masak dengan gula di api kecil hingga kering dan bisa digelindingkan. Dinginkan.',
      'Kocok mentega, margarine, dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Masukkan tepung terigu sedikit demi sedikit, aduk dengan spatula.',
      'Ambil adonan, pipihkan, isi dengan selai nanas, bentuk bulat. Ulangi hingga habis.',
      'Tata di loyang, olesi kuning telur, taburi keju parut.',
      'Panggang oven 150°C selama 20 menit hingga matang keemasan. Dinginkan.',
    ],
    tags: ['nastar', 'keju', 'kue kering', 'premium', 'Lebaran'],
    rating: 4.7,
  },
  {
    id: 'kue-kaastengels-v2',
    name: 'Kue Kaastengels Premium',
    description: 'Kue kaastengels premium dengan keju edam dan cheddar yang lebih banyak. Renyah, gurih, dan meleleh di mulut.',
    image: '🧀',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 25,
    servings: 20,
    calories: 115,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 240, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 140, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju edam parut', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju cheddar parut', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu evaporasi', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Kocok mentega hingga lembut. Masukkan kuning telur dan susu evaporasi, kocok rata.',
      'Campurkan tepung terigu dan maizena, ayak. Masukkan ke adonan.',
      'Tambahkan setengah keju parut, aduk rata hingga adonan bisa dibentuk.',
      'Giling adonan setebal 0.5 cm, potong batangan 4x1.5 cm.',
      'Tata di loyang, olesi kuning telur, taburi sisa keju.',
      'Panggang 160°C selama 20-25 menit hingga keemasan. Dinginkan.',
    ],
    tags: ['kaastengels', 'keju', 'premium', 'kue kering', 'renyah'],
    rating: 4.7,
  },
  {
    id: 'kue-putri-salju-coklat-v2',
    name: 'Kue Putri Salju Coklat',
    description: 'Kue putri salju dengan tambahan coklat bubuk dalam adonannya. Perpaduan manis, gurih, dan coklat yang lembut.',
    image: '🍪',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 30,
    servings: 25,
    calories: 95,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 230, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 20, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung maizena', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 55, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula halus (taburan)', amount: 100, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Sangrai tepung terigu 10 menit. Dinginkan.',
      'Kocok mentega dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Campurkan tepung terigu sangrai, maizena, dan coklat bubuk. Masukkan ke adonan.',
      'Aduk rata dengan spatula hingga adonan bisa dibentuk.',
      'Bentuk bulat atau gunakan cetakan, tata di loyang.',
      'Panggang 150°C selama 15-20 menit. Jangan terlalu kuning.',
      'Angkat, gulingkan di gula halus saat hangat. Taburi lagi setelah dingin.',
    ],
    tags: ['putri salju', 'coklat', 'kue kering', 'Natal', 'gurih'],
    rating: 4.6,
  },
  {
    id: 'kue-sagu-pandan-v2',
    name: 'Kue Sagu Pandan Keju',
    description: 'Kue sagu keju dengan aroma pandan yang harum. Teksturnya renyah, meleleh, dan lumer di mulut.',
    image: '🟢',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 20,
    servings: 20,
    calories: 100,
    ingredients: [
      { name: 'Tepung sagu', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju parut', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok mentega dan gula halus hingga lembut. Masukkan telur, kocok rata.',
      'Masukkan santan kental dan pasta pandan, aduk rata.',
      'Masukkan tepung sagu dan garam sedikit demi sedikit, aduk rata.',
      'Tambahkan setengah keju parut, aduk rata.',
      'Cetak adonan menggunakan cetakan atau bentuk bulat pipih.',
      'Tata di loyang, taburi sisa keju parut.',
      'Panggang 160°C selama 20-25 menit hingga matang. Dinginkan.',
    ],
    tags: ['sagu', 'pandan', 'keju', 'kue kering', 'renyah'],
    rating: 4.5,
  },
  {
    id: 'kue-lidah-kucing-matcha-v2',
    name: 'Kue Lidah Kucing Matcha',
    description: 'Kue lidah kucing tipis dengan aroma matcha Jepang yang khas. Warna hijau cantik dan rasa yang unik.',
    image: '🍵',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 20,
    calories: 80,
    ingredients: [
      { name: 'Putih telur', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 55, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 45, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 15, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 75, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bubuk matcha', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok putih telur dan gula halus hingga kental dan mengembang.',
      'Ayak tepung terigu, maizena, dan bubuk matcha. Masukkan ke adonan sambil diaduk lipat.',
      'Masukkan mentega cair sedikit demi sedikit, aduk rata.',
      'Masukkan adonan ke piping bag dengan spuit bulat kecil.',
      'Cetak adonan di loyang berlapis baking sheet memanjang 5 cm.',
      'Panggang 160°C selama 12-15 menit hingga pinggiran kecoklatan.',
      'Angkat, dinginkan. Simpan di wadah kedap udara.',
    ],
    tags: ['lidah kucing', 'matcha', 'Jepang', 'tipis', 'renyah'],
    rating: 4.4,
  },
  {
    id: 'kue-semprit-nanas-v2',
    name: 'Kue Semprit Selai Nanas',
    description: 'Kue semprit renyah dengan topping selai nanas di tengahnya. Bentuk bunga cantik dengan isian manis asam.',
    image: '🌸',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 30,
    servings: 25,
    calories: 85,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 55, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Selai nanas', amount: 100, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Kocok mentega dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Tambahkan susu kental manis, aduk rata.',
      'Ayak tepung terigu dan maizena. Masukkan ke adonan, aduk dengan spatula.',
      'Masukkan adonan ke piping bag dengan spuit bintang besar.',
      'Cetak bentuk spiral di loyang berlapis kertas baking.',
      'Berikan setetes selai nanas di tengah setiap kue.',
      'Panggang 150°C selama 15-20 menit hingga matang. Dinginkan.',
    ],
    tags: ['semprit', 'nanas', 'kue kering', 'bunga', 'Lebaran'],
    rating: 4.5,
  },
  {
    id: 'kue-lapis-surabaya',
    name: 'Kue Lapis Surabaya',
    description: 'Kue lapis Surabaya dengan tiga warna lapisan kuning, coklat, dan kuning. Tekstur lembut dan empuk dengan aroma mentega yang kaya.',
    image: '🍰',
    category: 'Dessert',
    difficulty: 'Susah',
    cookTime: 60,
    prepTime: 25,
    servings: 10,
    calories: 350,
    ingredients: [
      { name: 'Kuning telur', amount: 15, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Putih telur', amount: 8, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 180, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 180, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 20, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Emulsifier (SP)', amount: 1.5, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok kuning telur, setengah gula, dan emulsifier hingga kental dan pucat.',
      'Kocok putih telur dengan sisa gula hingga kaku (meringue).',
      'Masukkan meringue ke adonan kuning telur, aduk lipat.',
      'Masukkan tepung terigu perlahan, aduk lipat. Bagi 3 bagian.',
      'Campurkan satu bagian adonan dengan coklat bubuk.',
      'Tuang adonan kuning ke loyang, panggang 170°C selama 8-10 menit.',
      'Tuang adonan coklat, panggang lagi. Tuang adonan kuning terakhir, panggang.',
      'Dinginkan, potong-potong dan sajikan.',
    ],
    tags: ['lapis Surabaya', 'coklat', 'kuning telur', 'premium', 'tebal'],
    rating: 4.7,
  },
  {
    id: 'kue-sarang-semut-v2',
    name: 'Kue Sarang Semut',
    description: 'Kue sarang semut dengan lubang-lubang khas seperti sarang semut berkat campuran soda kue. Manis legit dan bertekstur lembut kenyal.',
    image: '🟤',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 50,
    prepTime: 20,
    servings: 10,
    calories: 280,
    ingredients: [
      { name: 'Telur ayam', amount: 4, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 200, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Margarine (leleh)', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus gula merah dengan santan hingga gula larut. Dinginkan.',
      'Kocok telur dan vanili hingga mengembang. Masukkan larutan gula merah dingin.',
      'Ayak tepung terigu dan soda kue. Masukkan ke adonan, aduk rata.',
      'Masukkan margarine leleh, aduk lipat hingga rata.',
      'Tuang adonan ke loyang yang sudah diolesi mentega dan dialasi kertas.',
      'Panggang oven 170°C selama 45-50 menit hingga matang.',
      'Tes kematangan dengan tusuk lidi. Angkat, dinginkan, potong dan sajikan.',
    ],
    tags: ['sarang semut', 'gula merah', 'santan', 'legit', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'kue-bolu-coklat-v2',
    name: 'Kue Bolu Coklat',
    description: 'Bolu coklat lembut dan moist dengan aroma coklat yang kaya. Cocok untuk acara ulang tahun dan camilan keluarga.',
    image: '🍫',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 8,
    calories: 290,
    ingredients: [
      { name: 'Telur ayam', amount: 5, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 130, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 130, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur, gula, dan vanili dengan kecepatan tinggi hingga kental dan pucat.',
      'Ayak tepung terigu dan coklat bubuk. Masukkan ke adonan secara bertahap sambil diaduk lipat.',
      'Tambahkan susu cair, aduk rata.',
      'Masukkan mentega leleh perlahan, aduk lipat hingga rata.',
      'Tuang adonan ke loyang yang sudah diolesi mentega dan dialasi kertas.',
      'Panggang oven 170°C selama 35-40 menit hingga matang.',
      'Tes kematangan dengan tusuk lidi. Angkat, dinginkan, potong dan sajikan.',
    ],
    tags: ['bolu', 'coklat', 'lembut', 'moist', 'ultah'],
    rating: 4.6,
  },
  {
    id: 'kue-bolu-marmer-v2',
    name: 'Kue Bolu Marmer',
    description: 'Bolu lembut dengan motif marmer cantik dari campuran adonan vanilla dan coklat. Klasik dan tidak pernah ketinggalan zaman.',
    image: '🍰',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 25,
    servings: 8,
    calories: 270,
    ingredients: [
      { name: 'Telur ayam', amount: 5, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 130, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 140, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 60, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Emulsifier (SP)', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Kocok telur, gula, vanili, dan emulsifier hingga kental dan pucat.',
      'Ayak tepung terigu, masukkan ke adonan secara bertahap sambil diaduk lipat.',
      'Tambahkan susu cair, aduk rata.',
      'Ambil 1/3 adonan, campurkan dengan coklat bubuk.',
      'Tuang adonan putih ke loyang, lalu tuang adonan coklat secara acak.',
      'Buat motif marmer menggunakan tusuk sate atau pisau.',
      'Panggang oven 170°C selama 35-40 menit hingga matang.',
      'Angkat, dinginkan, potong dan sajikan.',
    ],
    tags: ['bolu', 'marmer', 'coklat', 'klasik', 'lembut'],
    rating: 4.5,
  },
  {
    id: 'kue-pandan-santan-v2',
    name: 'Kue Pandan Santan',
    description: 'Kue bolu pandan berlapis santan yang harum dan lembut. Perpaduan aroma pandan dan gurihnya santan.',
    image: '🍃',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 8,
    calories: 250,
    ingredients: [
      { name: 'Telur ayam', amount: 5, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 140, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 120, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1.5, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur, gula, dan vanili hingga kental dan pucat.',
      'Masukkan tepung terigu secara bertahap, aduk lipat.',
      'Tambahkan santan kental dan pasta pandan, aduk rata.',
      'Masukkan mentega leleh perlahan, aduk lipat hingga rata.',
      'Tuang adonan ke loyang yang sudah diolesi mentega.',
      'Panggang oven 170°C selama 35-40 menit.',
      'Tes kematangan dengan tusuk lidi. Angkat, dinginkan.',
      'Potong-potong dan sajikan.',
    ],
    tags: ['pandan', 'santan', 'harum', 'lembut', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'kue-carabikang-v2',
    name: 'Kue Carabikang',
    description: 'Kue tradisional berbentuk bunga yang mekar dengan aroma pandan. Bertekstur kenyal dan manis cocok untuk teman ngopi.',
    image: '🌺',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan ragi instan dengan sedikit santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga kental.',
      'Masukkan campuran ragi, tepung terigu, tapioka, dan garam. Aduk rata.',
      'Tambahkan sisa santan dan pasta pandan, aduk rata.',
      'Diamkan adonan selama 1 jam hingga mengembang.',
      'Panaskan cetakan carabikang, olesi mentega. Tuang adonan hingga penuh.',
      'Tutup cetakan, masak api kecil hingga permukaan kering dan berlubang. Angkat.',
    ],
    tags: ['carabikang', 'pandan', 'tradisional', 'kenyal', 'jajan pasar'],
    rating: 4.3,
  },
  {
    id: 'kue-jongkong-v2',
    name: 'Kue Jongkong Betawi',
    description: 'Kue tradisional khas Betawi dari tepung beras dan santan dengan taburan kelapa parut. Kenyal dan gurih.',
    image: '🟩',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 15,
    servings: 8,
    calories: 170,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kelapa parut segar', amount: 100, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras, tapioka, dan garam. Tuang santan sedikit demi sedikit, aduk rata.',
      'Masukkan daun pandan, aduk rata.',
      'Bagi adonan menjadi dua: satu dicampur gula merah cair (untuk lapisan merah).',
      'Tuang adonan putih ke cetakan yang sudah diolesi minyak, kukus 10 menit.',
      'Tuang adonan merah di atasnya, kukus lagi 15 menit hingga matang.',
      'Angkat, dinginkan. Potong dadu, taburi kelapa parut. Sajikan.',
    ],
    tags: ['jongkong', 'Betawi', 'tepung beras', 'kenyal', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'kue-pukis-coklat-v2',
    name: 'Kue Pukis Coklat',
    description: 'Kue pukis dengan tambahan coklat bubuk yang membuatnya lembut dan harum coklat. Camilan tradisional favorit anak-anak.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 8,
    calories: 155,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
    ],
    steps: [
      'Larutkan ragi dengan sedikit santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga kental. Masukkan campuran ragi, aduk rata.',
      'Masukkan tepung terigu dan coklat bubuk, aduk rata.',
      'Tambahkan sisa santan dan mentega leleh, aduk rata. Diamkan 30 menit.',
      'Panaskan cetakan pukis, olesi mentega.',
      'Tuang adonan hingga 3/4 cetakan. Tutup, masak api kecil.',
      'Masak hingga matang dan permukaan kering. Angkat, sajikan.',
    ],
    tags: ['pukis', 'coklat', 'tradisional', 'lembut', 'anak-anak'],
    rating: 4.5,
  },
  {
    id: 'kue-cubit-green-tea',
    name: 'Kue Cubit Green Tea',
    description: 'Kue cubit mini dengan rasa green tea yang unik dan warna hijau cantik. Camilan kekinian bertekstur lembut yang disukai semua umur.',
    image: '🍵',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 10,
    calories: 130,
    ingredients: [
      { name: 'Tepung terigu', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Susu cair', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 40, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bubuk green tea', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Baking powder', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur dan gula hingga mengembang dan pucat.',
      'Masukkan susu cair dan bubuk green tea, aduk rata.',
      'Ayak tepung terigu dan baking powder, masukkan ke adonan, aduk rata.',
      'Tambahkan mentega leleh dan garam, aduk lipat.',
      'Panaskan cetakan kue cubit, olesi mentega tipis.',
      'Tuang adonan ke cetakan, masak hingga permukaan berlubang.',
      'Angkat, sajikan dengan taburan keju atau meses.',
    ],
    tags: ['kue cubit', 'green tea', 'mini', 'kekinian', 'anak-anak'],
    rating: 4.4,
  },
  {
    id: 'kue-dodol-garut',
    name: 'Kue Dodol Garut',
    description: 'Dodol Garut khas Jawa Barat yang legit dan kenyal dengan aroma gula merah. Dibuat dari tepung beras ketan dan santan yang dimasak lama.',
    image: '🟤',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 90,
    prepTime: 15,
    servings: 20,
    calories: 140,
    ingredients: [
      { name: 'Tepung beras ketan', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 200, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Rebus gula merah dengan 100ml air hingga larut. Saring, dinginkan.',
      'Campurkan tepung beras ketan dengan santan kental, aduk rata hingga tidak bergerindil.',
      'Masukkan larutan gula merah, gula pasir, garam, dan daun pandan.',
      'Masak adonan di atas api kecil sambil terus diaduk agar tidak gosong.',
      'Aduk terus selama 60-90 menit hingga adonan mengental dan berwarna coklat gelap.',
      'Tuang adonan ke loyang yang sudah diolesi minyak.',
      'Dinginkan, potong dan bungkus dengan plastik atau daun pisang.',
    ],
    tags: ['dodol', 'Garut', 'gula merah', 'legit', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'kue-wajik',
    name: 'Kue Wajik Gula Merah',
    description: 'Kue wajik berbentuk berlian dari ketan dan gula merah yang legit manis. Camilan tradisional yang sering disajikan saat acara adat.',
    image: '💎',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 15,
    servings: 15,
    calories: 160,
    ingredients: [
      { name: 'Beras ketan', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 250, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam beras ketan minimal 2 jam. Kukus ketan hingga matang, sisihkan.',
      'Rebus gula merah dengan santan kental dan daun pandan hingga gula larut.',
      'Masak larutan gula merah di api kecil hingga menjadi karamel kental dan mengental.',
      'Masukkan ketan kukus ke dalam karamel gula merah, aduk rata.',
      'Aduk terus dengan api kecil hingga semua ketan terbalut dan karamel mengering.',
      'Tuang ke loyang yang sudah diolesi minyak, tekan-tekan rata.',
      'Dinginkan dan potong berbentuk berlian atau sesuai selera.',
    ],
    tags: ['wajik', 'gula merah', 'ketan', 'tradisional', 'legit'],
    rating: 4.3,
  },
  {
    id: 'kue-mochi',
    name: 'Kue Mochi Isi Kacang',
    description: 'Kue mochi lembut kenyal dari tepung ketan dengan isian kacang tanah yang manis. Camilan Jepang-Indonesia yang populer.',
    image: '🍡',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 25,
    servings: 15,
    calories: 130,
    ingredients: [
      { name: 'Tepung ketan', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang tanah sangrai', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tepung sagu (untuk taburan)', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Pewarna makanan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan kacang tanah sangrai, campurkan dengan 50g gula pasir. Sisihkan sebagai isian.',
      'Campurkan tepung ketan, sisa gula pasir, garam, dan pewarna makanan.',
      'Tuang santan kental sedikit demi sedikit sambil diaduk rata.',
      'Kukus adonan selama 15 menit hingga matang dan mengkilap.',
      'Ambil sedikit adonan, pipihkan, isi dengan kacang tanah. Bentuk bulat.',
      'Gulingkan mochi di tepung sagu agar tidak lengket.',
      'Sajikan dalam cup kertas kecil.',
    ],
    tags: ['mochi', 'ketan', 'kacang', 'kenyal', 'Jepang'],
    rating: 4.5,
  },
  {
    id: 'es-krim-vanilla',
    name: 'Es Krim Vanilla Homemade',
    description: 'Es krim vanilla homemade yang lembut dan creamy tanpa menggunakan mesin. Rasa vanilla yang murni dan manis alami.',
    image: '🍦',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 10,
    prepTime: 30,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'Susu cair full cream', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Whipping cream', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kuning telur', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Vanili', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Maizena', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Kocok kuning telur dan gula hingga pucat dan mengembang.',
      'Panaskan susu cair hingga hangat (jangan mendidih). Tuang ke adonan telur, aduk rata.',
      'Masukkan maizena dan vanili, aduk rata. Masak di api kecil hingga mengental.',
      'Dinginkan adonan custard di kulkas selama 2 jam.',
      'Kocok whipping cream hingga kaku, campurkan ke custard dingin.',
      'Tuang ke wadah, simpan freezer minimal 4 jam.',
      'Sajikan dengan topping sesuai selera.',
    ],
    tags: ['es krim', 'vanilla', 'homemade', 'creamy', 'dingin'],
    rating: 4.5,
  },
  {
    id: 'es-krim-coklat',
    name: 'Es Krim Coklat',
    description: 'Es krim coklat yang rich dan creamy dengan potongan coklat. Dibuat homemade dengan bahan sederhana tapi hasilnya luar biasa.',
    image: '🍫',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 10,
    prepTime: 30,
    servings: 6,
    calories: 260,
    ingredients: [
      { name: 'Susu cair full cream', amount: 350, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Whipping cream', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Dark chocolate (potong)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kuning telur', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Lelehkan dark chocolate dengan metode double boiler, sisihkan.',
      'Kocok kuning telur dan gula hingga pucat dan mengembang.',
      'Panaskan susu dengan coklat bubuk hingga hangat. Tuang ke adonan telur.',
      'Masukkan coklat leleh dan vanili, aduk rata. Dinginkan di kulkas.',
      'Kocok whipping cream hingga kaku, campurkan ke adonan coklat.',
      'Tuang ke wadah, simpan freezer minimal 4-6 jam.',
      'Sajikan dengan taburan coklat chip atau wafer.',
    ],
    tags: ['es krim', 'coklat', 'homemade', 'rich', 'dingin'],
    rating: 4.6,
  },
  {
    id: 'puding-strawberry',
    name: 'Puding Strawberry Vla',
    description: 'Puding strawberry lembut dengan vla vanilla yang creamy. Warna pink cantik dengan rasa buah strawberry yang segar.',
    image: '🍮',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'Susu cair', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Selai strawberry', amount: 4, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Susu cair (vla)', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kuning telur (vla)', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Maizena (vla)', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan susu, gula, agar-agar, dan selai strawberry. Masak hingga mendidih.',
      'Tuang adonan puding ke cetakan, dinginkan hingga mengeras.',
      'Buat vla: kocok kuning telur dan gula. Panaskan susu, tuang ke telur.',
      'Masukkan maizena dan vanili, masak hingga mengental. Dinginkan.',
      'Tuang vla di atas puding strawberry yang sudah dingin.',
      'Dinginkan di kulkas minimal 2 jam sebelum disajikan.',
    ],
    tags: ['puding', 'strawberry', 'vla', 'lembut', 'segan'],
    rating: 4.5,
  },
  {
    id: 'puding-oreo',
    name: 'Puding Oreo',
    description: 'Puding susu lembut dengan potongan Oreo dan taburan crumbs. Perpaduan manis susu dengan coklat Oreo yang renyah.',
    image: '🍪',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'Susu cair', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Oreo (biskuit)', amount: 10, unit: 'keping', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Whipping cream', amount: 100, unit: 'ml', category: 'Pelengkap' },
    ],
    steps: [
      'Hancurkan 5 keping Oreo menjadi potongan kasar, 5 keping menjadi crumbs halus.',
      'Campurkan susu, gula, agar-agar, dan coklat bubuk. Masak hingga mendidih.',
      'Masukkan potongan Oreo kasar ke adonan puding, aduk rata.',
      'Tuang ke cetakan, taburi Oreo crumbs di atasnya.',
      'Dinginkan hingga mengeras.',
      'Sajikan dengan whipped cream di atasnya.',
    ],
    tags: ['puding', 'Oreo', 'coklat', 'susu', 'kekinian'],
    rating: 4.6,
  },
  {
    id: 'puding-kelapa-muda',
    name: 'Puding Kelapa Muda',
    description: 'Puding segar dengan daging kelapa muda dan air kelapa muda. Rasa manis alami yang menyegarkan di cuaca panas.',
    image: '🥥',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 6,
    calories: 150,
    ingredients: [
      { name: 'Air kelapa muda', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daging kelapa muda', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu', amount: 200, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Serut daging kelapa muda, sisihkan sebagian untuk taburan.',
      'Campurkan air kelapa muda, gula, agar-agar, susu kental manis, dan garam.',
      'Masak hingga mendidih dan agar-agar larut.',
      'Masukkan sebagian daging kelapa muda ke adonan.',
      'Tuang ke cetakan, dinginkan hingga mengeras.',
      'Sajikan dengan taburan kelapa muda segar dan es batu.',
    ],
    tags: ['puding', 'kelapa muda', 'segar', 'dingin', 'alami'],
    rating: 4.5,
  },
  {
    id: 'puding-tape',
    name: 'Puding Tape Singkong',
    description: 'Puding tape singkong dengan aroma tape yang khas dan rasa manis. Tekstur lembut puding berpadu kenyalnya tape singkong.',
    image: '🍮',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 6,
    calories: 190,
    ingredients: [
      { name: 'Tape singkong', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan tape singkong menggunakan garpu atau blender.',
      'Campurkan susu cair, gula, agar-agar, garam, dan pasta pandan.',
      'Masak hingga mendidih dan agar-agar larut.',
      'Masukkan tape singkong yang sudah dihaluskan, aduk rata.',
      'Tuang ke cetakan, dinginkan hingga mengeras.',
      'Simpan di kulkas, sajikan dingin.',
    ],
    tags: ['puding', 'tape singkong', 'pandan', 'tradisional', 'manis'],
    rating: 4.4,
  },
  {
    id: 'kue-cantik-manis',
    name: 'Kue Cantik Manis',
    description: 'Kue cantik manis berlapis warna-warni dengan tekstur kenyal dan lembut. Jajan pasar tradisional yang cantik dipandang.',
    image: '🌈',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 15,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 350, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Pewarna makanan', amount: 3, unit: 'warna', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung beras, tapioka, gula, dan garam. Tuang santan, aduk rata.',
      'Bagi adonan menjadi 3-4 bagian, beri pewarna makanan berbeda pada setiap bagian.',
      'Panaskan panci kukus. Siapkan cetakan yang sudah diolesi minyak.',
      'Tuang satu warna adonan ke cetakan, kukus 5 menit.',
      'Tuang warna berikutnya, kukus lagi 5 menit. Ulangi hingga semua lapisan selesai.',
      'Kukus lapisan terakhir 10 menit. Angkat, dinginkan.',
      'Potong-potong dan sajikan.',
    ],
    tags: ['cantik manis', 'warna-warni', 'kukus', 'kenyal', 'jajan pasar'],
    rating: 4.3,
  },
  {
    id: 'kue-kacang-hijau',
    name: 'Kue Kacang Hijau Pandan',
    description: 'Kue kacang hijau dengan aroma pandan yang harum dan tekstur lembut. Isian kacang hijau yang manis legit.',
    image: '🟢',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 10,
    calories: 180,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang hijau (kupas)', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Mentega (leleh)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Rebus kacang hijau hingga empuk, tiriskan. Haluskan dengan 50g gula pasir.',
      'Kocok telur dan sisa gula hingga mengembang.',
      'Masukkan santan kental, pasta pandan, dan garam. Aduk rata.',
      'Masukkan tepung terigu, aduk rata.',
      'Tambahkan mentega leleh, aduk lipat.',
      'Tuang setengah adonan ke loyang, beri isian kacang hijau halus.',
      'Tuang sisa adonan, panggang 170°C selama 25 menit hingga matang.',
    ],
    tags: ['kacang hijau', 'pandan', 'lembut', 'tradisional', 'manis'],
    rating: 4.4,
  },
  {
    id: 'kue-apem-jawa-v2',
    name: 'Kue Apem Jawa Gula Merah',
    description: 'Kue apem tradisional Jawa dengan tapai singkong dan santan. Rasanya manis dengan sedikit aroma tape yang khas.',
    image: '🟤',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 8,
    calories: 175,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tapai singkong', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan tapai singkong menggunakan garpu atau blender.',
      'Larutkan ragi instan dengan sedikit santan hangat. Diamkan 10 menit.',
      'Campurkan tepung beras, tapai, gula merah, gula pasir, garam, dan larutan ragi.',
      'Tuang santan sedikit demi sedikit, aduk rata. Tambahkan daun pandan.',
      'Diamkan adonan 2-3 jam hingga mengembang dan berbusa.',
      'Tuang adonan ke cetakan apem yang sudah diolesi minyak.',
      'Kukus 15-20 menit hingga matang. Angkat, dinginkan.',
    ],
    tags: ['apem', 'Jawa', 'tapai', 'santan', 'gula merah'],
    rating: 4.3,
  },
];
