import type { Recipe } from '@/types';

export const recipesDessert: Recipe[] = [
  {
    id: 'es-krim-kelapa-v2',
    name: 'Es Krim Kelapa',
    description:
      'Es krim homemade rasa kelapa yang creamy dan wangi. Menggunakan santan asli untuk cita rasa tropis yang otentik.',
    image: '🍧',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 10,
    prepTime: 30,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Kelapa parut segar', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Maizena', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan santan, susu cair, gula pasir, dan maizena di dalam panci.',
      'Masak dengan api kecil sambil terus diaduk hingga mengental.',
      'Angkat, masukkan kelapa parut dan vanili. Aduk rata.',
      'Dinginkan adonan, lalu masukkan ke dalam freezer selama 4 jam.',
      'Keluarkan, kocok dengan mixer untuk memecahkan kristal es. Kembalikan ke freezer.',
      'Ulangi sekali lagi, lalu biarkan hingga beku sempurna. Sajikan.',
    ],
    tags: ['es krim', 'kelapa', 'santan', 'dingin', 'tropis'],
    rating: 4.5,
  },
  {
    id: 'puding-mangga',
    name: 'Puding Mangga',
    description:
      'Puding susu lembut dengan saus mangga segar. Teksturnya halus dan kenyal, rasa manis asam mangga yang menyegarkan.',
    image: '🥭',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Mangga matang', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Garam', amount: 1, unit: 'pinch', category: 'Bumbu' },
    ],
    steps: [
      'Kupas mangga, blender 1 buah untuk saus dan potong dadu 1 buah untuk isian.',
      'Campurkan agar-agar, susu cair, gula, dan garam dalam panci. Masak hingga mendidih.',
      'Angkat, biarkan uap panas hilang. Tambahkan susu kental manis, aduk rata.',
      'Tuang setengah adonan ke cetakan, tambahkan potongan mangga. Tuang sisa adonan.',
      'Dinginkan hingga set. Simpan di kulkas.',
      'Sajikan dengan saus mangga blender di atasnya.',
    ],
    tags: ['puding', 'mangga', 'susu', 'dingin', 'segar'],
    rating: 4.6,
  },
  {
    id: 'puding-coklat',
    name: 'Puding Coklat',
    description:
      'Puding coklat lembut dan creamy yang meleleh di lidah. Dessert favorit anak-anak dan keluarga.',
    image: '🍫',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 3, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Coklat masak (dark chocolate)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Campurkan agar-agar, susu cair, coklat bubuk, dan gula dalam panci. Aduk rata.',
      'Masak dengan api kecil sambil diaduk hingga mendidih dan coklat larut sempurna.',
      'Masukkan potongan coklat masak, aduk hingga meleleh.',
      'Angkat, tambahkan susu kental manis, aduk rata.',
      'Tuang ke dalam cetakan puding. Biarkan dingin, lalu simpan di kulkas.',
      'Sajikan dingin dengan topping sesuai selera.',
    ],
    tags: ['puding', 'coklat', 'dingin', 'manis', 'lembut'],
    rating: 4.7,
  },
  {
    id: 'puding-vla',
    name: 'Puding Vla',
    description:
      'Puding susu lembut kenyal disajikan dengan saus vla vanilla yang creamy. Kombinasi tekstur dan rasa yang sempurna.',
    image: '🍮',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 195,
    ingredients: [
      { name: 'Agar-agar bubuk', amount: 1, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Mentega', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Untuk puding: campurkan agar-agar, susu cair, dan gula. Masak hingga mendidih.',
      'Tuang ke cetakan, biarkan dingin dan set. Simpan di kulkas.',
      'Untuk vla: kocok telur dengan gula. Tambahkan maizena dan susu kental manis, aduk rata.',
      'Panaskan susu cair, tuang perlahan ke adonan telur sambil diaduk cepat.',
      'Masak adonan vla di atas api kecil sambil diaduk hingga mengental.',
      'Angkat, tambahkan vanili dan mentega. Aduk hingga mentega meleleh.',
      'Dinginkan vla. Siram di atas puding yang sudah dingin. Sajikan.',
    ],
    tags: ['puding', 'vla', 'vanilla', 'creamy', 'dingin'],
    rating: 4.7,
  },
  {
    id: 'kue-lapis-legit',
    name: 'Kue Lapis Legit',
    description:
      'Kue lapis legit khas peranakan dengan lapisan-lapisan berwarna kuning keemasan. Aroma rempah dan mentega yang menggoda.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Susah',
    cookTime: 90,
    prepTime: 30,
    servings: 8,
    calories: 350,
    ingredients: [
      { name: 'Telur ayam', amount: 15, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Bumbu spekuk (kayu manis, cengkeh, pala)', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Rhum (opsional)', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur dan gula dengan mixer kecepatan tinggi selama 10 menit hingga kental dan pucat.',
      'Lelehkan mentega dan margarine, biarkan dingin.',
      'Masukkan campuran mentega secara perlahan ke adonan telur sambil diaduk lipat.',
      'Ayak tepung terigu, masukkan bergantian dengan susu kental manis ke adonan.',
      'Tambahkan bumbu spekuk dan rhum. Aduk rata.',
      'Panaskan oven 180°C. Tuang satu sendok sayur adonan ke loyang, panggang 5 menit.',
      'Lakukan layering (tuang, panggang, ulang) hingga adonan habis. Panggang lapisan terakhir lebih lama.',
      'Angkat, biarkan dingin. Potong-potong dan sajikan.',
    ],
    tags: ['lapis legit', 'rempah', 'peranakan', 'premium', 'Imlek'],
    rating: 4.8,
  },
  {
    id: 'kue-nastar',
    name: 'Kue Nastar',
    description:
      'Kue kering berbentuk bulan sabit berisi selai nanas yang manis asam. Kue wajib saat Lebaran dan hari raya.',
    image: '🍪',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 45,
    servings: 20,
    calories: 90,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur (adonan)', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Nanas matang', amount: 2, unit: 'buah', category: 'Isian' },
      { name: 'Gula pasir (untuk selai)', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Kuning telur (olesan)', amount: 2, unit: 'butir', category: 'Pelengkap' },
      { name: 'Susu evaporasi (olesan)', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Parut nanas, masak dengan gula pasir di api kecil hingga kering dan bisa digelindingkan (±30 menit). Dinginkan.',
      'Kocok mentega, margarine, dan gula halus hingga lembut.',
      'Masukkan kuning telur, kocok rata.',
      'Masukkan tepung terigu sedikit demi sedikit, aduk dengan spatula hingga adonan bisa dibentuk.',
      'Ambil sedikit adonan, pipihkan. Isi dengan selai nanas, bulatkan membentuk bulan sabit.',
      'Tata di loyang yang sudah diolesi mentega. Olesi permukaan dengan kuning telur dan susu.',
      'Panggang dalam oven 150°C selama 20 menit hingga kuning keemasan.',
      'Angkat, dinginkan. Simpan di wadah kedap udara.',
    ],
    tags: ['nastar', 'nanas', 'kue kering', 'Lebaran', 'populer'],
    rating: 4.8,
  },
  {
    id: 'kue-putri-salju',
    name: 'Kue Putri Salju',
    description:
      'Kue kering lembut bertabur gula halus putih seperti salju. Rasanya manis, gurih, dan lumer di mulut.',
    image: '❄️',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 30,
    servings: 25,
    calories: 85,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung maizena', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula halus (taburan)', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Kacang mede sangrai (opsional)', amount: 50, unit: 'gram', category: 'Isian' },
    ],
    steps: [
      'Sangrai tepung terigu selama 10 menit di atas api kecil, aduk rata. Dinginkan.',
      'Kocok mentega dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Campurkan tepung terigu sangrai dan maizena. Masukkan ke adonan, aduk rata dengan spatula.',
      'Jika menggunakan kacang mede, masukkan dan aduk rata.',
      'Ambil adonan, bentuk bulat atau gunakan cetakan kue. Tata di loyang.',
      'Panggang oven 150°C selama 15-20 menit. Jangan sampai kuning, tetap putih pucat.',
      'Angkat, biarkan hangat. Segera gulingkan di gula halus. Taburi lagi setelah dingin.',
    ],
    tags: ['putri salju', 'kue kering', 'Natal', 'Lebaran', 'gurih'],
    rating: 4.6,
  },
  {
    id: 'kue-semprit',
    name: 'Kue Semprit',
    description:
      'Kue kering renyah bertekstur cantik yang dicetak menggunakan spuit. Rasa mentega yang gurih dan renyah.',
    image: '🍪',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 20,
    servings: 25,
    calories: 80,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat chip (opsional)', amount: 30, unit: 'gram', category: 'Isian' },
    ],
    steps: [
      'Kocok mentega dan gula halus hingga lembut dan pucat.',
      'Masukkan kuning telur, kocok rata.',
      'Tambahkan susu kental manis, aduk rata.',
      'Campurkan tepung terigu dan maizena, ayak. Masukkan ke adonan, aduk rata dengan spatula.',
      'Masukkan adonan ke piping bag dengan spuit bintang.',
      'Cetak di loyang yang sudah dialasi kertas baking dengan bentuk spiral.',
      'Panggang oven 150°C selama 15-20 menit hingga matang dan sedikit kekuningan.',
      'Angkat, dinginkan. Beri topping coklat chip jika suka.',
    ],
    tags: ['semprit', 'kue kering', 'mentega', 'renyah', 'Lebaran'],
    rating: 4.5,
  },
  {
    id: 'kue-kaastengels',
    name: 'Kue Kaastengels',
    description:
      'Kue keju renyah khas Belanda-Indonesia berbentuk batangan. Dipanggang hingga garing dengan taburan keju di atasnya.',
    image: '🧀',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 25,
    servings: 20,
    calories: 100,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju cheddar parut', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok mentega hingga lembut. Masukkan kuning telur dan susu kental manis, kocok rata.',
      'Campurkan tepung terigu, maizena, dan garam. Ayak lalu masukkan ke adonan.',
      'Tambahkan setengah bagian keju parut, aduk rata.',
      'Giling adonan setebal 0.5 cm, potong berbentuk batangan 4x1.5 cm.',
      'Tata di loyang, olesi permukaan dengan kuning telur.',
      'Taburi sisa keju parut di atasnya.',
      'Panggang oven 160°C selama 20-25 menit hingga kekuningan.',
      'Angkat dan dinginkan di rak pendingin.',
    ],
    tags: ['kaastengels', 'keju', 'kue kering', 'renyah', 'Lebaran'],
    rating: 4.6,
  },
  {
    id: 'kue-sagu-keju',
    name: 'Kue Sagu Keju',
    description:
      'Kue kering dari tepung sagu yang renyah dengan taburan keju. Teksturnya unik, meleleh dan lumer di mulut.',
    image: '🧀',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 20,
    servings: 20,
    calories: 95,
    ingredients: [
      { name: 'Tepung sagu', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 125, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju parut', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok mentega dan gula halus hingga lembut. Masukkan telur, kocok rata.',
      'Masukkan santan kental, aduk rata.',
      'Masukkan tepung sagu dan garam sedikit demi sedikit, aduk rata.',
      'Tambahkan setengah bagian keju parut, aduk rata.',
      'Cetak adonan menggunakan cetakan kue atau bentuk bulat pipih.',
      'Tata di loyang. Taburi sisa keju parut di atasnya.',
      'Panggang oven 160°C selama 20-25 menit hingga matang merata.',
      'Angkat, dinginkan. Simpan di wadah kedap udara.',
    ],
    tags: ['sagu', 'keju', 'kue kering', 'renyah', 'populer'],
    rating: 4.5,
  },
  {
    id: 'kue-lidah-kucing',
    name: 'Kue Lidah Kucing',
    description:
      'Kue kering tipis dan renyah berbentuk lidah kucing. Rasanya gurih manis dengan aroma mentega dan vanilla.',
    image: '🍪',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 20,
    calories: 75,
    ingredients: [
      { name: 'Putih telur', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 15, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 75, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok putih telur dan gula halus hingga kental dan mengembang.',
      'Masukkan vanili, aduk rata.',
      'Ayak tepung terigu dan maizena, masukkan ke adonan secara bertahap sambil diaduk lipat.',
      'Masukkan mentega cair sedikit demi sedikit, aduk rata.',
      'Masukkan adonan ke piping bag dengan spuit bulat kecil.',
      'Cetak adonan di loyang berlapis baking sheet memanjang sepanjang 5 cm.',
      'Panggang oven 160°C selama 12-15 menit hingga pinggiran kecoklatan.',
      'Angkat, bentuk selagi hangat jika ingin melengkung. Dinginkan.',
    ],
    tags: ['lidah kucing', 'kue kering', 'renyah', 'tipis', 'Lebaran'],
    rating: 4.4,
  },
  {
    id: 'brownies-panggang',
    name: 'Brownies Panggang',
    description:
      'Brownies coklat yang dipanggang dengan tekstur fudgy dan padat. Aroma coklat yang kaya dan permukaan mengkilap.',
    image: '🍫',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 20,
    servings: 8,
    calories: 320,
    ingredients: [
      { name: 'Dark chocolate', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kacang almond (opsional)', amount: 50, unit: 'gram', category: 'Isian' },
    ],
    steps: [
      'Lelehkan dark chocolate dan mentega secara tim (leleh di atas air panas). Aduk rata, dinginkan.',
      'Kocok telur dan gula hingga kental. Masukkan vanili.',
      'Masukkan campuran coklat leleh ke adonan telur, aduk rata.',
      'Ayak tepung terigu dan coklat bubuk, masukkan ke adonan. Aduk lipat hingga rata.',
      'Tambahkan kacang almond jika suka.',
      'Tuang adonan ke loyang yang sudah diolesi mentega dan dialasi kertas.',
      'Panggang oven 170°C selama 25-30 menit. Tusuk dengan lidi, jika masih sedikit lengket berarti fudgy sempurna.',
      'Angkat, dinginkan sebelum dipotong.',
    ],
    tags: ['brownies', 'coklat', 'panggang', 'fudgy', 'kekinian'],
    rating: 4.7,
  },
  {
    id: 'brownies-kukus',
    name: 'Brownies Kukus',
    description:
      'Brownies coklat yang dikukus menghasilkan tekstur lembab dan lembut. Topping keju dan coklat membuatnya semakin nikmat.',
    image: '🍫',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 8,
    calories: 300,
    ingredients: [
      { name: 'Dark chocolate', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 3, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Keju parut', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Susu cair', amount: 50, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Lelehkan dark chocolate dan mentega, aduk rata. Dinginkan.',
      'Kocok telur dan gula hingga kental dan berwarna pucat.',
      'Masukkan campuran coklat leleh dan susu cair, aduk rata.',
      'Ayak tepung terigu dan coklat bubuk. Masukkan ke adonan, aduk lipat.',
      'Siapkan loyang kukus yang sudah diolesi mentega.',
      'Tuang setengah adonan, kukus 10 menit. Taburi keju parut.',
      'Tuang sisa adonan, kukus lagi 20-25 menit hingga matang.',
      'Angkat, dinginkan. Potong dan sajikan.',
    ],
    tags: ['brownies', 'kukus', 'coklat', 'lembut', 'kekinian'],
    rating: 4.7,
  },
  {
    id: 'lapis-surabaya',
    name: 'Lapis Surabaya',
    description:
      'Kue lapis tiga warna khas Surabaya dengan perpaduan lapisan kuning dan coklat. Tekstur lembut dan rasa mentega yang kaya.',
    image: '🍰',
    category: 'Dessert',
    difficulty: 'Susah',
    cookTime: 45,
    prepTime: 30,
    servings: 8,
    calories: 310,
    ingredients: [
      { name: 'Telur ayam', amount: 8, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 20, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Kocok telur dan gula dengan kecepatan tinggi selama 10 menit hingga kental dan pucat.',
      'Lelehkan mentega, dinginkan. Masukkan ke adonan telur secara perlahan sambil diaduk lipat.',
      'Bagi adonan jadi 3 bagian. Satu bagian dicampur coklat bubuk.',
      'Panaskan oven 190°C. Olesi loyang dengan mentega.',
      'Tuang adonan kuning pertama, ratakan. Panggang 8 menit.',
      'Tuang adonan coklat di atasnya, panggang lagi 8 menit.',
      'Tuang sisa adonan kuning, panggang 10-12 menit hingga matang.',
      'Angkat, balikkan kue di kertas baking. Dinginkan, gulung, lalu buka kembali. Potong dan sajikan.',
    ],
    tags: ['lapis surabaya', 'coklat', 'mentega', 'Surabaya', 'premium'],
    rating: 4.7,
  },
  {
    id: 'bolu-pandan',
    name: 'Bolu Pandan',
    description:
      'Bolu pandan hijau yang lembut dan harum dengan santan. Disajikan dengan vla pandan yang creamy dan manis.',
    image: '🍰',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 8,
    calories: 260,
    ingredients: [
      { name: 'Telur ayam', amount: 6, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Emulsifier (SP/TBM)', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Kocok telur, gula, vanili, dan emulsifier dengan kecepatan tinggi hingga kental dan pucat.',
      'Masukkan tepung terigu secara bertahap sambil diaduk perlahan.',
      'Tambahkan santan kental dan pasta pandan, aduk rata.',
      'Masukkan mentega leleh perlahan, aduk lipat hingga rata.',
      'Tuang adonan ke loyang yang sudah diolesi mentega dan dialasi kertas.',
      'Panggang oven 170°C selama 35-40 menit hingga matang.',
      'Tes kematangan dengan tusuk lidi. Angkat, dinginkan di rak.',
      'Potong-potong dan sajikan dengan vla pandan jika suka.',
    ],
    tags: ['bolu', 'pandan', 'santan', 'hijau', 'harum'],
    rating: 4.6,
  },
  {
    id: 'kue-sarang-semut',
    name: 'Kue Sarang Semut',
    description:
      'Bolu caramel bersarang dengan lubang-lubang unik seperti sarang semut. Teksturnya lembab dan rasa caramelnya kaya.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 50,
    prepTime: 25,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'Gula pasir (untuk karamel)', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air panas', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 4, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Santan kental', amount: 50, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Buat karamel: masak gula pasir dengan api kecil hingga berwarna kecoklatan dan berbusa.',
      'Tuang air panas perlahan ke karamel (hati-hati percikan). Aduk hingga karamel larut. Dinginkan.',
      'Kocok telur hingga kental. Masukkan larutan karamel, aduk rata.',
      'Ayak tepung terigu dan soda kue. Masukkan ke adonan, aduk rata.',
      'Tambahkan santan, mentega leleh, dan vanili. Aduk rata.',
      'Tuang adonan ke loyang yang sudah diolesi mentega.',
      'Panggang oven 175°C selama 45-50 menit hingga matang.',
      'Angkat, dinginkan. Balikkan kue, potong dan sajikan.',
    ],
    tags: ['sarang semut', 'caramel', 'bolu', 'unik', 'lembab'],
    rating: 4.6,
  },
  {
    id: 'kue-pancong',
    name: 'Kue Pancong',
    description:
      'Kue tradisional berbahan santan dan kelapa parut yang dipanggang di cetakan khusus. Luarnya renyah, dalamnya lembut.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 6,
    calories: 150,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pandan (simpul)', amount: 2, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung beras, kelapa parut, santan, gula, garam, dan daun pandan.',
      'Aduk rata hingga menjadi adonan yang bisa dicetak.',
      'Panaskan cetakan pancong, olesi sedikit mentega.',
      'Tuang adonan ke cetakan, jangan terlalu penuh.',
      'Panggang dengan api kecil hingga bagian bawah kecoklatan dan renyah.',
      'Balik kue pancong, panggang sebentar lagi hingga kedua sisi matang.',
      'Angkat, sajikan selagi hangat.',
    ],
    tags: ['pancong', 'santan', 'tradisional', 'panggang', 'Betawi'],
    rating: 4.4,
  },
  {
    id: 'kue-ape',
    name: 'Kue Ape',
    description:
      'Kue tradisional berbentuk bunga teratai dengan tepi renyah dan bagian tengah lembut. Berwarna hijau pandan yang cantik.',
    image: '🌺',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 6,
    calories: 130,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Telur ayam', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Ebi sangrai (opsional)', amount: 10, unit: 'gram', category: 'Isian' },
    ],
    steps: [
      'Campurkan semua bahan: tepung terigu, santan, gula, telur, pasta pandan, dan garam. Aduk rata.',
      'Jika suka, tambahkan ebi sangrai untuk versi gurih.',
      'Diamkan adonan selama 15 menit.',
      'Panaskan cetakan kue ape, olesi sedikit minyak.',
      'Tuang adonan ke cetakan hingga penuh. Tutup cetakan.',
      'Panggang dengan api kecil hingga tepi kue kering dan menggulung ke atas.',
      'Angkat, sajikan selagi hangat.',
    ],
    tags: ['kue ape', 'pandan', 'tradisional', 'jajan pasar', 'panggang'],
    rating: 4.3,
  },
  {
    id: 'dorayaki-v2',
    name: 'Dorayaki',
    description:
      'Kue pancake Jawa yang lembut berisi selai kacang merah atau coklat. Camilan yang lembut dan manis.',
    image: '🥞',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'Tepung terigu', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Baking powder', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Air', amount: 3, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Selai kacang merah atau coklat', amount: 100, unit: 'gram', category: 'Isian' },
    ],
    steps: [
      'Kocok telur dan gula hingga kental. Masukkan madu, aduk rata.',
      'Ayak tepung terigu dan baking powder. Masukkan ke adonan telur, aduk perlahan.',
      'Tambahkan air, aduk rata. Diamkan 15 menit.',
      'Panaskan wajan datar anti lengket dengan api kecil. Olesi sedikit mentega.',
      'Tuang satu sendok sayur adonan, buat bulatan kecil. Masak hingga permukaan berlubang.',
      'Balik, masak sebentar. Angkat, lakukan hingga adonan habis.',
      'Oleskan selai kacang merah atau coklat di satu sisi kue.',
      'Tutup dengan kue lain, tekan perlahan. Sajikan.',
    ],
    tags: ['dorayaki', 'pancake', 'Jepang', 'selai', 'lembut'],
    rating: 4.5,
  },
  {
    id: 'kue-cubit-v2',
    name: 'Kue Cubit',
    description:
      'Kue mini yang lembut dan kenyal, dimasak di cetakan khusus. Topping coklat, keju, atau meses membuatnya semakin lezat.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 10,
    calories: 85,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 75, unit: 'gram', category: 'Bumbu' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Baking powder', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur dan gula hingga kental dan pucat.',
      'Masukkan susu cair dan mentega leleh, aduk rata.',
      'Ayak tepung terigu, baking powder, dan vanili. Masukkan ke adonan, aduk perlahan.',
      'Panaskan cetakan kue cubit, olesi sedikit mentega.',
      'Tuang adonan ke cetakan hingga hampir penuh.',
      'Taburi topping sesuai selera: coklat chip, keju parut, atau meses.',
      'Tutup cetakan, masak dengan api kecil selama 5 menit hingga matang.',
      'Angkat, sajikan selagi hangat dan lembut.',
    ],
    tags: ['kue cubit', 'mini', 'coklat', 'camilan', 'kekinian'],
    rating: 4.6,
  },
  {
    id: 'kue-pukis',
    name: 'Kue Pukis',
    description:
      'Kue tradisional berbentuk setengah lingkaran dengan tekstur lembut. Beraroma pandan dan bisa diisi berbagai topping.',
    image: '🧇',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 8,
    calories: 140,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan ragi instan dengan santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga kental. Masukkan campuran santan, aduk rata.',
      'Masukkan tepung terigu, pasta pandan, dan garam. Aduk rata.',
      'Tambahkan mentega leleh, aduk rata. Diamkan adonan 30 menit.',
      'Panaskan cetakan pukis, olesi mentega.',
      'Tuang adonan hingga 3/4 cetakan. Tutup, masak api kecil.',
      'Taburi topping: keju parut, coklat chip, atau meses.',
      'Tutup kembali, masak hingga matang. Angkat, sajikan.',
    ],
    tags: ['pukis', 'tradisional', 'santan', 'pandan', 'jajan pasar'],
    rating: 4.5,
  },
  {
    id: 'kue-serabi',
    name: 'Kue Serabi',
    description:
      'Kue dadar tradisional dari tepung beras yang dimasak di atas tungku. Versi manis dengan kinca atau gurih dengan oncom.',
    image: '🧇',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 6,
    calories: 170,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun suji/pandan (air)', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah (untuk kinca)', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Kelapa parut (kinca)', amount: 50, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras, ragi instan, gula, dan garam. Tuang santan sedikit demi sedikit.',
      'Tambahkan air daun suji, aduk rata. Diamkan adonan 1 jam hingga mengembang.',
      'Untuk kinca: rebus gula merah dengan sedikit air hingga kental, tambahkan kelapa parut.',
      'Panaskan wajan serabi (teflon berlubang jika ada) dengan api kecil.',
      'Olesi sedikit minyak, tuang 1 sendok sayur adonan.',
      'Tutup wajan, masak hingga permukaan kering dan berpori.',
      'Angkat, olesi kinca gula merah di atasnya.',
      'Lipat menjadi dua dan sajikan panas-panas.',
    ],
    tags: ['serabi', 'Bandung', 'santan', 'tradisional', 'kinca'],
    rating: 4.6,
  },
  {
    id: 'bika-ambon-v2',
    name: 'Bika Ambon',
    description:
      'Kue bolu berpori khas Medan dengan aroma pandan yang harum. Teksturnya kenyal dan legit, dimakan berlapis.',
    image: '🍰',
    category: 'Dessert',
    difficulty: 'Susah',
    cookTime: 60,
    prepTime: 30,
    servings: 8,
    calories: 290,
    ingredients: [
      { name: 'Tepung sagu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 10, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Daun pandan/suji (air)', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Lemak sapi/minyak goreng', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Larutkan ragi instan dengan 2 sdm santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga kental. Masukkan air pandan/suji.',
      'Campurkan tepung sagu dengan sisa santan secara bergantian ke adonan telur.',
      'Masukkan larutan ragi dan garam. Aduk rata. Diamkan 1 jam hingga mengembang.',
      'Tuang adonan ke loyang bulat yang sudah diolesi minyak.',
      'Panggang oven 180°C selama 45-60 menit. Panggang dengan api atas bawah.',
      'Setelah matang, biarkan dalam oven 5 menit (matikan api) agar tidak kempis.',
      'Angkat, dinginkan. Potong dan sajikan.',
    ],
    tags: ['bika ambon', 'Medan', 'sagu', 'pandan', 'premium'],
    rating: 4.7,
  },
  {
    id: 'onde-onde',
    name: 'Onde-onde',
    description:
      'Bola-bola adonan tepung terigu berisi kacang hijau, dibalut wijen, dan digoreng renyah. Jajan pasar favorit.',
    image: '🟤',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 40,
    servings: 15,
    calories: 120,
    ingredients: [
      { name: 'Tepung terigu protein sedang', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang hijau (kupas)', amount: 150, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah (sisir)', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Wijen putih', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Air hangat', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus kacang hijau hingga empuk, tiriskan. Haluskan kacang hijau.',
      'Campurkan kacang hijau halus dengan gula merah sisir. Bulatkan menjadi bola-bola kecil untuk isian.',
      'Campurkan tepung terigu, ragi, gula, dan garam. Tambahkan air hangat sedikit demi sedikit, uleni hingga kalis.',
      'Diamkan adonan 30 menit hingga mengembang.',
      'Ambil sedikit adonan, pipihkan. Isi dengan bola kacang hijau, bulatkan rapat.',
      'Basahi bola onde-onde dengan air, gulingkan di atas wijen hingga rata.',
      'Goreng dalam minyak panas dengan api sedang sambil ditekan-tekan agar mengembang (meletus).',
      'Goreng hingga kecoklatan merata. Angkat dan tiriskan.',
    ],
    tags: ['onde-onde', 'wijen', 'kacang hijau', 'goreng', 'jajan pasar'],
    rating: 4.6,
  },
  {
    id: 'kue-bugis',
    name: 'Kue Bugis',
    description:
      'Kue tradisional dari tepung ketan berisi unti (kelapa parut gula merah). Dibungkus daun pisang dan dikukus.',
    image: '🟢',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 30,
    servings: 10,
    calories: 180,
    ingredients: [
      { name: 'Tepung ketan', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 150, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah (sisir)', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pisang (untuk membungkus)', amount: 10, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Untuk unti: sangrai kelapa parut sebentar. Masukkan gula merah sisir dan garam. Masak di api kecil hingga kering bisa digelindingkan. Dinginkan.',
      'Campurkan tepung ketan dengan santan dan daun pandan. Uleni hingga adonan kalis dan bisa dibentuk.',
      'Ambil sedikit adonan ketan, pipihkan di tangan.',
      'Isi dengan unti kelapa, bulatkan dan bentuk seperti oval/telur.',
      'Bungkus dengan daun pisang, semat dengan lidi/tusuk gigi.',
      'Kukus selama 25-30 menit hingga matang.',
      'Angkat, sajikan hangat atau dingin.',
    ],
    tags: ['kue bugis', 'ketan', 'unti', 'Bugis', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'kue-lupis',
    name: 'Kue Lupis',
    description:
      'Ketan yang dibungkus daun pisang segitiga dan dikukus, disajikan dengan kelapa parut dan gula merah cair. Simpel tapi nikmat.',
    image: '🟩',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 45,
    prepTime: 20,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'Beras ketan', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun pisang (muda)', amount: 12, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Kelapa parut (sangrai)', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam beras ketan minimal 4 jam. Tiriskan.',
      'Lumuri kelapa parut sangrai dengan sedikit garam, sisihkan.',
      'Rebus gula merah dengan air hingga menjadi sirup kental. Sisihkan.',
      'Ambil 2 lembar daun pisang, bentuk kerucut segitiga.',
      'Isi dengan 2 sdm beras ketan, padatkan. Lipat dan semat dengan lidi.',
      'Rebus lupis dalam air mendidih selama 3-4 jam hingga ketan benar-benar empuk dan matang.',
      'Angkat lupis, tiriskan.',
      'Potong-potong lupis, gulingkan di kelapa parut. Siram dengan gula merah cair. Sajikan.',
    ],
    tags: ['lupis', 'ketan', 'gula merah', 'tradisional', 'jajan pasar'],
    rating: 4.4,
  },
  {
    id: 'apem',
    name: 'Apem',
    description:
      'Kue tradisional dari tepung beras dan tape singkong yang dikukus. Rasa manis dengan sedikit aroma tape yang khas.',
    image: '🟤',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 20,
    servings: 8,
    calories: 140,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tape singkong', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 75, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pisang', amount: 8, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Haluskan tape singkong menggunakan garpu.',
      'Campurkan tepung beras, tape, gula, santan, soda kue, dan garam. Aduk rata.',
      'Diamkan adonan selama 30 menit.',
      'Panaskan kukusan. Olesi cetakan apem dengan sedikit minyak.',
      'Tuang adonan ke cetakan hingga 3/4 penuh.',
      'Kukus selama 20 menit hingga matang dan mengembang.',
      'Angkat, keluarkan dari cetakan. Bisa dibungkus daun pisang jika suka.',
      'Sajikan sebagai camilan tradisional.',
    ],
    tags: ['apem', 'tape', 'kukus', 'tradisional', 'jajan pasar'],
    rating: 4.3,
  },
  {
    id: 'kue-mangkok',
    name: 'Kue Mangkok',
    description:
      'Kue mangkok kukus yang mengembang mekar seperti bunga. Warna merah dan teksturnya lembut, simbol keberuntungan.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 10,
    calories: 130,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tape singkong', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 75, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Pewarna merah', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan tape singkong dengan garpu.',
      'Campurkan tepung terigu, tape, gula, santan, soda kue, garam, dan pewarna merah. Aduk rata.',
      'Diamkan adonan selama 1 jam hingga mengembang.',
      'Panaskan kukusan hingga air mendidih.',
      'Olesi cetakan kue mangkok dengan sedikit minyak. Tuang adonan hingga 3/4 penuh.',
      'Kukus selama 20 menit dengan api besar. Jangan buka tutup kukusan selama proses mengukus.',
      'Angkat kue mangkok yang sudah mekar. Dinginkan.',
      'Sajikan sebagai camilan tradisional yang manis dan lembut.',
    ],
    tags: ['kue mangkok', 'kukus', 'tape', 'Imlek', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'tape-goreng',
    name: 'Tape Goreng',
    description:
      'Tape singkong dibungkus adonan tepung tipis lalu digoreng renyah. Manis, renyah, dan aroma tape yang khas.',
    image: '🟡',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'Tape singkong', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Ambil sedikit tape singkong, bentuk bulat pipih.',
      'Campurkan tepung terigu, tepung beras, gula, garam, dan air. Aduk hingga adonan kental dan licin.',
      'Celupkan tape singkong ke adonan tepung, pastikan terlapisi rata.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning kecoklatan.',
      'Angkat dan tiriskan.',
      'Sajikan selagi hangat dan renyah.',
    ],
    tags: ['tape', 'goreng', 'rempah', 'camilan', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'pisang-ijo',
    name: 'Pisang Ijo',
    description:
      'Pisang yang dibungkus adonan tepung berwarna hijau pandan dan dikukus. Disajikan dengan kuah santan manis dingin.',
    image: '🟢',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 25,
    servings: 6,
    calories: 190,
    ingredients: [
      { name: 'Pisang raja/kepok (matang)', amount: 6, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air daun suji/pandan', amount: 100, unit: 'ml', category: 'Bumbu' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kupas pisang, belah menjadi dua.',
      'Campurkan tepung terigu, tepung beras, dan air daun suji. Uleni hingga adonan bisa dibentuk.',
      'Ambil sedikit adonan hijau, pipihkan dan bungkus pisang. Pastikan tertutup rata.',
      'Kukus pisang ijo selama 15 menit hingga adonan matang.',
      'Untuk kuah: masak santan dengan gula dan garam, aduk rata. Dinginkan.',
      'Tata pisang ijo di mangkuk, siram dengan kuah santan dingin.',
      'Sajikan sebagai dessert segar dan manis.',
    ],
    tags: ['pisang ijo', 'Makassar', 'pandan', 'kukus', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'kue-lumpur',
    name: 'Kue Lumpur',
    description:
      'Kue kukus tradisional bertekstur lembut dengan topping kismis dan kelapa parut. Warna kuning cantik dengan rasa pandan.',
    image: '🍮',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 8,
    calories: 150,
    ingredients: [
      { name: 'Kentang (rebus, haluskan)', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Margarine (leleh)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kismis', amount: 30, unit: 'gram', category: 'Isian' },
      { name: 'Kelapa parut (putih)', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur dan gula hingga kental dan pucat.',
      'Masukkan kentang yang sudah dihaluskan, aduk rata.',
      'Tambahkan santan kental, aduk rata.',
      'Masukkan tepung terigu dan vanili, aduk perlahan.',
      'Terakhir masukkan margarin leleh, aduk rata.',
      'Panaskan kukusan. Olesi cetakan kue lumpur dengan margarin.',
      'Tuang adonan ke cetakan hingga hampir penuh. Taburi kismis.',
      'Kukus selama 20 menit hingga matang. Angkat, taburi kelapa parut putih. Sajikan.',
    ],
    tags: ['kue lumpur', 'kentang', 'kukus', 'tradisional', 'lembut'],
    rating: 4.5,
  },
];
