import type { Recipe } from '@/types';

export const recipesDessertExtra: Recipe[] = [
  {
    id: 'kue-nastar-keju',
    name: 'Kue Nastar Keju',
    description: 'Variasi nastar premium dengan taburan keju parut di atasnya. Perpaduan selai nanas dan keju yang gurih manis.',
    image: '🧀',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 50,
    servings: 20,
    calories: 100,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 280, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 160, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 40, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Nanas matang', amount: 2, unit: 'buah', category: 'Isian' },
      { name: 'Gula pasir (selai)', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Keju cheddar parut', amount: 60, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Parut nanas, masak dengan gula di api kecil hingga kering dan bisa digelindingkan. Dinginkan.',
      'Kocok mentega, margarine, dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Masukkan tepung terigu sedikit demi sedikit, aduk dengan spatula.',
      'Ambil adonan, pipihkan, isi dengan selai nanas, bentuk bulat. Ulangi hingga habis.',
      'Tata di loyang, olesi kuning telur, taburi keju parut.',
      'Panggang oven 150°C selama 20 menit hingga matang keemasan. Dinginkan.',
    ],
    tags: ['nastar', 'keju', 'kue kering', 'premium', 'Lebaran'],
    rating: 4.7,
  },
  {
    id: 'kue-kastengel-premium',
    name: 'Kue Kastengel Premium',
    description: 'Kastengel premium dengan keju edam dan cheddar yang lebih banyak. Renyah, gurih, dan meleleh di mulut.',
    image: '🧀',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 25,
    servings: 20,
    calories: 115,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 240, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 140, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju edam parut', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju cheddar parut', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu evaporasi', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok mentega hingga lembut. Masukkan kuning telur dan susu evaporasi, kocok rata.',
      'Campurkan tepung terigu dan maizena, ayak. Masukkan ke adonan.',
      'Tambahkan setengah keju parut, aduk rata hingga adonan bisa dibentuk.',
      'Giling adonan setebal 0.5 cm, potong batangan 4x1.5 cm.',
      'Tata di loyang, olesi kuning telur, taburi sisa keju.',
      'Panggang 160°C selama 20-25 menit hingga keemasan. Dinginkan.',
    ],
    tags: ['kastengel', 'keju', 'premium', 'kue kering', 'renyah'],
    rating: 4.7,
  },
  {
    id: 'kue-putri-salju-coklat',
    name: 'Kue Putri Salju Coklat',
    description: 'Kue putri salju dengan tambahan coklat bubuk dalam adonannya. Perpaduan manis, gurih, dan coklat yang lembut.',
    image: '🍪',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 30,
    servings: 25,
    calories: 95,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 230, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 20, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung maizena', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 55, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula halus (taburan)', amount: 100, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Sangrai tepung terigu 10 menit. Dinginkan.',
      'Kocok mentega dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Campurkan tepung terigu sangrai, maizena, dan coklat bubuk. Masukkan ke adonan.',
      'Aduk rata dengan spatula hingga adonan bisa dibentuk.',
      'Bentuk bulat atau gunakan cetakan, tata di loyang.',
      'Panggang 150°C selama 15-20 menit. Jangan terlalu kuning.',
      'Angkat, gulingkan di gula halus saat hangat. Taburi lagi setelah dingin.',
    ],
    tags: ['putri salju', 'coklat', 'kue kering', 'Natal', 'gurih'],
    rating: 4.6,
  },
  {
    id: 'kue-sagu-pandan',
    name: 'Kue Sagu Pandan',
    description: 'Kue sagu keju dengan aroma pandan yang harum. Teksturnya renyah, meleleh, dan lumer di mulut.',
    image: '🌿',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 20,
    servings: 20,
    calories: 100,
    ingredients: [
      { name: 'Tepung sagu', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju parut', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok mentega dan gula halus hingga lembut. Masukkan telur, kocok rata.',
      'Masukkan santan kental dan pasta pandan, aduk rata.',
      'Masukkan tepung sagu dan garam sedikit demi sedikit, aduk rata.',
      'Tambahkan setengah keju parut, aduk rata.',
      'Cetak adonan menggunakan cetakan atau bentuk bulat pipih.',
      'Tata di loyang, taburi sisa keju parut.',
      'Panggang 160°C selama 20-25 menit hingga matang. Dinginkan.',
    ],
    tags: ['sagu', 'pandan', 'keju', 'kue kering', 'renyah'],
    rating: 4.5,
  },
  {
    id: 'kue-lidah-kucing-matcha',
    name: 'Kue Lidah Kucing Matcha',
    description: 'Kue lidah kucing tipis dengan aroma matcha Jepang yang khas. Warna hijau cantik dan rasa yang unik.',
    image: '🍵',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 20,
    calories: 80,
    ingredients: [
      { name: 'Putih telur', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 55, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 45, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 15, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 75, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bubuk matcha', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok putih telur dan gula halus hingga kental dan mengembang.',
      'Ayak tepung terigu, maizena, dan bubuk matcha. Masukkan ke adonan sambil diaduk lipat.',
      'Masukkan mentega cair sedikit demi sedikit, aduk rata.',
      'Masukkan adonan ke piping bag dengan spuit bulat kecil.',
      'Cetak adonan di loyang berlapis baking sheet memanjang 5 cm.',
      'Panggang 160°C selama 12-15 menit hingga pinggiran kecoklatan.',
      'Angkat, dinginkan. Simpan di wadah kedap udara.',
    ],
    tags: ['lidah kucing', 'matcha', 'Jepang', 'tipis', 'renyah'],
    rating: 4.4,
  },
  {
    id: 'kue-semprit-nanas',
    name: 'Kue Semprit Nanas',
    description: 'Kue semprit renyah dengan topping selai nanas di tengahnya. Bentuk bunga cantik dengan isian manis asam.',
    image: '🌸',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 30,
    servings: 25,
    calories: 85,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula halus', amount: 55, unit: 'gram', category: 'Bumbu' },
      { name: 'Kuning telur', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Maizena', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Selai nanas', amount: 100, unit: 'gram', category: 'Isian' },
    ],
    steps: [
      'Kocok mentega dan gula halus hingga lembut. Masukkan kuning telur, kocok rata.',
      'Tambahkan susu kental manis, aduk rata.',
      'Ayak tepung terigu dan maizena. Masukkan ke adonan, aduk dengan spatula.',
      'Masukkan adonan ke piping bag dengan spuit bintang besar.',
      'Cetak bentuk spiral di loyang berlapis kertas baking.',
      'Berikan setetes selai nanas di tengah setiap kue.',
      'Panggang 150°C selama 15-20 menit hingga matang. Dinginkan.',
    ],
    tags: ['semprit', 'nanas', 'kue kering', 'bunga', 'Lebaran'],
    rating: 4.5,
  },
  {
    id: 'kue-bolu-coklat',
    name: 'Kue Bolu Coklat',
    description: 'Bolu coklat lembut dan moist dengan aroma coklat yang kaya. Cocok untuk acara ulang tahun dan camilan keluarga.',
    image: '🍫',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 8,
    calories: 290,
    ingredients: [
      { name: 'Telur ayam', amount: 5, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 130, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 130, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur, gula, dan vanili dengan kecepatan tinggi hingga kental dan pucat.',
      'Ayak tepung terigu dan coklat bubuk. Masukkan ke adonan secara bertahap sambil diaduk lipat.',
      'Tambahkan susu cair, aduk rata.',
      'Masukkan mentega leleh perlahan, aduk lipat hingga rata.',
      'Tuang adonan ke loyang yang sudah diolesi mentega dan dialasi kertas.',
      'Panggang oven 170°C selama 35-40 menit hingga matang.',
      'Tes kematangan dengan tusuk lidi. Angkat, dinginkan, potong dan sajikan.',
    ],
    tags: ['bolu', 'coklat', 'lembut', 'moist', 'ultah'],
    rating: 4.6,
  },
  {
    id: 'kue-bolu-kukus-mekar',
    name: 'Kue Bolu Kukus Mekar',
    description: 'Bolu kukus yang mekar sempurna dengan tekstur lembut dan empuk. Berbagai pilihan rasa dan warna yang cantik.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur dan gula dengan kecepatan tinggi hingga kental dan mengembang.',
      'Masukkan santan, aduk rata dengan kecepatan rendah.',
      'Ayak tepung terigu, soda kue, dan vanili. Masukkan ke adonan, aduk lipat.',
      'Tambahkan pasta pandan, aduk rata.',
      'Siapkan cetakan bolu kukus yang sudah dialasi kertas cup.',
      'Tuang adonan hingga penuh (agar mekar sempurna).',
      'Kukus dengan api besar selama 15-20 menit. Jangan buka tutup kukusan.',
      'Angkat, dinginkan. Sajikan.',
    ],
    tags: ['bolu kukus', 'mekar', 'pandan', 'lembut', 'sederhana'],
    rating: 4.5,
  },
  {
    id: 'kue-bolu-marmer',
    name: 'Kue Bolu Marmer',
    description: 'Bolu lembut dengan motif marmer cantik dari campuran adonan vanilla dan coklat. Klasik dan tidak pernah ketinggalan zaman.',
    image: '🍰',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 25,
    servings: 8,
    calories: 270,
    ingredients: [
      { name: 'Telur ayam', amount: 5, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 130, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 140, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 60, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Emulsifier (SP)', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Kocok telur, gula, vanili, dan emulsifier hingga kental dan pucat.',
      'Ayak tepung terigu, masukkan ke adonan secara bertahap sambil diaduk lipat.',
      'Tambahkan susu cair, aduk rata.',
      'Ambil 1/3 adonan, campurkan dengan coklat bubuk.',
      'Tuang adonan putih ke loyang, lalu tuang adonan coklat secara acak.',
      'Buat motif marmer menggunakan tusuk sate atau pisau.',
      'Panggang oven 170°C selama 35-40 menit hingga matang.',
      'Angkat, dinginkan, potong dan sajikan.',
    ],
    tags: ['bolu', 'marmer', 'coklat', 'klasik', 'lembut'],
    rating: 4.5,
  },
  {
    id: 'kue-pandan-santan',
    name: 'Kue Pandan Santan',
    description: 'Kue bolu pandan berlapis santan yang harum dan lembut. Perpaduan aroma pandan dan gurihnya santan.',
    image: '🍃',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 8,
    calories: 250,
    ingredients: [
      { name: 'Telur ayam', amount: 5, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 140, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 120, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1.5, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur, gula, dan vanili hingga kental dan pucat.',
      'Masukkan tepung terigu secara bertahap, aduk lipat.',
      'Tambahkan santan kental dan pasta pandan, aduk rata.',
      'Masukkan mentega leleh perlahan, aduk lipat hingga rata.',
      'Tuang adonan ke loyang yang sudah diolesi mentega.',
      'Panggang oven 170°C selama 35-40 menit.',
      'Tes kematangan dengan tusuk lidi. Angkat, dinginkan.',
      'Potong-potong dan sajikan.',
    ],
    tags: ['pandan', 'santan', 'harum', 'lembut', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'kue-carabikang',
    name: 'Kue Carabikang',
    description: 'Kue tradisional berbentuk bunga yang mekar dengan aroma pandan. Bertekstur kenyal dan manis cocok untuk teman ngopi.',
    image: '🌺',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan ragi instan dengan sedikit santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga kental.',
      'Masukkan campuran ragi, tepung terigu, tapioka, dan garam. Aduk rata.',
      'Tambahkan sisa santan dan pasta pandan, aduk rata.',
      'Diamkan adonan selama 1 jam hingga mengembang.',
      'Panaskan cetakan carabikang, olesi mentega. Tuang adonan hingga penuh.',
      'Tutup cetakan, masak api kecil hingga permukaan kering dan berlubang. Angkat.',
    ],
    tags: ['carabikang', 'pandan', 'tradisional', 'kenyal', 'jajan pasar'],
    rating: 4.3,
  },
  {
    id: 'kue-jongkong',
    name: 'Kue Jongkong',
    description: 'Kue tradisional khas Betawi dari tepung beras dan santan dengan taburan kelapa parut. Kenyal dan gurih.',
    image: '🟩',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 15,
    servings: 8,
    calories: 170,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kelapa parut segar', amount: 100, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras, tapioka, dan garam. Tuang santan sedikit demi sedikit, aduk rata.',
      'Masukkan daun pandan, aduk rata.',
      'Bagi adonan menjadi dua: satu dicampur gula merah cair (untuk lapisan merah).',
      'Tuang adonan putih ke cetakan yang sudah diolesi minyak, kukus 10 menit.',
      'Tuang adonan merah di atasnya, kukus lagi 15 menit hingga matang.',
      'Angkat, dinginkan. Potong dadu, taburi kelapa parut. Sajikan.',
    ],
    tags: ['jongkong', 'Betawi', 'tepung beras', 'kenyal', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'kue-lapis-beras',
    name: 'Kue Lapis Beras',
    description: 'Kue lapis dari tepung beras yang kenyal dengan aroma pandan. Dibuat berlapis-lapis dan dibungkus daun pisang.',
    image: '🟩',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 10,
    calories: 180,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 350, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun suji/pandan', amount: 4, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Blender daun suji/pandan dengan sedikit air, saring ambil airnya.',
      'Campurkan tepung beras, santan, gula, garam, dan air pandan. Aduk rata.',
      'Bagi adonan menjadi dua bagian, satu beri pewarna hijau pandan.',
      'Siapkan cetakan yang sudah diolesi minyak. Tuang 2 sendok sayur adonan putih.',
      'Kukus 5 menit, tuang 2 sendok sayur adonan hijau. Ulangi bergantian.',
      'Kukus lapisan terakhir selama 15 menit hingga matang.',
      'Angkat, dinginkan, potong. Sajikan.',
    ],
    tags: ['lapis', 'tepung beras', 'pandan', 'kenyal', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'kue-lapis-ketan',
    name: 'Kue Lapis Ketan',
    description: 'Kue lapis legit dari tepung ketan yang kenyal dengan santan dan gula merah. Tekstur kenyal dan legit.',
    image: '🟫',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 20,
    servings: 10,
    calories: 200,
    ingredients: [
      { name: 'Tepung ketan', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus gula merah dengan 100ml air hingga larut. Saring, dinginkan.',
      'Campurkan tepung ketan, gula pasir, dan garam. Tuang santan sedikit demi sedikit, aduk rata.',
      'Tambahkan larutan gula merah, aduk rata hingga halus.',
      'Bagi adonan menjadi dua bagian.',
      'Siapkan loyang yang sudah diolesi minyak.',
      'Tuang satu lapisan adonan, kukus 8 menit. Tuang lapisan berikutnya, kukus lagi. Ulangi.',
      'Kukus lapisan terakhir 15 menit. Angkat, dinginkan, potong dan sajikan.',
    ],
    tags: ['lapis', 'ketan', 'santan', 'gula merah', 'kenyal'],
    rating: 4.4,
  },
  {
    id: 'kue-mangkok-gula-merah',
    name: 'Kue Mangkok Gula Merah',
    description: 'Kue mangkok tradisional dengan gula merah yang memberikan warna coklat kemerahan dan rasa manis legit.',
    image: '🧁',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 10,
    calories: 155,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Air hangat', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Larutkan ragi instan dengan air hangat. Diamkan 10 menit.',
      'Rebus gula merah dengan 100ml air, saring, dinginkan.',
      'Campurkan tepung terigu, tapioka, dan garam.',
      'Tuang larutan ragi, gula merah cair, dan santan ke campuran tepung. Aduk rata.',
      'Diamkan adonan selama 1 jam hingga mengembang.',
      'Tuang adonan ke cetakan kue mangkok yang sudah dialasi kertas.',
      'Kukus 15-20 menit hingga matang dan permukaan merekah. Angkat.',
    ],
    tags: ['mangkok', 'gula merah', 'tradisional', 'kukus', 'rekah'],
    rating: 4.4,
  },
  {
    id: 'kue-apem-jawa',
    name: 'Kue Apem Jawa',
    description: 'Kue apem tradisional Jawa dengan tapai singkong dan santan. Rasanya manis dengan sedikit aroma tape yang khas.',
    image: '🟤',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 8,
    calories: 175,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tapai singkong', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan tapai singkong menggunakan garpu atau blender.',
      'Larutkan ragi instan dengan sedikit santan hangat. Diamkan 10 menit.',
      'Campurkan tepung beras, tapai, gula, garam, dan larutan ragi.',
      'Tuang santan sedikit demi sedikit, aduk rata. Tambahkan daun pandan.',
      'Diamkan adonan 2-3 jam hingga mengembang dan berbusa.',
      'Tuang adonan ke cetakan apem yang sudah diolesi minyak.',
      'Kukus 15-20 menit hingga matang. Angkat, dinginkan.',
    ],
    tags: ['apem', 'Jawa', 'tapai', 'santan', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'kue-apem-pandan',
    name: 'Kue Apem Pandan',
    description: 'Kue apem hijau pandan yang harum dan manis. Teksturnya lembut kenyal dengan aroma pandan yang menggoda.',
    image: '🌿',
    category: 'Dessert',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 25,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Pasta pandan', amount: 1.5, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Larutkan ragi instan dengan sedikit santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga mengembang.',
      'Campurkan tepung terigu, tepung beras, dan garam.',
      'Masukkan campuran ragi, santan, pasta pandan ke adonan tepung. Aduk rata.',
      'Diamkan adonan 1-2 jam hingga mengembang.',
      'Tuang adonan ke cetakan apem yang sudah diolesi minyak.',
      'Kukus 15 menit hingga matang. Angkat, dinginkan.',
    ],
    tags: ['apem', 'pandan', 'harum', 'kukus', 'jajan pasar'],
    rating: 4.3,
  },
  {
    id: 'kue-pukis-coklat',
    name: 'Kue Pukis Coklat',
    description: 'Kue pukis dengan tambahan coklat bubuk yang membuatnya lembut dan harum coklat. Camilan tradisional favorit anak-anak.',
    image: '🍫',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 8,
    calories: 155,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Coklat bubuk', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
    ],
    steps: [
      'Larutkan ragi dengan sedikit santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga kental. Masukkan campuran ragi, aduk rata.',
      'Masukkan tepung terigu dan coklat bubuk, aduk rata.',
      'Tambahkan sisa santan dan mentega leleh, aduk rata. Diamkan 30 menit.',
      'Panaskan cetakan pukis, olesi mentega.',
      'Tuang adonan hingga 3/4 cetakan. Tutup, masak api kecil.',
      'Masak hingga matang dan permukaan kering. Angkat, sajikan.',
    ],
    tags: ['pukis', 'coklat', 'tradisional', 'lembut', 'anak-anak'],
    rating: 4.5,
  },
  {
    id: 'kue-pukis-keju',
    name: 'Kue Pukis Keju',
    description: 'Kue pukis gurih manis dengan taburan keju parut di atasnya. Kombinasi tekstur lembut dan keju yang meleleh.',
    image: '🧀',
    category: 'Dessert',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 8,
    calories: 165,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 75, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega (leleh)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju parut', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Larutkan ragi dengan sedikit santan hangat. Diamkan 10 menit.',
      'Kocok telur dan gula hingga kental. Masukkan campuran ragi, aduk rata.',
      'Masukkan tepung terigu, aduk rata.',
      'Tambahkan sisa santan dan mentega leleh, aduk rata. Diamkan 30 menit.',
      'Panaskan cetakan pukis, olesi mentega.',
      'Tuang adonan hingga 3/4 cetakan. Taburi keju parut. Tutup, masak api kecil.',
      'Masak hingga matang dan permukaan kering. Angkat, sajikan.',
    ],
    tags: ['pukis', 'keju', 'tradisional', 'lembut', 'gurih'],
    rating: 4.5,
  },
];