import type { Recipe } from '@/types';
export const recipesSnackExtra: Recipe[] = [
  {
    id: 'emping-melinjo',
    name: 'Emping Melinjo',
    description:
      'Emping renyah dari biji melinjo yang ditumbuk pipih dan digoreng. Camilan tradisional Indonesia yang gurih dan renyah.',
    image: '🟡',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 0,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Emping melinjo (beli jadi)', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Panaskan minyak goreng dalam wajan hingga benar-benar panas.',
      'Masukkan emping satu per satu agar tidak menempel.',
      'Goreng hingga emping mengembang dan berwarna kuning keemasan.',
      'Balik sekali agar matang merata.',
      'Angkat, tiriskan di tisu dapur.',
      'Taburi garam secukupnya, sajikan sebagai camilan atau teman nasi.',
    ],
    tags: ['emping', 'melinjo', 'renyah', 'goreng', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'keripik-singkong',
    name: 'Keripik Singkong',
    description:
      'Keripik tipis dari singkong yang digoreng renyah dengan bumbu gurih. Camilan favorit yang renyah dan tahan lama.',
    image: '🥔',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 30,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'Singkong', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Air es', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Kupas singkong, iris tipis-tipis menggunakan pisau atau alat pengiris.',
      'Haluskan bawang putih, kunyit, dan garam.',
      'Campurkan bumbu halus dengan air es.',
      'Rendam irisan singkong dalam air bumbu selama 30 menit.',
      'Tiriskan singkong, jemur sebentar hingga kering.',
      'Goreng dalam minyak panas hingga renyah dan kecoklatan.',
      'Angkat, tiriskan. Sajikan dalam toples kedap udara.',
    ],
    tags: ['keripik', 'singkong', 'renyah', 'gurih', 'tahan lama'],
    rating: 4.5,
  },
  {
    id: 'keripik-tempe',
    name: 'Keripik Tempe',
    description:
      'Keripik tempe tipis yang renyah dan gurih dengan bumbu bawang. Camilan sehat dari tempe yang digemari semua kalangan.',
    image: '🫘',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Tempe', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih halus', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kunyit bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air es', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 400, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Iris tempe sangat tipis menggunakan pisau tajam.',
      'Campurkan tepung tapioka, bawang putih halus, garam, dan kunyit bubuk.',
      'Tambahkan air es, aduk rata menjadi adonan encer.',
      'Celupkan irisan tempe ke adonan tepung.',
      'Goreng dalam minyak panas dengan api sedang hingga renyah.',
      'Angkat, tiriskan di tisu dapur.',
      'Sajikan sebagai camilan atau teman nasi.',
    ],
    tags: ['keripik', 'tempe', 'renyah', 'gurih', 'sehat'],
    rating: 4.4,
  },
  {
    id: 'keripik-pisang',
    name: 'Keripik Pisang',
    description:
      'Keripik pisang goreng renyah dengan rasa manis gurih. Camilan tropis yang mudah dibuat dan cocok untuk berbagai acara.',
    image: '🍌',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 5,
    calories: 240,
    ingredients: [
      { name: 'Pisang raja', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula pasir halus', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Air kapur sirih', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Kupas pisang, iris tipis menggunakan alat pengiris.',
      'Rendam irisan pisang dalam air kapur sirih selama 30 menit.',
      'Tiriskan irisan pisang, jemur sebentar hingga kering.',
      'Panaskan minyak goreng hingga benar-benar panas.',
      'Goreng irisan pisang hingga kuning keemasan dan renyah.',
      'Angkat, tiriskan. Taburi garam dan gula halus secukupnya.',
      'Simpan dalam toples kedap udara.',
    ],
    tags: ['keripik', 'pisang', 'renyah', 'manis gurih', 'tropis'],
    rating: 4.4,
  },
  {
    id: 'kerupuk-ikan-tenggiri',
    name: 'Kerupuk Ikan',
    description:
      'Kerupuk dari adonan ikan tenggiri dan tepung yang digoreng mengembang. Camilan renyah khas nusantara yang gurih.',
    image: '🐟',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 0,
    servings: 4,
    calories: 170,
    ingredients: [
      { name: 'Kerupuk ikan (beli jadi)', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Panaskan minyak goreng dalam wajan hingga benar-benar panas.',
      'Pastikan minyak sudah bergelembung banyak sebelum menggoreng.',
      'Masukkan kerupuk satu per satu.',
      'Kerupuk akan mengembang besar dalam hitungan detik.',
      'Angkat segera setelah mengembang, jangan biarkan gosong.',
      'Tiriskan di tisu dapur, sajikan.',
    ],
    tags: ['kerupuk', 'ikan', 'renyah', 'gurih', 'mengembang'],
    rating: 4.3,
  },
  {
    id: 'tempe-bacem',
    name: 'Tempe Bacem',
    description:
      'Tempe yang dimasak dengan bumbu gula merah dan kecap hingga manis legit. Camilan tradisional khas Jawa yang gurih.',
    image: '🫘',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 40,
    prepTime: 10,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Tempe', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Air kelapa', amount: 300, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Potong tempe menjadi bentuk dadu atau persegi panjang.',
      'Haluskan bawang putih dan bawang merah.',
      'Tumis bumbu halus bersama daun salam hingga harum.',
      'Masukkan tempe, gula merah, kecap manis, dan air kelapa.',
      'Masak dengan api kecil hingga bumbu meresap dan kuah habis.',
      'Angkat tempe bacem, bisa langsung disajikan atau digoreng sebentar.',
      'Sajikan sebagai camilan atau lauk pendamping.',
    ],
    tags: ['tempe', 'bacem', 'manis', 'gurih', 'Jawa'],
    rating: 4.6,
  },
  {
    id: 'tahu-bacem',
    name: 'Tahu Bacem',
    description:
      'Tahu dimasak dengan bumbu gula merah, kecap, dan rempah hingga empuk manis. Camilan tradisional Jawa yang favorit.',
    image: '🧈',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 40,
    prepTime: 10,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Tahu putih', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Air kelapa', amount: 300, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Belah tahu menjadi dua bagian, tiriskan.',
      'Haluskan bawang putih dan bawang merah.',
      'Tumis bumbu halus dengan daun salam hingga harum.',
      'Masukkan tahu, gula merah, kecap manis, dan air kelapa.',
      'Masak dengan api kecil hingga kuah menyusut dan bumbu meresap.',
      'Angkat tahu bacem. Bisa disajikan langsung atau digoreng.',
      'Sajikan sebagai camilan atau lauk pendamping nasi.',
    ],
    tags: ['tahu', 'bacem', 'manis', 'gurih', 'Jawa'],
    rating: 4.5,
  },
  {
    id: 'telur-asin',
    name: 'Telur Asin',
    description:
      'Telur bebek yang diasinkan dan direbus, berwarna merah kecoklatan dengan kuning telur berminyak. Camilan tradisional yang gurih.',
    image: '🥚',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 0,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Telur asin (beli jadi)', amount: 4, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Air', amount: 500, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Cuci bersih telur asin dari lumpur atau abu.',
      'Didihkan air dalam panci.',
      'Masukkan telur asin, rebus selama 20 menit.',
      'Angkat telur, celupkan ke air dingin agar mudah dikupas.',
      'Kupas kulit telur asin.',
      'Potong menjadi dua bagian, sajikan dengan nasi putih.',
    ],
    tags: ['telur asin', 'bebek', 'asin', 'gurih', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'telur-pindang',
    name: 'Telur Pindang',
    description:
      'Telur rebus dimasak dalam kuah bumbu gula merah dan rempah hingga berwarna coklat. Camilan khas Jawa yang aromatik.',
    image: '🥚',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 60,
    prepTime: 10,
    servings: 6,
    calories: 160,
    ingredients: [
      { name: 'Telur ayam', amount: 8, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun jati', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Kulit bawang merah', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Air', amount: 600, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Rebus telur hingga matang, kupas kulitnya.',
      'Didihkan air, masukkan daun jati, daun salam, kulit bawang, dan bawang putih.',
      'Tambahkan gula merah, aduk hingga larut.',
      'Masukkan telur rebus ke dalam rebusan bumbu.',
      'Masak dengan api kecil selama 45 menit hingga telur berwarna coklat.',
      'Angkat telur, dinginkan.',
      'Sajikan sebagai camilan atau lauk.',
    ],
    tags: ['telur pindang', 'Jawa', 'rempah', 'gula merah', 'aromatik'],
    rating: 4.5,
  },
  {
    id: 'mendol-tempe',
    name: 'Mendol Tempe',
    description:
      'Perkedel tempe khas Malang dengan bumbu yang gurih dan pedas. Camilan goreng dari tempe yang lembut dan harum.',
    image: '🫘',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Tempe', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 1, unit: 'batang', category: 'Sayuran' },
      { name: 'Tepung beras', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Kukus tempe 10 menit, haluskan.',
      'Haluskan bawang merah dan cabai rawit.',
      'Campurkan tempe halus, bumbu halus, kelapa parut, daun bawang, dan tepung beras.',
      'Bumbui garam, aduk rata.',
      'Bentuk adonan menjadi bulatan kecil atau lonjong.',
      'Goreng dalam minyak panas hingga kuning kecoklatan.',
      'Tiriskan, sajikan sebagai camilan.',
    ],
    tags: ['mendol', 'tempe', 'Malang', 'goreng', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'sate-tempe',
    name: 'Sate Tempe',
    description:
      'Tempe yang dipotong tipis, dibumbui, ditusuk, dan dibakar. Camilan sederhana yang gurih dan harum.',
    image: '🍢',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 220,
    ingredients: [
      { name: 'Tempe', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih halus', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tusuk sate', amount: 10, unit: 'buah', category: 'Pelengkap' },
      { name: 'Minyak goreng', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Potong tempe tipis memanjang.',
      'Campurkan kecap manis, bawang putih halus, dan cabai merah bubuk.',
      'Lumuri potongan tempe dengan bumbu, diamkan 15 menit.',
      'Tusuk tempe yang sudah dibumbui ke tusuk sate.',
      'Panggang sate tempe di atas pan anti lengket atau arang.',
      'Balik sesekali dan olesi sisa bumbu.',
      'Sajikan hangat sebagai camilan.',
    ],
    tags: ['sate', 'tempe', 'bakar', 'kecap', 'gurih'],
    rating: 4.3,
  },
  {
    id: 'sate-telur-puyuh',
    name: 'Sate Telur Puyuh',
    description:
      'Telur puyuh rebus yang dibumbui dan ditusuk, dibakar dengan bumbu kecap. Camilan unik yang gurih dan manis.',
    image: '🥚',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 3,
    calories: 200,
    ingredients: [
      { name: 'Telur puyuh rebus', amount: 12, unit: 'butir', category: 'Protein' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih halus', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tusuk sate', amount: 6, unit: 'buah', category: 'Pelengkap' },
      { name: 'Minyak goreng', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Rebus telur puyuh hingga matang, kupas kulitnya.',
      'Campurkan kecap manis, bawang putih halus, dan merica bubuk.',
      'Lumuri telur puyuh dengan bumbu, diamkan 10 menit.',
      'Tusuk 2 telur puyuh di setiap tusuk sate.',
      'Panggang di atas pan atau arang sambil diolesi sisa bumbu.',
      'Balik sesekali hingga bumbu meresap dan permukaan kecoklatan.',
      'Sajikan hangat sebagai camilan.',
    ],
    tags: ['sate', 'telur puyuh', 'bakar', 'kecap', 'gurih manis'],
    rating: 4.4,
  },
  {
    id: 'sate-usus',
    name: 'Sate Usus',
    description:
      'Usus ayam yang dibumbui dan dibakar dengan arang. Camilan khas street food Indonesia yang gurih dan empuk.',
    image: '🍢',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 180,
    ingredients: [
      { name: 'Usus ayam', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih halus', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Tusuk sate', amount: 10, unit: 'buah', category: 'Pelengkap' },
      { name: 'Jeruk limau', amount: 1, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Bersihkan usus ayam, balik dan cuci hingga bersih.',
      'Rebus usus sebentar, tiriskan.',
      'Campurkan kecap manis, bawang putih halus, dan cabai rawit.',
      'Lumuri usus dengan bumbu, tusuk ke tusuk sate.',
      'Bakar di atas arang sambil diolesi sisa bumbu.',
      'Masak hingga usus matang dan permukaan kecoklatan.',
      'Sajikan dengan perasan jeruk limau.',
    ],
    tags: ['sate', 'usus', 'bakar', 'street food', 'gurih'],
    rating: 4.2,
  },
  {
    id: 'sate-kerang',
    name: 'Sate Kerang',
    description:
      'Daging kerang yang ditusuk dan dibakar dengan bumbu kecap pedas. Camilan laut yang gurih dan harum.',
    image: '🐚',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 190,
    ingredients: [
      { name: 'Kerang hijau rebus', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang merah iris', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit iris', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Tusuk sate', amount: 10, unit: 'buah', category: 'Pelengkap' },
      { name: 'Jeruk limau', amount: 1, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus kerang hijau hingga cangkang terbuka. Ambil dagingnya.',
      'Tusuk daging kerang ke tusuk sate.',
      'Campurkan kecap manis, bawang merah iris, dan cabai rawit.',
      'Bakar sate kerang di atas arang.',
      'Olesi bumbu kecap saat membalik sate.',
      'Masak hingga kecoklatan dan harum.',
      'Sajikan dengan perasan jeruk limau.',
    ],
    tags: ['sate', 'kerang', 'laut', 'bakar', 'gurih'],
    rating: 4.3,
  },
  {
    id: 'sate-lilit-ikan',
    name: 'Sate Lilit Ikan',
    description:
      'Sate khas Bali dari adonan ikan yang dibumbui dan dililitkan di tusuk serai. Camilan gurih dengan aroma serai yang harum.',
    image: '🍢',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 25,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Ikan tenggiri fillet', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Kelapa parut', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Serai (batang besar)', amount: 8, unit: 'batang', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun jeruk iris', amount: 3, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan ikan tenggiri menggunakan cobek atau food processor.',
      'Haluskan bawang merah, cabai rawit, dan kunyit.',
      'Campurkan ikan halus, bumbu halus, kelapa parut, dan daun jeruk. Aduk rata.',
      'Bumbui garam dan gula, aduk hingga kalis.',
      'Ambil batang serai, pilin ujungnya. Lilitkan adonan ikan di sekeliling serai.',
      'Panggang di atas arang atau pan anti lengket hingga kecoklatan.',
      'Sajikan dengan sambal matah khas Bali.',
    ],
    tags: ['sate lilit', 'Bali', 'ikan', 'serai', 'tradisional'],
    rating: 4.7,
  },
  {
    id: 'pentol-bakso',
    name: 'Pentol Bakso',
    description:
      'Bakso sapi kenyal berukuran kecil yang digoreng atau direbus. Camilan khas Malang yang gurih dan nikmat.',
    image: '🟤',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 25,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Daging sapi giling', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih goreng', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu', amount: 3, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Air', amount: 100, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Haluskan bawang putih goreng, campurkan dengan daging giling.',
      'Tambahkan garam, merica, dan air es. Uleni hingga kalis.',
      'Masukkan tepung tapioka, uleni rata.',
      'Didihkan air, bulatkan adonan pentol menggunakan tangan.',
      'Rebus pentol hingga mengambang, angkat.',
      'Bisa disajikan dengan kuah atau digoreng.',
      'Sajikan pentol goreng dengan saus sambal kecap.',
    ],
    tags: ['pentol', 'bakso', 'sapi', 'Malang', 'kenyal'],
    rating: 4.5,
  },
  {
    id: 'cilok-goreng',
    name: 'Cilok',
    description:
      'Cilok (aci dicolok) dari tepung tapioka yang kenyal dengan saus kacang pedas. Camilan khas Bandung yang murah meriah.',
    image: '🟤',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Tepung tapioka', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih goreng halus', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 1, unit: 'batang', category: 'Sayuran' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air panas', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kacang tanah goreng', amount: 100, unit: 'gram', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung tapioka, tepung terigu, bawang putih goreng, dan garam.',
      'Tuang air panas sedikit demi sedikit, uleni hingga kalis.',
      'Tambahkan daun bawang iris, aduk rata.',
      'Bulatkan adonan menjadi bola-bola kecil.',
      'Rebus cilok dalam air mendidih hingga mengambang. Tiriskan.',
      'Buat saus: haluskan kacang tanah goreng, cabai rawit, dan gula merah.',
      'Sajikan cilok dengan siraman saus kacang.',
    ],
    tags: ['cilok', 'tapioka', 'kenyal', 'Bandung', 'saus kacang'],
    rating: 4.5,
  },
  {
    id: 'cimol-goreng',
    name: 'Cimol',
    description:
      'Bola-bola tepung kanji yang renyah di luar dan kenyal di dalam. Camilan khas Bandung yang gurih dan adiktif.',
    image: '⚪',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Tepung kanji', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 25, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih goreng', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air panas', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung kanji, tepung terigu, bawang putih goreng halus, dan garam.',
      'Tuang air panas sedikit demi sedikit, uleni hingga kalis.',
      'Bulatkan adonan menjadi bola-bola kecil sebesar kelereng.',
      'Goreng dalam minyak panas dengan api sedang.',
      'Goreng hingga permukaan menggelembung dan kecoklatan.',
      'Angkat, tiriskan di tisu dapur.',
      'Taburi bubuk cabai atau keju sesuai selera.',
    ],
    tags: ['cimol', 'kanji', 'kenyal', 'Bandung', 'gurih'],
    rating: 4.4,
  },
  {
    id: 'cireng-rujak',
    name: 'Cireng Rujak',
    description:
      'Cireng besar berisi rujak buah pedas manis. Camilan khas Bandung yang unik dengan perpaduan rasa gurih, pedas, dan manis.',
    image: '🟤',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 10,
    prepTime: 30,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'Tepung tapioka', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mangga muda parut', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Cabai rawit iris', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air panas', amount: 250, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Campurkan tepung tapioka dan terigu, tuang air panas. Uleni hingga kalis.',
      'Untuk isi rujak: campurkan mangga muda parut, gula merah, dan cabai rawit.',
      'Ambil adonan, pipihkan. Berisi campuran rujak.',
      'Bulatkan dan pipihkan kembali.',
      'Goreng dalam minyak panas dengan api sedang hingga kecoklatan.',
      'Tiriskan, sajikan hangat.',
    ],
    tags: ['cireng', 'rujak', 'mangga', 'pedas manis', 'Bandung'],
    rating: 4.6,
  },
  {
    id: 'gehu-bandung',
    name: 'Gehu',
    description:
      'Goreng tahu isi (gehu) khas Bandung berisi tauge dan bumbu gurih. Camilan renyah yang empuk di dalam.',
    image: '🧆',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Tahu putih besar', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Tauge', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Belah tahu menjadi dua, kerok bagian dalam untuk membuat lubang.',
      'Tumis bawang putih cincang hingga harum.',
      'Masukkan tauge dan daun bawang, tumis sebentar.',
      'Bumbui garam dan merica, angkat. Dinginkan.',
      'Isi bagian dalam tahu dengan tumisan tauge.',
      'Goreng tahu isi dalam minyak panas hingga kecoklatan.',
      'Tiriskan, sajikan dengan saus sambal.',
    ],
    tags: ['gehu', 'tahu isi', 'Bandung', 'tauge', 'goreng'],
    rating: 4.4,
  },
  {
    id: 'tahu-susu',
    name: 'Tahu Susu',
    description:
      'Tahu goreng isi susu yang lembut dan manis. Camilan favorit anak-anak yang lembut meleleh di mulut.',
    image: '🥛',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 190,
    ingredients: [
      { name: 'Tahu putih kecil', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Isian' },
      { name: 'Gula pasir halus', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Tepung terigu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Air es', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Belah tahu menjadi dua, buang bagian tengah sedikit untuk lubang.',
      'Campurkan susu kental manis dan gula pasir halus.',
      'Isi lubang tahu dengan campuran susu, rekatkan dengan sedikit adonan tepung.',
      'Buat adonan tepung: campurkan tepung, telur, dan air es.',
      'Celupkan tahu isi ke adonan tepung.',
      'Goreng dalam minyak panas dengan api sedang hingga kecoklatan.',
      'Tiriskan, sajikan hangat.',
    ],
    tags: ['tahu susu', 'manis', 'lembut', 'anak-anak', 'goreng'],
    rating: 4.5,
  },
  {
    id: 'tahu-walik',
    name: 'Tahu Walik',
    description:
      'Tahu yang dibalik isian ke luar dan digoreng renyah. Camilan khas Purbalingga yang gurih dan unik.',
    image: '🧈',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Tahu putih kecil', amount: 10, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Daging ayam cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Belah tahu menjadi dua, keluarkan bagian dalamnya.',
      'Haluskan bagian dalam tahu, campurkan dengan ayam cincang dan daun bawang.',
      'Tambahkan bawang putih halus, garam, dan merica. Aduk rata.',
      'Isi kulit tahu dengan campuran adonan, rekatkan.',
      'Balik tahu sehingga bagian kulit berada di dalam.',
      'Goreng dalam minyak panas hingga kecoklatan dan renyah.',
      'Tiriskan, sajikan dengan saus cabai atau kecap.',
    ],
    tags: ['tahu walik', 'Purbalingga', 'goreng', 'gurih', 'unik'],
    rating: 4.4,
  },
  {
    id: 'tahu-crispy-pedas',
    name: 'Tahu Crispy Pedas',
    description:
      'Tahu goreng berbalut tepung crispy dengan bumbu cabai yang pedas. Camilan renyah pedas yang cocok untuk penggemar sambal.',
    image: '🌶️',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Tahu putih', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Cabai bubuk', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Bawang putih bubuk', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air es', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Potong tahu menjadi bentuk dadu.',
      'Campurkan tepung terigu, tapioka, cabai bubuk, bawang putih bubuk, dan garam.',
      'Tambahkan air es, aduk rata. Biarkan ada gumpalan untuk tekstur crispy.',
      'Celupkan tahu ke adonan tepung pedas.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan.',
      'Angkat, tiriskan di tisu dapur.',
      'Sajikan dengan saus sambal atau mayones pedas.',
    ],
    tags: ['tahu', 'crispy', 'pedas', 'cabai', 'renyah'],
    rating: 4.5,
  },
  {
    id: 'odading-bandung',
    name: 'Odading',
    description:
      'Roti goreng mengembang khas Bandung yang renyah di luar dan empuk di dalam. Camilan legendaris yang viral dan gurih.',
    image: '🍞',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 30,
    servings: 6,
    calories: 250,
    ingredients: [
      { name: 'Tepung terigu', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan ragi, gula, dan susu hangat. Diamkan 10 menit.',
      'Masukkan tepung terigu, telur, margarin leleh, dan adonan ragi.',
      'Uleni hingga kalis dan elastis. Diamkan 1 jam hingga mengembang.',
      'Kempiskan adonan, bagi menjadi bulatan kecil.',
      'Diamkan lagi 20 menit hingga mengembang.',
      'Goreng dalam minyak banyak dengan api kecil hingga kecoklatan.',
      'Angkat, tiriskan. Sajikan hangat.',
    ],
    tags: ['odading', 'Bandung', 'roti goreng', 'mengembang', 'viral'],
    rating: 4.4,
  },
  {
    id: 'bakwan-jagung',
    name: 'Bakwan Jagung',
    description:
      'Bakwan goreng dari adonan jagung manis yang renyah dan manis gurih. Camilan favorit yang gampang dibuat di rumah.',
    image: '🌽',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 190,
    ingredients: [
      { name: 'Jagung manis pipil', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Cabai rawit iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan jagung manis pipil, tepung terigu, dan telur.',
      'Tambahkan daun bawang iris, cabai rawit, dan garam.',
      'Tambahkan sedikit air jika perlu, aduk rata.',
      'Ambil satu sendok sayur adonan, tuang ke minyak panas.',
      'Goreng dengan api sedang hingga kuning kecoklatan.',
      'Balik sekara, goreng hingga kedua sisi matang.',
      'Tiriskan, sajikan dengan saus sambal.',
    ],
    tags: ['bakwan', 'jagung', 'goreng', 'manis gurih', 'populer'],
    rating: 4.5,
  },
  {
    id: 'bola-udang',
    name: 'Bola-Bola Udang',
    description:
      'Bola udang goreng renyah berisi udang utuh. Camilan seafood yang gurih dan renyah favorit keluarga.',
    image: '🦐',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Udang kupas', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Tepung tapioka', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 40, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 1, unit: 'batang', category: 'Sayuran' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Cincang kasar sebagian udang, biarkan sebagian utuh untuk isi.',
      'Campurkan tepung tapioka, tepung terigu, bawang putih halus, garam, dan merica.',
      'Tambahkan udang cincang dan daun bawang, aduk rata.',
      'Ambil sedikit adonan, pipihkan. Berisi udang utuh.',
      'Bulatkan dan rapatkan, lakukan hingga adonan habis.',
      'Goreng dalam minyak panas hingga kuning keemasan.',
      'Tiriskan, sajikan dengan saus sambal mayones.',
    ],
    tags: ['bola udang', 'seafood', 'goreng', 'renyah', 'gurih'],
    rating: 4.6,
  },
  {
    id: 'lumpia-semarang-udang',
    name: 'Lumpia Semarang Udang',
    description:
      'Lumpia goreng renyah berisi rebung dan udang khas Semarang. Camilan legendaris yang gurih dan renyah.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 10,
    prepTime: 30,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'Kulit lumpia', amount: 15, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Udang kupas cincang', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Rebung bambu', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Rebus rebung bambu hingga empuk, tiriskan dan iris tipis.',
      'Tumis bawang putih dan bawang merah hingga harum.',
      'Masukkan udang cincang, aduk hingga berubah warna.',
      'Tambahkan rebung, daun bawang, gula merah, garam, merica. Aduk rata.',
      'Dinginkan isian.',
      'Ambil kulit lumpia, beri isian. Gulung rapat, rekatkan tepi.',
      'Goreng hingga kuning keemasan dan renyah.',
    ],
    tags: ['lumpia', 'Semarang', 'udang', 'rebung', 'legendaris'],
    rating: 4.7,
  },
  {
    id: 'lumpia-basah',
    name: 'Lumpia Basah',
    description:
      'Lumpia segar berisi rebung bambu dan taoge dengan saus tauco khas Semarang. Camilan segar yang gurih dan manis.',
    image: '🥗',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Kulit lumpia basah (beli jadi)', amount: 10, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Rebung bambu', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Tauge', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Tauco', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
    ],
    steps: [
      'Rebus rebung hingga empuk, iris tipis.',
      'Tumis bawang putih hingga harum.',
      'Masukkan tauco, rebung, tauge, dan daun bawang.',
      'Bumbui garam, gula merah, dan merica. Masak hingga matang, angkat.',
      'Ambil kulit lumpia basah, beri isian sayuran.',
      'Gulung rapat, potong serong.',
      'Sajikan dengan saus cabai dan bawang putih goreng.',
    ],
    tags: ['lumpia basah', 'Semarang', 'segar', 'tauco', 'sayuran'],
    rating: 4.6,
  },
  {
    id: 'risoles-mayo-tuna',
    name: 'Risoles Mayo Tuna',
    description:
      'Risoles renyah berisi ragout tuna dan mayones. Camilan modern dengan rasa seafood yang gurih dan creamy.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 25,
    servings: 4,
    calories: 270,
    ingredients: [
      { name: 'Kulit risoles (beli jadi)', amount: 12, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Tuna kaleng', amount: 1, unit: 'kaleng', category: 'Protein' },
      { name: 'Wortel dadu kecil', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang bombay iris', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Mayones', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Susu cair', amount: 80, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Telur kocok (pencelup)', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Tepung panir', amount: 100, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Tumis bawang bombay hingga layu dan harum.',
      'Masukkan wortel, masak sebentar.',
      'Tambahkan tuna kaleng, susu, garam, dan merica. Masak hingga kental.',
      'Angkat, tambahkan mayones. Aduk rata dan dinginkan.',
      'Ambil kulit risoles, isi 1 sdm ragout. Lipat segitiga.',
      'Celupkan ke telur kocok, gulingkan di tepung panir.',
      'Goreng hingga kuning keemasan.',
    ],
    tags: ['risoles', 'tuna', 'mayones', 'modern', 'seafood'],
    rating: 4.5,
  },
  {
    id: 'pastel-ayam-kuning',
    name: 'Pastel Ayam',
    description:
      'Pastel goreng renyah berisi ragout ayam, wortel, dan kentang. Camilan tradisional yang mengenyangkan dan gurih.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 25,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam cincang', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Wortel iris korek api', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Kentang rebus', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 1, unit: 'batang', category: 'Sayuran' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Untuk kulit: campurkan tepung, garam, margarin, dan air. Uleni, diamkan 15 menit.',
      'Giling tipis kulit, cetak bulat.',
      'Haluskan kentang rebus.',
      'Tumis bumbu halus, masukkan ayam, wortel, dan kentang halus.',
      'Bumbui garam dan merica, masak hingga kental. Dinginkan.',
      'Ambil kulit pastel, isi dengan ragout. Lipat dan rekatkan tepi.',
      'Goreng hingga kuning keemasan, sajikan.',
    ],
    tags: ['pastel', 'ayam', 'goreng', 'ragout', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'pastel-tutup',
    name: 'Pastel Tutup',
    description:
      'Pastel berisi ragout sayuran dan daging yang ditutup pastry. Camilan khas Betawi yang lembut dan gurih.',
    image: '🥧',
    category: 'Snack',
    difficulty: 'Susah',
    cookTime: 30,
    prepTime: 30,
    servings: 6,
    calories: 290,
    ingredients: [
      { name: 'Tepung terigu', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging sapi cincang', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Wortel dadu', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Kentang dadu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Telur (pencelup)', amount: 1, unit: 'butir', category: 'Protein' },
    ],
    steps: [
      'Untuk kulit: campurkan tepung, mentega, dan air es. Uleni hingga kalis, diamkan.',
      'Tumis bawang bombay, masukkan daging cincang hingga berubah warna.',
      'Tambahkan wortel, kentang, susu, garam, merica. Masak hingga kental.',
      'Giling adonan kulit, cetak bulat menggunakan mangkuk.',
      'Letakkan isian ragout di tengah kulit.',
      'Olesi tepi kulit dengan telur kocok, tutup dengan kulit lainnya.',
      'Panggang oven 180°C selama 20 menit hingga kecoklatan.',
    ],
    tags: ['pastel tutup', 'Betawi', 'pastry', 'gurih', 'oven'],
    rating: 4.6,
  },
  {
    id: 'panada-manado',
    name: 'Panada',
    description:
      'Roti goreng berisi ikan cakalang bumbu pedas khas Manado. Camilan khas Sulawesi Utara yang gurih dan pedas.',
    image: '🐟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 30,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'Tepung terigu', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ikan cakalang suwir', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun jeruk iris', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung, ragi, garam, dan air hangat. Uleni hingga kalis, diamkan 1 jam.',
      'Tumis bawang merah dan bawang putih hingga harum.',
      'Masukkan cabai rawit, daun jeruk, dan ikan cakalang suwir.',
      'Bumbui garam dan gula, masak hingga bumbu meresap. Dinginkan.',
      'Bagi adonan roti, pipihkan. Berisi tumisan ikan.',
      'Lipat menjadi setengah lingkaran, rekatkan tepi.',
      'Goreng dalam minyak panas hingga kecoklatan.',
    ],
    tags: ['panada', 'Manado', 'cakalang', 'pedas', 'Sulawesi'],
    rating: 4.6,
  },
  {
    id: 'karipap-kari',
    name: 'Karipap',
    description:
      'Karipap (curry puff) berisi kentang dan kari ayam. Camilan khas Melayu yang gurih dengan aroma rempah kari.',
    image: '🥧',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 30,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kentang rebus', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Bubuk kari', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang bombay iris', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kelapa parut', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Telur (pencelup)', amount: 1, unit: 'butir', category: 'Protein' },
    ],
    steps: [
      'Untuk kulit: campurkan tepung, garam, mentega, dan air. Uleni, diamkan 15 menit.',
      'Tumis bawang bombay, masukkan ayam cincang.',
      'Tambahkan kentang halus dan bubuk kari.',
      'Masukkan kelapa parut, bumbui garam. Masak hingga kering, dinginkan.',
      'Giling adonan kulit, cetak bulat.',
      'Berisi kari kentang ayam, lipat setengah lingkaran. Rekatkan tepi.',
      'Goreng hingga kuning keemasan, sajikan.',
    ],
    tags: ['karipap', 'kari', 'Melayu', 'kentang', 'rempah'],
    rating: 4.5,
  },
  {
    id: 'kroket-kentang',
    name: 'Kroket',
    description:
      'Kroket kentang berisi daging ragout yang renyah di luar dan lembut di dalam. Camilan Belanda-Indo yang klasik.',
    image: '🥔',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 25,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Kentang rebus', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging sapi cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Wortel dadu kecil', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Telur kocok (pencelup)', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Tepung panir', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan kentang rebus, campurkan dengan pala bubuk, garam, dan merica.',
      'Tumis bawang putih, masukkan daging cincang hingga berubah warna.',
      'Tambahkan wortel, masak sebentar. Angkat, dinginkan.',
      'Ambil adonan kentang, pipihkan. Berisi tumisan daging.',
      'Bulatkan membentuk kroket, celupkan ke telur kocok.',
      'Gulingkan di tepung panir hingga rata.',
      'Goreng hingga kuning keemasan, sajikan.',
    ],
    tags: ['kroket', 'kentang', 'daging', 'Belanda-Indo', 'renyah'],
    rating: 4.6,
  },
  {
    id: 'nem-ragi',
    name: 'Nem',
    description:
      'Nem (spring roll) goreng berisi bihun, sayuran, dan telur. Camilan khas Semarang yang gurih dan renyah.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Kulit lumpia', amount: 12, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Bihun', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur rebus', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Kol iris halus', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Wortel iris korek api', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 1, unit: 'batang', category: 'Sayuran' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Rebus bihun, tiriskan dan potong-potong.',
      'Tumis bawang putih hingga harum.',
      'Masukkan kol, wortel, dan bihun. Bumbui garam dan merica.',
      'Tambahkan telur rebus yang dicincang dan daun bawang. Aduk rata.',
      'Dinginkan isian.',
      'Ambil kulit lumpia, beri 1 sdm isian. Gulung rapat.',
      'Goreng hingga kuning keemasan dan renyah.',
    ],
    tags: ['nem', 'spring roll', 'Semarang', 'goreng', 'gurih'],
    rating: 4.4,
  },
  {
    id: 'sosis-solo',
    name: 'Sosis Solo',
    description:
      'Sosis goreng dari adonan daging cincang dibungkus kulit telur dadar. Camilan khas Solo yang gurih dan empuk.',
    image: '🌭',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 25,
    servings: 4,
    calories: 270,
    ingredients: [
      { name: 'Daging sapi cincang', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Telur', amount: 5, unit: 'butir', category: 'Protein' },
      { name: 'Tepung terigu', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kelapa parut', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 200, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang merah dan bawang putih.',
      'Tumis bumbu halus, masukkan daging cincang. Masak hingga matang.',
      'Tambahkan kelapa parut, garam, dan merica. Aduk rata, angkat.',
      'Untuk kulit: kocok telur dengan tepung terigu dan sedikit air.',
      'Buat dadar tipis dari adonan telur sebagai kulit.',
      'Ambil selembar kulit dadar, berisi tumisan daging. Gulung rapat.',
      'Kukus 15 menit, lalu goreng sebentar hingga kecoklatan.',
    ],
    tags: ['sosis solo', 'Solo', 'daging', 'goreng', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'sosis-goreng-isi',
    name: 'Sosis Goreng Isi',
    description:
      'Sosis yang dibelah dan diisi keju serta cabai, dibalut tepung dan digoreng. Camilan modern yang gurih dan pedas.',
    image: '🌭',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Sosis sapi', amount: 4, unit: 'batang', category: 'Protein' },
      { name: 'Keju parut', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Cabai rawit iris', amount: 4, unit: 'buah', category: 'Isian' },
      { name: 'Tepung terigu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Tepung panir', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Belah sosis memanjang tanpa putus.',
      'Isi celah sosis dengan keju parut dan cabai rawit iris.',
      'Campurkan tepung terigu, telur, dan sedikit air menjadi adonan encer.',
      'Celupkan sosis ke adonan tepung.',
      'Gulingkan di tepung panir hingga rata.',
      'Goreng dalam minyak panas hingga kuning keemasan.',
      'Potong-potong, sajikan dengan saus sambal atau tomat.',
    ],
    tags: ['sosis', 'keju', 'goreng', 'pedas', 'modern'],
    rating: 4.4,
  },
  {
    id: 'nasi-goreng-bungkus',
    name: 'Nasi Goreng Bungkus',
    description:
      'Nasi goreng kecil dibungkus daun pisang atau kertas minyak. Camilan praktis yang gurih dan mengenyangkan.',
    image: '🍘',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kerupuk', amount: 8, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Daun pisang', amount: 4, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang halus bawang putih dan bawang merah.',
      'Tumis bumbu halus dan cabai rawit hingga harum.',
      'Masukkan nasi dingin, aduk dengan api besar.',
      'Tambahkan kecap manis, garam, dan merica. Aduk rata.',
      'Orak-arik telur ke dalam nasi goreng.',
      'Ambil porsi kecil, bungkus dengan daun pisang.',
      'Sajikan dengan kerupuk.',
    ],
    tags: ['nasi goreng', 'bungkus', 'praktis', 'gurih', 'street food'],
    rating: 4.3,
  },
  {
    id: 'nasi-kucing-komplit',
    name: 'Nasi Kucing Komplit',
    description:
      'Nasi kucing berbagai rasa: sambal, orek, suwir, dan dadar. Camilan murah meriah khas Jogja yang lengkap.',
    image: '🍚',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'Nasi putih', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Teri nasi', amount: 50, unit: 'gram', category: 'Protein' },
      { name: 'Tempe', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Ayam suwir', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun pisang', amount: 8, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Tumis bawang merah dan cabai rawit hingga harum.',
      'Buat sambal teri dari tumisan bumbu dengan teri nasi.',
      'Buat orek tempe dengan bumbu kecap manis.',
      'Sisir ayam suwir dengan bumbu sederhana.',
      'Ambil sejumput nasi, tata di daun pisang.',
      'Variasikan topping: sambal teri, orek tempe, ayam suwir.',
      'Bungkus dan semat dengan lidi, sajikan.',
    ],
    tags: ['nasi kucing', 'Jogja', 'murah meriah', 'komplit', 'jajanan'],
    rating: 4.5,
  },
  {
    id: 'mie-kocok-bandung',
    name: 'Mie Kocok',
    description:
      'Mie kuning direbus disajikan dengan kuah kaki sapi, kikil, dan tauge. Camilan khas Bandung yang gurih dan hangat.',
    image: '🍜',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'Mie kuning', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kikil sapi', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih goreng', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Ebi sangrai', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Sambal', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Kecap manis', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus kikil sapi hingga empuk, potong-potong.',
      'Rebus air untuk kuah, masukkan bawang putih goreng dan ebi.',
      'Bumbui kuah dengan garam, merica, dan penyedap.',
      'Blansir tauge sebentar, tiriskan.',
      'Rebus mie kuning hingga matang, tiriskan.',
      'Tata mie di mangkuk, tambahkan kikil dan tauge.',
      'Siram kuah panas, tambahkan sambal, kecap, dan daun bawang.',
    ],
    tags: ['mie kocok', 'Bandung', 'kikil', 'kuah', 'hangat'],
    rating: 4.6,
  },
  {
    id: 'mie-celor-palembang',
    name: 'Mie Celor',
    description:
      'Mie kuning disajikan dengan kuah santan kelapa, udang, dan tauge. Camilan khas Palembang yang creamy dan gurih.',
    image: '🍜',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'Mie kuning besar', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Udang kupas', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kucai iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Ebi', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang goreng', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Tumis bawang putih halus dan ebi hingga harum.',
      'Masukkan udang kupas, masak hingga berubah warna.',
      'Tuang santan, bumbui garam dan merica. Masak hingga mendidih.',
      'Rebus tauge dan kucai sebentar, tiriskan.',
      'Rebus mie kuning hingga matang, tiriskan.',
      'Tata mie di mangkuk, tambahkan tauge, kucai, dan udang.',
      'Siram kuah santan panas, taburi bawang goreng.',
    ],
    tags: ['mie celor', 'Palembang', 'santan', 'udang', 'Palembang'],
    rating: 4.6,
  },
  {
    id: 'mie-ayam-bakso',
    name: 'Mie Ayam',
    description:
      'Mie kuning dengan topping ayam cincang bumbu kecap, bakso, dan pangsit. Camilan populer yang mengenyangkan.',
    image: '🍜',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Mie kuning', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam dada', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Bakso sapi', amount: 8, unit: 'buah', category: 'Protein' },
      { name: 'Pangsit goreng', amount: 8, unit: 'buah', category: 'Pelengkap' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Sawi hijau', amount: 100, unit: 'gram', category: 'Sayuran' },
    ],
    steps: [
      'Cincang halus dada ayam, tumis dengan bawang putih.',
      'Tambahkan kecap manis, garam, dan merica. Masak hingga matang.',
      'Rebus bakso sapi hingga mengambang.',
      'Rebus mie kuning hingga matang, tiriskan.',
      'Blansir sawi hijau sebentar.',
      'Tata mie di mangkuk, tambahkan topping ayam dan bakso.',
      'Siram kuah kaldu, tambahkan pangsit goreng dan daun bawang.',
    ],
    tags: ['mie ayam', 'bakso', 'kecap', 'populer', 'mengenyangkan'],
    rating: 4.7,
  },
  {
    id: 'pempek-lenjer',
    name: 'Pempek Lenjer',
    description:
      'Pempek lenjer (panjang) khas Palembang dari ikan tenggiri dan sagu. Camilan legendaris dengan cuka kuah yang segar.',
    image: '🐟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Ikan tenggiri fillet', amount: 250, unit: 'gram', category: 'Protein' },
      { name: 'Tepung sagu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air es', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Cuka pempek', amount: 100, unit: 'ml', category: 'Pelengkap' },
      { name: 'Gula merah', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan ikan tenggiri menggunakan food processor.',
      'Campurkan ikan halus dengan garam dan gula, uleni.',
      'Tambahkan air es dan tepung sagu sedikit demi sedikit. Uleni hingga kalis.',
      'Bentuk adonan menjadi bulat panjang (lenjer).',
      'Rebus dalam air mendidih hingga mengambang.',
      'Angkat, tiriskan. Goreng sebentar jika suka.',
      'Sajikan dengan kuah cuka pempek dan sambal.',
    ],
    tags: ['pempek', 'Palembang', 'ikan tenggiri', 'lenjer', 'cuka'],
    rating: 4.7,
  },
  {
    id: 'model-palembang',
    name: 'Model',
    description:
      'Pempek berbentuk mangkuk dari ikan tenggiri dengan kuah santan kuning. Camilan khas Palembang yang creamy.',
    image: '🥣',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 25,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'Ikan tenggiri fillet', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Tepung sagu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kunyit parut', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.75, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
    ],
    steps: [
      'Haluskan ikan tenggiri, campurkan dengan sagu, garam, dan gula.',
      'Cetak adonan mangkuk kecil menggunakan mangkuk kecil.',
      'Kukus selama 15 menit hingga matang.',
      'Untuk kuah: rebus santan dengan kunyit parut dan bawang putih halus.',
      'Bumbui kuah dengan garam. Masak hingga mendidih.',
      'Masukkan pempek model ke dalam kuah santan.',
      'Sajikan hangat dengan taburan daun bawang.',
    ],
    tags: ['model', 'Palembang', 'santan', 'ikan', 'kuah kuning'],
    rating: 4.5,
  },
  {
    id: 'beras-kencur-minuman',
    name: 'Beras Kencur',
    description:
      'Minuman tradisional dari beras dan kencur yang manis segar. Camilan sehat yang menyegarkan dan berkhasiat.',
    image: '🍵',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'Beras', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kencur', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu', amount: 4, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam beras selama 2 jam, tiriskan.',
      'Haluskan beras dan kencur menggunakan blender dengan sedikit air.',
      'Rebus air, masukkan adonan beras kencur.',
      'Masak hingga mendidih, aduk terus agar tidak menggumpal.',
      'Tambahkan gula merah dan garam, aduk hingga larut.',
      'Saring minuman, dinginkan.',
      'Sajikan dingin dengan es batu.',
    ],
    tags: ['beras kencur', 'jamu', 'tradisional', 'segar', 'sehat'],
    rating: 4.6,
  },
];
