import type { Recipe } from '@/types';

export const recipesMakanSiang2: Recipe[] = [
  {
    id: 'ikan-bakar-rica',
    name: 'Ikan Bakar Rica-Rica Manado',
    description:
      'Ikan bakar dengan bumbu rica-rica pedas khas Manado yang menggugah selera. Bumbu cabai dan tomat yang dibakar memberikan aroma smoky yang khas.',
    image: '🐠',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Ikan kembung atau tongkol', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Cabai merah besar', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 2, unit: 'buah', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan, belah punggung tidak putus. Lumuri dengan perasan jeruk nipis dan garam, diamkan 15 menit.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan jahe.',
      'Panaskan sedikit minyak, tumis bumbu halus bersama serai yang dimemarkan dan daun jeruk hingga harum.',
      'Masukkan tomat yang dipotong-potong, aduk hingga layu. Tambahkan garam dan gula merah.',
      'Balur ikan dengan setengah bumbu rica-rica. Bakar ikan di atas arang atau pemanggang sambil dioles sisa bumbu.',
      'Bakar hingga kedua sisi matang sempurna dengan warna kecoklatan.',
      'Sajikan dengan nasi putih hangat dan lalapan segar.',
    ],
    tags: ['ikan bakar', 'rica-rica', 'Manado', 'pedas', 'panggang'],
    rating: 4.7,
  },
  {
    id: 'ikan-kuah-kuning',
    name: 'Ikan Kuah Kuning Maluku',
    description:
      'Sup ikan berkuah kuning segar khas Maluku dengan rempah kunyit dan daun kunyit yang harum. Hidangan ringan yang cocok untuk makan siang.',
    image: '🥘',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Ikan tenggiri atau kakap', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Kunyit', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong ikan menjadi beberapa bagian, cuci bersih. Lumuri dengan perasan jeruk nipis dan garam.',
      'Haluskan kunyit, bawang merah, bawang putih, dan cabai rawit.',
      'Didihkan air dalam panci, masukkan bumbu halus, serai yang dimemarkan, daun kunyit, dan daun jeruk.',
      'Masak kuah hingga mendidih dan bumbu matang sekitar 10 menit.',
      'Masukkan potongan ikan, masak dengan api sedang hingga ikan matang.',
      'Bumbui dengan garam, koreksi rasa.',
      'Sajikan hangat dengan nasi putih dan sambal.',
    ],
    tags: ['ikan', 'kuah kuning', 'Maluku', 'sup', 'segar'],
    rating: 4.5,
  },
  {
    id: 'sambal-colo-colo',
    name: 'Sambal Colo-Colo Maluku',
    description:
      'Sambal segar khas Maluku dengan campuran cabai, tomat, bawang, dan perasan jeruk nipis. Cocok sebagai pendamping ikan bakar atau seafood.',
    image: '🌶️',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 4,
    calories: 45,
    ingredients: [
      { name: 'Cabai rawit', amount: 15, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Terasi bakar', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 10, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak kelapa', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Iris halus cabai rawit, cabai merah keriting, dan bawang merah.',
      'Potong dadu kecil tomat merah.',
      'Campurkan semua bahan iris dalam sebuah mangkuk.',
      'Tambahkan terasi bakar, garam, dan gula merah.',
      'Peras jeruk nipis dan tambahkan minyak kelapa.',
      'Aduk rata semua bahan, diamkan 5 menit agar bumbu meresap.',
      'Sajikan sebagai pelengkap ikan bakar, ikan goreng, atau seafood.',
    ],
    tags: ['sambal', 'colo-colo', 'Maluku', 'segar', 'pedas'],
    rating: 4.4,
  },
  {
    id: 'ikan-bakar-jimbaran',
    name: 'Ikan Bakar Jimbaran Bali',
    description:
      'Ikan bakar bumbu base genep khas Jimbaran Bali dengan aroma rempah yang kuat. Disajikan dengan sambal matah yang menyegarkan.',
    image: '🏝️',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 30,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'Ikan kakap atau snapper', amount: 600, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kemiri', amount: 4, unit: 'butir', category: 'Bumbu' },
      { name: 'Terasi', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Jeruk limau', amount: 2, unit: 'buah', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan, belah punggung. Lumuri jeruk limau dan garam, diamkan 15 menit.',
      'Haluskan bawang merah, bawang putih, cabai merah, cabai rawit, kunyit, jahe, kemiri, dan terasi.',
      'Tumis bumbu halus bersama serai yang dimemarkan dan daun jeruk hingga matang dan harum.',
      'Balur ikan dengan bumbu yang sudah dimasak, ratakan hingga merata.',
      'Bakar ikan di atas arang atau pemanggang, bolak-balik hingga matang sempurna.',
      'Sajikan dengan sambal matah dan nasi putih hangat.',
    ],
    tags: ['ikan bakar', 'Jimbaran', 'Bali', 'base genep', 'rempah'],
    rating: 4.8,
  },
  {
    id: 'nasi-campur-bali',
    name: 'Nasi Campur Bali',
    description:
      'Nasi putih dengan aneka lauk khas Bali seperti lawar, sate lilit, ayam betutu, dan sambal matah. Perpaduan rasa yang lengkap dan memuaskan.',
    image: '🎋',
    category: 'Makan Siang',
    difficulty: 'Susah',
    cookTime: 90,
    prepTime: 45,
    servings: 4,
    calories: 620,
    ingredients: [
      { name: 'Nasi putih', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam kampung', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Daging sapi giling', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Kelapa parut', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 4, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 6, unit: 'lembar', category: 'Bumbu' },
      { name: 'Terasi', amount: 2, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Masak nasi putih menggunakan rice cooker.',
      'Untuk lawar: tumis bumbu halus, masukkan daging giling, aduk hingga matang. Tambahkan kelapa parut, aduk rata.',
      'Untuk ayam: lumuri ayam dengan bumbu halus, kukus hingga empuk lalu panggang sebentar.',
      'Untuk sambal matah: iris halus bawang merah, cabai rawit, serai, dan daun jeruk. Siram minyak panas.',
      'Potong-potong ayam yang sudah matang.',
      'Tata nasi di piring, susun lawar, ayam, dan sate di sekeliling nasi.',
      'Sajikan dengan sambal matah dan kerupuk.',
    ],
    tags: ['nasi campur', 'Bali', 'lawar', 'komplit', 'tradisional'],
    rating: 4.9,
  },
  {
    id: 'soto-banjarmasin',
    name: 'Soto Banjar',
    description:
      'Soto ayam bening khas Banjarmasin dengan kuah susu yang gurih dan wangi ketumbar. Disajikan dengan perkedel kentang dan telur rebus.',
    image: '🍵',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Ayam potong', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Ketumbar', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Pala', amount: 0.5, unit: 'butir', category: 'Bumbu' },
      { name: 'Air', amount: 1000, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Telur rebus', amount: 4, unit: 'butir', category: 'Protein' },
      { name: 'Perkedel kentang', amount: 8, unit: 'buah', category: 'Pelengkap' },
      { name: 'Bawang goreng', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Seledri iris', amount: 2, unit: 'sendok makan', category: 'Sayuran' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, dan ketumbar.',
      'Rebus ayam dalam air hingga mendidih, buang buihnya.',
      'Masukkan bumbu halus, kayu manis, cengkeh, dan pala. Masak hingga ayam empuk.',
      'Angkat ayam, suwir-suwir dagingnya.',
      'Tuangkan susu cair ke kuah soto, aduk rata. Jangan sampai mendidih kuat agar susu tidak pecah.',
      'Bumbui garam dan merica, koreksi rasa.',
      'Tata suwiran ayam, telur rebus, dan perkedel di mangkuk. Siram kuah panas.',
      'Taburi bawang goreng, daun bawang, dan seledri iris.',
    ],
    tags: ['soto', 'Banjar', 'susu', 'ketumbar', 'hangat'],
    rating: 4.6,
  },
  {
    id: 'amparan-tatak',
    name: 'Amparan Tatak Kalimantan',
    description:
      'Kue lapis tradisional khas Kalimantan Selatan dari tepung beras dan santan dengan aroma pandan. Tekstur lembut dan legit cocok untuk teman makan siang.',
    image: '🟡',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 30,
    servings: 8,
    calories: 250,
    ingredients: [
      { name: 'Tepung beras', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Margarine', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
    ],
    steps: [
      'Sisir halus gula merah, larutkan dengan sedikit air panas lalu saring.',
      'Campurkan tepung beras, santan, larutan gula merah, telur, dan garam. Aduk rata.',
      'Blender daun pandan dengan sedikit santan, saring, masukkan ke adonan.',
      'Olesi loyang dengan margarin, tuang adonan setengah tinggi loyang.',
      'Kukus dalam kukusan panas selama 20 menit hingga setengah matang.',
      'Tuang sisa adonan, kukus kembali selama 25 menit hingga matang sempurna.',
      'Angkat, dinginkan, potong-potong dan sajikan.',
    ],
    tags: ['amparan tatak', 'Kalimantan', 'kue tradisional', 'santan', 'pandan'],
    rating: 4.3,
  },
  {
    id: 'ayam-taliwang',
    name: 'Ayam Taliwang Lombok',
    description:
      'Ayam bakar pedas khas Lombok dengan bumbu rica-rica dan plecing yang khas. Kelezatan kuliner Sasak yang terkenal hingga mancanegara.',
    image: '🐔',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 25,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Ayam kampung', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Cabai merah besar', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 15, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Terasi', amount: 2, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Tomat merah', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Jeruk limau', amount: 2, unit: 'buah', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Belah ayam jadi dua bagian, lumuri jeruk limau dan garam, diamkan 15 menit.',
      'Presto atau ungkep ayam hingga empuk selama 20 menit.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, terasi, tomat, kunyit, dan jahe.',
      'Tumis bumbu halus hingga matang dan harum. Tambahkan kecap manis dan garam.',
      'Balur ayam yang sudah empuk dengan bumbu taliwang hingga merata.',
      'Bakar ayam di atas arang atau pemanggang sambil sesekali dioles bumbu.',
      'Bakar hingga kedua sisi kecoklatan dan bumbu meresap.',
      'Sajikan dengan plecing kangkung dan nasi putih.',
    ],
    tags: ['ayam taliwang', 'Lombok', 'pedas', 'bakar', 'Sasak'],
    rating: 4.8,
  },
  {
    id: 'ayam-bakar-taliwang',
    name: 'Ayam Bakar Taliwang',
    description:
      'Varian ayam taliwang yang dibakar sempurna dengan olesan bumbu merah khas. Daging ayam yang empuk dengan kulit garing berbumbu pedas manis.',
    image: '🔥',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'Ayam kampung potong', amount: 800, unit: 'gram', category: 'Protein' },
      { name: 'Cabai merah keriting', amount: 12, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Kemiri', amount: 4, unit: 'butir', category: 'Bumbu' },
      { name: 'Terasi udang', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air kelapa', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Cuci bersih ayam, tiriskan.',
      'Sangrai kemiri, haluskan bersama cabai merah, cabai rawit, bawang merah, bawang putih, dan terasi.',
      'Panaskan minyak, tumis bumbu halus hingga harum. Masukkan kecap manis dan garam.',
      'Tuang air kelapa, masukkan ayam. Ungkep dengan api kecil hingga bumbu meresap dan air menyusut.',
      'Angkat ayam, tiriskan sebentar.',
      'Bakar ayam di atas arang atau pemanggang, bolak-balik hingga kecoklatan.',
      'Sajikan dengan nasi dan sambal plecing.',
    ],
    tags: ['ayam bakar', 'taliwang', 'Lombok', 'pedas', 'ungkep'],
    rating: 4.7,
  },
  {
    id: 'sate-pusu',
    name: 'Sate Pusu NTB',
    description:
      'Sate daging khas Sumbawa NTB yang dibumbui sederhana tapi memiliki cita rasa yang luar biasa. Disajikan dengan lontong dan kuah santan.',
    image: '🍡',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 35,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Daging sapi has dalam', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kemiri', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Terasi', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kelapa parut', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Lontong', amount: 4, unit: 'buah', category: 'Bahan Utama' },
    ],
    steps: [
      'Potong daging sapi berukuran kecil-kecil seukuran dadu.',
      'Haluskan bawang merah, bawang putih, cabai rawit, kemiri, dan terasi.',
      'Campurkan daging dengan bumbu halus dan garam, aduk rata. Diamkan 30 menit.',
      'Tusukkan daging ke tusuk sate bambu, padatkan.',
      'Bakar sate di atas arang sambil dibolak-balik hingga matang.',
      'Untuk kuah: rebus santan dengan sisa bumbu dan kelapa parut hingga mendidih.',
      'Sajikan sate pusu dengan lontong dan kuah santan hangat.',
    ],
    tags: ['sate pusu', 'NTB', 'Sumbawa', 'santan', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'spaghetti-bolognese',
    name: 'Spaghetti Bolognese',
    description:
      'Spaghetti dengan saus daging bolognese yang kaya rasa tomat dan rempah Italia. Menu fusion yang populer di restoran Indonesia.',
    image: '🍝',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    calories: 520,
    ingredients: [
      { name: 'Spaghetti', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging sapi giling', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat segar', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Saus tomat', amount: 200, unit: 'ml', category: 'Bumbu' },
      { name: 'Tomat pasta', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Oregano kering', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Keju parmesan', amount: 30, unit: 'gram', category: 'Pelengkap' },
      { name: 'Minyak zaitun', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Didihkan air berisi garam, rebus spaghetti hingga al dente. Tiriskan, sisihkan.',
      'Cincang halus bawang bombay dan bawang putih. Potong dadu tomat segar.',
      'Panaskan minyak zaitun, tumis bawang bombay dan bawang putih hingga harum.',
      'Masukkan daging sapi giling, aduk hingga berubah warna dan matang.',
      'Tambahkan tomat segar, saus tomat, tomat pasta, dan oregano. Aduk rata.',
      'Masak saus dengan api kecil selama 20 menit hingga mengental. Bumbui garam dan merica.',
      'Tata spaghetti di piring, siram saus bolognese. Taburi keju parmesan.',
    ],
    tags: ['spaghetti', 'bolognese', 'fusion', 'Italia', 'daging sapi'],
    rating: 4.6,
  },
  {
    id: 'nasi-goreng-udang',
    name: 'Nasi Goreng Udang Spesial',
    description:
      'Nasi goreng dengan udang segar dan bumbu kecap yang gurih. Menu makan siang yang praktis namun tetap lezat dan mengenyangkan.',
    image: '🦐',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 12,
    prepTime: 15,
    servings: 3,
    calories: 480,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Udang kupas', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk udang', amount: 6, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Acar timun', amount: 50, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang halus bawang merah, bawang putih, dan cabai merah.',
      'Panaskan minyak, tumis bumbu halus hingga harum.',
      'Masukkan udang, aduk hingga berubah warna.',
      'Orak-arik telur di sisi wajan, aduk bersama udang.',
      'Tambahkan nasi dingin, kecap manis, dan saus tiram. Aduk rata dengan api besar.',
      'Masukkan irisan daun bawang, aduk sebentar.',
      'Sajikan dengan kerupuk udang dan acar timun.',
    ],
    tags: ['nasi goreng', 'udang', 'kecap', 'cepat saji', 'seafood'],
    rating: 4.7,
  },
  {
    id: 'nasi-goreng-merah',
    name: 'Nasi Goreng Merah',
    description:
      'Nasi goreng khas Surabaya dengan warna merah dari saus tomat dan cabai. Rasa manis pedas yang khas menjadikannya favorit keluarga.',
    image: '❤️',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 3,
    calories: 460,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 500, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Udang kupas', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Saus tomat', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kerupuk', amount: 6, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Timun', amount: 1, unit: 'buah', category: 'Sayuran' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, dan cabai merah keriting.',
      'Panaskan minyak, tumis bumbu halus hingga harum.',
      'Masukkan udang dan telur, orak-arik hingga setengah matang.',
      'Tambahkan nasi dingin, aduk rata dengan api besar.',
      'Tuangkan saus tomat, kecap manis, dan saus tiram. Aduk hingga nasi berwarna merah rata.',
      'Masak hingga nasi terpisah dan sedikit kering.',
      'Sajikan dengan kerupuk, irisan timun, dan telur dadar.',
    ],
    tags: ['nasi goreng', 'merah', 'Surabaya', 'saus tomat', 'pedas'],
    rating: 4.6,
  },
  {
    id: 'nasi-goreng-terasi',
    name: 'Nasi Goreng Terasi',
    description:
      'Nasi goreng dengan aroma khas terasi yang menggugah selera. Perpaduan rasa gurih dan pedas yang nendang.',
    image: '🫙',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 12,
    servings: 2,
    calories: 440,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 350, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Terasi udang', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk', amount: 4, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, cabai rawit, dan terasi.',
      'Panaskan minyak, tumis bumbu halus hingga harum.',
      'Masukkan telur, orak-arik hingga setengah matang.',
      'Tambahkan nasi dingin, aduk rata dengan api besar.',
      'Tuang kecap manis, aduk hingga semua butiran nasi terbumbui rata.',
      'Masukkan irisan daun bawang, aduk sebentar.',
      'Sajikan dengan kerupuk dan pelengkap sesuai selera.',
    ],
    tags: ['nasi goreng', 'terasi', 'pedas', 'gurih', 'cepat saji'],
    rating: 4.5,
  },
  {
    id: 'mie-goreng-jawa',
    name: 'Mie Goreng Jawa',
    description:
      'Mie goreng dengan bumbu kecap dan sayuran khas Jawa yang sederhana namun lezat. Cita rasa rumahan yang selalu dirindukan.',
    image: '🍜',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 490,
    ingredients: [
      { name: 'Mie kuning basah', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Sawi hijau', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk', amount: 6, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Bawang goreng', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus mie kuning sebentar, tiriskan.',
      'Cincang bumbu, iris sawi dan kol.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan telur, orak-arik sebentar.',
      'Tambahkan sawi, kol, dan mie. Tuang kecap manis.',
      'Aduk rata dengan api besar hingga matang.',
      'Sajikan dengan kerupuk dan taburan bawang goreng.',
    ],
    tags: ['mie goreng', 'Jawa', 'kecap', 'sederhana', 'populer'],
    rating: 4.5,
  },
  {
    id: 'mie-goreng-seafood',
    name: 'Mie Goreng Seafood',
    description:
      'Mie goreng dengan aneka seafood segar seperti udang, cumi, dan sayuran. Menu makan siang spesial yang bergizi tinggi.',
    image: '🦑',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 510,
    ingredients: [
      { name: 'Mie kuning basah', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Udang kupas', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Cumi-cumi', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Sawi hijau', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Wortel', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
    ],
    steps: [
      'Rebus mie kuning sebentar, tiriskan.',
      'Bersihkan cumi, potong-potong. Cuci udang.',
      'Cincang bumbu, iris sayuran.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan udang dan cumi, aduk hingga berubah warna.',
      'Orak-arik telur, masukkan mie, kecap manis, dan saus tiram. Aduk rata.',
      'Tambahkan sawi dan wortel, masak sebentar hingga layu.',
      'Sajikan dengan taburan daun bawang dan pelengkap.',
    ],
    tags: ['mie goreng', 'seafood', 'udang', 'cumi', 'spesial'],
    rating: 4.7,
  },
  {
    id: 'kwetiau-goreng',
    name: 'Kwetiau Goreng',
    description:
      'Kwetiau goreng yang lembut dan gurih dengan isian sayuran dan seafood. Hidangan peranakan yang populer di seluruh Indonesia.',
    image: '🥡',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 12,
    prepTime: 10,
    servings: 3,
    calories: 470,
    ingredients: [
      { name: 'Kwetiau basah', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Udang kupas', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Sawi hijau', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk', amount: 5, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam kwetiau basah sebentar, tiriskan.',
      'Cincang bumbu, iris sawi dan kol.',
      'Panaskan minyak, tumis bumbu halus hingga harum.',
      'Masukkan udang, aduk hingga berubah warna.',
      'Orak-arik telur, masukkan kwetiau, kecap manis, dan saus tiram.',
      'Aduk rata dengan api besar, tambahkan sayuran.',
      'Masak hingga kwetiau terbumbui dan sayuran layu.',
      'Sajikan dengan kerupuk dan acar.',
    ],
    tags: ['kwetiau', 'goreng', 'peranakan', 'seafood', 'kecap'],
    rating: 4.5,
  },
  {
    id: 'bihun-goreng',
    name: 'Bihun Goreng',
    description:
      'Bihun goreng dengan bumbu kecap yang gurih dan isian sayuran yang renyah. Menu sederhana yang cocok untuk makan siang sehari-hari.',
    image: '🥢',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 350,
    ingredients: [
      { name: 'Bihun jagung', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Sawi hijau', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Wortel', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang', amount: 1, unit: 'batang', category: 'Sayuran' },
    ],
    steps: [
      'Rendam bihun dalam air panas selama 5 menit, tiriskan.',
      'Cincang bumbu, iris tipis sayuran.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan telur, orak-arik sebentar.',
      'Tambahkan sayuran, aduk hingga layu.',
      'Masukkan bihun, kecap manis, dan saus tiram. Aduk rata.',
      'Masak dengan api besar hingga bumbu meresap.',
      'Sajikan dengan kerupuk dan taburan daun bawang.',
    ],
    tags: ['bihun', 'goreng', 'kecap', 'sederhana', 'sayuran'],
    rating: 4.3,
  },
  {
    id: 'nasi-goreng-kari',
    name: 'Nasi Goreng Kari',
    description:
      'Nasi goreng dengan cita rasa kari yang creamy dan wangi rempah. Perpaduan unik antara nasi goreng Indonesia dan kari Asia Tenggara.',
    image: '🍛',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 12,
    prepTime: 10,
    servings: 3,
    calories: 490,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 450, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Udang kupas', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bumbu kari siap pakai', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Santan', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Sawi hijau', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kerupuk', amount: 6, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Bawang goreng', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang bawang merah dan bawang putih.',
      'Panaskan minyak, tumis bumbu halus dan bumbu kari hingga harum.',
      'Masukkan udang, aduk hingga berubah warna.',
      'Orak-arik telur, masukkan nasi dingin.',
      'Tuang santan, aduk rata dengan api besar.',
      'Tambahkan sawi hijau, masak hingga kuah menyusut.',
      'Sajikan dengan kerupuk dan taburan bawang goreng.',
    ],
    tags: ['nasi goreng', 'kari', 'santan', 'rempah', 'fusion'],
    rating: 4.5,
  },
  {
    id: 'nasi-goreng-kepiting',
    name: 'Nasi Goreng Kepiting',
    description:
      'Nasi goreng premium dengan daging kepiting yang manis dan gurih. Menu spesial yang sering ditemukan di restoran seafood.',
    image: '🦀',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 520,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 450, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging kepiting', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk udang', amount: 6, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang halus bumbu, iris daun bawang.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan daging kepiting, aduk hingga matang.',
      'Orak-arik telur, masukkan nasi dingin.',
      'Tambahkan kecap manis dan saus tiram, aduk rata.',
      'Masukkan irisan daun bawang, aduk sebentar.',
      'Sajikan dengan kerupuk udang dan acar.',
    ],
    tags: ['nasi goreng', 'kepiting', 'seafood', 'premium', 'kecap'],
    rating: 4.7,
  },
  {
    id: 'nasi-goreng-putih',
    name: 'Nasi Goreng Putih',
    description:
      'Nasi goreng sederhana tanpa kecap dengan garam dan merica sebagai bumbu utama. Rasa original nasi goreng yang tidak kalah lezat.',
    image: '🍚',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 8,
    prepTime: 8,
    servings: 2,
    calories: 380,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 350, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk', amount: 4, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang halus bawang putih dan bawang merah.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan telur, orak-arik hingga setengah matang.',
      'Tambahkan nasi dingin, aduk rata dengan api besar.',
      'Bumbui garam dan merica, aduk hingga nasi terpisah.',
      'Masukkan irisan daun bawang, aduk sebentar.',
      'Sajikan dengan kerupuk dan pelengkap.',
    ],
    tags: ['nasi goreng', 'putih', 'sederhana', 'tanpa kecap', 'cepat saji'],
    rating: 4.2,
  },
  {
    id: 'nasi-goreng-atali',
    name: 'Nasi Goreng Ati Ampela',
    description:
      'Nasi goreng dengan ati ampela ayam yang bumbu dan gurih. Lauk klasik yang selalu jadi favorit pecinta jeroan.',
    image: '🍗',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    calories: 470,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 450, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ati ampela ayam', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Kerupuk', amount: 6, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus ati ampela hingga empuk, potong-potong.',
      'Cincang bumbu, iris daun bawang.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan ati ampela, aduk hingga sedikit kecoklatan.',
      'Orak-arik telur, masukkan nasi dingin.',
      'Tambahkan kecap manis dan saus tiram, aduk rata.',
      'Masukkan daun bawang, aduk sebentar.',
      'Sajikan dengan kerupuk dan acar.',
    ],
    tags: ['nasi goreng', 'ati ampela', 'jeroan', 'kecap', 'gurih'],
    rating: 4.6,
  },
  {
    id: 'tumis-tahu-telur',
    name: 'Tumis Tahu Telur',
    description:
      'Tumis sederhana tahu dan telur dengan bumbu kecap yang gurih. Lauk harian yang ekonomis tapi tetap lezat untuk keluarga.',
    image: '🥚',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 12,
    prepTime: 8,
    servings: 3,
    calories: 250,
    ingredients: [
      { name: 'Tahu putih', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 1, unit: 'batang', category: 'Sayuran' },
    ],
    steps: [
      'Potong tahu menjadi dadu, goreng sebentar hingga kuning kecoklatan.',
      'Cincang bumbu, iris daun bawang.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan telur, orak-arik hingga setengah matang.',
      'Tambahkan tahu goreng, kecap manis, dan saus tiram.',
      'Aduk rata, bumbui garam secukupnya.',
      'Masukkan irisan daun bawang, aduk sebentar.',
      'Sajikan dengan nasi putih hangat.',
    ],
    tags: ['tumis', 'tahu', 'telur', 'sederhana', 'ekonomis'],
    rating: 4.3,
  },
  {
    id: 'tumis-tempe-kecap',
    name: 'Tumis Tempe Kecap',
    description:
      'Tumis tempe dengan bumbu kecap manis yang manis gurih dan cabai rawit pedas. Lauk rumahan yang sederhana tapi nagih.',
    image: '🫘',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 8,
    servings: 3,
    calories: 230,
    ingredients: [
      { name: 'Tempe', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 10, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Potong tempe berbentuk dadu atau memanjang.',
      'Goreng tempe sebentar hingga setengah kering, angkat tiriskan.',
      'Iris tipis bawang merah, potong-potong cabai.',
      'Panaskan sedikit minyak, tumis bumbu hingga harum.',
      'Masukkan tempe goreng, aduk rata.',
      'Tambahkan kecap manis, garam, dan gula merah.',
      'Masak dengan api sedang hingga bumbu meresap.',
      'Angkat dan sajikan dengan nasi putih.',
    ],
    tags: ['tempe', 'tumis', 'kecap', 'pedas', 'rumahan'],
    rating: 4.4,
  },
  {
    id: 'oseng-buncis',
    name: 'Oseng Buncis',
    description:
      'Oseng buncis dengan bumbu cabai dan terasi yang gurih pedas. Tumis sayuran sederhana yang segar dan cocok sebagai lauk.',
    image: '🫛',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 3,
    calories: 140,
    ingredients: [
      { name: 'Buncis', amount: 300, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Terasi', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 10, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Potong serong buncis, cuci bersih.',
      'Iris tipis bawang merah, cincang bawang putih, potong cabai.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan buncis, aduk rata.',
      'Tambahkan terasi, garam, dan gula merah.',
      'Tumis dengan api besar hingga buncis matang tapi tetap renyah.',
      'Angkat, sajikan dengan nasi putih dan lauk lainnya.',
    ],
    tags: ['oseng', 'buncis', 'sayuran', 'sederhana', 'pedas'],
    rating: 4.2,
  },
  {
    id: 'oseng-maos',
    name: 'Oseng Maos',
    description:
      'Oseng khas Banyumas dengan daun maos (daun kecombrang) yang memberikan aroma khas dan rasa segar. Sayuran tradisional yang unik.',
    image: '🌿',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 12,
    prepTime: 15,
    servings: 3,
    calories: 170,
    ingredients: [
      { name: 'Daun maos (kecombrang)', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Buncis', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Terasi', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 10, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Petik daun maos, cuci bersih dan potong-potong.',
      'Potong serong buncis, iris tipis bumbu.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan buncis, tumis sebentar.',
      'Tambahkan daun maos, aduk rata.',
      'Bumbui terasi, garam, dan gula merah.',
      'Tumis hingga sayuran layu namun tetap segar.',
      'Angkat dan sajikan dengan nasi hangat.',
    ],
    tags: ['oseng', 'maos', 'kecombrang', 'Banyumas', 'tradisional'],
    rating: 4.1,
  },
  {
    id: 'tumis-toge',
    name: 'Tumis Toge',
    description:
      'Tumis toge (tauge) dengan bawang putih dan kecap yang sederhana tapi lezat. Lauk sayuran ekonomis yang cocok untuk makan sehari-hari.',
    image: '🌱',
    category: 'Makan Siang',
    difficulty: 'Mudah',
    cookTime: 8,
    prepTime: 8,
    servings: 2,
    calories: 120,
    ingredients: [
      { name: 'Toge (tauge)', amount: 250, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Cuci toge, buang ujung akarnya.',
      'Cincang halus bawang putih dan bawang merah, potong cabai.',
      'Panaskan minyak, tumis bumbu hingga harum.',
      'Masukkan toge, aduk rata dengan api besar.',
      'Tambahkan kecap manis dan garam, aduk cepat.',
      'Masak sebentar saja agar toge tetap renyah.',
      'Angkat dan sajikan segera.',
    ],
    tags: ['tumis', 'toge', 'tauge', 'sederhana', 'segar'],
    rating: 4.0,
  },
  {
    id: 'asem-asem-banyuwangi',
    name: 'Asem-Asem Banyuwangi',
    description:
      'Tulang sapi atau iga yang dimasak dengan kuah asem segar khas Banyuwangi. Kuah bening yang asam segar dengan daging sapi yang empuk.',
    image: '🍖',
    category: 'Makan Siang',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 15,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Tulang sapi atau iga', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Asem jawa', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 1200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Sambal terasi', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus tulang sapi hingga empuk, buang buihnya.',
      'Larutkan asem jawa dengan sedikit air, saring ambil airnya.',
      'Haluskan bawang merah, bawang putih, dan cabai rawit.',
      'Tumis bumbu halus bersama daun salam dan serai hingga harum.',
      'Masukkan tumisan bumbu ke rebusan tulang sapi.',
      'Tambahkan air asem, garam, dan gula merah. Masak hingga mendidih.',
      'Koreksi rasa, sajikan dengan toge rebus dan sambal terasi.',
    ],
    tags: ['asem-asem', 'Banyuwangi', 'tulang sapi', 'asam', 'segar', 'tradisional'],
    rating: 4.3,
  },
];