import type { Recipe } from '@/types';

export const recipesSnack: Recipe[] = [
  {
    id: 'risoles',
    name: 'Risoles Ragout',
    description:
      'Risoles goreng berisi ragout sayuran dan daging ayam yang gurih. Camilan populer yang renyah di luar dan lembut di dalam.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Kulit risoles (beli jadi)', amount: 15, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Daging ayam cincang', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Wortel dadu kecil', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Kentang rebus', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang bombay iris', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Telur kocok (pencelup)', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Tepung panir', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Tumis bawang bombay dan bawang putih hingga harum.',
      'Masukkan ayam cincang, aduk hingga berubah warna.',
      'Tambahkan wortel dan kentang halus, aduk rata.',
      'Tuang susu, bumbui garam, merica, dan gula. Masak hingga kental dan mengental.',
      'Ambil kulit risoles, isi 1 sdm ragout. Lipat segitiga, rekatkan tepi.',
      'Celupkan ke telur kocok, gulingkan di tepung panir.',
      'Goreng hingga kuning keemasan. Tiriskan dan sajikan.',
    ],
    tags: ['risoles', 'ragout', 'goreng', 'camilan', 'populer'],
    rating: 4.6,
  },
  {
    id: 'pastel',
    name: 'Pastel Sayur',
    description:
      'Pastel goreng renyah berisi sayuran, telur rebus, dan bihun dengan bumbu gurih. Camilan tradisional yang mengenyangkan.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 25,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Tepung terigu', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Wortel iris korek api', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Bihun', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur rebus', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Untuk kulit: campurkan tepung, garam, margarin, dan air. Uleni hingga kalis. Diamkan 15 menit.',
      'Giling tipis adonan kulit, cetak bulat menggunakan mangkuk kecil.',
      'Rebus bihun, tiriskan. Potong-potong. Iris wortel korek api.',
      'Tumis bumbu halus hingga harum. Masukkan wortel, bihun, dan daun bawang. Bumbui.',
      'Ambil kulit pastel, isi campuran sayuran dan setengah telur rebus. Lipat dan rekatkan tepi.',
      'Goreng dalam minyak panas hingga kuning keemasan. Tiriskan.',
    ],
    tags: ['pastel', 'sayur', 'goreng', 'tradisional', 'camilan'],
    rating: 4.5,
  },
  {
    id: 'siomay',
    name: 'Siomay Bandung',
    description:
      'Siomay ikan tenggiri kukus disajikan dengan saus kacang pedas manis, kentang, tahu, dan kol. Camilan gurih khas Bandung.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'Ikan tenggiri fillet', amount: 250, unit: 'gram', category: 'Protein' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur putih', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Tahu putih', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Kentang', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Kol', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang tanah goreng', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan ikan tenggiri, campurkan dengan tepung tapioka, telur putih, garam, dan merica. Uleni hingga kalis.',
      'Ambil adonan, bentuk bulat lonjong. Rekatkan ke pangsi tahu dan irisan kentang.',
      'Kukus selama 15-20 menit hingga matang dan mengapung.',
      'Untuk saus: haluskan kacang tanah goreng dan cabai rawit.',
      'Tambahkan air panas, kecap manis, gula merah, dan garam. Aduk rata.',
      'Rebus kol dan kentang sebentar. Tata di piring.',
      'Siram saus kacang di atas siomay. Sajikan dengan jeruk limau.',
    ],
    tags: ['siomay', 'Bandung', 'ikan', 'kacang', 'kukus'],
    rating: 4.7,
  },
  {
    id: 'batagor',
    name: 'Batagor',
    description:
      'Bakso tahu goreng khas Bandung dengan adonan ikan tenggiri yang kenyal. Disajikan dengan saus kacang pedas manis.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 30,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Ikan tenggiri fillet', amount: 250, unit: 'gram', category: 'Protein' },
      { name: 'Tepung tapioka', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tahu putih besar', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Kacang tanah goreng', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan ikan tenggiri, campurkan dengan tepung tapioka, telur, garam, dan merica.',
      'Belah tahu menjadi dua bagian, isikan adonan ikan di sela-sela tahu.',
      'Goreng batagor dalam minyak panas hingga kuning kecoklatan.',
      'Buat adonan sisa menjadi bulat-bulat bakso goreng.',
      'Untuk saus: haluskan kacang tanah dan cabai rawit, tambahkan kecap manis dan air.',
      'Potong-potong batagor, siram saus kacang. Sajikan.',
    ],
    tags: ['batagor', 'Bandung', 'ikan', 'goreng', 'kacang'],
    rating: 4.7,
  },
  {
    id: 'cireng',
    name: 'Cireng Isi',
    description:
      'Cireng (aci goreng) renyah dari tepung tapioka dengan isian oncom atau keju. Camilan khas Bandung yang gurih.',
    image: '🟤',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Tepung tapioka', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air panas', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang putih goreng', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Oncom (untuk isi)', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung tapioka dan tepung terigu. Tuang air panas sedikit demi sedikit, uleni.',
      'Tambahkan bawang putih goreng halus, daun bawang, garam, dan merica. Uleni hingga kalis.',
      'Ambil sedikit adonan, pipihkan. Isi dengan oncom yang sudah ditumis.',
      'Bulatkan dan pipihkan kembali. Ulangi hingga adonan habis.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning kecoklatan.',
      'Angkat, tiriskan. Sajikan dengan saus sambal atau bumbu rujak.',
    ],
    tags: ['cireng', 'aci', 'goreng', 'Bandung', 'pedas'],
    rating: 4.5,
  },
  {
    id: 'lumpia-semarang',
    name: 'Lumpia Semarang',
    description:
      'Lumpia goreng renyah berisi rebung bambu dan udang dengan bumbu gurih manis. Jajanan khas Semarang yang legendaris.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 10,
    prepTime: 30,
    servings: 4,
    calories: 270,
    ingredients: [
      { name: 'Kulit lumpia', amount: 15, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Rebung bambu', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Udang kupas cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Daging ayam cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Rebus rebung bambu hingga empuk, tiriskan. Iris tipis.',
      'Tumis bumbu halus hingga harum. Masukkan ayam cincang dan udang.',
      'Tambahkan rebung, daun bawang, gula merah, garam, dan merica. Masak hingga bumbu meresap.',
      'Dinginkan isian.',
      'Ambil kulit lumpia, beri 1-2 sdm isian. Gulung rapat, rekatkan tepi dengan sedikit tepung encer.',
      'Goreng dalam minyak panas hingga kuning keemasan dan renyah.',
      'Tiriskan, sajikan dengan saus cabai atau sambal.',
    ],
    tags: ['lumpia', 'Semarang', 'rebung', 'goreng', 'legendaris'],
    rating: 4.8,
  },
  {
    id: 'serabi',
    name: 'Serabi Solo',
    description:
      'Serabi (pancake Indonesia) dari tepung beras yang lembut dan berpori. Dibuat di atas pan tanah liat tradisional.',
    image: '🥞',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Tepung beras', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kelapa parut sangrai (topping)', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Gula merah cair (kinca)', amount: 100, unit: 'ml', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung beras, ragi, gula, dan garam. Aduk rata.',
      'Tuang santan sedikit demi sedikit sambil diaduk hingga halus.',
      'Diamkan adonan selama 30 menit hingga mengembang. Tambahkan soda kue, aduk perlahan.',
      'Panaskan pan tanah liat (atau pan anti lengket) di atas api kecil.',
      'Tuang 1 sendok sayur adonan, ratakan. Tutup pan dan biarkan hingga pori-pori muncul dan permukaan kering.',
      'Angkat serabi, hidangkan dengan topping kelapa parut dan gula merah cair (kinca).',
    ],
    tags: ['serabi', 'Solo', 'tepong beras', 'kinca', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'bika-ambon',
    name: 'Bika Ambon',
    description:
      'Kue bolu berpori khas Medan dengan aroma pandan dan mentega. Tekstur lembut bersarang yang unik dan nikmat.',
    image: '🍰',
    category: 'Snack',
    difficulty: 'Susah',
    cookTime: 60,
    prepTime: 30,
    servings: 8,
    calories: 200,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 250, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Telur', amount: 6, unit: 'butir', category: 'Protein' },
      { name: 'Gula pasir', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Ragi instan', amount: 1.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Mentega', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Blender santan dengan daun pandan, saring ambil air hijaunya.',
      'Kocok telur dan gula hingga kental berwarna putih.',
      'Masukkan tepung terigu sedikit demi sedikit sambil diaduk perlahan.',
      'Tuang santan pandan, aduk rata. Tambahkan ragi, aduk perlahan.',
      'Diamkan adonan selama 1-2 jam hingga mengembang dan berbusa.',
      'Tambahkan mentega leleh, aduk perlahan.',
      'Tuang ke cetakan bika ambon yang sudah dipanaskan. Oven dengan api bawah 180°C selama 45-50 menit.',
    ],
    tags: ['bika ambon', 'Medan', 'pandan', 'berpori', 'tradisional'],
    rating: 4.7,
  },
  {
    id: 'onde-onde-snack',
    name: 'Onde-Onde Kacang Hijau',
    description:
      'Bola-bola adonan tepung berisi kacang hijau manis, dibalut wijen dan digoreng renyah. Jajan pasar favorit sepanjang masa.',
    image: '🟡',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 40,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang hijau (rebus, haluskan)', amount: 150, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah sisir', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Wijen putih', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Susu cair', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Air hangat', amount: 80, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Untuk isi: masak kacang hijau halus dengan gula merah hingga kalis dan bisa digelindingkan. Dinginkan, bulatkan.',
      'Campurkan tepung, ragi, gula, dan susu. Uleni dengan air hangat hingga kalis. Diamkan 30 menit.',
      'Ambil sedikit adonan, pipihkan. Isi dengan bola kacang hijau. Bulatkan rapat.',
      'Basahi bola dengan air, gulingkan di wijen hingga rata.',
      'Goreng dalam minyak dingin, nyalakan api sedang. Goreng sambil diaduk agar matang merata.',
      'Tiriskan setelah kuning keemasan. Sajikan.',
    ],
    tags: ['onde-onde', 'wijen', 'kacang hijau', 'jajan pasar', 'goreng'],
    rating: 4.6,
  },
  {
    id: 'kue-lapis',
    name: 'Kue Lapis Legit',
    description:
      'Kue lapis legit berlapis-lapis dengan aroma rempah spekuk. Tekstur padat dan kaya rasa, camilan favorit saat Imlek.',
    image: '🍰',
    category: 'Snack',
    difficulty: 'Susah',
    cookTime: 90,
    prepTime: 30,
    servings: 8,
    calories: 250,
    ingredients: [
      { name: 'Mentega', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir halus', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Telur', amount: 10, unit: 'butir', category: 'Protein' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kayu manis bubuk', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Cengkeh bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok mentega dan gula halus hingga lembut dan creamy.',
      'Masukkan telur satu per satu, kocok hingga mengembang.',
      'Ayak tepung terigu, masukkan sedikit demi sedikit sambil diaduk perlahan.',
      'Tambahkan susu kental manis, kayu manis, pala, dan cengkeh bubuk. Aduk rata.',
      'Tuang satu sendok sayur adonan ke loyang yang sudah diolesi mentega.',
      'Panggang selama 5 menit hingga set. Tuang lapis berikutnya, ulangi hingga adonan habis.',
      'Panggang lapis terakhir lebih lama hingga permukaan kecoklatan. Dinginkan sebelum dipotong.',
    ],
    tags: ['kue lapis', 'legit', 'spekuk', 'Imlek', 'rempah'],
    rating: 4.8,
  },
  {
    id: 'kue-cucur',
    name: 'Kue Cucur',
    description:
      'Kue tradisional dari tepung beras dan gula merah dengan bagian tengah yang mekar dan bersarang. Manis dan legit.',
    image: '🟤',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 190,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah sisir', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Larutkan gula merah dengan santan, rebus bersama daun pandan. Saring, dinginkan.',
      'Campurkan tepung beras ke larutan santan gula merah. Aduk rata hingga tidak bergerindil.',
      'Diamkan adonan selama 30 menit hingga gula merah mengendap di bawah.',
      'Panaskan minyak goreng dalam wajan datar dengan api kecil.',
      'Ambil endapan gula merah, tuang adonan di atasnya. Masak tanpa dibolak-balik.',
      'Tunggu hingga bagian tengah mekar bersarang dan permukaan kering.',
      'Angkat, tiriskan minyak. Sajikan.',
    ],
    tags: ['kue cucur', 'tradisional', 'gula merah', 'santan', 'merekah'],
    rating: 4.4,
  },
  {
    id: 'nagasari',
    name: 'Nagasari',
    description:
      'Kue tradisional dari tepung beras berisi irisan pisang raja, dibungkus daun pisang. Tekstur kenyal dan aroma pandan.',
    image: '🟢',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Pisang raja matang', amount: 3, unit: 'buah', category: 'Isian' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun pisang (pembungkus)', amount: 8, unit: 'lembar', category: 'Bahan Utama' },
    ],
    steps: [
      'Rebus santan bersama daun pandan, gula, dan garam hingga mendidih.',
      'Masukkan tepung beras sedikit demi sedikit sambil diaduk cepat.',
      'Aduk terus hingga adonan mengental dan meletus-letus.',
      'Potong pisang raja sepanjang 4 cm.',
      'Ambil selembar daun pisang, olesi tipis minyak.',
      'Letakkan irisan pisang, tuang 2 sdm adonan di atasnya.',
      'Bungkus dan lipat ujung-ujungnya. Kukus selama 20 menit hingga matang.',
    ],
    tags: ['nagasari', 'pisang', 'kenyal', 'tradisional', 'jajan pasar'],
    rating: 4.5,
  },
  {
    id: 'klepon-pandan',
    name: 'Klepon Pandan',
    description:
      'Klepon kenyal berwarna hijau pandan berisi gula merah cair, dibalut kelapa parut. Jajan pasar favorit yang meleleh di mulut.',
    image: '🟢',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Tepung ketan', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah sisir', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Kelapa parut sangrai', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Daun pandan/suji', amount: 5, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Air hangat', amount: 120, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Blender daun pandan/suji dengan sedikit air, saring ambil air hijaunya.',
      'Campurkan tepung ketan dengan air pandan hijau, uleni hingga kalis.',
      'Ambil sedikit adonan, pipihkan. Isi gula merah, bulatkan rapat.',
      'Rebus air mendidih. Masukkan klepon, masak hingga mengambang (±5 menit).',
      'Angkat, langsung gulingkan di kelapa parut sangrai.',
      'Sajikan dalam piring atau cup kecil.',
    ],
    tags: ['klepon', 'pandan', 'gula merah', 'ketan', 'jajan pasar'],
    rating: 4.7,
  },
  {
    id: 'dadar-gulung-snack',
    name: 'Dadar Gulung Kelapa',
    description:
      'Crepe hijau pandan berisi unti kelapa (kelapa parut + gula merah). Camilan manis tradisional yang nikmat.',
    image: '🥞',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 200, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Daun suji/pandan', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Untuk unti: masak kelapa parut dengan gula merah, daun pandan, dan garam hingga kering. Dinginkan.',
      'Blender daun suji dengan sedikit air, saring.',
      'Campurkan tepung, telur, santan, air suji, dan garam. Aduk rata, saring.',
      'Panaskan pan anti lengket, olesi tipis minyak. Tuang adonan tipis.',
      'Masak hingga matang, angkat. Ulangi hingga adonan habis.',
      'Ambil selembar dadar, isi 1 sdm unti kelapa. Gulung rapat.',
      'Sajikan sebagai camilan atau dengan secangkir teh.',
    ],
    tags: ['dadar gulung', 'unti kelapa', 'pandan', 'manis', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'lempeng-durian',
    name: 'Lempeng Durian',
    description:
      'Lempeng tipis berisi daging durian manis. Jajanan khas Medan dan Sumatera Barat yang harum dan lezat.',
    image: '🟡',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'Tepung terigu', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Daging durian', amount: 200, unit: 'gram', category: 'Isian' },
      { name: 'Santan', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung, telur, santan, gula, dan garam. Aduk rata hingga halus, saring.',
      'Panaskan pan anti lengket, olesi tipis minyak.',
      'Tuang 1 sendok sayur adonan, ratakan tipis memutar.',
      'Masak hingga permukaan kering dan tepi mengangkat.',
      'Letakkan daging durian di tengah lempeng, lipat menjadi setengah lingkaran.',
      'Angkat, ulangi hingga adonan habis. Sajikan hangat.',
    ],
    tags: ['lempeng', 'durian', 'Medan', 'manis', 'aromatik'],
    rating: 4.5,
  },
  {
    id: 'kue-talam',
    name: 'Kue Talam',
    description:
      'Kue dua lapis dari tepung beras dan santan dengan lapisan hijau pandan. Lembut, kenyal, dan manis gurih.',
    image: '🟩',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 15,
    servings: 6,
    calories: 190,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Blender daun pandan dengan 100ml santan, saring ambil air hijaunya.',
      'Campurkan tepung beras, tapioka, gula, dan garam.',
      'Tuang santan pandan hijau, aduk rata dan saring.',
      'Bagi adonan dua: satu bagian hijau, satu bagian putih.',
      'Tuang adonan hijau ke loyang yang sudah diolesi minyak. Kukus 15 menit.',
      'Tuang adonan putih di atasnya, kukus lagi 15 menit hingga matang.',
      'Dinginkan, potong-potong dan sajikan.',
    ],
    tags: ['kue talam', 'pandan', 'kukus', 'kenyal', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'kue-bolu-kukus',
    name: 'Kue Bolu Kukus',
    description:
      'Bolu kukus yang lembut dan mekar sempurna dengan aroma mentega. Camilan tradisional yang mudah dibuat di rumah.',
    image: '🍰',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'SP (emulsifier)', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Santan', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega leleh', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Vanili', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur, gula, dan SP hingga mengembang dan kental selama 10 menit.',
      'Masukkan tepung terigu sedikit demi sedikit sambil diaduk perlahan.',
      'Tambahkan santan, aduk rata.',
      'Masukkan mentega leleh dan vanili, aduk lipat perlahan.',
      'Olesi cetakan bolu kukus dengan minyak. Tuang adonan hingga 3/4 penuh.',
      'Kukus dengan api besar selama 15 menit. Jangan buka tutup selama proses mengukus.',
      'Angkat, dinginkan. Keluarkan dari cetakan.',
    ],
    tags: ['bolu kukus', 'merekah', 'lembut', 'praktis', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'wingko-babat',
    name: 'Wingko Babat',
    description:
      'Kue tradisional khas Semarang dari tepung ketan dan kelapa parut. Tekstur lembut dan legit dengan aroma kelapa.',
    image: '🟡',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 15,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'Tepung ketan', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Santan', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Margarine', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur dan gula hingga mengembang.',
      'Masukkan tepung ketan, kelapa parut, santan, dan garam. Aduk rata.',
      'Tambahkan margarin leleh, aduk rata.',
      'Diamkan adonan selama 15 menit.',
      'Tuang adonan ke cetakan wingko yang sudah diolesi margarin.',
      'Panggang dalam oven 180°C selama 15-20 menit hingga permukaan kecoklatan.',
      'Angkat, dinginkan dan keluarkan dari cetakan.',
    ],
    tags: ['wingko', 'Semarang', 'ketan', 'kelapa', 'legendaris'],
    rating: 4.6,
  },
  {
    id: 'martabak-telur-mini-snack',
    name: 'Martabak Telur Mini',
    description:
      'Martabak telur ukuran mini dengan kulit garing berisi telur, daging, dan daun bawang. Camilan gurih yang mudah dimakan.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'Kulit lumpia', amount: 12, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Daging sapi cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah iris', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 3, unit: 'batang', category: 'Sayuran' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 200, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Tumis bawang merah iris hingga harum, masukkan daging cincang. Masak hingga matang.',
      'Kocok telur, masukkan tumisan daging, daun bawang, garam, dan merica.',
      'Ambil kulit lumpia, beri 2 sdm adonan telur. Lipat segitiga, rekatkan tepi.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan.',
      'Angkat dan tiriskan.',
      'Sajikan dengan saus sambal atau acar timun.',
    ],
    tags: ['martabak', 'telur', 'mini', 'goreng', 'gurih'],
    rating: 4.5,
  },
  {
    id: 'rempeyek',
    name: 'Rempeyek Kacang',
    description:
      'Rempeyek renyah berisi kacang tanah dengan adonan tepung beras yang gurih. Camilan renyah yang cocok untuk teman nasi.',
    image: '🥜',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Kacang tanah', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang putih halus', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit iris', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun jeruk iris tipis', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Air', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Rendam kacang tanah dalam air hangat selama 30 menit. Tiriskan.',
      'Campurkan tepung beras, tapioka, bawang putih halus, cabai rawit, daun jeruk, dan garam.',
      'Tambahkan air sedikit demi sedikit, aduk rata hingga adonan encer.',
      'Ambil satu sendok sayur adonan, masukkan 5-6 butir kacang.',
      'Tuang ke minyak panas, goreng hingga renyah dan kecoklatan.',
      'Tiriskan di tisu dapur. Sajikan sebagai camilan atau lauk.',
    ],
    tags: ['rempeyek', 'kacang', 'renyah', 'gurih', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'tahu-crispy',
    name: 'Tahu Crispy',
    description:
      'Tahu goreng berbalut tepung crispy yang renyah dan gurih. Camilan sederhana yang disukai anak-anak maupun dewasa.',
    image: '🧈',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    calories: 190,
    ingredients: [
      { name: 'Tahu putih', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Bawang putih bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air es', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Potong tahu menjadi bentuk dadu atau segitiga.',
      'Campurkan tepung terigu, tapioka, garam, dan bawang putih bubuk.',
      'Tambahkan air es, aduk rata. Biarkan ada gumpalan-gumpalan kecil untuk tekstur crispy.',
      'Celupkan tahu ke adonan tepung, pastikan terlapisi rata.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan.',
      'Tiriskan di tisu dapur. Sajikan dengan saus sambal atau kecap.',
    ],
    tags: ['tahu', 'crispy', 'goreng', 'renyah', 'praktis'],
    rating: 4.4,
  },
  {
    id: 'tempe-mendoan',
    name: 'Tempe Mendoan',
    description:
      'Tempe tipis berbalut adonan tepung yang renyah di luar tapi tetap lembut di dalam. Camilan khas Banyumas yang gurih.',
    image: '🫘',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Tempe (potong tipis)', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 40, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Daun kucai iris', amount: 1, unit: 'sendok makan', category: 'Sayuran' },
      { name: 'Cabai rawit iris', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air es', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Potong tempe tipis-tipis (sekitar 0.5 cm).',
      'Campurkan tepung terigu, tepung beras, daun bawang, kucai, cabai rawit, dan garam.',
      'Tambahkan air es, aduk rata. Adonan harus agak kental.',
      'Celupkan potongan tempe ke adonan, pastikan terbalut rata.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning kecoklatan.',
      'Angkat, tiriskan. Sajikan dengan sambal kecap atau cabai rawit.',
    ],
    tags: ['tempe', 'mendoan', 'goreng', 'Banyumas', 'renyah'],
    rating: 4.5,
  },
  {
    id: 'gorengan-bakwan',
    name: 'Bakwan Sayur',
    description:
      'Bakwan goreng berisi sayuran segar seperti kol, wortel, dan taoge. Gorengan favorit yang gurih dan renyah.',
    image: '🟤',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 170,
    ingredients: [
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kol iris halus', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Wortel parut', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Tauge', amount: 30, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Seledri iris', amount: 1, unit: 'sendok makan', category: 'Sayuran' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung terigu, garam, dan merica.',
      'Tambahkan air sedikit demi sedikit, aduk rata.',
      'Masukkan kol iris, wortel parut, tauge, daun bawang, dan seledri. Aduk rata.',
      'Ambil 1 sendok sayur adonan, tuang ke minyak panas.',
      'Goreng dengan api sedang hingga kuning kecoklatan dan renyah.',
      'Angkat, tiriskan. Sajikan dengan sambal kecap.',
    ],
    tags: ['bakwan', 'sayur', 'goreng', 'gorengan', 'populer'],
    rating: 4.4,
  },
  {
    id: 'sayur-godog',
    name: 'Sayur Godog',
    description:
      'Sayuran godog (rebus) khas Bali dengan bumbu genep yang harum dan gurih. Camilan sehat dari rebusan sayuran segar.',
    image: '🥬',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 150,
    ingredients: [
      { name: 'Labu siam', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Jagung manis', amount: 1, unit: 'bonggol', category: 'Sayuran' },
      { name: 'Kelapa parut', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, cabai rawit, dan kunyit.',
      'Tumis bumbu halus hingga harum, masukkan kelapa parut. Aduk rata.',
      'Tambahkan air secukupnya, didihkan.',
      'Masukkan jagung manis, masak sebentar.',
      'Tambahkan labu siam dan kacang panjang. Masak hingga sayuran empuk.',
      'Bumbui garam dan gula merah. Masak hingga kuah sedikit menyusut.',
      'Angkat, sajikan sebagai camilan atau lauk.',
    ],
    tags: ['sayur godog', 'Bali', 'kelapa', 'rebus', 'sehat'],
    rating: 4.3,
  },
  {
    id: 'kerupuk-kulit',
    name: 'Kerupuk Kulit Sapi',
    description:
      'Kerupuk dari kulit sapi yang digoreng hingga mengembang renyah. Camilan renyah gurih yang cocok untuk teman makan.',
    image: '🟡',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 0,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Kerupuk kulit sapi (beli jadi)', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 500, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Panaskan minyak goreng dalam jumlah banyak hingga benar-benar panas (suhu tinggi).',
      'Masukkan kerupuk kulit satu per satu agar tidak menempel.',
      'Kerupuk akan mengembang besar dalam hitungan detik.',
      'Balik sekali agar matang merata, jangan sampai gosong.',
      'Angkat, tiriskan di tisu dapur.',
      'Sajikan sebagai camilan atau teman nasi.',
    ],
    tags: ['kerupuk', 'kulit', 'sapi', 'renyah', 'gurih'],
    rating: 4.3,
  },
  {
    id: 'asinan-betawi',
    name: 'Asinan Betawi',
    description:
      'Asinan sayur dan buah khas Jakarta dengan kuah asam pedas yang menyegarkan. Camilan tradisional yang unik dan nagih.',
    image: '🥗',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 140,
    ingredients: [
      { name: 'Kol iris', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Tauge', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Timun iris', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Tahu putih', amount: 2, unit: 'buah', category: 'Protein' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Terasi', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Cuka', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Cuci bersih semua sayuran, tiriskan.',
      'Goreng tahu sebentar, potong-potong.',
      'Haluskan cabai rawit, bawang merah, dan terasi.',
      'Campurkan bumbu halus dengan cuka, gula merah, garam, dan 200ml air.',
      'Masukkan semua sayuran dan tahu ke dalam kuah bumbu.',
      'Aduk rata, diamkan di kulkas minimal 1 jam agar bumbu meresap.',
      'Sajikan dingin sebagai camilan segar.',
    ],
    tags: ['asinan', 'Betawi', 'asam pedas', 'segar', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'rujak-buah',
    name: 'Rujak Buah',
    description:
      'Aneka buah segar dengan bumbu rujak pedas manis dari gula merah dan cabai. Camilan tradisional yang menyegarkan.',
    image: '🌶️',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 4,
    calories: 150,
    ingredients: [
      { name: 'Mangga muda', amount: 1, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Nanas', amount: 0.5, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Jambu biji', amount: 1, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Bengkuang', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kedondong', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Terasi', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong-potong semua buah sesuai selera.',
      'Haluskan cabai rawit, gula merah, terasi, dan garam menggunakan cobek.',
      'Ulek hingga bumbu halus dan gula merah larut.',
      'Tambahkan sedikit air jika bumbu terlalu kental.',
      'Tata buah-buahan di piring saji.',
      'Siram atau sajikan bumbu rujak terpisah sebagai celupan.',
    ],
    tags: ['rujak', 'buah', 'pedas manis', 'segar', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'es-krim-kelapa',
    name: 'Es Krim Kelapa',
    description:
      'Es krim lembut dari santan kelapa dengan potongan kelapa muda. Dessert sekaligus camilan yang menyegarkan di cuaca panas.',
    image: '🍦',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 0,
    prepTime: 20,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daging kelapa muda', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Gelatin plain', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Rebus santan bersama daun pandan hingga mendidih. Angkat.',
      'Larutkan gelatin dengan 2 sdm air hangat.',
      'Campurkan santan panas, susu kental manis, gula, dan larutan gelatin. Aduk rata.',
      'Dinginkan adonan, masukkan ke freezer.',
      'Setelah setengah beku, keluarkan dan kocok dengan mixer selama 5 menit.',
      'Masukkan potongan kelapa muda. Kembalikan ke freezer.',
      'Bekukan hingga padat. Sajikan dalam cup atau cone.',
    ],
    tags: ['es krim', 'kelapa', 'segar', 'dingin', 'manis'],
    rating: 4.4,
  },
  {
    id: 'pisang-coklat',
    name: 'Pisang Coklat',
    description:
      'Pisang goreng crispy berisi lelehan coklat. Camilan manis yang praktis dan disukai anak-anak maupun dewasa.',
    image: '🍫',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Pisang raja matang', amount: 5, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Lembaran kulit lumpia', amount: 10, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Coklat batang/meses', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Tepung terigu (perekat)', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Air', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Kupas pisang, belah dua memanjang.',
      'Letakkan potongan coklat di atas pisang. Lipat pisang membungkus coklat.',
      'Bungkus dengan kulit lumpia. Rekatkan tepi menggunakan adonan tepung dan air.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan.',
      'Angkat, tiriskan di tisu dapur.',
      'Taburi gula pasir atau meses di atasnya. Sajikan selagi hangat.',
    ],
    tags: ['pisang', 'coklat', 'goreng', 'manis', 'anak-anak'],
    rating: 4.6,
  },
  {
    id: 'tahu-isi',
    name: 'Tahu Isi Sayur',
    description:
      'Tahu goreng berisi sayuran dan daging cincang yang gurih. Camilan sehat dan mengenyangkan dengan protein nabati.',
    image: '🧈',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Tahu putih lonjong', amount: 6, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Wortel dadu kecil', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol iris halus', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Daging ayam cincang', amount: 80, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Belah tahu menjadi dua bagian, kerok bagian tengahnya untuk membuat rongga.',
      'Tumis bumbu halus hingga harum. Masukkan ayam cincang, aduk hingga matang.',
      'Tambahkan wortel dan kol, masak sebentar. Bumbui garam dan merica.',
      'Isi rongga tahu dengan campuran sayuran. Rekatkan dengan sedikit adonan tepung.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning kecoklatan.',
      'Angkat, tiriskan. Sajikan dengan saus sambal.',
    ],
    tags: ['tahu', 'isi', 'sayur', 'goreng', 'sehat'],
    rating: 4.4,
  },
  {
    id: 'dimsum-ayam',
    name: 'Dimsum Ayam',
    description:
      'Dimsum ayam kukus yang lembut dan juicy dengan aroma bawang putih. Camilan yang sehat karena dikukus tanpa minyak.',
    image: '🥟',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 25,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Daging ayam giling', amount: 250, unit: 'gram', category: 'Protein' },
      { name: 'Udang kupas cincang', amount: 50, unit: 'gram', category: 'Protein' },
      { name: 'Kulit dimsum (beli jadi)', amount: 20, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang bombay cincang', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe parut', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Wortel parut', amount: 30, unit: 'gram', category: 'Sayuran' },
      { name: 'Minyak wijen', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan daging ayam giling, udang cincang, bawang putih, bawang bombay, dan jahe.',
      'Tambahkan saus tiram, kecap asin, minyak wijen, garam, dan merica. Aduk rata.',
      'Masukkan wortel parut, aduk perlahan.',
      'Ambil kulit dimsum, beri 1 sdm adonan. Lipat membentuk kantong. Ulangi.',
      'Olesi dasar kukusan dengan minyak. Tata dimsum di atasnya.',
      'Kukus selama 15-20 menit hingga matang.',
      'Sajikan dengan saus sambal, kecap, dan irisan jahe.',
    ],
    tags: ['dimsum', 'ayam', 'kukus', 'sehat', 'Tiongkok'],
    rating: 4.7,
  },
  {
    id: 'kue-cubit',
    name: 'Kue Cubit',
    description:
      'Kue kecil bertekstur lembut dengan topping coklat dan keju. Jajanan anak sekolah yang lembut dan manis.',
    image: '🧁',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    calories: 210,
    ingredients: [
      { name: 'Tepung terigu', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Susu cair', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Baking powder', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Margarine leleh', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Coklat chip/meses', amount: 30, unit: 'gram', category: 'Pelengkap' },
      { name: 'Keju parut', amount: 30, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Kocok telur dan gula hingga mengembang dan berwarna putih.',
      'Masukkan tepung terigu dan baking powder, aduk perlahan.',
      'Tambahkan susu cair dan margarin leleh. Aduk rata.',
      'Panaskan cetakan kue cubit, olesi sedikit margarin.',
      'Tuang adonan ke cetakan hingga 3/4 penuh.',
      'Taburi coklat chip atau keju parut di atasnya.',
      'Tutup cetakan, masak hingga permukaan kue kering. Angkat.',
    ],
    tags: ['kue cubit', 'manis', 'coklat', 'keju', 'anak-anak'],
    rating: 4.5,
  },
  {
    id: 'dorayaki',
    name: 'Dorayaki',
    description:
      'Kue pancake Jepang berlapis berisi selai kacang merah (anko). Camilan lembut dan manis yang disukai semua usia.',
    image: '🥞',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Madu', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Soda kue', amount: 0.5, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Air', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Selai kacang merah (anko)', amount: 100, unit: 'gram', category: 'Isian' },
    ],
    steps: [
      'Kocok telur dan gula hingga mengembang.',
      'Tambahkan madu, aduk rata.',
      'Masukkan tepung terigu dan soda kue, aduk perlahan.',
      'Tambahkan air, aduk rata hingga adonan halus. Diamkan 15 menit.',
      'Panaskan pan anti lengket, olesi sedikit minyak.',
      'Tuang satu sendok sayur adonan, buat bentuk bulat. Masak hingga gelembung muncul.',
      'Balik, masak sebentar. Angkat.',
      'Olesi satu sisi dorayaki dengan selai kacang merah. Tumpuk dengan dorayaki lain.',
    ],
    tags: ['dorayaki', 'Jepang', 'anko', 'pancake', 'manis'],
    rating: 4.5,
  },
  {
    id: 'piscok',
    name: 'Piscok (Pisang Coklat Keju)',
    description:
      'Roti tawar berisi pisang, coklat, dan keju yang dipanggang. Camilan manis gurih yang mudah dibuat.',
    image: '🍌',
    category: 'Snack',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    calories: 230,
    ingredients: [
      { name: 'Roti tawar', amount: 8, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Pisang raja matang', amount: 3, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Coklat batang/meses', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Keju parut', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Mentega', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Susu kental manis', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Olesi roti tawar dengan mentega.',
      'Iris tipis pisang, tata di atas roti.',
      'Taburi coklat batang parut dan keju.',
      'Beri sedikit susu kental manis.',
      'Gulung roti atau lipat menjadi setengah lingkaran.',
      'Panggang di pan anti lengket atau oven hingga kecoklatan dan keju meleleh.',
      'Angkat, potong-potong. Sajikan hangat.',
    ],
    tags: ['piscok', 'pisang', 'coklat', 'keju', 'panggang'],
    rating: 4.4,
  },
  {
    id: 'makaroni-panggang',
    name: 'Makaroni Panggang',
    description:
      'Makaroni rebus disiram saus keju creamy dan dipanggang hingga kecoklatan. Camilan pasta yang lezat dan mengenyangkan.',
    image: '🧀',
    category: 'Snack',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Makaroni elbow', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Keju cheddar parut', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Tepung terigu', amount: 1, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Sosis ayam iris', amount: 2, unit: 'batang', category: 'Protein' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus makaroni hingga al dente (setengah matang). Tiriskan.',
      'Lelehkan mentega, masukkan tepung terigu. Aduk cepat selama 1 menit.',
      'Tuang susu cair sedikit demi sedikit sambil terus diaduk hingga saus mengental.',
      'Masukkan setengah bagian keju parut, aduk hingga meleleh. Bumbui garam dan merica.',
      'Masukkan makaroni rebus dan sosis iris ke dalam saus keju. Aduk rata.',
      'Tuang ke dalam loyang yang sudah diolesi mentega.',
      'Taburi sisa keju parut di atasnya. Panggang oven 180°C selama 15 menit hingga kecoklatan.',
    ],
    tags: ['makaroni', 'panggang', 'keju', 'pasta', 'baking'],
    rating: 4.6,
  },
];
