import type { Recipe } from '@/types';

export const recipesSarapan: Recipe[] = [
  {
    id: 'lontong-sayur',
    name: 'Lontong Sayur',
    description:
      'Lontong padat disiram kuah santan kuning dengan sayur labu siam, kacang panjang, dan chayote. Sarapan tradisional yang mengenyangkan.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Beras (untuk lontong)', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Labu siam', amount: 200, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Santan kental', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah keriting', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Cuci beras, masukkan ke daun pisang yang dilipat membentuk silinder. Kukus selama 2 jam hingga lontong padat. Potong-potong.',
      'Potong dadu labu siam dan iris kacang panjang sepanjang 3 cm.',
      'Haluskan bawang merah, bawang putih, cabai, dan kunyit.',
      'Tumis bumbu halus bersama daun salam hingga harum.',
      'Tuangkan santan kental, masukkan labu siam. Masak hingga setengah matang.',
      'Tambahkan kacang panjang, bumbui garam. Masak hingga sayuran empuk dan kuah mengental.',
      'Tata lontong di piring, siram kuah sayur. Sajikan dengan kerupuk dan sambal.',
    ],
    tags: ['lontong', 'sayur', 'santan', 'sarapan', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'nasi-kuning',
    name: 'Nasi Kuning',
    description:
      'Nasi berwarna kuning cantik dari kunyit, dimasak dengan santan dan rempah. Sering disajikan dalam tumpeng untuk acara syukuran.',
    image: '🍚',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'Beras', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kunyit parut', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Cuci beras hingga bersih, tiriskan.',
      'Parut kunyit, peras ambil airnya. Campurkan dengan santan.',
      'Masukkan beras ke rice cooker, tuang campuran santan kunyit.',
      'Tambahkan daun salam, serai yang dimemarkan, dan daun jeruk. Bumbui garam.',
      'Masak seperti biasa hingga nasi matang. Aduk rata sebelum disajikan.',
      'Sajikan dengan lauk: ayam goreng, urap, perkedel, dan sambal.',
    ],
    tags: ['nasi', 'kuning', 'kunyit', 'tumpeng', 'sarapan'],
    rating: 4.7,
  },
  {
    id: 'bubur-sumsum',
    name: 'Bubur Sumsum',
    description:
      'Bubur halus dari tepung beras yang kenyal, disiram kuah gula merah cair. Sarapan manis tradisional yang lembut dan nikmat.',
    image: '🥣',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 10,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Tepung beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung beras dengan 200ml santan, aduk rata hingga tidak bergerindil.',
      'Panaskan sisa santan (300ml) dengan daun pandan dan sedikit garam hingga mendidih.',
      'Tuang adonan tepung beras ke santan mendidih, aduk terus hingga mengental dan meletus-letus.',
      'Angkat, tuang ke cetakan atau mangkuk kecil. Biarkan dingin.',
      'Untuk kuah: rebus gula merah dengan 200ml air hingga kental. Saring.',
      'Sajikan bubur sumsum dengan siraman kuah gula merah.',
    ],
    tags: ['bubur', 'sumsum', 'gula merah', 'manis', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'bubur-kacang-hijau',
    name: 'Bubur Kacang Hijau',
    description:
      'Bubur kacang hijau yang lembut dengan santan dan gula merah. Sarapan hangat yang kaya serat dan nutrisi.',
    image: '🫘',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 45,
    prepTime: 10,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'Kacang hijau', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 120, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 600, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Rendam kacang hijau selama minimal 2 jam (lebih baik semalam) hingga mengembang.',
      'Rebus kacang hijau dengan air hingga empuk dan pecah-pecah, sekitar 30-40 menit.',
      'Panaskan santan dengan daun pandan dan garam hingga mendidih. Angkat.',
      'Masak gula merah dengan 100ml air hingga larut dan kental, saring.',
      'Tuang santan ke dalam bubur kacang hijau, aduk rata.',
      'Sajikan hangat dengan siraman gula merah cair.',
    ],
    tags: ['bubur', 'kacang hijau', 'santan', 'manis', 'sehat'],
    rating: 4.6,
  },
  {
    id: 'nasi-lemak',
    name: 'Nasi Lemak',
    description:
      'Nasi yang dimasak dengan santan dan daun pandan, disajikan dengan sambal teri, kacang, telur, dan timun. Sarapan khas Melayu.',
    image: '🥥',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'Beras', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 350, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Teri medan', amount: 50, unit: 'gram', category: 'Protein' },
      { name: 'Kacang tanah goreng', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Telur rebus', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Timun iris', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Sambal', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci beras hingga bersih, tiriskan.',
      'Campurkan santan, ikat daun pandan, dan garam. Masukkan ke rice cooker bersama beras.',
      'Masak hingga matang. Aduk rata.',
      'Goreng teri medan hingga renyah. Sangrai kacang tanah.',
      'Rebus telur, belah dua. Iris tipis timun.',
      'Penyajian: cetak nasi lemak, taruh di daun pisang atau piring.',
      'Tata lauk: sambal teri, kacang tanah, telur rebus, dan irisan timun di sekeliling nasi.',
    ],
    tags: ['nasi', 'lemak', 'santan', 'Melayu', 'sarapan'],
    rating: 4.7,
  },
  {
    id: 'pecel-sayur',
    name: 'Pecel Sayur',
    description:
      'Aneka sayuran rebus disiram bumbu kacang khas Madiun. Sarapan sehat dan bergizi tinggi dengan rasa gurih dan sedikit pedas.',
    image: '🥗',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 320,
    ingredients: [
      { name: 'Kacang tanah goreng', amount: 200, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Kangkung', amount: 150, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kecipir', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Gula merah', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Kerupuk', amount: 5, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus air hingga mendidih. Blansir semua sayuran satu per satu selama 1 menit. Tiriskan.',
      'Haluskan kacang tanah goreng, cabai rawit, cabai merah, dan gula merah menggunakan cobek.',
      'Tambahkan sedikit air panas untuk mengencerkan bumbu kacang hingga kekentalan yang diinginkan.',
      'Bumbui garam secukupnya, aduk rata.',
      'Tata sayuran rebus di piring saji.',
      'Siram bumbu kacang di atas sayuran.',
      'Taburi kerupuk dan bawang goreng. Sajikan dengan nasi atau lontong.',
    ],
    tags: ['pecel', 'sayuran', 'kacang', 'sehat', 'Madiun'],
    rating: 4.5,
  },
  {
    id: 'roti-bakar-telur',
    name: 'Roti Bakar Telur',
    description:
      'Roti tawar dipanggang hingga kecoklatan, diisi telur dadar, selai, dan mentega. Sarapan praktis yang mengenyangkan.',
    image: '🍞',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 350,
    ingredients: [
      { name: 'Roti tawar', amount: 4, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Mentega', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Selai (coklat/strawberry)', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Keju parut', amount: 30, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Kocok lepas telur dengan garam.',
      'Olesi roti tawar dengan mentega, panggang di atas pan hingga kecoklatan kedua sisi.',
      'Buat telur dadar tipis di pan yang sama.',
      'Tata roti panggang, letakkan telur dadar di atasnya.',
      'Tambahkan selai dan taburi keju parut.',
      'Tutup dengan roti lainnya, potong diagonal. Sajikan hangat.',
    ],
    tags: ['roti', 'bakar', 'telur', 'praktis', 'cepat saji'],
    rating: 4.3,
  },
  {
    id: 'dadar-gulung-sarapan',
    name: 'Dadar Gulung Kelapa',
    description:
      'Crepe tipis berisi kelapa parut yang dimasak dengan gula merah. Sarapan manis tradisional yang nikmat dengan secangkir teh.',
    image: '🥞',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 1, unit: 'butir', category: 'Protein' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 200, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Untuk isi: masak kelapa parut dengan gula merah, daun pandan, dan sedikit garam di atas api kecil hingga kering dan gula larut rata. Angkat, dinginkan.',
      'Campurkan tepung terigu, telur, santan, dan garam. Aduk rata hingga tidak bergerindil. Saring.',
      'Tambahkan air perasan daun suji untuk warna hijau (opsional).',
      'Panaskan pan anti lengket, olesi tipis minyak. Tuang 1 sendok sayur adonan, ratakan tipis.',
      'Masak hingga matang dan tidak lengket. Angkat.',
      'Ambil satu lembar dadar, berisi 1 sdm unti kelapa. Gulung rapat. Ulangi hingga habis.',
    ],
    tags: ['dadar', 'gulung', 'kelapa', 'manis', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'omelet-sayur',
    name: 'Omelet Sayur',
    description:
      'Omelet lembut berisi aneka sayuran segar seperti wortel, jagung, dan bayam. Sarapan sehat yang kaya protein dan vitamin.',
    image: '🍳',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 8,
    prepTime: 10,
    servings: 2,
    calories: 220,
    ingredients: [
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Wortel parut', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Jagung manis pipil', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Bayam iris', amount: 30, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang merah iris', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur bersama garam dan merica bubuk.',
      'Tumis bawang merah iris hingga harum. Masukkan wortel parut dan jagung, tumis sebentar.',
      'Angkat tumisan sayur, masukkan ke dalam adonan telur. Tambahkan bayam iris.',
      'Panaskan minyak di pan anti lengket. Tuang adonan telur.',
      'Masak dengan api kecil hingga permukaan setengah matang.',
      'Lipat omelet menjadi dua. Masak sebentar lagi hingga matang sempurna.',
      'Sajikan dengan nasi putih hangat dan sambal.',
    ],
    tags: ['omelet', 'sayur', 'sehat', 'protein', 'praktis'],
    rating: 4.4,
  },
  {
    id: 'nasi-goreng-telur',
    name: 'Nasi Goreng Telur',
    description:
      'Nasi goreng sederhana dengan telur mata sapi dan kecap manis. Sarapan klasik yang cepat dibuat dan disukai semua orang.',
    image: '🍳',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 400,
    ingredients: [
      { name: 'Nasi putih dingin', amount: 350, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kerupuk', amount: 4, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Cincang halus bawang putih dan bawang merah.',
      'Panaskan minyak, tumis bumbu halus dan cabai rawit hingga harum.',
      'Masukkan nasi dingin, aduk rata dengan api besar.',
      'Tambahkan kecap manis, aduk hingga nasi terbalut rata.',
      'Sisir telur ke pinggir wajan, buat telur dadar terpisah atau orak-arik langsung di nasi.',
      'Aduk rata nasi dan telur. Angkat.',
      'Sajikan dengan kerupuk dan acar.',
    ],
    tags: ['nasi goreng', 'telur', 'sarapan', 'cepat saji', 'praktis'],
    rating: 4.5,
  },
  {
    id: 'nasi-pecel',
    name: 'Nasi Pecel',
    description:
      'Nasi putih disajikan dengan sayuran pecel, bumbu kacang, dan rempeyek. Sarapan tradisional Jawa yang sehat dan lezat.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 20,
    servings: 2,
    calories: 410,
    ingredients: [
      { name: 'Nasi putih', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang tanah goreng', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Kangkung', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kacang panjang', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Kenikir', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol iris', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Rempeyek', amount: 5, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Rebus air hingga mendidih. Blansir semua sayuran sebentar, tiriskan.',
      'Haluskan kacang tanah goreng bersama cabai rawit dan gula merah.',
      'Tambahkan air panas sedikit demi sedikit hingga bumbu kacang mencapai kekentalan yang diinginkan.',
      'Bumbui garam secukupnya, aduk rata.',
      'Tata nasi putih di piring.',
      'Tata sayuran rebus di samping nasi.',
      'Siram bumbu kacang di atas sayuran. Taburi rempeyek.',
    ],
    tags: ['pecel', 'nasi', 'kacang', 'sayuran', 'Jawa'],
    rating: 4.5,
  },
  {
    id: 'puding-roti',
    name: 'Puding Roti',
    description:
      'Puding lembut dari roti tawar, telur, dan susu. Sarapan manis yang bisa dipersiapkan malam sebelumnya.',
    image: '🍮',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'Roti tawar', amount: 6, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Telur', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Susu cair', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Mentega', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Raisin (kismis)', amount: 30, unit: 'gram', category: 'Pelengkap' },
      { name: 'Kayu manis bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Olesi loyang dengan mentega. Tata roti tawar yang sudah dipotong-potong di dasar loyang.',
      'Taburi raisin di atas roti secara merata.',
      'Kocok telur bersama gula pasir hingga mengembang.',
      'Tambahkan susu cair dan kayu manis bubuk, aduk rata.',
      'Tuang adonan susu telur ke atas roti. Biarkan meresap selama 10 menit.',
      'Panggang dalam oven 180°C selama 30 menit hingga permukaan kecoklatan.',
      'Angkat, dinginkan sebentar. Potong dan sajikan.',
    ],
    tags: ['puding', 'roti', 'manis', 'panggang', 'praktis'],
    rating: 4.4,
  },
  {
    id: 'smoothie-bowl',
    name: 'Smoothie Bowl',
    description:
      'Bowl smoothie buah segar yang kental, dihias granola, potongan buah, dan biji chia. Sarapan sehat modern yang instagramable.',
    image: '🫐',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 310,
    ingredients: [
      { name: 'Pisang beku', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Buah beri beku', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu almond', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Yogurt Greek', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Granola', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Biji chia', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Madu', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Blender pisang beku, buah beri beku, susu almond, dan yogurt hingga kental dan halus.',
      'Tuang smoothie ke dalam mangkuk.',
      'Hias dengan granola, potongan buah segar, dan biji chia.',
      'Siram madu di atasnya.',
      'Sajikan segera selagi dingin dan segar.',
    ],
    tags: ['smoothie', 'bowl', 'sehat', 'buah', 'modern'],
    rating: 4.5,
  },
  {
    id: 'granola-yogurt',
    name: 'Granola Yogurt',
    description:
      'Yogurt creamy dicampur granola renyah, madu, dan potongan buah segar. Sarapan sehat dan praktis tanpa perlu masak.',
    image: '🥣',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 0,
    prepTime: 5,
    servings: 2,
    calories: 280,
    ingredients: [
      { name: 'Yogurt plain', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Granola', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Pisang iris', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Blueberry', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Biji chia', amount: 1, unit: 'sendok teh', category: 'Pelengkap' },
    ],
    steps: [
      'Siapkan mangkuk saji.',
      'Tuang yogurt plain ke dalam mangkuk.',
      'Taburi granola secara merata di atas yogurt.',
      'Tambahkan irisan pisang dan blueberry.',
      'Siram madu dan taburi biji chia.',
      'Sajikan segera. Bisa disimpan di kulkas sebentar jika suka dingin.',
    ],
    tags: ['granola', 'yogurt', 'sehat', 'praktis', 'tanpa masak'],
    rating: 4.3,
  },
  {
    id: 'roti-canai',
    name: 'Roti Canai',
    description:
      'Roti pipih berlapis-lapis yang renyah di luar dan lembut di dalam. Diseduh dengan kuah kari atau dimakan langsung.',
    image: '🫓',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 40,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'Tepung terigu', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Air', amount: 80, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung terigu, garam, gula, susu, dan air. Uleni hingga kalis dan elastis.',
      'Bagi adonan menjadi 8 bagian bulat. Olesi permukaan dengan minyak, diamkan 1 jam.',
      'Ambil satu adonan, pipihkan dan olesi mentega. Lipat dan gulung membentuk spiral.',
      'Pipihkan kembali spiral adonan hingga tipis dan lebar.',
      'Panaskan pan anti lengket, olesi sedikit minyak. Panggang roti canai hingga kecoklatan kedua sisi.',
      'Angkat dan pukul-pukul agar berlapis. Sajikan dengan kuah kari atau gula.',
    ],
    tags: ['roti canai', 'berlapis', 'Melayu', 'panggang', 'sarapan'],
    rating: 4.6,
  },
  {
    id: 'martabak-telur-mini',
    name: 'Martabak Telur Mini',
    description:
      'Martabak telur ukuran kecil dengan kulit lumpia renyah berisi telur dan daging cincang. Sarapan gurih yang praktis.',
    image: '🥟',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'Kulit lumpia', amount: 10, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Daging sapi cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah iris', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun bawang iris', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 200, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Tumis bawang merah iris hingga harum, masukkan daging cincang. Masak hingga berubah warna, angkat.',
      'Kocok telur, masukkan tumisan daging, daun bawang, garam, dan merica.',
      'Ambil satu lembar kulit lumpia, beri 2 sdm adonan telur. Lipat segitiga, rekatkan tepi dengan sedikit adonan telur.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan.',
      'Angkat dan tiriskan.',
      'Sajikan dengan saus sambal atau acar timun.',
    ],
    tags: ['martabak', 'telur', 'mini', 'goreng', 'praktis'],
    rating: 4.5,
  },
  {
    id: 'soto-banjar',
    name: 'Soto Banjar',
    description:
      'Soto kuah bening khas Kalimantan Selatan dengan daging ayam, telur puyuh, perkedel, dan ketupat. Hangat dan gurih.',
    image: '🍲',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Ayam potong', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Pala', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kapulaga', amount: 2, unit: 'butir', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Air', amount: 1200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Perkedel kentang', amount: 8, unit: 'buah', category: 'Pelengkap' },
      { name: 'Telur puyuh rebus', amount: 8, unit: 'butir', category: 'Protein' },
      { name: 'Bawang goreng', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Haluskan bawang putih, bawang merah, jahe, dan kunyit.',
      'Didihkan air, masukkan ayam dan bumbu halus.',
      'Tambahkan pala, kapulaga, dan kayu manis. Masak hingga ayam empuk.',
      'Angkat ayam, suwir dagingnya. Kembalikan tulang ke kuah.',
      'Bumbui kuah dengan garam dan merica. Masak sebentar lagi.',
      'Sajikan kuah di mangkuk dengan suwiran ayam, perkedel, dan telur puyuh.',
      'Taburi bawang goreng dan irisan daun seledri. Sajikan dengan ketupat.',
    ],
    tags: ['soto', 'Banjar', 'Kalsel', 'rempah', 'hangat'],
    rating: 4.7,
  },
  {
    id: 'ketoprak',
    name: 'Ketoprak',
    description:
      'Tahu, tekwan, tauge, dan bihun disiram bumbu kacang dan kecap manis. Sarapan khas Jakarta yang gurih dan mengenyangkan.',
    image: '🥗',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 3,
    calories: 350,
    ingredients: [
      { name: 'Tahu putih', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Mie kuning', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tauge', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Ketupat/lontong', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Kacang tanah goreng', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang goreng', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Kerupuk', amount: 5, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Goreng tahu putih hingga kuning kecoklatan. Potong-potong.',
      'Rebus tauge sebentar, tiriskan. Rebus mie kuning, tiriskan.',
      'Haluskan kacang tanah goreng dan cabai rawit. Tambahkan air panas untuk mengencerkan.',
      'Bumbui bumbu kacang dengan garam dan gula merah, aduk rata.',
      'Potong ketupat, tata di piring saji.',
      'Tata tauge, mie kuning, dan tahu goreng di atas ketupat.',
      'Siram bumbu kacang dan kecap manis. Taburi bawang goreng dan kerupuk.',
    ],
    tags: ['ketoprak', 'kacang', 'tahu', 'Betawi', 'sarapan'],
    rating: 4.4,
  },
  {
    id: 'lupis',
    name: 'Lupis',
    description:
      'Ketan yang dibungkus daun pisang, dikukus, dan disajikan dengan kelapa parut serta gula merah cair. Sarapan tradisional yang manis.',
    image: '🟢',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 20,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'Beras ketan', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 150, unit: 'gram', category: 'Pelengkap' },
      { name: 'Gula merah', amount: 150, unit: 'gram', category: 'Pelengkap' },
      { name: 'Daun pisang', amount: 8, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 150, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Rendam beras ketan selama minimal 3 jam. Tiriskan.',
      'Ambil 2 lembar daun pisang, tata ketan memanjang. Bungkus segitiga dan ikat rapi.',
      'Kukus lupis selama 45 menit hingga ketan matang dan pulen.',
      'Sangrai kelapa parut sebentar, taburi garam, aduk rata.',
      'Rebus gula merah dengan 100ml air hingga kental. Saring.',
      'Buka bungkusan lupis, gulingkan di kelapa parut sangrai.',
      'Siram gula merah cair di atas lupis. Sajikan.',
    ],
    tags: ['lupis', 'ketan', 'gula merah', 'tradisional', 'manis'],
    rating: 4.5,
  },
  {
    id: 'onde-onde-sarapan',
    name: 'Onde-Onde Wijen',
    description:
      'Bola-bola adonan tepung terigu berisi kacang hijau, dibalut wijen dan digoreng. Jajan pasar renyah untuk sarapan.',
    image: '🟡',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 40,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'Tepung terigu protein rendah', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang hijau (rebus, haluskan)', amount: 150, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah sisir', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Wijen putih', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ragi instan', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Susu cair', amount: 50, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Air hangat', amount: 80, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Untuk isi: masak kacang hijau halus dengan gula merah dan garam di api kecil hingga kalis dan bisa digelindingkan.',
      'Bulatkan isi kacang hijau sebesar kelereng. Dinginkan.',
      'Campurkan tepung, ragi, gula, dan susu. Uleni dengan air hangat hingga kalis. Diamkan 30 menit.',
      'Ambil sedikit adonan, pipihkan. Isi dengan bola kacang hijau. Bulatkan rapat.',
      'Basahi bola adonan dengan air, gulingkan di wijen hingga rata.',
      'Goreng dalam minyak dingin, nyalakan api sedang. Goreng sambil diaduk-aduk agar tidak gosong.',
      'Tiriskan setelah kuning keemasan. Sajikan.',
    ],
    tags: ['onde-onde', 'wijen', 'kacang hijau', 'goreng', 'tradisional'],
    rating: 4.6,
  },
  {
    id: 'nasi-gudeg',
    name: 'Nasi Gudeg',
    description:
      'Nasi disajikan dengan gudeg nangka muda manis, ayam kampung, dan sambal krecek. Sarapan khas Yogyakarta yang istimewa.',
    image: '🍛',
    category: 'Sarapan',
    difficulty: 'Susah',
    cookTime: 120,
    prepTime: 30,
    servings: 4,
    calories: 450,
    ingredients: [
      { name: 'Nangka muda', amount: 500, unit: 'gram', category: 'Sayuran' },
      { name: 'Santan', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Ayam potong', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Gula merah', amount: 50, unit: 'gram', category: 'Bumbu' },
      { name: 'Tebu merah (areh)', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Nasi putih', amount: 400, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Potong nangka muda kecil-kecil. Rebus hingga empuk, tiriskan.',
      'Haluskan bawang merah, bawang putih, dan kunyit.',
      'Tumis bumbu halus bersama daun salam hingga harum.',
      'Masukkan nangka muda, tuang santan. Masak dengan api kecil selama 2 jam.',
      'Tambahkan gula merah dan tebu. Aduk sesekali hingga kuah menyusut dan gudeg berwarna coklat.',
      'Ungkep ayam dengan bumbu halus terpisah hingga matang dan kering.',
      'Sajikan nasi putih dengan gudeg, ayam, dan sambal krecek.',
    ],
    tags: ['gudeg', 'Yogyakarta', 'nangka', 'santan', 'tradisional'],
    rating: 4.8,
  },
  {
    id: 'panekuk',
    name: 'Panekuk',
    description:
      'Panekuk (pancake) lembut dan fluffy yang dipanggang sempurna. Disajikan dengan madu, buah segar, dan butter.',
    image: '🥞',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    calories: 320,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Susu cair', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 30, unit: 'gram', category: 'Bumbu' },
      { name: 'Mentega', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Baking powder', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Buah segar (pisang/strawberry)', amount: 50, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung terigu, gula, dan baking powder dalam mangkuk.',
      'Kocok telur, tambahkan susu cair. Tuang ke campuran tepung, aduk rata hingga halus.',
      'Lelehkan mentega, masukkan ke adonan. Aduk rata.',
      'Panaskan pan anti lengket dengan api kecil. Olesi sedikit mentega.',
      'Tuang 1 sendok sayur adonan, masak hingga muncul gelembung di permukaan.',
      'Balik panekuk, masak sebentar lagi hingga kecoklatan.',
      'Tata panekuk bertumpuk, siram madu dan hias buah segar.',
    ],
    tags: ['panekuk', 'pancake', 'manis', 'praktis', 'fluffy'],
    rating: 4.5,
  },
  {
    id: 'french-toast',
    name: 'French Toast',
    description:
      'Roti tawar direndam telur dan susu, kemudian dipanggang hingga keemasan. Disajikan dengan madu dan kayu manis.',
    image: '🍞',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 340,
    ingredients: [
      { name: 'Roti tawar tebal', amount: 4, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kayu manis bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Kocok telur bersama susu, gula pasir, dan kayu manis bubuk.',
      'Rendam roti tawar ke dalam adonan telur selama 10 detik per sisi.',
      'Panaskan mentega di pan anti lengket dengan api sedang.',
      'Panggang roti hingga kecoklatan keemasan, sekitar 2-3 menit per sisi.',
      'Angkat, tata di piring saji.',
      'Siram madu di atasnya. Sajikan hangat dengan buah segar.',
    ],
    tags: ['french toast', 'roti', 'telur', 'panggang', 'praktis'],
    rating: 4.4,
  },
  {
    id: 'mie-instan-spesial',
    name: 'Mie Instan Spesial',
    description:
      'Mie instan dimasak dengan tambahan sayuran, telur, dan sosis. Disulap menjadi sarapan yang lebih bergizi dan lezat.',
    image: '🍜',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 420,
    ingredients: [
      { name: 'Mie instan', amount: 2, unit: 'bungkus', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Sosis ayam', amount: 2, unit: 'batang', category: 'Protein' },
      { name: 'Sawi hijau', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Kol iris', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 1, unit: 'siung', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Rebus air, masak mie instan setengah matang. Tiriskan.',
      'Iris tipis bawang putih dan bawang merah. Potong sosis dan sawi.',
      'Tumis bumbu iris hingga harum, masukkan sosis dan kol.',
      'Masukkan mie instan, bumbu bubuk, dan kecap manis. Aduk rata.',
      'Tambahkan sawi, masak sebentar hingga layu.',
      'Buat telur mata sapi atau orak-arik, letakkan di atas mie.',
      'Sajikan dengan kerupuk dan taburan daun bawang.',
    ],
    tags: ['mie instan', 'spesial', 'praktis', 'cepat saji', 'murah'],
    rating: 4.3,
  },
  {
    id: 'sandwich-telur',
    name: 'Sandwich Telur',
    description:
      'Sandwich roti isi telur dadar, selada, tomat, dan mayones. Sarapan praktis yang bisa dibawa bekal ke kantor.',
    image: '🥪',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 8,
    prepTime: 10,
    servings: 2,
    calories: 330,
    ingredients: [
      { name: 'Roti tawar', amount: 4, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 3, unit: 'butir', category: 'Protein' },
      { name: 'Selada', amount: 4, unit: 'lembar', category: 'Sayuran' },
      { name: 'Tomat iris', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Mayones', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Mentega', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Kocok telur dengan garam dan merica. Buat dadar tipis, potong sesuai ukuran roti.',
      'Olesi roti dengan mentega, panggang sebentar hingga kecoklatan.',
      'Tata selada di atas roti, tambahkan telur dadar dan irisan tomat.',
      'Olesi mayones di atasnya.',
      'Tutup dengan roti lainnya, tekan perlahan.',
      'Potong diagonal, bungkus dengan kertas pembungkus jika untuk bekal.',
    ],
    tags: ['sandwich', 'telur', 'bekal', 'praktis', 'sehat'],
    rating: 4.4,
  },
  {
    id: 'risoles-mayo',
    name: 'Risoles Mayo',
    description:
      'Risoles renyah berisi ragout sayuran dan mayo. Camilan sekaligus sarapan yang lembut di dalam dan garing di luar.',
    image: '🥟',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 30,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'Kulit risoles (beli jadi)', amount: 15, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Wortel dadu kecil', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kentang rebus', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Ayam cincang', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang bombay iris', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Mayones', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Telur kocok (untuk pencelup)', amount: 2, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Tepung panir', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Tumis bawang putih dan bawang bombay hingga harum.',
      'Masukkan ayam cincang, aduk hingga berubah warna.',
      'Tambahkan wortel dan kentang yang sudah dihaluskan. Aduk rata.',
      'Tambahkan susu, garam, merica, dan sedikit gula. Masak hingga mengental.',
      'Angkat, dinginkan. Campurkan mayones ke dalam ragout.',
      'Ambil kulit risoles, beri 1 sdm ragout. Lipat amplop. Ulangi.',
      'Celupkan risoles ke telur kocok, gulingkan di tepung panir.',
      'Goreng hingga kuning keemasan. Tiriskan dan sajikan.',
    ],
    tags: ['risoles', 'mayo', 'goreng', 'isi ragout', 'camilan'],
    rating: 4.5,
  },
  {
    id: 'ongol-ongol',
    name: 'Ongol-Ongol',
    description:
      'Kue kenyal dari tepung hunkwe berwarna-warni, dibalut kelapa parut. Sarapan manis tradisional yang segar.',
    image: '🟩',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Tepung hunkwe', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kelapa parut', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Larutkan tepung hunkwe dengan santan, aduk rata hingga tidak bergerindil.',
      'Masukkan gula merah, gula pasir, daun pandan, dan garam. Aduk rata.',
      'Masak di atas api dengan terus diaduk hingga adonan mengental dan mengkilap.',
      'Angkat, tuang ke loyang yang sudah diolesi minyak.',
      'Dinginkan hingga set. Potong-potong kotak.',
      'Gulingkan potongan ongol-ongol di kelapa parut.',
      'Sajikan sebagai sarapan atau camilan.',
    ],
    tags: ['ongol-ongol', 'hunkwe', 'kelapa', 'manis', 'tradisional'],
    rating: 4.3,
  },
  {
    id: 'bubur-mutiara',
    name: 'Bubur Mutiara',
    description:
      'Bubur dari butiran sagu mutiara dengan santan dan gula merah. Tekstur kenyal dan manis yang menyegarkan di pagi hari.',
    image: '🫧',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    calories: 270,
    ingredients: [
      { name: 'Sagu mutiara', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Rendam sagu mutiara dalam air selama minimal 1 jam.',
      'Rebus air hingga mendidih, masukkan sagu mutiara.',
      'Masak dengan api sedang hingga mutiara menjadi bening dan mengapung, sekitar 20 menit.',
      'Panaskan santan dengan daun pandan dan garam hingga mendidih. Angkat.',
      'Rebus gula merah dengan 100ml air hingga larut, saring.',
      'Sajikan bubur mutiara dalam mangkuk, siram santan dan gula merah cair.',
    ],
    tags: ['bubur', 'mutiara', 'sagu', 'santan', 'manis'],
    rating: 4.4,
  },
  {
    id: 'kolak-pisang',
    name: 'Kolak Pisang',
    description:
      'Pisang, ubi, dan kolang-kaling dimasak dengan santan dan gula merah. Sarapan manis hangat yang khas saat bulan Ramadhan.',
    image: '🍌',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Pisang raja matang', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Ubi jalar', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kolang-kaling', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Kupas pisang, potong serong. Kupas ubi jalar, potong dadu.',
      'Didihkan santan bersama daun pandan dan garam.',
      'Masukkan gula merah, aduk hingga larut.',
      'Masukkan ubi jalar, masak hingga setengah empuk.',
      'Tambahkan pisang dan kolang-kaling. Masak hingga semua bahan matang.',
      'Angkat, sajikan hangat atau dingin sesuai selera.',
    ],
    tags: ['kolak', 'pisang', 'santan', 'Ramadhan', 'manis'],
    rating: 4.6,
  },
  {
    id: 'nasi-tim',
    name: 'Nasi Tim',
    description:
      'Nasi tim ayam khas Tionghoa Indonesia, dikukus dengan bumbu gurih dan daging ayam cincang. Sarapan lembut dan bergizi.',
    image: '🍚',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 20,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'Beras', amount: 250, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging ayam cincang', amount: 200, unit: 'gram', category: 'Protein' },
      { name: 'Jamur kuping', amount: 30, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Saus tiram', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Minyak wijen', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kaldu ayam', amount: 400, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Rendam beras selama 30 menit, tiriskan.',
      'Tumis bawang putih, bawang merah, dan jahe hingga harum.',
      'Masukkan ayam cincang, aduk hingga berubah warna.',
      'Tambahkan jamur kuping, kecap asin, saus tiram, dan minyak wijen. Masak hingga matang.',
      'Bagi adonan ayam ke mangkuk-mangkuk kecil. Atasnya taruh beras.',
      'Tuang kaldu ayam di setiap mangkuk. Kukus selama 30 menit hingga nasi matang.',
      'Angkat, aduk nasi dan ayam. Sajikan hangat.',
    ],
    tags: ['nasi tim', 'ayam', 'kukus', 'Tionghoa', 'bergizi'],
    rating: 4.6,
  },
  {
    id: 'bubur-menado',
    name: 'Bubur Manado (Tinutuan)',
    description:
      'Bubur khas Manado dengan aneka sayuran dan jagung. Disajikan dengan ikan asin, sambal, dan perasan jeruk nipis.',
    image: '🥣',
    category: 'Sarapan',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 15,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'Beras', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Jagung manis pipil', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Labu kuning', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Kangkung', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Bayam', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun melinjo', amount: 50, unit: 'gram', category: 'Sayuran' },
      { name: 'Kelapa parut sangrai', amount: 50, unit: 'gram', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Ikan asin', amount: 2, unit: 'ekor', category: 'Protein' },
      { name: 'Jeruk nipis', amount: 2, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci beras dan jagung. Rebus dengan air secukupnya.',
      'Setelah setengah matang, masukkan labu kuning yang sudah dipotong dadu.',
      'Masak hingga labu empuk dan bubur mulai mengental.',
      'Masukkan kangkung, bayam, dan daun melinjo. Aduk rata.',
      'Bumbui garam secukupnya. Masak sebentar hingga sayuran layu.',
      'Sajikan bubur dalam mangkuk.',
      'Taburi kelapa parut sangrai, ikan asin goreng, dan beri perasan jeruk nipis.',
    ],
    tags: ['bubur', 'Manado', 'tinutuan', 'sayuran', 'kaya serat'],
    rating: 4.7,
  },
  {
    id: 'tape-singkong-goreng',
    name: 'Tape Singkong Goreng',
    description:
      'Tape singkong dibalut tepung dan digoreng renyah. Sarapan manis dengan aroma tape yang khas dan tekstur renyah.',
    image: '🍠',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 10,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'Tape singkong', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung beras', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air es', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Pisahkan tape singkong dari seratnya, geprek sedikit agar melebar.',
      'Campurkan tepung terigu, tepung beras, gula, dan garam.',
      'Tambahkan air es sedikit demi sedikit, aduk rata hingga adonan kental.',
      'Celupkan tape singkong ke adonan tepung.',
      'Goreng dalam minyak panas dengan api sedang hingga kuning keemasan.',
      'Angkat, tiriskan di tisu dapur. Sajikan selagi hangat.',
    ],
    tags: ['tape', 'singkong', 'goreng', 'manis', 'tradisional'],
    rating: 4.4,
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal',
    description:
      'Oatmeal lembut dimasak dengan susu, madu, dan buah-buahan segar. Sarapan sehat kaya serat untuk memulai hari.',
    image: '🥣',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 5,
    servings: 2,
    calories: 280,
    ingredients: [
      { name: 'Rolled oats', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Pisang iris', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Blueberry', amount: 30, unit: 'gram', category: 'Sayuran' },
      { name: 'Kayu manis bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan rolled oats dan susu cair di dalam panci kecil.',
      'Masak dengan api sedang, aduk sesekali selama 3-5 menit hingga mengental.',
      'Angkat, tuang ke mangkuk.',
      'Taburi kayu manis bubuk.',
      'Hias dengan irisan pisang dan blueberry.',
      'Siram madu di atasnya. Sajikan selagi hangat.',
    ],
    tags: ['oatmeal', 'sehat', 'serat', 'buah', 'diet'],
    rating: 4.3,
  },
  {
    id: 'waffle',
    name: 'Waffle',
    description:
      'Waffle renyah di luar dan lembut di dalam, disajikan dengan maple syrup dan buah segar. Sarapan barat yang lezat.',
    image: '🧇',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 2,
    calories: 350,
    ingredients: [
      { name: 'Tepung terigu', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Susu cair', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Mentega leleh', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Baking powder', amount: 1, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Maple syrup', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Buah segar (strawberry/blueberry)', amount: 50, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Campurkan tepung, gula, dan baking powder.',
      'Kocok telur, campurkan dengan susu. Tuang ke campuran tepung.',
      'Tambahkan mentega leleh, aduk rata hingga halus.',
      'Panaskan waffle maker, olesi sedikit mentega.',
      'Tuang adonan secukupnya, tutup dan masak hingga matang dan kecoklatan.',
      'Angkat, tata di piring.',
      'Siram maple syrup dan hias buah segar. Sajikan hangat.',
    ],
    tags: ['waffle', 'panggang', 'manis', 'barat', 'praktis'],
    rating: 4.5,
  },
  {
    id: 'avocado-toast',
    name: 'Avocado Toast',
    description:
      'Roti panggang dengan selai alpukat segar, telur mata sapi, dan taburan cabai flakes. Sarapan sehat yang modern dan lezat.',
    image: '🥑',
    category: 'Sarapan',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 5,
    servings: 2,
    calories: 370,
    ingredients: [
      { name: 'Roti gandum', amount: 2, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Alpukat matang', amount: 1, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Jeruk nipis', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica hitam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Cabai flakes', amount: 0.5, unit: 'sendok teh', category: 'Pelengkap' },
      { name: 'Minyak zaitun', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Panggang roti gandum hingga kecoklatan dan renyah.',
      'Belah alpukat, kerok dagingnya. Campurkan dengan perasan jeruk nipis, garam, dan merica.',
      'Oleskan selai alpukat secara merata di atas roti panggang.',
      'Buat telur mata sapi dengan minyak zaitun.',
      'Letakkan telur di atas roti yang sudah diolesi alpukat.',
      'Taburi cabai flakes dan merica hitam. Sajikan segera.',
    ],
    tags: ['avocado', 'toast', 'sehat', 'modern', 'alpukat'],
    rating: 4.5,
  },
];
