import type { Recipe } from '@/types';

export const recipesMakanMalam1: Recipe[] = [
  {
    id: 'gulai-kambing',
    name: 'Gulai Kambing',
    description:
      'Gulai kambing khas Padang dengan kuah santan kental berbumbu rempah yang hangat dan menggugah selera. Daging kambing yang empuk berpadu dengan kuah gurih cocok disantap dengan nasi putih hangat.',
    image: '🐐',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 150,
    prepTime: 30,
    servings: 6,
    calories: 580,
    ingredients: [
      { name: 'Daging kambing (has dalam)', amount: 700, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah besar', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 3, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 3, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging kambing berukuran 4x4 cm. Rebus sebentar untuk menghilangkan bau, tiriskan.',
      'Haluskan bawang merah, bawang putih, cabai merah, cabai rawit, jahe, dan kunyit.',
      'Panaskan minyak, tumis bumbu halus bersama lengkuas, serai, daun jeruk, dan daun kunyit hingga harum.',
      'Masukkan daging kambing, aduk hingga berubah warna.',
      'Tuangkan santan kental sedikit demi sedikit sambil terus diaduk.',
      'Masak dengan api kecil selama 2-2,5 jam hingga daging empuk dan kuah mengental.',
      'Bumbui garam dan gula merah secukupnya, aduk rata.',
      'Sajikan hangat dengan nasi putih dan kerupuk merah.',
    ],
    tags: ['gulai', 'kambing', 'Padang', 'santan', 'rempah', 'hangat'],
    rating: 4.8,
  },
  {
    id: 'kari-ayam',
    name: 'Kari Ayam',
    description:
      'Kari ayam dengan kuah santan kuning yang kaya rempah dan aroma harum. Daging ayam yang empuk berenak dalam kuah kental yang pedas gurih.',
    image: '🍛',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 20,
    servings: 5,
    calories: 420,
    ingredients: [
      { name: 'Ayam potong', amount: 600, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan bawang merah, bawang putih, cabai merah, kunyit, dan jahe.',
      'Panaskan minyak, tumis bumbu halus bersama serai dan daun salam hingga harum.',
      'Masukkan ayam potong, aduk hingga permukaan ayam berubah warna putih.',
      'Tuangkan santan kental secara perlahan sambil diaduk agar tidak pecah.',
      'Masak dengan api sedang selama 45 menit hingga ayam empuk dan kuah mengental.',
      'Bumbui garam dan sedikit gula merah, koreksi rasa.',
      'Angkat dan sajikan dengan nasi putih hangat serta acar timun.',
    ],
    tags: ['kari', 'ayam', 'santan', 'kuning', 'rempah', 'hangat'],
    rating: 4.7,
  },
  {
    id: 'kari-udang',
    name: 'Kari Udang',
    description:
      'Kari udang dengan kuah santan berwarna kuning keemasan yang kaya rempah. Udang segar yang kenyal berpadu dengan kuah gurih yang cocok untuk makan malam.',
    image: '🦐',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'Udang besar (kupas sisakan ekor)', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Tomat', amount: 2, unit: 'buah', category: 'Sayuran' },
    ],
    steps: [
      'Bersihkan udang, buang kepala dan kulit. Cuci dan tiriskan.',
      'Haluskan bawang merah, bawang putih, cabai merah, kunyit, dan jahe.',
      'Tumis bumbu halus bersama serai dan daun salam hingga harum dan matang.',
      'Masukkan potongan tomat, masak hingga tomat layu.',
      'Tuang santan kental, masak dengan api sedang hingga mendidih.',
      'Masukkan udang, masak sebentar selama 5-8 menit hingga udang berwarna merah dan matang.',
      'Bumbui garam dan gula pasir secukupnya.',
      'Sajikan kari udang panas dengan nasi putih.',
    ],
    tags: ['kari', 'udang', 'santan', 'seafood', 'rempah'],
    rating: 4.6,
  },
  {
    id: 'gulai-nangka',
    name: 'Gulai Nangka Muda',
    description:
      'Gulai nangka muda khas Padang dengan kuah santan kental berwarna kuning. Tekstur nangka yang empuk dan serat-seratnya menyerap bumbu hingga ke dalam.',
    image: '🍐',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Nangka muda', amount: 500, unit: 'gram', category: 'Sayuran' },
      { name: 'Santan kental', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong nangka muda berukuran sedang, cuci bersih.',
      'Rebus nangka muda sebentar hingga setengah empuk, tiriskan.',
      'Haluskan bawang merah, bawang putih, cabai merah, dan kunyit.',
      'Tumis bumbu halus bersama lengkuas, serai, dan daun salam hingga harum.',
      'Masukkan nangka muda yang sudah direbus, aduk rata.',
      'Tuang santan kental, masak dengan api kecil hingga kuah mengental.',
      'Bumbui garam dan gula merah secukupnya, masak hingga nangka empuk.',
      'Sajikan dengan nasi putih hangat dan lauk pendamping.',
    ],
    tags: ['gulai', 'nangka', 'Padang', 'santan', 'sayuran', 'vegetarian'],
    rating: 4.5,
  },
  {
    id: 'gulai-daun-pakis',
    name: 'Gulai Daun Pakis',
    description:
      'Gulai daun pakis atau paku dengan kuah santan kuning yang gurih dan sedikit pedas. Sayuran hutan yang unik ini memiliki tekstur renyah dan rasa yang khas.',
    image: '🌿',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Daun pakis (paku)', amount: 300, unit: 'gram', category: 'Sayuran' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Petik daun pakis, ambil bagian yang muda dan lunak. Cuci bersih dan tiriskan.',
      'Haluskan bawang merah, bawang putih, cabai merah, dan kunyit.',
      'Panaskan sedikit minyak, tumis bumbu halus bersama lengkuas, serai, dan daun salam hingga harum.',
      'Tuangkan santan kental, aduk rata dan biarkan mendidih.',
      'Masukkan daun pakis, masak dengan api sedang selama 10 menit.',
      'Bumbui garam dan sedikit gula merah.',
      'Masak hingga daun pakis empuk dan kuah mengental.',
      'Sajikan sebagai lauk pendamping nasi putih hangat.',
    ],
    tags: ['gulai', 'pakis', 'sayuran', 'santan', 'Padang', 'sehat'],
    rating: 4.4,
  },
  {
    id: 'kari-daging',
    name: 'Kari Daging Santan',
    description:
      'Kari daging sapi dengan kuah santan pekat berwarna kekuningan yang kaya akan rempah. Daging sapi dimasak hingga sangat empuk dan meresap bumbu.',
    image: '🥘',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 120,
    prepTime: 25,
    servings: 5,
    calories: 520,
    ingredients: [
      { name: 'Daging sapi (has dalam)', amount: 600, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 700, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 7, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah besar', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 3, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 3, unit: 'cm', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging sapi berukuran 4x4 cm, cuci bersih.',
      'Haluskan bawang merah, bawang putih, cabai merah, cabai rawit, kunyit, dan jahe.',
      'Tumis bumbu halus bersama lengkuas, serai, daun jeruk, dan kayu manis hingga harum.',
      'Masukkan daging sapi, aduk hingga permukaan daging berubah warna.',
      'Tuang santan kental sedikit demi sedikit, aduk rata agar santan tidak pecah.',
      'Masak dengan api kecil selama 1,5-2 jam hingga daging empuk.',
      'Bumbui garam dan gula merah, koreksi rasa.',
      'Sajikan panas dengan nasi putih hangat dan kerupuk.',
    ],
    tags: ['kari', 'daging sapi', 'santan', 'rempah', 'empuk', 'hangat'],
    rating: 4.7,
  },
  {
    id: 'gulai-telur',
    name: 'Gulai Telur Padang',
    description:
      'Gulai telur rebus khas Padang dengan kuah santan kuning yang gurih dan pedas. Telur yang direbus lalu dimasak dalam kuah gulai hingga bumbu meresap sempurna.',
    image: '🥚',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'Telur ayam (rebus)', amount: 8, unit: 'butir', category: 'Protein' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus telur ayam hingga matang, kupas kulitnya.',
      'Haluskan bawang merah, bawang putih, cabai merah, dan kunyit.',
      'Panaskan sedikit minyak, tumis bumbu halus bersama lengkuas, serai, dan daun salam.',
      'Tuang santan kental, masak hingga mendidih sambil diaduk.',
      'Masukkan telur rebus, masak dengan api kecil selama 20 menit.',
      'Bumbui garam dan gula merah, aduk pelan agar telur tidak pecah.',
      'Masak hingga kuah mengental dan bumbu meresap ke telur.',
      'Sajikan dengan nasi putih hangat.',
    ],
    tags: ['gulai', 'telur', 'Padang', 'santan', 'praktis', 'hemat'],
    rating: 4.3,
  },
  {
    id: 'kari-ikan-aceh',
    name: 'Kari Ikan Aceh',
    description:
      'Kari ikan khas Aceh dengan kuah santan kental berwarna kuning dan aroma rempah yang kuat. Ikan yang segar dimasak dalam kuah kari yang pedas dan harum.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 5,
    calories: 380,
    ingredients: [
      { name: 'Ikan tongkol atau kakap', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Kunyit', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 2, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Potong-potong ikan sesuai selera, cuci bersih dan tiriskan.',
      'Haluskan bawang merah, bawang putih, cabai merah, cabai rawit, kunyit, dan jahe.',
      'Tumis bumbu halus bersama lengkuas, serai, dan daun kunyit hingga harum.',
      'Tuang santan kental, masak dengan api sedang sambil diaduk hingga mendidih.',
      'Masukkan potongan ikan secara perlahan agar tidak hancur.',
      'Masak selama 15 menit hingga ikan matang dan kuah mengental.',
      'Bumbui garam dan gula merah secukupnya.',
      'Sajikan panas dengan nasi putih dan kerupuk.',
    ],
    tags: ['kari', 'ikan', 'Aceh', 'santan', 'pedas', 'rempah'],
    rating: 4.6,
  },
  {
    id: 'ayam-sambal-matah',
    name: 'Ayam Sambal Matah Bali',
    description:
      'Ayam goreng renyah disajikan dengan sambal matah khas Bali yang segar dan pedas. Perpaduan ayam gurih dengan sambal mentah yang aromatik menciptakan cita rasa yang unik.',
    image: '🐔',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Ayam fillet', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Bawang merah', amount: 8, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Serai', amount: 3, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Minyak kelapa', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Jeruk limau', amount: 1, unit: 'buah', category: 'Pelengkap' },
      { name: 'Minyak goreng', amount: 200, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Marinasi ayam fillet dengan bawang putih halus dan garam selama 15 menit.',
      'Goreng ayam dalam minyak panas hingga matang kecoklatan, tiriskan. Potong-potong.',
      'Iris halus bawang merah, cabai rawit, serai bagian putih, dan daun jeruk.',
      'Campurkan semua bahan iris dalam mangkuk.',
      'Panaskan minyak kelapa hingga berasap, siramkan ke atas campuran bahan iris.',
      'Aduk rata, tambahkan perasan jeruk limau dan garam.',
      'Tata potongan ayam goreng di piring saji.',
      'Siram sambal matah di atas ayam, sajikan dengan nasi putih.',
    ],
    tags: ['ayam', 'sambal matah', 'Bali', 'pedas', 'segar', 'goreng'],
    rating: 4.8,
  },
  {
    id: 'ikan-bakar-dabu-dabu',
    name: 'Ikan Bakar Sambal Dabu-Dabu',
    description:
      'Ikan bakar khas Manado yang disajikan dengan sambal dabu-dabu segar pedas. Kuah sambal yang asam pedas dari tomat, cabai, dan bawang membuat ikan bakar terasa istimewa.',
    image: '🐠',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'Ikan cakalang atau tongkol', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Tomat merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun kemangi', amount: 1, unit: 'ikat', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan, belah jadi dua bagian tanpa dipisahkan. Lumuri garam dan perasan jeruk nipis.',
      'Haluskan bawang putih, jahe, dan kunyit untuk olesan ikan.',
      'Olesi ikan dengan bumbu halus, diamkan 15 menit.',
      'Bakar ikan di atas arang atau pemanggang hingga matang kedua sisi.',
      'Potong dadu tomat, iris halus cabai rawit dan bawang merah untuk sambal dabu-dabu.',
      'Campurkan tomat, cabai, bawang merah, garam, dan perasan jeruk nipis. Aduk rata.',
      'Tata ikan bakar di piring, siram sambal dabu-dabu di atasnya.',
      'Hiasi dengan daun kemangi dan sajikan hangat.',
    ],
    tags: ['ikan bakar', 'dabu-dabu', 'Manado', 'pedas', 'segar', 'sambal'],
    rating: 4.7,
  },
  {
    id: 'terong-balado',
    name: 'Terong Balado Padang',
    description:
      'Terong goreng dengan sambal balado khas Padang yang pedas manis dan berwarna merah menyala. Tekstur terong yang lembut berpadu sempurna dengan sambal yang kaya rasa.',
    image: '🍆',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 10,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Terong ungu', amount: 3, unit: 'buah', category: 'Sayuran' },
      { name: 'Cabai merah besar', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat merah', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Gula merah', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 200, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Potong terong bulat-bulat setebal 1 cm. Rendam dalam air garam sebentar.',
      'Goreng terong dalam minyak panas hingga kuning kecoklatan dan empuk. Tiriskan.',
      'Goreng sebentar cabai merah, cabai rawit, bawang merah, bawang putih, dan tomat hingga layu.',
      'Haluskan semua bahan yang sudah digoreng menggunakan cobek atau blender.',
      'Panaskan sedikit minyak, tumis sambal halus hingga matang dan berminyak.',
      'Tambahkan gula merah dan garam, aduk rata.',
      'Masukkan terong goreng ke dalam sambal, aduk pelan hingga terong terbalut sambal.',
      'Sajikan sebagai lauk pendamping nasi putih hangat.',
    ],
    tags: ['terong', 'balado', 'Padang', 'pedas', 'sambal', 'vegetarian'],
    rating: 4.5,
  },
  {
    id: 'udang-sambal-hijau',
    name: 'Udang Sambal Hijau',
    description:
      'Udang segar yang dimasak dengan sambal hijau dari cabai hijau dan tomat hijau. Perpaduan udang kenyal dengan sambal hijau yang segar dan pedas menggugah selera.',
    image: '🦐',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'Udang besar', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Cabai hijau besar', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit hijau', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Tomat hijau', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun salam', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan udang, buang kepala dan kaki. Cuci dan tiriskan.',
      'Goreng sebentar cabai hijau, cabai rawit hijau, tomat hijau, bawang merah, dan bawang putih.',
      'Haluskan semua bahan yang sudah digoreng dengan cobek secara kasar.',
      'Panaskan sedikit minyak, tumis sambal hijau bersama daun salam hingga harum.',
      'Masukkan udang, aduk hingga udang berubah warna merah.',
      'Tambahkan garam dan gula merah, masak hingga udang matang sempurna.',
      'Angkat dan sajikan dengan nasi putih hangat.',
    ],
    tags: ['udang', 'sambal hijau', 'pedas', 'seafood', 'segar'],
    rating: 4.6,
  },
  {
    id: 'ikan-asin-sambal',
    name: 'Ikan Asin Sambal Tomat',
    description:
      'Ikan asin goreng disajikan dengan sambal tomat yang manis pedas dan segar. Lauk sederhana yang sangat nikmat untuk makan malam bersama nasi putih hangat.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 3,
    calories: 250,
    ingredients: [
      { name: 'Ikan asin (pilih jenis favorit)', amount: 3, unit: 'ekor', category: 'Protein' },
      { name: 'Tomat merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Minyak goreng', amount: 100, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Rendam ikan asin dalam air hangat selama 15 menit untuk mengurangi rasa asin. Tiriskan.',
      'Goreng ikan asin dalam minyak panas hingga kering dan kecoklatan. Tiriskan.',
      'Goreng sebentar tomat, cabai merah, cabai rawit, bawang merah, dan bawang putih hingga layu.',
      'Ulek kasar semua bahan goreng bersama garam dan gula merah.',
      'Panaskan sedikit minyak, tumis sambal tomat hingga matang dan berminyak.',
      'Tata ikan asin goreng di piring saji.',
      'Siram sambal tomat di atas ikan asin.',
      'Sajikan dengan nasi putih hangat dan lalapan.',
    ],
    tags: ['ikan asin', 'sambal tomat', 'pedas', 'sederhana', 'lauk'],
    rating: 4.4,
  },
  {
    id: 'sup-buntut',
    name: 'Sup Buntut Jakarta',
    description:
      'Sup buntut sapi dengan kuah bening gurih yang kaya rempah dan sayuran segar. Buntut sapi yang dimasak lama menghasilkan kaldu yang sangat sedap.',
    image: '🍲',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 180,
    prepTime: 30,
    servings: 6,
    calories: 450,
    ingredients: [
      { name: 'Buntut sapi', amount: 800, unit: 'gram', category: 'Protein' },
      { name: 'Wortel', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Kentang', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Pala', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Seledri', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Bawang goreng', amount: 3, unit: 'sendok makan', category: 'Pelengkap' },
      { name: 'Garam dan merica', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus buntut sapi hingga mendidih, buang air rebusan pertama. Bilas bersih buntut.',
      'Didihkan air baru, masukkan buntut sapi. Masak dengan api kecil selama 2 jam.',
      'Haluskan bawang putih dan bawang merah, tumis hingga harum.',
      'Masukkan tumisan bumbu ke dalam rebusan buntut bersama pala, cengkeh, dan kayu manis.',
      'Potong dadu wortel dan kentang. Masukkan ke sup setelah buntut cukup empuk.',
      'Masak hingga sayuran matang. Bumbui garam dan merica.',
      'Masukkan irisan daun bawang dan seledri.',
      'Sajikan panas dengan taburan bawang goreng, nasi putih, dan sambal.',
    ],
    tags: ['sup', 'buntut', 'Jakarta', 'rempah', 'kaldu', 'hangat'],
    rating: 4.8,
  },
  {
    id: 'sup-kambing',
    name: 'Sup Kambing Madura',
    description:
      'Sup kambing kuah bening khas Madura dengan aroma rempah yang kuat dan kuah gurih sedap. Daging kambing yang empuk dimasak dengan rempah pilihan menghasilkan sup yang menghangatkan.',
    image: '🫕',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 150,
    prepTime: 25,
    servings: 5,
    calories: 480,
    ingredients: [
      { name: 'Tulang kambing dan daging', amount: 700, unit: 'gram', category: 'Protein' },
      { name: 'Bawang putih', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Pala', amount: 0.5, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Garam dan merica', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus tulang kambing dan daging, buang air rebusan pertama. Cuci bersih.',
      'Didihkan air baru, masukkan tulang dan daging kambing. Masak dengan api kecil selama 2 jam.',
      'Haluskan bawang putih, bawang merah, dan jahe. Tumis hingga harum.',
      'Masukkan tumisan bumbu ke dalam rebusan sup.',
      'Tambahkan lengkuas, serai, kayu manis, cengkeh, dan pala.',
      'Masak terus hingga daging empuk dan kuah berwarna kecoklatan.',
      'Bumbui garam dan merica, masukkan irisan daun bawang.',
      'Sajikan panas dengan nasi putih, kerupuk, dan sambal.',
    ],
    tags: ['sup', 'kambing', 'Madura', 'rempah', 'hangat', 'kuah bening'],
    rating: 4.7,
  },
  {
    id: 'sup-ikan-patin',
    name: 'Sup Ikan Patin',
    description:
      'Sup ikan patin dengan kuah bening asam segar yang menggugah selera. Daging ikan patin yang lembut dan tidak berduri membuat sup ini cocok untuk semua kalangan.',
    image: '🐡',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'Ikan patin', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Tomat', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Belimbing sayur', amount: 3, unit: 'buah', category: 'Sayuran' },
      { name: 'Daun kemangi', amount: 1, unit: 'ikat', category: 'Sayuran' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Potong ikan patin berukuran sedang, cuci bersih. Lumuri perasan jeruk nipis.',
      'Didihkan air, masukkan bawang putih dan bawang merah yang digeprek.',
      'Tambahkan jahe yang dimemarkan dan cabai rawit.',
      'Masukkan potongan tomat dan belimbing sayur.',
      'Masak hingga sayuran empuk, lalu masukkan potongan ikan patin.',
      'Masak sebentar saja hingga ikan matang dan daging berwarna putih.',
      'Bumbui garam, koreksi rasa.',
      'Sajikan dengan daun kemangi segar dan sambal.',
    ],
    tags: ['sup', 'ikan patin', 'asam', 'segar', 'kuah bening', 'sehat'],
    rating: 4.4,
  },
  {
    id: 'sup-krim-ayam',
    name: 'Sup Krim Ayam',
    description:
      'Sup krim ayam dengan kuah kental dan creamy yang menghangatkan tubuh. Daging ayam suwir dan sayuran dalam saus krim yang lembut cocok untuk makan malam.',
    image: '🥣',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'Dada ayam', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Susu cair', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Tepung terigu', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Wortel', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Kentang', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Jagung manis pipil', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Mentega', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam dan merica', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rebus dada ayam hingga matang, suwir-suwir dagingnya.',
      'Potong dadu kecil wortel dan kentang.',
      'Tumis bawang bombay dan bawang putih dengan mentega hingga harum.',
      'Masukkan tepung terigu, aduk rata selama 1 menit.',
      'Tuang susu cair secara perlahan sambil terus diaduk agar tidak menggumpal.',
      'Masukkan wortel, kentang, dan jagung manis. Masak hingga sayuran empuk.',
      'Tambahkan suwiran ayam, garam, dan merica.',
      'Masak hingga kuah mengental. Sajikan hangat dengan roti panggang.',
    ],
    tags: ['sup', 'krim', 'ayam', 'creamy', 'hangat', 'barat'],
    rating: 4.5,
  },
  {
    id: 'rendang-ayam',
    name: 'Rendang Ayam',
    description:
      'Rendang ayam khas Minang dengan bumbu rempah yang dimasak hingga kering dan meresap sempurna. Daging ayam yang lembut berbalut bumbu rendang yang gurih dan kaya rempah.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 120,
    prepTime: 30,
    servings: 5,
    calories: 460,
    ingredients: [
      { name: 'Ayam potong', amount: 700, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cabai merah besar', amount: 8, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 7, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 3, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam dan gula merah', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan jahe.',
      'Panaskan sedikit minyak, tumis bumbu halus bersama lengkuas, serai, dan daun jeruk hingga harum.',
      'Masukkan ayam potong, aduk hingga berubah warna.',
      'Tuang santan kental sedikit demi sedikit sambil diaduk.',
      'Masak dengan api kecil selama 1,5-2 jam hingga kuah menyusut dan mengering.',
      'Aduk sesekali agar tidak gosong di bagian bawah.',
      'Tambahkan garam dan gula merah di tengah proses memasak.',
      'Masak hingga bumbu benar-benar kering dan berwarna coklat gelap. Sajikan dengan nasi.',
    ],
    tags: ['rendang', 'ayam', 'Padang', 'rempah', 'kering', 'khas'],
    rating: 4.8,
  },
  {
    id: 'rendang-telur',
    name: 'Rendang Telur Padang',
    description:
      'Telur rebus yang dimasak dengan bumbu rendang khas Padang hingga kering dan berwarna coklat kehitaman. Lauk sederhana yang tahan lama dan sangat cocok untuk bekal.',
    image: '🥚',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 90,
    prepTime: 15,
    servings: 4,
    calories: 330,
    ingredients: [
      { name: 'Telur ayam (rebus)', amount: 10, unit: 'butir', category: 'Protein' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cabai merah', amount: 6, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Rebus telur hingga matang, kupas kulitnya.',
      'Goreng sebentar telur rebus hingga permukaan sedikit kecoklatan.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan jahe.',
      'Tumis bumbu halus bersama lengkuas, serai, dan daun jeruk hingga harum.',
      'Tuang santan kental, masak hingga mendidih.',
      'Masukkan telur rebus, masak dengan api kecil selama 1-1,5 jam.',
      'Aduk sesekali hingga kuah mengering dan bumbu berwarna gelap.',
      'Sajikan dengan nasi putih hangat.',
    ],
    tags: ['rendang', 'telur', 'Padang', 'kering', 'bekal', 'hemat'],
    rating: 4.3,
  },
  {
    id: 'rendang-ikan',
    name: 'Rendang Ikan',
    description:
      'Rendang ikan khas Sumatera Barat dengan bumbu rempah yang kaya dan dimasak hingga kering. Ikan yang dipilih bertekstur padat agar tidak hancur saat dimasak lama.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 100,
    prepTime: 20,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'Ikan tongkol atau tembang', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cabai merah', amount: 7, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan, potong-potong. Lumuri garam dan kunyit, diamkan 10 menit.',
      'Goreng ikan sebentar hingga setengah matang, tiriskan.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan kunyit.',
      'Tumis bumbu halus bersama lengkuas, serai, dan daun jeruk.',
      'Tuang santan kental, masak hingga mendidih.',
      'Masukkan ikan goreng, masak dengan api kecil hingga kuah mengering.',
      'Aduk pelan agar ikan tidak hancur, masak hingga bumbu kering.',
      'Sajikan dengan nasi putih hangat.',
    ],
    tags: ['rendang', 'ikan', 'Padang', 'rempah', 'kering', 'laut'],
    rating: 4.5,
  },
  {
    id: 'rendang-nangka',
    name: 'Rendang Nangka',
    description:
      'Rendang nangka muda khas Minang yang dimasak hingga kering dengan bumbu rendang yang meresap. Lauk vegetarian yang kaya serat dan cocok untuk makan malam sehat.',
    image: '🍐',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 120,
    prepTime: 20,
    servings: 5,
    calories: 300,
    ingredients: [
      { name: 'Nangka muda', amount: 600, unit: 'gram', category: 'Sayuran' },
      { name: 'Santan kental', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cabai merah', amount: 7, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 4, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Potong nangka muda berukuran kecil, rebus hingga setengah empuk dan tiriskan.',
      'Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan jahe.',
      'Tumis bumbu halus bersama lengkuas, serai, dan daun jeruk hingga harum.',
      'Masukkan nangka muda, aduk rata hingga terbalut bumbu.',
      'Tuang santan kental sedikit demi sedikit.',
      'Masak dengan api kecil selama 1,5-2 jam hingga kuah mengering.',
      'Aduk sesekali agar tidak gosong.',
      'Sajikan dengan nasi putih hangat sebagai lauk vegetarian.',
    ],
    tags: ['rendang', 'nangka', 'Padang', 'vegetarian', 'serat', 'sehat'],
    rating: 4.4,
  },
  {
    id: 'semur-daging',
    name: 'Semur Daging Betawi',
    description:
      'Semur daging sapi khas Betawi dengan kuah kecap manis yang kental, manis, dan gurih. Daging sapi dimasak perlahan hingga empuk dalam kuah cokelat yang menggoda.',
    image: '🥩',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 90,
    prepTime: 20,
    servings: 5,
    calories: 480,
    ingredients: [
      { name: 'Daging sapi has dalam', amount: 600, unit: 'gram', category: 'Protein' },
      { name: 'Kecap manis', amount: 6, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 6, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Gula merah', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Tomat', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging sapi berukuran 3x3 cm, cuci bersih.',
      'Haluskan bawang merah dan bawang putih, tumis hingga harum.',
      'Masukkan daging sapi, aduk hingga berubah warna.',
      'Tambahkan kecap manis, gula merah, pala bubuk, kayu manis, dan cengkeh.',
      'Tuang air hingga daging terendam, masak dengan api kecil.',
      'Masak selama 1,5 jam hingga daging empuk dan kuah mengental.',
      'Masukkan potongan tomat, masak sebentar.',
      'Bumbui garam, koreksi rasa. Sajikan dengan nasi dan acar.',
    ],
    tags: ['semur', 'daging', 'Betawi', 'kecap', 'manis', 'rempah'],
    rating: 4.7,
  },
  {
    id: 'semur-ayam',
    name: 'Semur Ayam Kentang',
    description:
      'Semur ayam dengan kentang dalam kuah kecap manis yang manis gurih dan kental. Lauk rumahan yang mudah dibuat dan disukai semua anggota keluarga.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 45,
    prepTime: 15,
    servings: 4,
    calories: 400,
    ingredients: [
      { name: 'Ayam potong', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Kentang', amount: 3, unit: 'buah', category: 'Sayuran' },
      { name: 'Kecap manis', amount: 5, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Gula merah', amount: 15, unit: 'gram', category: 'Bumbu' },
      { name: 'Tomat', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong kentang dadu sedang, goreng sebentar hingga permukaan kering. Tiriskan.',
      'Haluskan bawang merah dan bawang putih, tumis hingga harum.',
      'Masukkan ayam potong, aduk hingga berubah warna putih.',
      'Tambahkan kecap manis, gula merah, dan pala bubuk.',
      'Tuang air secukupnya, masak dengan api sedang hingga ayam setengah empuk.',
      'Masukkan kentang goreng, masak hingga kuah mengental.',
      'Masukkan potongan tomat, bumbui garam dan koreksi rasa.',
      'Sajikan dengan nasi putih hangat dan acar timun.',
    ],
    tags: ['semur', 'ayam', 'kentang', 'kecap', 'manis', 'rumahan'],
    rating: 4.5,
  },
  {
    id: 'steak-ayam-tepung',
    name: 'Steak Ayam Tepung',
    description:
      'Steak ayam berbalut tepung crispy yang digoreng hingga keemasan dan renyah. Disajikan dengan saus sambal mayones dan sayuran segar sebagai menu makan malam praktis.',
    image: '🍖',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 20,
    servings: 3,
    calories: 420,
    ingredients: [
      { name: 'Dada ayam fillet', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Tepung terigu', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung roti', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Merica bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kubis', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Wortel', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Potong dada ayam memanjang, pukul-pukul agar pipih dan merata.',
      'Bumbui ayam dengan bawang putih halus, garam, dan merica. Diamkan 15 menit.',
      'Siapkan tiga wadah: tepung terigu, telur kocok, dan tepung roti.',
      'Balut ayam secara berurutan: tepung terigu, telur kocok, lalu tepung roti.',
      'Goreng ayam dalam minyak panas dengan api sedang hingga kuning keemasan.',
      'Tiriskan, potong-potong steak ayam.',
      'Iris tipis kubis dan wortel, tata di piring sebagai sayuran pendamping.',
      'Sajikan steak ayam crispy dengan saus sambal mayones.',
    ],
    tags: ['steak', 'ayam', 'tepung', 'crispy', 'goreng', 'praktis'],
    rating: 4.3,
  },
  {
    id: 'ayam-teriyaki',
    name: 'Ayam Teriyaki',
    description:
      'Ayam fillet yang dimasak dengan saus teriyaki manis gurih khas Jepang. Perpaduan rasa manis dari kecap Jepang dan gurih dari bumbu membuat ayam ini istimewa.',
    image: '🏯',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 10,
    servings: 3,
    calories: 350,
    ingredients: [
      { name: 'Ayam fillet', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Kecap Jepang (shoyu)', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Mirin', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 1.5, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Minyak wijen', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Bawang bombay', amount: 0.5, unit: 'buah', category: 'Sayuran' },
      { name: ' wijen sangrai', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Potong ayam fillet memanjang, bumbui garam dan merica.',
      'Campurkan kecap Jepang, mirin, gula pasir, dan minyak wijen untuk saus teriyaki.',
      'Tumis bawang putih dan jahe cincang hingga harum.',
      'Masukkan ayam fillet, masak hingga permukaan berwarna putih.',
      'Tuang saus teriyaki, masak hingga saus mengental dan melapisi ayam.',
      'Masukkan irisan bawang bombay, aduk sebentar.',
      'Angkat, tata di piring saji.',
      'Taburi wijen sangrai dan sajikan dengan nasi putih.',
    ],
    tags: ['ayam', 'teriyaki', 'Jepang', 'manis', 'gurih', 'cepat'],
    rating: 4.6,
  },
  {
    id: 'katsu-curry',
    name: 'Katsu Curry Jepang',
    description:
      'Perpaduan katsu ayam goreng tepung roti renyah dengan kuah kari Jepang yang creamy dan hangat. Makan malam fusion Jepang yang mengenyangkan dan lezat.',
    image: '🍘',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 40,
    prepTime: 20,
    servings: 4,
    calories: 520,
    ingredients: [
      { name: 'Dada ayam fillet', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Tepung terigu', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung roti', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Bumbu kari Jepang (roux)', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kentang', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Wortel', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Air', amount: 500, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Minyak goreng', amount: 300, unit: 'ml', category: 'Bumbu' },
    ],
    steps: [
      'Potong ayam fillet memanjang. Balut tepung, celup telur kocok, lalu gulingkan di tepung roti.',
      'Goreng ayam katsu dalam minyak panas hingga kuning keemasan. Tiriskan, potong-potong.',
      'Potong dadu kentang, wortel, dan bawang bombay.',
      'Tumis bawang bombay hingga layu dan harum.',
      'Tambahkan kentang dan wortel, tuang air. Masak hingga sayuran empuk.',
      'Masukkan bumbu kari Jepang, aduk hingga larut dan kuah mengental.',
      'Tata nasi di piring, siram kuah kari di sebelahnya.',
      'Letakkan potongan katsu di atas kuah kari. Sajikan.',
    ],
    tags: ['katsu', 'curry', 'Jepang', 'goreng', 'fusion', 'hangat'],
    rating: 4.7,
  },
  {
    id: 'butter-chicken',
    name: 'Butter Chicken India',
    description:
      'Ayam yang dimasak dalam saus tomat kental dengan butter dan rempah khas India. Kuah yang creamy dan kaya rasa membuat menu ini sangat populer di seluruh dunia.',
    image: '🧈',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 50,
    prepTime: 25,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'Ayam fillet (potong dadu)', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Yogurt plain', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tomat merah', amount: 4, unit: 'buah', category: 'Sayuran' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Butter', amount: 40, unit: 'gram', category: 'Bumbu' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai merah bubuk', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Marinasi ayam dengan yogurt, cabai merah bubuk, garam, dan bawang putih halus selama minimal 1 jam.',
      'Panggang ayam yang sudah dimarinasi di oven 200°C selama 15 menit.',
      'Rebus tomat, kupas kulit, lalu blender hingga halus.',
      'Tumis bawang bombay cincang dengan butter hingga harum dan layu.',
      'Masukkan jahe cincang dan tomat blender, masak hingga kuah mengental.',
      'Tambahkan santan kental, garam, dan cabai merah bubuk.',
      'Masukkan ayam panggang ke dalam saus, masak 10 menit.',
      'Tambahkan sisa butter di akhir, aduk rata. Sajikan dengan naan atau nasi.',
    ],
    tags: ['butter chicken', 'India', 'creamy', 'rempah', 'tomat', 'internasional'],
    rating: 4.8,
  },
  {
    id: 'nasi-biryani',
    name: 'Nasi Biryani Kambing',
    description:
      'Nasi biryani khas India dengan daging kambing yang empuk dan nasi beraroma rempah. Setiap butir nasi meresap rempah dan kaldu daging yang sedap.',
    image: '🍚',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 120,
    prepTime: 30,
    servings: 6,
    calories: 550,
    ingredients: [
      { name: 'Beras basmati', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging kambing', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Yogurt plain', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang bombay', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai merah bubuk', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kunyit bubuk', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 4, unit: 'butir', category: 'Bumbu' },
      { name: 'Kapulaga', amount: 3, unit: 'butir', category: 'Bumbu' },
    ],
    steps: [
      'Rendam beras basmati selama 30 menit, tiriskan.',
      'Tumis bawang bombay iris tipis hingga garing, sisihkan sebagian untuk taburan.',
      'Tumis bumbu halus bersama kayu manis, cengkeh, dan kapulaga hingga harum.',
      'Masukkan daging kambing, aduk hingga berubah warna. Tambahkan yogurt.',
      'Masak daging dengan api kecil hingga empuk dan kuah menyusut.',
      'Rebus beras basmati setengah matang, tiriskan.',
      'Tata nasi dan daging kambing secara berselang-seling dalam panci. Kukus 30 menit.',
      'Sajikan dengan taburan bawang goreng dan acar.',
    ],
    tags: ['biryani', 'kambing', 'India', 'rempah', 'nasi', 'premium'],
    rating: 4.8,
  },
  {
    id: 'kebab-turki',
    name: 'Kebab Turki',
    description:
      'Kebab daging kambing yang dibumbui rempah Turki lalu dipanggang hingga matang sempurna. Disajikan dalam roti pita dengan sayuran segar dan saus yogurt.',
    image: '🥙',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 25,
    servings: 4,
    calories: 400,
    ingredients: [
      { name: 'Daging kambing giling', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Roti pita', amount: 4, unit: 'lembar', category: 'Bahan Utama' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Tomat', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Selada', amount: 4, unit: 'lembar', category: 'Sayuran' },
      { name: 'Timun', amount: 1, unit: 'buah', category: 'Sayuran' },
      { name: 'Yogurt plain', amount: 100, unit: 'gram', category: 'Pelengkap' },
      { name: 'Cabai rawit', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Merica dan garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan daging kambing giling dengan bawang bombay parut, bawang putih halus, merica, dan garam.',
      'Uleni adonan daging, bentuk memanjang seperti kebab dan tusukkan ke tusuk.',
      'Panggang kebab di atas pemanggang atau oven 200°C selama 15-20 menit hingga matang.',
      'Potong dadu tomat dan iris tipis timun.',
      'Buat saus yogurt: campurkan yogurt, cabai rawit cincang, garam, dan sedikit air.',
      'Hangatkan roti pita sebentar.',
      'Isi roti pita dengan irisan daging kebab, selada, tomat, dan timun.',
      'Siram saus yogurt, gulung roti dan sajikan.',
    ],
    tags: ['kebab', 'Turki', 'daging kambing', 'roti pita', 'internasional'],
    rating: 4.6,
  },
  {
    id: 'tom-yum-goong',
    name: 'Tom Yum Goong Thailand',
    description:
      'Sup asam pedas khas Thailand dengan udang segar, jamur, dan rempah yang harum. Kuahnya yang segar dan aromatik menjadi favorit pecinta kuliner Asia Tenggara.',
    image: '🌶️',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Udang besar', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Jamur straw', amount: 100, unit: 'gram', category: 'Sayuran' },
      { name: 'Serai', amount: 3, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk purut', amount: 5, unit: 'lembar', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Terasi', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Juasam limau', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Santan', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula dan garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan udang, sisakan ekor. Potong jamur straw menjadi dua bagian.',
      'Didihkan air, masukkan serai yang dimemarkan, daun jeruk, dan jahe iris.',
      'Masukkan cabai rawit dan terasi, masak hingga harum.',
      'Tambahkan udang dan jamur, masak hingga udang berwarna merah.',
      'Tuang santan, masak sebentar hingga kuah sedikit berminyak.',
      'Tambahkan perasan jeruk nipis, gula, dan garam. Koreksi rasa asam pedasnya.',
      'Masak sebentar lagi, jangan sampai mendidih setelah jeruk dimasukkan.',
      'Sajikan panas dengan taburan daun ketumbar.',
    ],
    tags: ['tom yum', 'Thailand', 'udang', 'asam pedas', 'sup', 'seafood'],
    rating: 4.7,
  },
  {
    id: 'pad-thai',
    name: 'Pad Thai',
    description:
      'Mie goreng khas Thailand dengan saus tamarind manis asam, udang, tahu, dan tauge. Hidangan jalanan Thailand yang kini mendunia dengan rasa yang unik.',
    image: '🍜',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 20,
    servings: 3,
    calories: 430,
    ingredients: [
      { name: 'Mie beras kering', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Udang kupas', amount: 150, unit: 'gram', category: 'Protein' },
      { name: 'Tahu goreng', amount: 100, unit: 'gram', category: 'Protein' },
      { name: 'Tauge', amount: 80, unit: 'gram', category: 'Sayuran' },
      { name: 'Daun bawang', amount: 2, unit: 'batang', category: 'Sayuran' },
      { name: 'Telur ayam', amount: 2, unit: 'butir', category: 'Protein' },
      { name: 'Tamarind (asam jawa)', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap ikan', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Gula merah', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Kacang tanah sangrai', amount: 30, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Rendam mie beras dalam air hangat selama 20 menit hingga lunak, tiriskan.',
      'Larutkan asam jawa dengan sedikit air, saring ambil airnya.',
      'Campurkan air asam jawa dengan kecap ikan dan gula merah.',
      'Panaskan wajan dengan api besar, tumis udang hingga berubah warna. Angkat.',
      'Orak-arik telur di wajan yang sama, masukkan tahu goreng potong.',
      'Masukkan mie, tuang saus tamarind. Aduk rata dengan api besar.',
      'Tambahkan tauge dan daun bawang iris, aduk sebentar.',
      'Sajikan dengan kacang tanah sangrai, irisan jeruk limau, dan cabai.',
    ],
    tags: ['pad thai', 'Thailand', 'mie', 'udang', 'asam manis', 'internasional'],
    rating: 4.7,
  },
  {
    id: 'pho-bo',
    name: 'Pho Bo Vietnam',
    description:
      'Sup mi Vietnam dengan kuah kaldu sapi bening yang kaya rempah dan irisan daging sapi tipis. Kuah yang hangat dan aromatic menjadi pelengkap sempurna mi kenyal.',
    image: '🍜',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 240,
    prepTime: 30,
    servings: 5,
    calories: 380,
    ingredients: [
      { name: 'Tulang sapi', amount: 500, unit: 'gram', category: 'Protein' },
      { name: 'Daging sapi has dalam (iris tipis)', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Mie pho', amount: 300, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Bintang anise', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Kapulaga', amount: 2, unit: 'butir', category: 'Bumbu' },
      { name: 'Kecap ikan', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Daun bawang', amount: 3, unit: 'batang', category: 'Sayuran' },
      { name: 'Tauge dan selada', amount: 100, unit: 'gram', category: 'Sayuran' },
    ],
    steps: [
      'Panggang tulang sapi di oven hingga kecoklatan untuk menghasilkan kaldu yang sedap.',
      'Rebus tulang sapi dalam air banyak dengan api kecil selama 3 jam.',
      'Bakar jahe dan bawang bombay, masukkan ke kaldu.',
      'Tambahkan kayu manis, bintang anise, kapulaga, dan kecap ikan.',
      'Saring kaldu, bumbui garam dan gula.',
      'Rebus mie pho terpisah, tiriskan.',
      'Tata mie di mangkuk, siram kaldu panas. Letakkan irisan daging sapi mentah di atasnya.',
      'Sajikan dengan tauge, selada, daun bawang, irisan cabai, dan perasan jeruk nipis.',
    ],
    tags: ['pho', 'Vietnam', 'sapi', 'kuah bening', 'rempah', 'sup'],
    rating: 4.8,
  },
  {
    id: 'beef-rendang',
    name: 'Beef Rendang Premium',
    description:
      'Rendang daging sapi premium menggunakan daging has dalam terbaik dengan bumbu rempah pilihan. Dimasak perlahan hingga bumbu benar-benar meresap dan kering sempurna.',
    image: '🥩',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 240,
    prepTime: 40,
    servings: 8,
    calories: 600,
    ingredients: [
      { name: 'Daging sapi has dalam (premium)', amount: 1000, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 1000, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cabai merah besar', amount: 12, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 10, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 7, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Lengkuas', amount: 6, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 5, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun jeruk', amount: 7, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 4, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Potong daging sapi berukuran besar (6x6 cm), cuci bersih dan tiriskan.',
      'Haluskan semua bumbu: cabai, bawang, jahe, dan kunyit.',
      'Tumis bumbu halus bersama lengkuas, serai, daun jeruk, dan daun kunyit hingga sangat harum.',
      'Masukkan daging sapi, aduk hingga semua permukaan terbalut bumbu.',
      'Tuang santan secara bertahap sambil terus diaduk agar tidak pecah.',
      'Masak dengan api sangat kecil selama 3-4 jam. Aduk setiap 15 menit.',
      'Setelah kuah mengering dan minyak keluar, lanjutkan aduk hingga bumbu benar-benar kering.',
      'Matikan api, diamkan semalaman agar bumbu lebih meresap. Sajikan dengan nasi.',
    ],
    tags: ['beef', 'rendang', 'premium', 'Padang', 'rempah', 'spesial'],
    rating: 5.0,
  },
  {
    id: 'ikan-gurame-bakar',
    name: 'Ikan Gurame Bakar',
    description:
      'Ikan gurame bakar dengan bumbu kecap dan rempah yang meresap hingga ke daging. Kulit gurame yang renyah dan daging yang tebal membuat hidangan ini sangat istimewa.',
    image: '🐠',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 20,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'Ikan gurame', amount: 1, unit: 'ekor (600g)', category: 'Protein' },
      { name: 'Kecap manis', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 4, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan gurame, belah punggung tanpa putus. Lumuri garam dan perasan jeruk nipis.',
      'Haluskan bawang putih, bawang merah, cabai merah, jahe, dan kunyit.',
      'Campurkan bumbu halus dengan kecap manis, daun salam, dan garam untuk olesan.',
      'Olesi ikan gurame dengan bumbu secara merata, diamkan 20 menit agar meresap.',
      'Bakar ikan di atas arang atau pemanggang dengan api sedang.',
      'Olesi bumbu secukupnya saat membalik ikan.',
      'Bakar hingga kedua sisi matang dan kulit kering kecoklatan.',
      'Sajikan dengan sambal terasi, lalapan, dan nasi putih hangat.',
    ],
    tags: ['ikan bakar', 'gurame', 'kecap', 'panggang', 'rempah', 'laut'],
    rating: 4.7,
  },
  {
    id: 'sapi-panggang',
    name: 'Sapi Panggang Bumbu Kecap',
    description:
      'Daging sapi panggang dengan bumbu kecap manis yang gurih dan manis. Daging yang empuk berbalut bumbu kecap berwarna cokelat kehitaman yang menggoda selera.',
    image: '🥩',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 60,
    prepTime: 30,
    servings: 5,
    calories: 450,
    ingredients: [
      { name: 'Daging sapi has luar', amount: 600, unit: 'gram', category: 'Protein' },
      { name: 'Kecap manis', amount: 5, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang bombay', amount: 1, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Merica hitam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Kecap asin', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Mentega', amount: 20, unit: 'gram', category: 'Bumbu' },
      { name: 'Wortel', amount: 2, unit: 'buah', category: 'Sayuran' },
      { name: 'Kentang', amount: 2, unit: 'buah', category: 'Sayuran' },
    ],
    steps: [
      'Tusuk-tusuk daging sapi dengan garpu agar bumbu meresap.',
      'Campurkan kecap manis, kecap asin, bawang putih halus, jahe parut, dan merica hitam.',
      'Marinasi daging sapi dalam bumbu selama minimal 2 jam di kulkas.',
      'Panaskan oven pada suhu 180°C.',
      'Panggang daging selama 40-50 menit hingga matang sesuai selera.',
      'Olesi bumbu marinasi dan mentega saat memanggang agar permukaan berkilau.',
      'Panggang wortel dan kentang yang sudah dibumbui sebagai pendamping.',
      'Potong daging tipis, sajikan dengan sayuran panggang.',
    ],
    tags: ['sapi panggang', 'kecap', 'panggang', 'daging', 'barat', 'spesial'],
    rating: 4.6,
  },
  {
    id: 'bebek-bakar-madu',
    name: 'Bebek Bakar Madu',
    description:
      'Bebek bakar dengan olesan madu dan bumbu rempah yang membuat kulit renyah dan daging empuk. Rasa manis gurih dari madu berpadu sempurna dengan aroma bakaran.',
    image: '🦆',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 90,
    prepTime: 30,
    servings: 4,
    calories: 500,
    ingredients: [
      { name: 'Bebek', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Madu', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kecap manis', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Merica hitam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Minyak wijen', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan bebek, potong menjadi 4 bagian.',
      'Haluskan bawang putih, bawang merah, jahe, dan kunyit.',
      'Marinasi bebek dengan bumbu halus, kecap manis, minyak wijen, garam, dan merica selama 2 jam.',
      'Kukus bebek yang sudah dimarinasi selama 45 menit hingga empuk.',
      'Panaskan oven pada suhu 200°C.',
      'Tata bebek di loyang, olesi campuran madu dan kecap manis.',
      'Panggang selama 20-25 menit hingga kulit kecoklatan dan renyah.',
      'Sajikan dengan sambal, lalapan, dan nasi putih hangat.',
    ],
    tags: ['bebek', 'bakar', 'madu', 'rempah', 'renyah', 'spesial'],
    rating: 4.8,
  },
  {
    id: 'ayam-pop-padang',
    name: 'Ayam Pop Padang',
    description:
      'Ayam pop khas Padang yang dikukus dengan bumbu gurih kemudian disiram kuah santan dan sambal hijau. Daging ayam yang sangat empuk dan berwarna putih pucat ini khas Padang.',
    image: '🍗',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 45,
    prepTime: 15,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'Ayam kampung', amount: 1, unit: 'ekor', category: 'Protein' },
      { name: 'Santan', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Serai', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Cabai hijau', amount: 10, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong ayam kampung menjadi 4 bagian, cuci bersih.',
      'Haluskan bawang putih, jahe, dan kunyit untuk bumbu kukusan.',
      'Campurkan ayam dengan bumbu halus, serai, dan daun salam.',
      'Kukus ayam selama 30 menit hingga empuk dan matang.',
      'Sementara itu, buat sambal hijau: goreng cabai hijau sebentar, ulek kasar dengan garam.',
      'Panaskan santan, bumbui garam, masak hingga mendidih.',
      'Tata ayam pop di piring saji, siram kuah santan.',
      'Sajikan dengan sambal hijau Padang dan nasi putih hangat.',
    ],
    tags: ['ayam pop', 'Padang', 'kukus', 'santan', 'sambal hijau', 'khas'],
    rating: 4.7,
  },
  {
    id: 'palai-bada-ikan',
    name: 'Palai Bada Ikan',
    description:
      'Palai bada ikan khas Minangkabau berupa ikan yang dibalut adonan bada (campuran kelapa parut dan bumbu) lalu dibungkus daun pisang dan dibakar. Olahan ikan tradisional yang sangat aromatik.',
    image: '🐟',
    category: 'Makan Malam',
    difficulty: 'Sedang',
    cookTime: 30,
    prepTime: 25,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'Ikan teri atau ikan kecil', amount: 300, unit: 'gram', category: 'Protein' },
      { name: 'Kelapa parut', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Cabai merah', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Cabai rawit', amount: 5, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 2, unit: 'siung', category: 'Bumbu' },
      { name: 'Daun kunyit', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Daun pisang', amount: 4, unit: 'lembar', category: 'Pelengkap' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Lidah api (tusuk gigi)', amount: 4, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci bersih ikan, tiriskan.',
      'Haluskan cabai merah, cabai rawit, bawang merah, dan bawang putih.',
      'Campurkan kelapa parut dengan bumbu halus, iris daun kunyit, dan garam.',
      'Aduk rata adonan palai bada hingga semua bahan tercampur merata.',
      'Ambil selembar daun pisang, beri 2 sendok makan adonan bada.',
      'Letakkan beberapa ekor ikan di atas adonan, lipat daun pisang dan semat dengan lidah api.',
      'Bakar palai bada di atas arang api kecil selama 15-20 menit hingga daun sedikit gosong.',
      'Buka bungkusan, sajikan palai bada dengan nasi putih hangat.',
    ],
    tags: ['palai', 'bada', 'Minang', 'tradisional', 'ikan', 'daun pisang'],
    rating: 4.5,
  },
  {
    id: 'ikan-patin-bakar',
    name: 'Ikan Patin Bakar',
    description:
      'Ikan patin bakar dengan bumbu olesan kecap dan rempah yang meresap ke daging ikan. Daging ikan patin yang lembut dan tidak berduri membuatnya cocok untuk semua umur.',
    image: '🐡',
    category: 'Makan Malam',
    difficulty: 'Mudah',
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'Ikan patin', amount: 600, unit: 'gram', category: 'Protein' },
      { name: 'Kecap manis', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 4, unit: 'siung', category: 'Bumbu' },
      { name: 'Bawang merah', amount: 3, unit: 'siung', category: 'Bumbu' },
      { name: 'Cabai merah', amount: 3, unit: 'buah', category: 'Bumbu' },
      { name: 'Jahe', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Kunyit', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Jeruk nipis', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Garam', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Daun salam', amount: 3, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Bersihkan ikan patin, belah punggungnya. Lumuri garam dan perasan jeruk nipis.',
      'Haluskan bawang putih, bawang merah, cabai merah, jahe, dan kunyit.',
      'Campurkan bumbu halus dengan kecap manis dan daun salam untuk olesan.',
      'Olesi ikan patin dengan bumbu secara merata, diamkan 15 menit.',
      'Bakar ikan di atas arang atau pemanggang dengan api sedang.',
      'Olesi bumbu secukupnya saat membalik ikan agar tidak kering.',
      'Bakar hingga kedua sisi matang sempurna dan berwarna kecoklatan.',
      'Sajikan dengan sambal, lalapan, dan nasi putih hangat.',
    ],
    tags: ['ikan bakar', 'patin', 'kecap', 'panggang', 'mudah', 'segar'],
    rating: 4.5,
  },
  {
    id: 'nasi-kebuli',
    name: 'Nasi Kebuli Kambing',
    description:
      'Nasi kebuli khas Betawi dengan kaldu kambing dan rempah yang harum. Setiap butir nasi meresap kaldu yang sedap berpadu dengan daging kambing empuk.',
    image: '🍚',
    category: 'Makan Malam',
    difficulty: 'Susah',
    cookTime: 90,
    prepTime: 30,
    servings: 6,
    calories: 520,
    ingredients: [
      { name: 'Beras basmati', amount: 400, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Daging kambing', amount: 400, unit: 'gram', category: 'Protein' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Bawang bombay', amount: 2, unit: 'buah', category: 'Bumbu' },
      { name: 'Bawang putih', amount: 5, unit: 'siung', category: 'Bumbu' },
      { name: 'Jahe', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 4, unit: 'cm', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 4, unit: 'butir', category: 'Bumbu' },
      { name: 'Kapulaga', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Bumbu rasa kambing', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 1.5, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam beras basmati selama 30 menit, tiriskan.',
      'Tumis bawang bombay iris tipis hingga layu dan harum.',
      'Tambahkan bawang putih, jahe, kayu manis, cengkeh, dan kapulaga.',
      'Masukkan daging kambing, aduk hingga berubah warna.',
      'Tuang santan kental dan air secukupnya. Masak hingga daging empuk.',
      'Angkat daging, masukkan beras basmati ke dalam kaldu. Masak seperti nasi biasa.',
      'Sementara itu, iris tipis daging kambing, tumis kembali hingga sedikit kering.',
      'Setelah nasi matang, aduk rata dan sajikan dengan daging kambing tumis di atasnya.',
    ],
    tags: ['nasi kebuli', 'kambing', 'Betawi', 'rempah', 'aromatik', 'premium'],
    rating: 4.8,
  },
];
