import type { Recipe } from '@/types';

export const recipesMinuman: Recipe[] = [
  {
    id: 'es-jeruk',
    name: 'Es Jeruk',
    description:
      'Minuman segar dari perasan jeruk manis dengan gula dan es batu. Penyejuk di cuaca panas yang simpel tapi menyegarkan.',
    image: '🍊',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 80,
    ingredients: [
      { name: 'Jeruk manis', amount: 4, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang dingin', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Bahan Utama' },
    ],
    steps: [
      'Belah jeruk manis, peras airnya dan saring biji-bijinya.',
      'Campurkan air perasan jeruk dengan gula pasir, aduk hingga gula larut.',
      'Tambahkan air matang dingin, aduk rata.',
      'Tuang ke dalam gelas, tambahkan es batu. Sajikan segera.',
    ],
    tags: ['jeruk', 'segar', 'dingin', 'sederhana', 'sehat'],
    rating: 4.3,
  },
  {
    id: 'jus-alpukat',
    name: 'Jus Alpukat',
    description:
      'Jus alpukat kental dan creamy dengan susu coklat dan gula. Minuman bergizi tinggi yang disukai semua umur.',
    image: '🥑',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 320,
    ingredients: [
      { name: 'Alpukat matang', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Susu coklat', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 8, unit: 'butir', category: 'Bahan Utama' },
    ],
    steps: [
      'Belah alpukat, ambil dagingnya dengan sendok.',
      'Masukkan daging alpukat ke dalam blender bersama susu coklat dan gula pasir.',
      'Blender hingga halus dan kental.',
      'Tuang ke dalam gelas, tambahkan es batu. Sajikan segera.',
    ],
    tags: ['alpukat', 'jus', 'susu', 'bergizi', 'segar'],
    rating: 4.6,
  },
  {
    id: 'es-cincau',
    name: 'Es Cincau',
    description:
      'Minuman segar dengan potongan cincau hitam, sirup gula merah, dan santan. Dessert sekaligus minuman pelepas dahaga.',
    image: '🧊',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 150,
    ingredients: [
      { name: 'Cincau hitam', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah (sisir)', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Es batu serut', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Potong cincau hitam berbentuk kubus kecil.',
      'Rebus gula merah dengan 200ml air hingga larut dan sedikit kental. Angkat, saring, dinginkan.',
      'Panaskan santan dengan sedikit garam, aduk rata. Dinginkan.',
      'Siapkan gelas, tata cincau hitam di dasar gelas.',
      'Tambahkan es batu serut, tuang sirup gula merah dan santan di atasnya. Sajikan segera.',
    ],
    tags: ['cincau', 'gula merah', 'santan', 'segar', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'es-dawet',
    name: 'Es Dawet',
    description:
      'Minuman tradisional Jawa dengan cendol hijau, santan, dan gula merah cair. Segar dan manis alami.',
    image: '🍧',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'Tepung beras', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung kanji', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air daun suji/pandan', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 150, unit: 'gram', category: 'Bumbu' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Campurkan tepung beras dan tepung kanji. Tambahkan air daun suji sedikit demi sedikit sambil diaduk hingga rata.',
      'Masak adonan di atas api kecil sambil terus diaduk hingga mengental dan mengkilap.',
      'Cetak adonan menggunakan cetakan cendol (saringan berlubang) ke dalam air dingin. Biarkan mengeras.',
      'Rebus gula merah dengan 150ml air hingga larut kental. Saring dan dinginkan.',
      'Masak santan dengan garam, aduk rata. Dinginkan.',
      'Tata cendol hijau di gelas, tambahkan es batu serut.',
      'Tuang santan dan sirup gula merah di atasnya. Sajikan segera.',
    ],
    tags: ['dawet', 'cendol', 'gula merah', 'santan', 'Jawa'],
    rating: 4.7,
  },
  {
    id: 'es-kelapa-muda',
    name: 'Es Kelapa Muda',
    description:
      'Air kelapa muda segar dengan daging kelapa, es batu, dan sirup. Minuman alami pelepas dahaga tropis.',
    image: '🥥',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 120,
    ingredients: [
      { name: 'Kelapa muda', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Sirup gula', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Garam', amount: 1, unit: 'pinch', category: 'Bumbu' },
    ],
    steps: [
      'Buka kelapa muda, tuang airnya ke dalam wadah.',
      'Kerok daging kelapa muda dengan sendok.',
      'Bagi air kelapa ke dua gelas, tambahkan sirup gula dan sedikit garam, aduk rata.',
      'Masukkan daging kelapa muda ke dalam gelas.',
      'Tambahkan es batu secukupnya. Sajikan segera.',
    ],
    tags: ['kelapa muda', 'segar', 'alami', 'tropis', 'sehat'],
    rating: 4.6,
  },
  {
    id: 'bandrek',
    name: 'Bandrek',
    description:
      'Minuman hangat khas Sunda dari jahe, serai, kayu manis, dan rempah. Cocok diminum saat cuaca dingin atau hujan.',
    image: '🍵',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 3,
    calories: 110,
    ingredients: [
      { name: 'Jahe (geprek)', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Serai (geprek)', amount: 2, unit: 'batang', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 5, unit: 'cm', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 4, unit: 'butir', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Kelapa parut sangrai (opsional)', amount: 30, unit: 'gram', category: 'Pelengkap' },
    ],
    steps: [
      'Geprek jahe dan serai agar aroma lebih keluar.',
      'Didihkan air dalam panci. Masukkan jahe, serai, kayu manis, cengkeh, dan daun pandan.',
      'Masak dengan api kecil selama 10 menit agar rempah meresap.',
      'Masukkan gula merah, aduk hingga larut.',
      'Saring kuah bandrek ke dalam gelas.',
      'Taburi kelapa parut sangrai di atasnya jika suka. Sajikan hangat.',
    ],
    tags: ['bandrek', 'jahe', 'hangat', 'rempah', 'Sunda'],
    rating: 4.6,
  },
  {
    id: 'wedang-jahe',
    name: 'Wedang Jahe',
    description:
      'Minuman jahe hangat tradisional Jawa yang menghangatkan tubuh. Diseduh dengan gula merah dan serai untuk rasa lebih kaya.',
    image: '🫚',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 5,
    servings: 3,
    calories: 95,
    ingredients: [
      { name: 'Jahe (geprek)', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Serai (geprek)', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Air', amount: 700, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Pelengkap' },
    ],
    steps: [
      'Geprek jahe agar aroma keluar. Pukul-pukul serai.',
      'Didihkan air, masukkan jahe dan serai.',
      'Masak dengan api kecil selama 15 menit.',
      'Masukkan gula merah, aduk hingga larut.',
      'Saring ke dalam gelas. Beri perasan jeruk nipis. Sajikan hangat.',
    ],
    tags: ['wedang', 'jahe', 'hangat', 'Jawa', 'rempah'],
    rating: 4.5,
  },
  {
    id: 'wedang-ronde',
    name: 'Wedang Ronde',
    description:
      'Minuman hangat khas Jawa berisi bola-bola tepung ketan berisi kacang tanah, dengan kuah jahe yang pedas manis.',
    image: '🍡',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 25,
    prepTime: 30,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'Tepung ketan', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang tanah sangrai', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah (sisir halus)', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Jahe (geprek)', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah (untuk kuah)', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Serai (geprek)', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung ketan dengan air hangat sedikit demi sedikit, uleni hingga kalis.',
      'Cincang halus kacang tanah sangrai, campurkan dengan gula merah sisir untuk isian.',
      'Ambil sedikit adonan ketan, pipihkan. Isi dengan campuran kacang dan gula merah. Bulatkan.',
      'Didihkan air, rebus bola-bola ronde hingga mengambang (±5 menit). Angkat, tiriskan.',
      'Untuk kuah: rebus jahe, serai, daun pandan, dan gula merah dalam 800ml air selama 15 menit.',
      'Saring kuah, beri sedikit garam. Taruh bola ronde di mangkuk, siram dengan kuah jahe hangat.',
    ],
    tags: ['wedang', 'ronde', 'jahe', 'ketan', 'hangat'],
    rating: 4.7,
  },
  {
    id: 'wedang-uwuh',
    name: 'Wedang Uwuh',
    description:
      'Minuman herbal khas Imogiri, Yogyakarta dari aneka rempah dan dedaunan. Rasanya hangat dan aromanya harum.',
    image: '🫙',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 5,
    servings: 3,
    calories: 70,
    ingredients: [
      { name: 'Kayu secang', amount: 20, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Jahe', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Serai', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun pala', amount: 3, unit: 'lembar', category: 'Bumbu' },
      { name: 'Cengkeh', amount: 3, unit: 'butir', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 3, unit: 'cm', category: 'Bumbu' },
      { name: 'Gula merah', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Cuci bersih semua rempah. Geprek jahe dan serai.',
      'Didihkan air dalam panci. Masukkan kayu secang, jahe, serai, daun pala, cengkeh, dan kayu manis.',
      'Masak dengan api kecil selama 12 menit hingga air berwarna kemerahan dan aroma harum.',
      'Masukkan gula merah, aduk hingga larut.',
      'Saring kuah ke dalam gelas. Sajikan hangat.',
    ],
    tags: ['wedang', 'uwuh', 'herbal', 'rempah', 'Yogyakarta'],
    rating: 4.4,
  },
  {
    id: 'sekoteng',
    name: 'Sekoteng',
    description:
      'Minuman hangat khas Jakarta dengan kuah jahe, berisi kacang tanah, kolang-kaling, potongan roti, dan biji delima.',
    image: '🥤',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 15,
    servings: 3,
    calories: 190,
    ingredients: [
      { name: 'Jahe (geprek)', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang tanah (sangrai)', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Kolang-kaling', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Roti tawar', amount: 3, unit: 'lembar', category: 'Isian' },
      { name: 'Biji delima putih', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Serai (geprek)', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Air', amount: 700, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Geprek jahe dan serai. Didihkan air, masukkan jahe dan serai.',
      'Masak kuah jahe dengan api kecil selama 12 menit. Masukkan gula merah, aduk hingga larut.',
      'Sangrai kacang tanah, kupas kulitnya. Potong roti tawar berbentuk dadu kecil.',
      'Cuci bersih kolang-kaling dan biji delima putih.',
      'Saring kuah jahe ke dalam mangkuk.',
      'Tata kacang tanah, kolang-kaling, roti tawar, dan biji delima di dalam mangkuk.',
      'Siram dengan kuah jahe hangat. Sajikan selagi hangat.',
    ],
    tags: ['sekoteng', 'jahe', 'hangat', 'Betawi', 'tradisional'],
    rating: 4.5,
  },
  {
    id: 'ronde',
    name: 'Ronde',
    description:
      'Bola-bola ketan kenyal berisi kacang tanah dan gula merah, disajikan dengan kuah jahe hangat. Jajanan khas musim hujan.',
    image: '🍡',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 20,
    prepTime: 25,
    servings: 3,
    calories: 170,
    ingredients: [
      { name: 'Tepung ketan', amount: 180, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kacang tanah sangrai', amount: 40, unit: 'gram', category: 'Isian' },
      { name: 'Gula merah (sisir)', amount: 40, unit: 'gram', category: 'Isian' },
      { name: 'Jahe (geprek)', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah (kuah)', amount: 60, unit: 'gram', category: 'Bumbu' },
      { name: 'Air', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan tepung ketan dengan air hangat, uleni hingga kalis dan bisa dibentuk.',
      'Cincang kasar kacang tanah sangrai, campur dengan gula merah sisir untuk isian.',
      'Ambil sedikit adonan ketan, pipihkan. Isi dengan campuran kacang, bulatkan rapat.',
      'Didihkan air, rebus ronde hingga mengambang ±5 menit. Angkat.',
      'Rebus jahe dan gula merah dengan 600ml air selama 12 menit, saring.',
      'Tata ronde di mangkuk, siram kuah jahe hangat. Sajikan.',
    ],
    tags: ['ronde', 'ketan', 'jahe', 'hangat', 'jajan pasar'],
    rating: 4.6,
  },
  {
    id: 'es-teler',
    name: 'Es Teler',
    description:
      'Minuman segar legendaris dengan alpukat, nangka, kelapa muda, susu kental manis, dan sirup cocopandan.',
    image: '🍧',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 3,
    calories: 280,
    ingredients: [
      { name: 'Alpukat matang', amount: 1, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Nangka matang', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kelapa muda', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 4, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Sirup cocopandan', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Potong dadu alpukat dan nangka matang.',
      'Kerok daging kelapa muda.',
      'Siapkan gelas saji, tata potongan alpukat, nangka, dan kelapa muda.',
      'Tambahkan es batu serut hingga penuh.',
      'Tuangkan susu kental manis dan sirup cocopandan di atasnya.',
      'Sajikan segera sebelum es mencair.',
    ],
    tags: ['es teler', 'alpukat', 'nangka', 'segar', 'legendaris'],
    rating: 4.8,
  },
  {
    id: 'es-kopyor',
    name: 'Es Kopyor',
    description:
      'Minuman segar dengan daging kelapa kopyor bertekstur unik, disajikan dengan santan, sirup, dan es batu serut.',
    image: '🥥',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 160,
    ingredients: [
      { name: 'Kelapa kopyor', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Sirup gula merah', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Pandan (opsional)', amount: 1, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Buka kelapa kopyor, ambil dagingnya. Cuci bersih.',
      'Panaskan santan dengan garam dan daun pandan. Aduk rata, dinginkan.',
      'Potong-potong daging kopyor sesuai selera.',
      'Siapkan gelas, tata daging kopyor.',
      'Tambahkan es batu serut.',
      'Tuangkan santan dingin dan sirup gula merah. Sajikan segera.',
    ],
    tags: ['kopyor', 'kelapa', 'santan', 'segar', 'premium'],
    rating: 4.5,
  },
  {
    id: 'teh-tarik',
    name: 'Teh Tarik',
    description:
      'Teh hitam dengan susu kental manis yang ditarik-tarik menghasilkan buih halus. Minuman khas Kopitiam yang creamy dan harum.',
    image: '☕',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 140,
    ingredients: [
      { name: 'Teh hitam (teh celup)', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Susu kental manis', amount: 4, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Air panas', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
    ],
    steps: [
      'Seduh teh celup dengan air panas selama 5 menit hingga warnanya pekat.',
      'Angkat teh celup, masukkan susu kental manis dan gula pasir. Aduk rata.',
      'Tuang teh dari satu wadah ke wadah lain berulang-ulang (setidaknya 5 kali) dari ketinggian untuk membuat buih.',
      'Tuang ke dalam gelas. Sajikan hangat atau tambahkan es batu.',
    ],
    tags: ['teh tarik', 'susu', 'kopi', 'Kopitiam', 'creamy'],
    rating: 4.7,
  },
  {
    id: 'kopi-susu',
    name: 'Kopi Susu',
    description:
      'Kopi hitam pekat dicampur susu segar dan gula aren. Kopi susu kekinian yang creamy dan manis alami.',
    image: '☕',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    calories: 180,
    ingredients: [
      { name: 'Kopi hitam (bubuk/saset)', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Air panas', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Susu segar dingin', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula aren cair', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 5, unit: 'butir', category: 'Bahan Utama' },
    ],
    steps: [
      'Seduh kopi dengan air panas, aduk rata. Biarkan agak dingin.',
      'Masukkan gula aren cair ke dasar gelas.',
      'Tambahkan es batu.',
      'Tuang susu segar dingin di atas es.',
      'Terakhir tuang kopi hitam perlahan di atasnya sehingga terlihat layer.',
      'Aduk sebelum diminum. Sajikan.',
    ],
    tags: ['kopi', 'susu', 'gula aren', 'kekinian', 'dingin'],
    rating: 4.7,
  },
  {
    id: 'jamu-kunyit-asam',
    name: 'Jamu Kunyit Asam',
    description:
      'Jamu tradisional dari kunyit dan asam jawa yang menyegarkan. Berkhasiat menjaga kesehatan dan stamina tubuh.',
    image: '🧃',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    calories: 65,
    ingredients: [
      { name: 'Kunyit segar', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Asam jawa', amount: 50, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 800, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Perasan jeruk nipis', amount: 2, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Parut atau blender kunyit segar, peras dan saring ambil airnya.',
      'Larutkan asam jawa dengan sedikit air, saring ambil airnya.',
      'Didihkan 800ml air. Masukkan air kunyit dan air asam jawa.',
      'Masukkan gula merah dan garam. Masak dengan api kecil selama 10 menit.',
      'Angkat, saring kuah jamu ke wadah.',
      'Tambahkan perasan jeruk nipis. Sajikan dingin atau hangat sesuai selera.',
    ],
    tags: ['jamu', 'kunyit', 'asam', 'herbal', 'sehat'],
    rating: 4.4,
  },
  {
    id: 'jamu-beras-kencur',
    name: 'Jamu Beras Kencur',
    description:
      'Jamu tradisional dari beras dan kencur yang menyegarkan dan menghangatkan. Berkhasiat meredakan pegal-pegal.',
    image: '🥛',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 4,
    calories: 75,
    ingredients: [
      { name: 'Beras', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Kencur', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Jahe', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air', amount: 700, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Rendam beras selama 1 jam, tiriskan.',
      'Haluskan beras, kencur, dan jahe menggunakan blender dengan sedikit air.',
      'Didihkan sisa air dalam panci, masukkan daun pandan.',
      'Masukkan adonan beras-kencur yang sudah dihaluskan. Masak dengan api kecil.',
      'Tambahkan gula merah dan garam. Masak selama 10 menit sambil terus diaduk.',
      'Saring jamu ke dalam gelas. Sajikan dingin lebih nikmat.',
    ],
    tags: ['jamu', 'beras kencur', 'herbal', 'tradisional', 'sehat'],
    rating: 4.3,
  },
  {
    id: 'es-cendol',
    name: 'Es Cendol',
    description:
      'Cendol hijau pandan dengan santan gurih dan sirup gula merah pekat. Minuman pelepas dahaga khas Nusantara.',
    image: '🧊',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 220,
    ingredients: [
      { name: 'Tepung beras', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 30, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air daun suji/pandan', amount: 150, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 120, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.5, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air', amount: 100, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Campurkan tepung beras dan tepung tapioka. Tambahkan air daun suji sedikit demi sedikit, aduk hingga rata.',
      'Masak adonan di atas api kecil sambil diaduk-aduk hingga kental dan meletus-letus.',
      'Cetak adonan cendol melalui cetakan khusus ke dalam mangkuk berisi air dingin.',
      'Rebus gula merah dengan 100ml air hingga kental, saring. Dinginkan.',
      'Panaskan santan dengan garam, aduk rata. Dinginkan.',
      'Tata cendol hijau di gelas, tambahkan es batu serut.',
      'Tuang santan dan sirup gula merah di atasnya. Sajikan.',
    ],
    tags: ['cendol', 'santan', 'gula merah', 'pandan', 'Nusantara'],
    rating: 4.7,
  },
  {
    id: 'es-doger',
    name: 'Es Doger',
    description:
      'Minuman segar khas Bandung berisi cendol, kelapa muda, tape singkong, sirup merah, dan susu. Manis dan gurih.',
    image: '🍧',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 3,
    calories: 260,
    ingredients: [
      { name: 'Susu kental manis', amount: 6, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Air', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cendol hijau', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Daging kelapa muda', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Tape singkong', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Sirup merah/rosegren', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Pandan (opsional)', amount: 1, unit: 'lembar', category: 'Bumbu' },
    ],
    steps: [
      'Campurkan susu kental manis dengan air dingin dan daun pandan. Aduk rata, dinginkan.',
      'Cuci bersih tape singkong. Potong-potong kelapa muda.',
      'Siapkan gelas saji. Tata tape singkong, cendol hijau, dan kelapa muda.',
      'Tambahkan es batu serut.',
      'Tuang campuran susu pandan dan sirup merah di atasnya.',
      'Sajikan segera.',
    ],
    tags: ['doger', 'Bandung', 'susu', 'cendol', 'segar'],
    rating: 4.5,
  },
  {
    id: 'es-goyobod',
    name: 'Es Goyobod',
    description:
      'Minuman khas Sumedang berisi kolang-kaling, cincau, roti, dan agar-agar putih dalam kuah santan manis.',
    image: '🥤',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 15,
    servings: 3,
    calories: 200,
    ingredients: [
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Kolang-kaling', amount: 100, unit: 'gram', category: 'Isian' },
      { name: 'Cincau hitam', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Roti tawar', amount: 2, unit: 'lembar', category: 'Isian' },
      { name: 'Agar-agar putih (potong dadu)', amount: 50, unit: 'gram', category: 'Isian' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 150, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Panaskan santan dengan gula merah dan garam. Aduk rata, didihkan sebentar. Dinginkan.',
      'Cuci kolang-kaling. Potong cincau hitam dan agar-agar putih berbentuk dadu kecil.',
      'Potong roti tawar berbentuk dadu kecil.',
      'Siapkan gelas, tata kolang-kaling, cincau, agar-agar, dan roti tawar.',
      'Tambahkan es batu serut.',
      'Tuang kuah santan gula merah yang sudah dingin. Sajikan.',
    ],
    tags: ['goyobod', 'Sumedang', 'santan', 'tradisional', 'segar'],
    rating: 4.3,
  },
  {
    id: 'es-oyen',
    name: 'Es Oyen',
    description:
      'Minuman segar khas Bandung berisi kelapa muda, blewah, melon, nata de coco, dan susu. Rasa manis dan menyegarkan.',
    image: '🍧',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 3,
    calories: 210,
    ingredients: [
      { name: 'Kelapa muda', amount: 1, unit: 'butir', category: 'Bahan Utama' },
      { name: 'Blewah', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Melon', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Nata de coco', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Susu kental manis', amount: 4, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Sirup cocopandan', amount: 3, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Kerok daging kelapa muda. Potong dadu blewah dan melon.',
      'Tiriskan nata de coco dari airnya.',
      'Siapkan gelas saji. Tata blewah, melon, nata de coco, dan daging kelapa muda.',
      'Tambahkan es batu serut.',
      'Tuangkan susu kental manis dan sirup cocopandan.',
      'Sajikan segera selagi dingin.',
    ],
    tags: ['oyen', 'Bandung', 'buah', 'segar', 'dingin'],
    rating: 4.5,
  },
  {
    id: 'sarabba',
    name: 'Sarabba',
    description:
      'Minuman hangat khas Makassar dari santan, jahe, dan gula aren. Menghangatkan tubuh dan cocok diminum saat hujan.',
    image: '🍵',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 15,
    prepTime: 5,
    servings: 3,
    calories: 160,
    ingredients: [
      { name: 'Jahe (geprek)', amount: 80, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula aren', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Serai (geprek)', amount: 1, unit: 'batang', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Telur ayam (opsional)', amount: 1, unit: 'butir', category: 'Pelengkap' },
    ],
    steps: [
      'Geprek jahe dan serai agar aromanya keluar.',
      'Panaskan santan dalam panci dengan api sedang.',
      'Masukkan jahe, serai, daun pandan, dan gula aren. Aduk rata.',
      'Masak dengan api kecil selama 12 menit hingga santan mendidih dan aroma rempah keluar.',
      'Jika menggunakan telur, kocok lepas dan tuang perlahan ke dalam santan sambil diaduk cepat.',
      'Beri garam, aduk rata. Saring ke dalam gelas. Sajikan hangat.',
    ],
    tags: ['sarabba', 'Makassar', 'santan', 'jahe', 'hangat'],
    rating: 4.5,
  },
  {
    id: 'es-buah',
    name: 'Es Buah',
    description:
      'Campuran segar aneka buah potong dengan sirup manis, susu, dan es batu. Minuman sehat yang menyegarkan.',
    image: '🍹',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 15,
    servings: 4,
    calories: 150,
    ingredients: [
      { name: 'Semangka', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Melon', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Nanas', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Jeruk', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Naga merah', amount: 100, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Sirup cocopandan', amount: 4, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Susu kental manis', amount: 3, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Es batu serut', amount: 250, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Potong dadu semua buah: semangka, melon, nanas, dan buah naga. Kupas dan belah jeruk.',
      'Siapkan mangkuk besar, campurkan semua potongan buah.',
      'Tambahkan sirup cocopandan dan susu kental manis, aduk rata.',
      'Dinginkan di kulkas selama 15 menit.',
      'Sajikan di gelas atau mangkuk dengan es batu serut di atasnya.',
    ],
    tags: ['es buah', 'buah', 'segar', 'sehat', 'dingin'],
    rating: 4.6,
  },
  {
    id: 'smoothie-mangga',
    name: 'Smoothie Mangga',
    description:
      'Smoothie mangga segar dan creamy dengan yogurt dan madu. Minuman bergizi untuk sarapan atau camilan sore.',
    image: '🥭',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 200,
    ingredients: [
      { name: 'Mangga matang', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Yogurt plain', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Susu cair', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Madu', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Es batu', amount: 6, unit: 'butir', category: 'Bahan Utama' },
    ],
    steps: [
      'Kupas mangga, potong dagingnya dan masukkan ke dalam blender.',
      'Tambahkan yogurt, susu cair, dan madu.',
      'Blender hingga halus dan kental.',
      'Tuang ke dalam gelas, tambahkan es batu jika suka. Sajikan segera.',
    ],
    tags: ['smoothie', 'mangga', 'yogurt', 'segar', 'bergizi'],
    rating: 4.6,
  },
  {
    id: 'jus-jambu',
    name: 'Jus Jambu',
    description:
      'Jus jambu biji merah yang kaya vitamin C. Rasa manis asam segar dengan sedikit gula dan perasan jeruk nipis.',
    image: '🍐',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 110,
    ingredients: [
      { name: 'Jambu biji merah', amount: 3, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang', amount: 200, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Pelengkap' },
      { name: 'Es batu', amount: 4, unit: 'butir', category: 'Bahan Utama' },
    ],
    steps: [
      'Cuci bersih jambu biji, potong-potong. Tidak perlu dikupas.',
      'Masukkan potongan jambu ke dalam blender bersama air matang dan gula pasir.',
      'Blender hingga halus. Saring jika tidak suka bijinya.',
      'Tambahkan perasan jeruk nipis, aduk rata.',
      'Tuang ke dalam gelas, tambahkan es batu. Sajikan segera.',
    ],
    tags: ['jus', 'jambu', 'vitamin C', 'sehat', 'segar'],
    rating: 4.4,
  },
  {
    id: 'jus-wortel-apel',
    name: 'Jus Wortel Apel',
    description:
      'Kombinasi jus wortel dan apel yang menyegarkan dengan sedikit jahe. Kaya beta-karoten dan vitamin untuk kesehatan mata.',
    image: '🥕',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 10,
    servings: 2,
    calories: 130,
    ingredients: [
      { name: 'Wortel', amount: 3, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Apel merah', amount: 2, unit: 'buah', category: 'Bahan Utama' },
      { name: 'Jahe segar', amount: 1, unit: 'cm', category: 'Bumbu' },
      { name: 'Gula pasir', amount: 1, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air matang', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Perasan jeruk nipis', amount: 1, unit: 'sendok makan', category: 'Pelengkap' },
    ],
    steps: [
      'Kupas wortel dan apel. Potong-potong kecil.',
      'Masukkan wortel, apel, jahe, gula, dan air ke dalam blender.',
      'Blender hingga halus.',
      'Saring jus jika diinginkan. Tambahkan perasan jeruk nipis.',
      'Tuang ke gelas. Sajikan dingin.',
    ],
    tags: ['jus', 'wortel', 'apel', 'sehat', 'vitamin'],
    rating: 4.5,
  },
  {
    id: 'susu-jahe',
    name: 'Susu Jahe',
    description:
      'Susu hangat dengan perasan jahe segar dan gula aren. Minuman penghangat tubuh yang lembut dan menenangkan.',
    image: '🥛',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 170,
    ingredients: [
      { name: 'Susu segar', amount: 400, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Jahe segar (parut)', amount: 2, unit: 'sendok makan', category: 'Bahan Utama' },
      { name: 'Gula aren', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Kayu manis', amount: 2, unit: 'cm', category: 'Bumbu' },
      { name: 'Pala bubuk', amount: 1, unit: 'pinch', category: 'Bumbu' },
    ],
    steps: [
      'Parut jahe segar, peras ambil airnya.',
      'Panaskan susu di panci dengan api kecil.',
      'Masukkan air jahe, gula aren, kayu manis, dan pala bubuk.',
      'Aduk rata dan masak hingga susu hangat dan gula larut. Jangan sampai mendidih.',
      'Saring susu ke dalam gelas. Sajikan hangat.',
    ],
    tags: ['susu', 'jahe', 'hangat', 'penghangat', 'segar'],
    rating: 4.5,
  },
  {
    id: 'es-campur-pandan',
    name: 'Es Campur Pandan',
    description:
      'Es campur spesial dengan cendol pandan, cincau, kolang-kaling, dan kuah santan gula merah. Wangi pandan yang harum.',
    image: '🍧',
    category: 'Minuman',
    difficulty: 'Sedang',
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    calories: 240,
    ingredients: [
      { name: 'Tepung beras', amount: 60, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Tepung tapioka', amount: 20, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Air pandan/suji', amount: 100, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Cincau hitam', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Kolang-kaling', amount: 80, unit: 'gram', category: 'Isian' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 100, unit: 'gram', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
    ],
    steps: [
      'Campurkan tepung beras, tapioka, dan air pandan. Masak di api kecil sambil diaduk hingga kental.',
      'Cetak cendol pandan ke dalam air dingin.',
      'Potong cincau hitam berbentuk dadu kecil. Cuci kolang-kaling.',
      'Rebus gula merah dengan sedikit air hingga kental, saring.',
      'Panaskan santan dengan garam, dinginkan.',
      'Tata cendol pandan, cincau, dan kolang-kaling di gelas. Tambahkan es batu serut.',
      'Tuang santan dan sirup gula merah di atasnya. Sajikan segera.',
    ],
    tags: ['es campur', 'pandan', 'cendol', 'santan', 'segar'],
    rating: 4.6,
  },
  {
    id: 'kopi-tubruk',
    name: 'Kopi Tubruk',
    description:
      'Kopi tradisional Indonesia dengan gula yang diseduh langsung di gelas. Aroma kopi pekat dan rasa manis alami.',
    image: '☕',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 5,
    prepTime: 2,
    servings: 1,
    calories: 60,
    ingredients: [
      { name: 'Kopi bubuk hitam', amount: 2, unit: 'sendok teh', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Air panas', amount: 200, unit: 'ml', category: 'Bahan Utama' },
    ],
    steps: [
      'Masukkan kopi bubuk dan gula pasir ke dalam gelas.',
      'Tuangkan air panas ke dalam gelas.',
      'Aduk rata hingga gula larut.',
      'Diamkan beberapa saat agar ampas kopi mengendap.',
      'Minum kopi tubruk selagi hangat. Ampas tidak perlu diminum.',
    ],
    tags: ['kopi', 'tubruk', 'tradisional', 'hitam', 'sederhana'],
    rating: 4.4,
  },
  {
    id: 'es-kacang-merah',
    name: 'Es Kacang Merah',
    description:
      'Minuman segar khas Sulawesi dengan kacang merah rebus, santan, gula merah, dan es serut. Manis dan bergizi.',
    image: '🫘',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 20,
    prepTime: 15,
    servings: 3,
    calories: 230,
    ingredients: [
      { name: 'Kacang merah kering', amount: 150, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Santan kental', amount: 300, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Gula merah', amount: 80, unit: 'gram', category: 'Bumbu' },
      { name: 'Daun pandan', amount: 2, unit: 'lembar', category: 'Bumbu' },
      { name: 'Garam', amount: 0.25, unit: 'sendok teh', category: 'Bumbu' },
      { name: 'Es batu serut', amount: 200, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Pewarna merah (opsional)', amount: 1, unit: 'sendok teh', category: 'Bumbu' },
    ],
    steps: [
      'Rendam kacang merah selama minimal 4 jam atau semalam.',
      'Rebus kacang merah dengan air hingga empuk, sekitar 45-60 menit.',
      'Panaskan santan dengan gula merah, daun pandan, dan garam. Masak hingga gula larut, dinginkan.',
      'Tiriskan kacang merah yang sudah matang.',
      'Siapkan gelas, tata kacang merah rebus.',
      'Tambahkan es batu serut.',
      'Tuang kuah santan gula merah di atasnya. Sajikan segera.',
    ],
    tags: ['kacang merah', 'santan', 'Sulawesi', 'manis', 'segar'],
    rating: 4.3,
  },
  {
    id: 'teh-rosella',
    name: 'Teh Rosella',
    description:
      'Teh dari kelopak bunga rosella yang berwarna merah cantik. Kaya antioksidan dengan rasa asam segar yang menyegarkan.',
    image: '🌺',
    category: 'Minuman',
    difficulty: 'Mudah',
    cookTime: 10,
    prepTime: 5,
    servings: 3,
    calories: 45,
    ingredients: [
      { name: 'Kelopak bunga rosella kering', amount: 15, unit: 'gram', category: 'Bahan Utama' },
      { name: 'Gula pasir', amount: 2, unit: 'sendok makan', category: 'Bumbu' },
      { name: 'Air', amount: 600, unit: 'ml', category: 'Bahan Utama' },
      { name: 'Jeruk nipis', amount: 1, unit: 'buah', category: 'Pelengkap' },
      { name: 'Daun mint (opsional)', amount: 3, unit: 'lembar', category: 'Pelengkap' },
    ],
    steps: [
      'Cuci bersih kelopak rosella kering.',
      'Didihkan air, masukkan kelopak rosella.',
      'Masak dengan api kecil selama 8 menit hingga air berwarna merah pekat.',
      'Angkat, saring teh rosella ke dalam teko.',
      'Tambahkan gula pasir, aduk hingga larut.',
      'Tuang ke gelas, beri irisan jeruk nipis dan daun mint. Sajikan dingin atau hangat.',
    ],
    tags: ['rosella', 'teh', 'antioksidan', 'sehat', 'segar'],
    rating: 4.4,
  },
];
